### ISSUE TITLE
Properly initialize schedule dialog

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1002]
When I schedule a pipeline, specify certain settings in the core tab, save the changes. Then I schedule another pipeline - by default I see the previous changes. 

Solution. Everytime I click "schedule" (or in general open schedula a pipeline dialog) the dialog must be properly initialized to the same initial values (today is selected in the calendar, etc.)

**Comment by skodapetr** [comment]
I think it's related to the #958 .. so we can .. post this there and do not create new issue ..

**Comment by tomas-knap** [comment]
duplicated #958
