### ISSUE TITLE
Creation od DPU - inconsistency between folder structure and DPU tree

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1004]
See #1003.

Further, when such error is shown (as described in #1003), the folder for the given DPU and the jar itself is still stored, so it is on the filesystem and not in the DPU tree. In case of error when saving new DPU template, the result must be consistent - if the new DPU is not in the tree it must not be in the folder structure, there must not be a directory for the DPU

**Comment by skodapetr** [comment]
Well if this happen after #1003 then .. we can close .. the directory should be deleted, but the cote catchs only exceptiions not errors (like in this case) the error case .. that the clean up code has not been executed .. I will add the error checks, that should solves this.

**Comment by skodapetr** [comment]
ps: reassigned
