### ISSUE TITLE
Log message detail - textarea for long message - ma omezenou delku?

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1009]
![screen shot 2014-01-01 at 11 05 32 pm](https://f.cloud.github.com/assets/3014917/1830265/e2f6b416-7330-11e3-9059-0719d4713495.png)

**Comment by bogo777** [comment]
There should be no limit, if more space is needed, scrollbars around text area should appear, like this:

![image](https://f.cloud.github.com/assets/1550848/1831516/a19c93b6-7392-11e3-879d-67c49132744f.png)
