### ISSUE TITLE
Possibility to delete and copy pipeline

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#101]

**Comment by tomas-knap** [comment]
Honzo, udelej tam prosim rovnou nejaky test, ktery zkopiruje pipeline A (file extractor, file loader), ve zkopirovane pipeline B upravi cestu k souboru u file extractoru a u file loaderu. Pusti A, Pusti B, vysledky musi byt ruzne.

**Comment by janvojt** [comment]
Tests added in commit 736e1de9.
