### ISSUE TITLE
Exception in gui

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1012]
This happens when preparing the pipeline, then suddenly the gui was not responding properly, couple of actions (add DPU, add DPU, close, do not change changes) was stacked and then executed. 

Rather than showing the exception as for example below, it is better to show: "Unexpected error occurs. Please reload the application". And log the full original message to the frontend.log. Because this exception is confusing: 

![screen shot 2014-01-02 at 7 32 27 pm](https://f.cloud.github.com/assets/3014917/1834408/475b2896-73dc-11e3-9534-461c0131044e.png)

**Comment by bogo777** [comment]
It is hard to catch described status, but I remember that we discussed hiding/unifying errors for final version, so it could be solved by that?

**Comment by tomas-knap** [comment]
So basically you will hide all the errors in gui but write an error to the log?

**Comment by bogo777** [comment]
I think that was the idea, but there was some discussion and I don't know if this was the winning idea.

**Comment by tomas-knap** [comment]
Well, the best would be to show "Unexpected error occurs. Please reload the application". And log as error the original cause. The reason is that if we only hide, users may still realize some strange behaviour and may be confused. Is that possible?

**Comment by bogo777** [comment]
Do you mean simple error message with the text, or the one with "click here" link which sometimes occur too? That one is for Vaadins internal problems and I don't know if we can invoke it on demand...

**Comment by tomas-knap** [comment]
It could be the normal one

**Comment by tomas-knap** [comment]
@bogo777  Please write here short description how you intend to solve the exceptions. Just to know that we comprehend it in the same way

**Comment by bogo777** [comment]
We use error handler for exceptions which are not caught in the code. We look for some exceptions and provide custom error messages. e.g. "Database is offline!" 
For rest, the original error message is shown. 

I would change the last "unrecognized" category only. We would provide common error message shown for all of these exception and the original cause would be logged.

**Comment by tomas-knap** [comment]
Ok, so basically the change will be that basically all unrecognized exceptions will be hidden (logged) but instead of them some general error will be shown. If yes, than I agree.
