### ISSUE TITLE
Exception in gui

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1013]
This happens when preparing the pipeline, then suddenly the gui was not responding properly, couple of actions (add DPU, add DPU, close, do not change changes) was stacked and then executed. Please ensure that an exception "Unexpected error occurs. Please reload the application". Because this exception is confusing: 

![screen shot 2014-01-02 at 7 32 27 pm](https://f.cloud.github.com/assets/3014917/1834408/475b2896-73dc-11e3-9534-461c0131044e.png)

**Comment by bogo777** [comment]
Duplicates #1012.
