### ISSUE TITLE
When putting core DPUs on the canvas, they have description -- null --

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1014]
test on odcs-test

![screen shot 2014-01-02 at 6 00 58 pm](https://f.cloud.github.com/assets/3014917/1835132/dc68e5c4-73e9-11e3-974b-5a357da01607.png)

**Comment by skodapetr** [comment]
Tohle už by se stávat nemělo, Honza navíc odstranil v comitu tu classu jenž to dělala.Tedy jedině, že by to zůstalo v DB .. tedy udělat select a změnit tyhle hodnoty na null.

**Comment by skodapetr** [comment]
Upravil jsem v databázi na odcs-test. Tedy pokud byl problém jen tam, měl by být vyřešen.
