### ISSUE TITLE
Problem loading data for RUIAN - too long literals for Virtuoso

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1017]
See pipeline exec 157 on odcs-test. There is RUIAN PDU instance, which start running, but when the first file is processed, it calls addStatement on RDF repo and then it writes "Database is down after XX attempts". But when checking the database, it is ok and running, so there is problem only with one connection - one thread. I even managed to run dbpedia pipeline on top of the same virtuoso. WHy is the fautl tolerant repository not able to reconnect?

**Comment by tomas-knap** [comment]
Even when restarting db, it does not reconnect

**Comment by tomas-knap** [comment]
Extractor ruian. Ma tam v hlavni DPU tride:

@OutputDataUnit(name = "XMLObce")
    public RDFDataUnit outObce; 

Nicmene pro samotne ziskavani dat a posilani dat do dalsiho DPU pouziva tridy Scraper_parser

Scraper_parser s = new Scraper_parser();
        s.logger = logger;
        s.ctx = ctx;
        s.obce = outObce;

Kde s.obce je definovana jako RDFDataUnit, ale bez anotaci a primo na tride Scraper_parse. Pri parsovani pak vola: 

obce.addTriple(obce.createURI("http://linked.opendata.cz/ontology/odcs/DataUnit"), obce.createURI("http://linked.opendata.cz/ontology/odcs/xmlValue"),obce.createLiteral(doc));

A nasledne, kdyz koukam do logu, tak je tam:

Database is down after 1 attempts while calling method add(Statement st, Resource... contexts).

**Comment by tomas-knap** [comment]
Further, problem is that such pipeline cannot be cancelled when it tries to reconnect!

**Comment by tomas-knap** [comment]
Btw. Kdyz se vola 

@Override
    public void addTriple(Resource subject, URI predicate, Value object) {
        Statement statement = new StatementImpl(subject, predicate, object);
        addStatement(statement, graph);

```
}
```

tak se pouziva FailureTolerantRepo?

**Comment by tomesj** [comment]
Když se volá metoda 
@Override
    public void addTriple(Resource subject, URI predicate, Value object) {
        Statement statement = new StatementImpl(subject, predicate, object);
        addStatement(statement, graph);

```
}
```

, tak v metodě addStatement(statement,graph) se pak volá metoda getConnection(), která buď vrací sdílené už vytvořené a sdílené connection, pokud není tak zavolá repository.getConnection(), jehož implementace je v případě Virtuosa v třídě FailureTolerantRepositoryWrapper.

**Comment by tomesj** [comment]
Jinak, co se týká výpadků, implementace v rámci FailureTollerantWrapper je dle implementace schopná se sama zotavit :-) 

Jinak metoda ve třídě FailureTollerantWrapper  pracují s connection je typu synchonized, což by možná mohl být ten problém....Jinak nevím

**Comment by tomas-knap** [comment]
Jirko, 
1. proc myslis, ze by ten synchronized byl spatne? Problem je v tom, ze to porad vraci cannot connect to db. Kdyby byl problem v tom synchronized, tak bych cekal, ze tam trebas zatuhne a bude cekat az jinak metoda opusti tu synchronized metodu. 
2. K te tve druhe uprave v commitu, 
-        this.getConnection().add(url, baseURI, dataFormat, contexts);
  -        repoConnection().add(url, baseURI, dataFormat, contexts);

this.getConnection() interne vola repoConnection, tedy proc ta uprava?

**Comment by tomas-knap** [comment]
Jirko, zkus kdyztak tu pipeline u sebe a zkus si to oddebugovat. Pokud na problem narazis i u sebe, bude se ti to lip ladit. Kdyz ne, tak napis.

**Comment by tomas-knap** [comment]
Koukam na to jeste jednou, v logu je ted: 

virtuoso.jdbc4.VirtuosoException: Problem during closing : Broken pipe

![screen shot 2014-01-04 at 10 36 05 am](https://f.cloud.github.com/assets/3014917/1844377/afdd6116-7523-11e3-8d83-9c91c593aa1c.png)

**Comment by tomas-knap** [comment]
Tak ted uz mi to nesebehne vubec, je tam nekde nekonecna smycka pravdepodobne:

![screen shot 2014-01-04 at 2 01 58 pm](https://f.cloud.github.com/assets/3014917/1844627/6bace7a6-7540-11e3-9a87-0c378c6494f8.png)

Tak nic, tohle je chyba u me, v repozitari ten problem neni.Ale problem pospany v predchozich prispevcich trva

**Comment by tomesj** [comment]
Zkusím tuhle pipeline u sebe :-)

**Comment by tomas-knap** [comment]
Nejaky postreh?

**Comment by tomas-knap** [comment]
Myslim ze problem bude s tim, ze ta trojice, ktera se tam uklada ma objekt (literal), ktery obsahuje soubor, ktery ma 10000+ radek. Tedy vypada to, ze to connection.addTriple nikdy neuspeje.

**Comment by tomas-knap** [comment]
It works in case of localRDF, so the problem is when inserting the triple to Virtuoso

**Comment by tomesj** [comment]
Koukám, že Tomáš byl rychlejší 
- je to přesně tak 
- ten literál je moc velký a proto pokus o přidání této trojice nezdaří 
- vyhodí to stejnou chybu jako u výpadku RepositoryException a proto se snaží stávající spojení zahodit a získat nové stále do nekonečna...

**Comment by tomas-knap** [comment]
Ale pro local RDF to projde. Tedy je otazkou, zda se podari nastavit nejak virtuoso, aby to proslo. Nad tim zkus prosim popremyslet. Muzes to testovat tak, ze vzdy zkusis ulozit jednu trojici rucne a uvidis

**Comment by tomesj** [comment]
Tak pokus vložit hned 1. trojici na Virtuoso neprošlo ani ručně. Bude potřeba najít nějaký parametr, kterým se toto dá nastavit :-)

**Comment by tomas-knap** [comment]
Jirko, posli mi kdyztak prosim v priloze tu vkladanou trojici, zeptam se
Hugha (virtuoso podpora). Ty se zatim prosim koukni na #886

2014/1/4 Jiří Tomeš notifications@github.com

**Comment by tomesj** [comment]
Já už na #886 mám prakticky hotovou

Jde o to, že pro localRepo abychom mohli spočítat velikost, tak načítáme do 
repozitáře daný soubor graf
- nejvíce času pak trvají načtení dat ze souboru do repozitáře - metoda 
  parse(fileStream, baseURI)
- dále ještě metoda setContainerDataSource - řádek 210, třída 
  IntlibPagedTable, frontend (především super.setContainerDataSource
  (newDataSource));

Vše ostatní běží rychle.

Co s tím ?

Jinak najdu ti tu trojici - chtěl jsem jí vložit na github, ale ani mi to 
nedovolilo to vložit :-)

---------- Původní zpráva ----------
Od: Tomas Knap notifications@github.com
Datum: 4. 1. 2014
Předmět: Re: [ODCS] Problem with FailureTlerantRepo - cannot reconnect even 
if the db is still on (#1017)

"
Jirko, posli mi kdyztak prosim v priloze tu vkladanou trojici, zeptam se 
Hugha (virtuoso podpora). Ty se zatim prosim koukni na #886 

2014/1/4 Jiří Tomeš notifications@github.com 

> Tak pokus vložit hned 1. trojici na Virtuoso neprošlo ani ručně. Bude 
> potřeba najít nějaký parametr, kterým se toto dá nastavit :-) 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub<https://github.com/mff-
> uk/ODCS/issues/1017#issuecomment-31583360> 
> . 
> 
> —
> Reply to this email directly or view it on GitHub
> (https://github.com/mff-uk/ODCS/issues/1017#issuecomment-31585482). 

"

**Comment by skodapetr** [comment]
For the frontend conteiner we can try ROC and DataSources. But theire usage
will require some cooperation from rdf side - see dao .ReadOnlyAcess.
Dne 4.1.2014 20:17 "Jiří Tomeš" notifications@github.com napsal(a):

**Comment by tomas-knap** [comment]
1)
"- Bohuslav totiž v RDFQuery používá v metodě size() a loadItems vždy novou instanci pro LocalRepo
- tedy během browseru se dvakrát vytvoří repozitář a dvakrát se do něj nasypou data
- to lze zrychlit určitě na jedno načtení - držet si ten repozitář sdíleně (podobně jako connection)."

Jo, to by urcite slo. Kolik by to obnaselo prace?

2)

"Jde o to, že pro localRepo abychom mohli spočítat velikost, tak načítáme do repozitáře daný soubor graf
- nejvíce času pak trvají načtení dat ze souboru do repozitáře - metoda parse(fileStream, baseURI)"

Pockej,kdyz pustim v rezimu debug pipeline nad virtuosem, tak po dobehnuti zustanou data v pristusnych grafech v DB. Kdyz pustim v rezimu debug pipeline nad local RDF, tak potom zustanou soubory, ktere uz primo predstavuji ty native repozitories ne? Tedy staci se nad tim souborem (repozitarem) dotazat stejne jako nad virtuosem, ne? Nebo jak si tam ukladas data pro pozdejsi browse/query?

 3)
"- dále ještě metoda setContainerDataSource - řádek 210, třída IntlibPagedTable, frontend (především super.setContainerDataSource(newDataSource));"

V pripade prochazeni dat na virtuosem to trva stejne dlouho nebo podobne?

**Comment by tomesj** [comment]
1) Už jsem opravil viz 
commit 9d20a5162c3c0ade229bbc4f3ab3508b395da8eca 
a issue #886 

2) Pro Virtuoso je to tak jak píšeš, pro LocalRepo by to šlo taky, ale tam se ty data nasypou do souboru a pak se vytvoří prázdné LocalRepo a všechno se tam nasype.

Rozdíl je v tom, že když vytvoříš instanci virtuosa a dáš mu správný graf, můžeš rovnou pracovat.
Když jednou vytvoříš LocalRepo můžeš s ním pracovat tak dlouho, dokud ho nezničíš. Jak to ale jednou uděláš, už nemáš šanci - jde o to, že pak nelze udělat něco ve smyslu vytvořím instanci a dám jí jen název grafu a můžu pracovat (tak jako pro virtuoso), to tady nefunguje - proto se data před "zničením" načítají do souboru a zase "načítají" do repozitáře :-)

Alternativou by bylo držet si jeden/více repozitářů někde a nikdy je neukončovat (jen v případě ukončení) aplikace - pak by se data nemusela načítat.

3) V případě Virtuosa je to rychlé, ta metoda totiž volá v sobě to druhé načítání repozitáře - v současnosti už je to sdílené, takže je taky už rychlá :-)

**Comment by tomas-knap** [comment]
Presunul jsem debatu k #886

**Comment by tomas-knap** [comment]
test on Virtuoso 7

**Comment by tomas-knap** [comment]
File data unit may be used as an alternative
