### ISSUE TITLE
Adjust Dependency Graph

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#102]
so that when debuging DPU X only the DPUs needed to obtain inputs of X and evaluate X are run. 

Pozn. od Bohuslava: debug till the selected DPU funguje, potřeba upravit DependencyGraph(teď skončí execution v okamžiku, že se vykoná žádané DPU, ale nikde není zaručeno, že předtím neproběhnou nějaká, která nejsou potřeba)

**Comment by janvojt** [comment]
Implemented in commit d9e45186.
