### ISSUE TITLE
Nsoud - strange data type conversion

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1020]
The file being outputted by XSLT (metadata) is: 

![screen shot 2014-01-04 at 4 20 00 pm](https://f.cloud.github.com/assets/3014917/1844799/d23699fa-7553-11e3-990e-04f079bdc240.png)

But  when such file is loaded to virtuoso, I got: 

![screen shot 2014-01-04 at 4 19 43 pm](https://f.cloud.github.com/assets/3014917/1844800/e04f3574-7553-11e3-8870-45de0c140616.png)

**Comment by tomas-knap** [comment]
It is fine using localRDF 

![screen shot 2014-01-04 at 4 33 08 pm](https://f.cloud.github.com/assets/3014917/1844815/949a7182-7555-11e3-90db-32ed59a2cff8.png)

**Comment by tomas-knap** [comment]
Solved (workaround) by not using data type on fileYear literal

**Comment by jakubklimek** [comment]
Yes, these are related to Virtuoso issues https://github.com/openlink/virtuoso-opensource/issues/114 and https://github.com/openlink/virtuoso-opensource/issues/125
