### ISSUE TITLE
Stack trace missing for error in FailureTolerantRepo

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1021]
Jirko, koukni prosim proc chybi stack trace v pripade problemu s obnovenim connection, viz:

![screen shot 2014-01-04 at 10 14 41 pm](https://f.cloud.github.com/assets/3014917/1845385/5a5e9090-7585-11e3-9a20-74b45daa2bba.png)

Je mozne, ze se k tomu stack trace vubec nedostanes

**Comment by tomesj** [comment]
Tohle je ještě před rozdělením do nové třídy - navíc je to myslím kvůli tomu, že jste zapomněli na {}. V poslední verzi by to mělo být. 

I tak se k tomu já osobně od sebe nedostanu.

**Comment by tomesj** [comment]
Tak jsem do logu rovnou přidal i ještě stack trace výpis - viz předchozí commit.
