### ISSUE TITLE
Showing named graph when browse/query for localRDF

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1022]
WHen using localRDF, is there any sense showing named graph of the data?

![screen shot 2014-01-04 at 10 48 08 pm](https://f.cloud.github.com/assets/3014917/1845446/117a7592-758a-11e3-8a17-3eb225cd5bba.png)

**Comment by skodapetr** [comment]
Mozna jestli to neni tim, ze frontend na urovni gui nevi, ze je to local,
nebo virtuosu? Utvareni je ve zvlast ni tride a frontend pak pracuje s
repository.
 Dne 4.1.2014 22:50 "Tomas Knap" notifications@github.com napsal(a):

**Comment by tomas-knap** [comment]
schovat named graphs pro local
