### ISSUE TITLE
Execution monitor - log viewer - problem showing values <..>?

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1024]
The value for log is correct in exec detail log browser

![screen shot 2014-01-05 at 10 08 39 am](https://f.cloud.github.com/assets/3014917/1846317/14f6412e-75e9-11e3-964a-29ec28a22a2d.png)

But no values between <> in detail

![screen shot 2014-01-05 at 10 08 47 am](https://f.cloud.github.com/assets/3014917/1846318/18012c76-75e9-11e3-9ed4-707072876c11.png)

**Comment by skodapetr** [comment]
Problem can be just in the TextArea or whatever is used .. the < .. > is probably somehow interpreted as html .. use of some "text to save html .. function should solve this".

On the other hand .. it can be feature as if you log <b>Bold</b> you can use some HTML in logs, records ..
