### ISSUE TITLE
Tooltip with full log message, wrapped. 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1025]
So that it is not necessary to click on the log to see the detail, but tooltip is enough. 
If it can be done easily. 

![screen shot 2014-01-05 at 10 10 30 am](https://f.cloud.github.com/assets/3014917/1846321/4fb60e48-75e9-11e3-97d2-8505c1acd9b8.png)

**Comment by bogo777** [comment]
Implemented as for input/output descriptions in mapping dialog, but it doesn't work in this place, strange. Will continue...

**Comment by tomas-knap** [comment]
Any progress?

**Comment by bogo777** [comment]
The difference between mapping dialog(where it works) and logs(where it doesn't) is that for logs the PagedTable from addon is used and for mapping dialog standard table from Vaadin is used. 

I can try using newer version of addon, but I don't know if it will help.

**Comment by tomas-knap** [comment]
Ok, so there is problem with the addon? 

Please try the latest version of the addon, if that does not help, we will postpone this issue.

**Comment by bogo777** [comment]
Update to latest version didn't help.

**Comment by tomas-knap** [comment]
ok, we will postpone
