### ISSUE TITLE
Problem adding data to virtuoso, again problem with repository.add() method

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1028]
See odcs-test, pipeline exec 192, log page 192.

Either there must be clear message why it was not added (e.g. because there is a problem with triple x,y,z), or it must be tuned so that it can add the file. 

![screen shot 2014-01-05 at 12 48 49 pm](https://f.cloud.github.com/assets/3014917/1846509/795271ea-75ff-11e3-89ca-7a082e5f9ff9.png)

**Comment by tomesj** [comment]
Is not actuall - is not used last version, where is include stack trace and problem described message.

**Comment by tomas-knap** [comment]
Happened again, although in a slightly different sitation. Please see exec 195. There is stack trace, but there is no reason why the data cannot be added. Writing just: Cannot put TTL file is not enough. Some inner exception must be hidden. Please check that

**Comment by tomas-knap** [comment]
Again replicated in exec record 197.

**Comment by tomas-knap** [comment]
Also happened on odcs, exec number 178. The same error, but no information why the ttl fine cannot be added

**Comment by tomesj** [comment]
For errors you describe is not responsible RDF module
- try to contact person, which is responsible for that.

I dont know nothing about that 
![image](https://f.cloud.github.com/assets/3481055/1847088/37bfe584-7634-11e3-9c32-7e25c8953fa9.png)

**Comment by tomesj** [comment]
Extractor psp.cz - line 120

try {
                outputDataUnit.addFromTurtleFile(new File(tempfilename));
            }
            catch (RDFException e)
            {
                logger.error("Cannot put TTL to repository.");
                throw new DPUException("Cannot put TTL to repository.");
            }

While is not used e.getMessage() or something like that, or throw DPUException("Cannot put TTL to repository", ex)...

This is question for autor of this DPU.

**Comment by tomas-knap** [comment]
Diky, upravim

**Comment by tomas-knap** [comment]
See DPUa/#38
