### ISSUE TITLE
DPU detail description - max length 512

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1029]
Please at least 2048.

**Comment by janvojt** [comment]
DPU description should be unlimited, see https://github.com/mff-uk/ODCS/blob/3c18694e60af2d10563cfae4ebd570e1b9470180/db/virtuoso/rdbms/schema.sql#L39.

**Comment by tomas-knap** [comment]
Aha, tak je mozne, ze mam starou verzi db.
