### ISSUE TITLE
Fail to load configuration - Transformer, SPARQL and RDF file loader

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#103]
I can display configuration for describes DPUs. Problem is not solved using clean&build. 

Extractors dialogs are OK. 

![image](https://f.cloud.github.com/assets/3481055/793040/78a7a81a-ebd9-11e2-977f-93000afa6714.png)

**Comment by janvojt** [comment]
I can confirm this. Jar file exists in mentioned path and is readable. Petr, please look into this asap.

**Comment by skodapetr** [comment]
If the exception ends on "cannot be resolved" it means that the jar file exist is readable but not all of the required packages are available.

Solved in commit "conf.properties update". Please update configuration file ( module.frontend.expose  value)
