### ISSUE TITLE
Problems with improved iterator (ordered by queries)

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1031]
When running pipeline ares test on odcs-test, pipeline exec 188, see logs for DPU XSLT basic. As you can see at the end of the log for this DPU, all files were processed, but after that, there was an error: 

DPU 'XSLT Basic' publish message short: 'Problem evaluating the query to obtain files to be processed. Processing ends.' long: ': SPARQL execute failed:[SELECT ?s ?o where {?s ?o } ORDER BY ?s ?o LIMIT 20000 OFFSET 80000] Exception:virtuoso.jdbc4.VirtuosoException: Virtuoso Communications Link Failure (timeout) : Connection to the server lost'

XSLT is using the improved iterator using limit + offset queries.

**Comment by tomas-knap** [comment]
![screen shot 2014-01-05 at 1 36 39 pm](https://f.cloud.github.com/assets/3014917/1846577/91fa6822-7606-11e3-85e6-746130ee6f5f.png)

**Comment by tomesj** [comment]
Your limit for MaxSortedTopRows in Virtuoso.ini is too slow
- it should be great than LIMIT+OFFSET used value  (100 000 for this example). 

Start limit value is set to value 20 000 (optimal speed), 
OFFSET+=LIMIT, after successfully iteration, 
It ends, if iteration is is empty (returns no triples yet).

**Comment by tomas-knap** [comment]
Tim to neni, mam to nastavene na 100 000 000. Je mozne, ze virtuoso ignoruje hodnoty vetsi nez 100 000, ale to je treba zjistit

**Comment by tomesj** [comment]
Tak to je divné, já ten limit mám taky velký - zkoušel jsem to pro 7 mil triplů a bylo vše OK :-)

**Comment by tomas-knap** [comment]
Mno, hlavne je divne, ze to psalo v momente, kdy uz byly vsechny iterace hotove. Tedy zkontroluj prosim zaver toho iteratoru - kdyz se vycerpa posledni polozka.

**Comment by tomesj** [comment]
Kouknu se teď závěr toho iteratoru, ale myslím, že kdyby chyba byla tam, že už by se to nějak projevilo.

**Comment by tomesj** [comment]
Chybu tu žádnou nevidím, chová se to jak má

**Comment by tomas-knap** [comment]
Could be solved by #1033

**Comment by tomesj** [comment]
Solved thanks solving #1033.
