### ISSUE TITLE
SPARQL Loader - how effective is work with RDF repo when connection.add() repeatedly called 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1032]
Out of memory quite often in SPARQL Loader, 
See ODCS (localRDF) - execution monitor records 181, 184

For exec 184, before DPU loader, the memory taken was 4,9-5,2GB, max was 6GB. So loader has to take at least 700-800MB. Why? 

![screen shot 2014-01-05 at 11 14 36 pm](https://f.cloud.github.com/assets/3014917/1847592/e08f09ca-7656-11e3-86ee-f47c7bf189fb.png)

Question @tomesj : How is it with native RDF repo (localRDF), if I call connection.addTurtleFile() 10000x, it is serialized to the file after every call or at the end when 10000 files with triples are loaded to memory?

**Comment by tomesj** [comment]
I dont know internal implementation of native RDF - I dont know reason of this problem.

**Comment by tomas-knap** [comment]
Yes, but you should have a general idea how it works, whether ti holds everything in a memory till the end of DPU  execution (till the time when the native repository is closed) or every conection.add() operation is directly stored to the file

**Comment by tomesj** [comment]
Is not stored after every calling connection.add() - it is keep in some pairs in memory and then synchronize to file, when is" right time for application". But I dont know, when is it executed.

**Comment by tomesj** [comment]
I find in javadoc for NativeStore - possible solution of your problem 

public void setForceSync(boolean forceSync)
- Specifiec whether updates should be synced to disk forcefully, must be called before initialization. Enabling this feature may prevent corruption in case of events like power loss, but can have a severe impact on write performance. By default, this feature is disabled.

**Comment by tomas-knap** [comment]
Ok, so we should profile the SPARQL loader to see the memory footprint.
setForceSync() may help, but as they wrote, it has severe impact on
performance, so I think that we need something in the middle, it is not
needed to synchronize every single triple directly to disk.

**Comment by tomas-knap** [comment]
If you look at:

![screen shot 2014-01-06 at 9 35 39 am](https://f.cloud.github.com/assets/3014917/1849266/b67b21e4-76ad-11e3-8e31-662c22e1653b.png)

You can check that on ODCS. 
As you can see loader was loading the data for more than 4hours, taking 6GBs of memory (see #1034). I will try to reproduce that with a single running pipeline.

**Comment by tomas-knap** [comment]
Mno, ze to zabira prilis mnoho pameti. tedy zmer si memory footprint. Da se k tomu pouzit napr. 
http://visualvm.java.net/. To je zdarma, jen stahnes a spustis myslim, uvidi to bezici Javy

Zkus to prosim zmery trebas pro nahravani nejakych stovek tisic trojic - s localRDF i virtuoso. Pouzij trebas ten graf "...nsoud/backup"  Sepsal jsem ti to k #1034

napis sem prosim vysledky, tedy o kolik se zvedlo vytizeni heap space pri SPARQL loaderu (pastni sem taky obrazek toho grafu z visualJVM)

**Comment by tomas-knap** [comment]
Jirko, ted jsem testoval samotny SPARQL loader, viz execution 194, odcs, localRDF, validator vypnuty. A tady je vysledek: 

bezela jedina pipeline, zaclo to stoupat az pri SPARQL loaderu!

![screen shot 2014-01-06 at 11 17 55 am](https://f.cloud.github.com/assets/3014917/1849727/f9bafe26-76bb-11e3-8d39-ad8048222f53.png)

**Comment by tomas-knap** [comment]
Je potreba sahnout jeste po silnejsich profilovacich toolech, abys videl v cem presne je problem. Zkus trebas: 

http://www.ej-technologies.com/download/jprofiler/files
nebo http://www.eclipse.org/mat/ (ten je free)

**Comment by tomesj** [comment]
Nejde tady čistě o implementaci NativeStore ? Protože když se podíváš do logu, tak se tam provádí pro každou trojici jaká si optimalizace a to myslím "žere" dost tu pamět. Pokud tohle dělá jen localRDF, tak je to jasné - implementace  je stejná pro oba :-)

**Comment by tomas-knap** [comment]
Nad virtuosem se to chova rozumne, viz odcs-test, exec 203:

![screen shot 2014-01-06 at 12 09 43 pm](https://f.cloud.github.com/assets/3014917/1850022/2707ccea-76c3-11e3-88a2-6f1e56abfa85.png)

**Comment by tomesj** [comment]
Viděl bych to stejně.

**Comment by tomesj** [comment]
Jinak přikládám svoje výsledky měření - 1 pipeline, SPARQL extractor -> SPARQL loader (300 tisíc trojic):

Virtuoso: (čas začátku loaderu 12:02)
![virtuoso](https://f.cloud.github.com/assets/3481055/1850396/bd69e760-76d0-11e3-87f8-6ce243303372.jpg)

NativeStore: (čas začátku loaderu 13:00)
![nativstore](https://f.cloud.github.com/assets/3481055/1850397/c47fe536-76d0-11e3-8dde-f72bd66fed79.jpg)

**Comment by tomas-knap** [comment]
Jirko, udelej si pipeline, ktera ma SPARQL extractor:

http://internal.xrg.cz:8890/sparql
http://linked.opendata.cz/resource/dataset/legislation/nsoud.cz

Je tam cca 300tisic taky, ale na tom mi to uz padalo

A nasledne loader nekam k tobe. Staci pro ten localRDF.  A mezitim zkus mrknout do kodu/pouzit jeden z tech vykonnejsich profileru, abys zjistil, jake objekty ti tam zustavaji vistet

**Comment by tomesj** [comment]
Dobrá zkusím :-)

**Comment by tomas-knap** [comment]
Zkousel jsem jeste nsoud.cz pipeline, s dvoujnasobnymi daty a taky jsem se 2GB narazil:

![screen shot 2014-01-06 at 3 46 37 pm](https://f.cloud.github.com/assets/3014917/1851048/65310cd4-76e1-11e3-853e-478470c9a06e.png)

**Comment by tomesj** [comment]
Zkoušel jsem to už po úpravě a dostal tyhle výsledky (localRDF, velká data):

Performance:
![performance](https://f.cloud.github.com/assets/3481055/1851085/55656222-76e2-11e3-87f4-a5b9139ac8da.jpg)

Memory:
![memory](https://f.cloud.github.com/assets/3481055/1851088/5c90c32a-76e2-11e3-965f-4ee89a01672e.jpg)

Tedy pohybuje se to u mě v normálních hodnotách (nic neobvyklého)

**Comment by tomas-knap** [comment]
Jirko, co myslis tim "velka data"? 

Zkus to kdyztak prosim na: 
http://internal.xrg.cz:8890/sparql
http://linked.opendata.cz/resource/dataset/legislation/nsoud.cz/backup

Dat je tam 2790494 triplu.

**Comment by tomas-knap** [comment]
Jinak z tech obrazku budou nejspis zajimave - allocation hot spots, mrknem na to tady

**Comment by tomas-knap** [comment]
Tak jsem zkusil tvoje upravy zatim na odcs-test a bez vysledku - i tam to pada. ZKontroluju celkove zatizeni systemu. 

Viz pipeline exec 209 na odcs-test

**Comment by tomas-knap** [comment]
Ale bude tam problem, cela pipeline vzdy sebehne a skonci to u nejmene narocne aktivity - nahrani dat

**Comment by tomesj** [comment]
Tohle tedy můžeme uzavřít ne - viz mail :-)

**Comment by tomas-knap** [comment]
jj

2014/1/8 Jiøí Tome¹ notifications@github.com

**Comment by tomas-knap** [comment]
The problem was with low physical memory on the server + to high maxHeapSize
