### ISSUE TITLE
OrderedQueryIterator not resistant to db failures

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1033]
This error appears when XSLT DPU was using OrderQuery interator:

[screen shot 2014-01-05 at 11 45 02 pm](https://f.cloud.github.com/assets/3014917/1847623/286af7aa-765b-11e3-9493-87d6655c950b.png)

It should try to reconnect as defined in config.properties, so typically indefinitely.

We should discuss the FailureTolerantRepo tomorrow

**Comment by tomas-knap** [comment]
Jirko co jsi zjistil v tomto ohledu? Zkus trebas nejakou pipeline s XSLT a pri provadeni XSLT zabij db a obnov. Iterator by to mel prezit. Dej mi prosim vedet vysledky.

**Comment by tomesj** [comment]
Na to se podívám během dneška/zítřka. Dám pak vědět výsledky.

**Comment by tomesj** [comment]
Pro odzkoušení potřebu, aby jsi mi jako autor nejdřív odstranit problém #1057

**Comment by tomas-knap** [comment]
Jirko, posli mi prosim jeste tu tvou konfiguraci XSLT a take co tam leze jako vstup

**Comment by tomas-knap** [comment]
#1057 rika, ze je v ceste znak < >, coz je spatne, ten tam byt nema. Ale nevim jak se tam dostal

**Comment by tomesj** [comment]
Konfiguraci i mou pipeline jsem ti poslal na mail.

**Comment by tomesj** [comment]
Tak jsem udělal pipeline dle 
[INTLIB] Decisions from nsoud.cz - Daily updates 

A výsledek stále stejný: (viz screen)

![image](https://f.cloud.github.com/assets/3481055/1896031/f86285ca-7b76-11e3-88ae-3831bf8be1f7.png)

Tedy #1057 stále přetrvává - možná že tam používáš něco specifického pro UNIX, co na Windowsu nefunguje.

**Comment by tomas-knap** [comment]
Jirko, zkus prosim ted, zkompiluj si novy XSLT DPU

Tomas

2014/1/12 Jiøí Tome¹ notifications@github.com

**Comment by tomesj** [comment]
Tak je to OK, díky :-)

**Comment by tomesj** [comment]
Výsledky testování 
- vyzkoušena pipeline s XSLT, při provádění XSLT výpadky/obnova DB - iterátor i vše ostatní OK :-)

**Comment by tomas-knap** [comment]
Ok, kdyztak zas otevreme
