### ISSUE TITLE
When pipeline finishes/is cancelled, heap is not properly revealed

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1035]
No pipeline is running, but: 
![screen shot 2014-01-06 at 9 39 41 am](https://f.cloud.github.com/assets/3014917/1849290/728f2ee8-76ae-11e3-84f8-465d31b7d455.png)

**Comment by skodapetr** [comment]
What "profiler" do you use to get this informations?

**Comment by tomas-knap** [comment]
Could be caused by the previous run of SPARQL loader, see #1034

**Comment by tomas-knap** [comment]
http://visualvm.java.net/
