### ISSUE TITLE
Proof-read the user doc

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1037]

**Comment by tomas-knap** [comment]
aktualizovat obrazky, popis
uvodni stranka
precist (marie)
- sehnat nekoho, kdo zkusi podle navodu zalozit pipeline (1 extraktor, 1 loader) , pustit, podivat se na vysledek, pustit v debugu, podivat se na data co produkuje DPU. 
- sehnat nekoho kdo to precte a opravi Aj

deadline 20.1.

**Comment by tomas-knap** [comment]
Do not forget to add description of core DPUs - SPARQL extractor/loader, SPARQL transformer, RDF extractor/loader. Prepare screenshots and basic descriptions and ask @tomesj to add the detailed description of every param. 
Till 20.1.

**Comment by kukharm** [comment]
done
