### ISSUE TITLE
SPARQL Extractor in DBpedia pipeline. Null values

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#1039]
SPARQL Extractor in DBpedia pipeline contains null values on Details tab

![sparql extractor](https://f.cloud.github.com/assets/3471169/1850070/ed2ee362-76c4-11e3-8911-d5120cedf738.jpg)

**Comment by tomesj** [comment]
I have last version and I have no problem with null values.

**Comment by kukharm** [comment]
I  tested on commit ee5fdc9943cc42b5b7db5be6ecd1257ae9c69e13
Author: Jan Vojt jan@vojt.net 2014-01-06 00:22:49
Committer: Jan Vojt jan@vojt.net 2014-01-06 00:22:49
and reinstall DB today.
There is no problem with SPARQL extractor itself, but when i open it from DBpedia pipeline that is initially in the system there are null values. I think the problem is in data.sql  or schema.sql file

**Comment by tomesj** [comment]
Yes, maybe is it in data.sql or schema.sql - please reasign this for Honza. I have lots of work with others more important issues. Thanks

**Comment by tomas-knap** [comment]
Please ensure that the sample data - dbpedia pipeline and the DPUs on it work properly when somebody tries to open DPU details on dbpedia pipeline

**Comment by tomesj** [comment]
DBpedia pipeline has actually no problem with null values - it is solved thanks using onDesarialize() metod. 
Re-open this issue in case of problems in the future.
