### ISSUE TITLE
Remember me does not work when user logs in

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1040]
I have to insert credentials everytime

**Comment by janvojt** [comment]
Steps to reproduce?

Just to be clear, cookie is deleted on explicit user request to log out.

**Comment by tomas-knap** [comment]
I have to log in again and again. Cookies enabled. There is cookie:
remember-meContent:
"rO0ABXNyADJjei5jdW5pLm1mZi54cmcub2Rjcy5mcm9udGVuZC5hdXRoLlJlbWVtYmVyTWVUb2tlbkpDmYlA5jrQAgADTAAHY3JlYXRlZHQAEExqYXZhL3V0aWwvRGF0ZTtMAARoYXNodAASTGphdmEvbGFuZy9TdHJpbmc7TAAIdXNlcm5hbWVxAH4AAnhwc3IADmphdmEudXRpbC5EYXRlaGqBAUtZdBkDAAB4cHcIAAABQvc+7MR4dACEMTA6NDBlNDlmYzk4YTRlNzdlZTk4M2RmMWRhNDJmNGE2YTg4M2M0M2QwMGZiYWFmYWI0NjZiNmJiNzRiMWQxYjdmZjpiOGY5NDhhMzk5Y2RlYzUzN2VkMDE5MDczZTdlYTY4ZDgyYzJkZTNkYTE0YjU5NzlmNGVlYTdkZTE5NGIyY2ZjdAAFYWRtaW4="
Domain:odcs.xrg.czPath:/Send for:Any kind of connectionAccessible to script:
YesCreated:Sunday, December 15, 2013 6:12:11 PMExpires:Thursday, February
13, 2014 6:12:11 PM

**Comment by janvojt** [comment]
Was the problem only on your localhost? I just tried my machine and it works. I also tried odcs.xrg and odcs-test, both worked. I tried it by invalidating session in tomcat.

**Comment by janvojt** [comment]
If it does not work for you on odcs.xrg, it is most likely caused by some browser setting or antivirus on your client. Please try a different PC, so we can investigate...

**Comment by janvojt** [comment]
@tomas-knap bump

**Comment by janvojt** [comment]
May be related to #1067.

**Comment by tomas-knap** [comment]
Zkousel jsem to ted a cookies jsou v poradku, nechapu. Funguje to
