### ISSUE TITLE
Possibility to store data into files as they are exchanged between DPUs

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1041]
There has to be an alternative way hot to output big files other than storing them as literals. 

Motivation:RUIAN provides XML files which has 100s MBs

**Comment by tomas-knap** [comment]
Petre, pridej tam prosim metodu: 

FileDataUnit.getNumberOfFiles(), ktera ti vrati pocet files

**Comment by skodapetr** [comment]
@tomas-knap done, no tests have been added in order to provide the required method ASAP

**Comment by tomas-knap** [comment]
See pipeline exec #245 on ODCS-Test, problem in preexecutor, probably caused by previous DPU, which already stores something to file data unit - called add(x, true) on file data unit

**Comment by tomas-knap** [comment]
throws also when asLink is false, thus add(x,false)
