### ISSUE TITLE
Merging data units with native repository

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1042]
Can we merge data units as a whole, not by parts? In case of virtuoso, it is merged as a whole

**Comment by tomesj** [comment]
Tohle není dobrý nápad
1) Kvůli velké kolekci nelze mergovat najednou - vše se drží v paměti (to byl náš první nástřel), když se použije lazy přístup jde o maximálně po jednotlivých trojicích

2) To, že se merguje po částech má své výhody - přidává se po 1000 trojicích naráz, místo toho aby se přidávala každá trojice samostatně - je to rychlejší

3) Sám jsi měl vedl k tomu, abych to takhle udělal - výhoda viz body 1) a 2) tak nechápu důvod, proč to najednou měnit. Vůbec bych si nepomohli, ba naopak

**Comment by tomas-knap** [comment]
Jj, urcite ma smysl mergovat aspon po skupinkach. Jen mi slo o to, zda neni proste mozne pro native openRDF rep zavolat neco jako repository.copyTO(targetRep), coz samozrejme interne taky pojede streamove, tedy ze to bude postupne nacitat triples a nahravat je do targetRep

**Comment by tomesj** [comment]
Tvé myšlence rozumím, ale bohužel žádná taková metoda není. Musíme se spokojit, s tím co máme v openRDF k dispozici. Myslím, že s tím, co máme to řešíme i tak dost efektivně :-)

**Comment by tomas-knap** [comment]
Check whether there is no way how to merge the data at once

**Comment by ghost** [comment]
in this branch it is resolved : https://github.com/UnifiedViews/Core/tree/develop
