### ISSUE TITLE
Create RDF REconnect aspect

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1043]

**Comment by janvojt** [comment]
I am attaching from our email conversation.

> modul RDF totiz nema zavislost ani na Spring ani na AspectJ. Skusil som aspekt dat priamo do backendu ako to je pre SQL. Tam je zas problem, ze momentalne sa v backende pouziva Spring-AOP ktore nevie aplikovat aspekty na ine zavisle moduly (pre relacnu db to funguje, pretoze tam sa aspekt pouziva na fasadach, ktore su spring-managed beany). Problem je, ze ked pouzijem pre backend aspectj, tak by fungoval aspekt pre rdf, ale nefungoval by pre sql, aby fungoval ten, musel by som weavovat z backendu aj do commons-app, ale to zas nejde, pretoze by sa springovske aspekty weavovali do commons-app dvakrat, co konci compiletime chybou.
> 
> Ako riesenie skusim teda ten aspekt pre rdf dat do modulu rdf, zavislost na aspectj dat len do maven pluginu aby sa zbytocne cely aspectj nepridaval do jarka, a nejak vymysliet injection konfiguracie (kedze tu nemame spring), mozno to skusim az po spojazdneni virtuoso 7...

@skodape You did some refactoring of RDF module. What is the current status? Do you have any comments on RDF reconnect aspect?

**Comment by skodapetr** [comment]
No RDF je teď rozdělený, tedy teoreticky můžeme do něj dostat spring aniž by se dostal do DPU. Na druhou stranu se zřejmě bude ještě poněkud upravovat, neb aktuálně "neodpovídá" tomu rozdělenému stavu.  A nevytváří tak ostré rozhraní z hlediska funkcionality tak jak by to mělo být - což souvisí s tím, že dříve to byl prostě jeden modul pro všechny a všechno. 

@tomas-knap  Proč jsme vlastně chtěli ten reconnect aspekt? Nebo aktuálně RDF nereconectuje?

**Comment by janvojt** [comment]
> Proč jsme vlastně chtěli ten reconnect aspekt? Nebo aktuálně RDF nereconectuje?

It works, but the code is thousands lines of mess and repeated code.

**Comment by tomas-knap** [comment]
New connection has to be created when virtuoso is again on, which cannot be done easily with aspects.
