### ISSUE TITLE
Strange running times of pipelines

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1045]
![screen shot 2014-01-07 at 4 05 50 pm](https://f.cloud.github.com/assets/3014917/1860038/5a96e8c6-77ad-11e3-98b5-701600051583.png)
![screen shot 2014-01-07 at 4 06 03 pm](https://f.cloud.github.com/assets/3014917/1860041/5d770dbe-77ad-11e3-80dc-fae67450b266.png)
![screen shot 2014-01-07 at 4 06 09 pm](https://f.cloud.github.com/assets/3014917/1860045/62231060-77ad-11e3-923f-420b4a7d8343.png)

**Comment by tomas-knap** [comment]
See the change in duration of data from PSP.cz 
It seems that data from psp.cz is the only pipeline for which the duration is updated. Check if it works correctly when more pipelines is running continuously

**Comment by bogo777** [comment]
Tried to reproduce on local and on test instance by running multiple different pipelines simultaneously, but the duration was updated correctly...

**Comment by tomas-knap** [comment]
cannot reproduce
