### ISSUE TITLE
Settings data loaded only when the session starts?

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1046]
When user changes number of rows in table and the same user is logged in a different session, the other user sees the change only when new session is started. 

Please discuss why. The settings are loaded only when the session starts?

![screen shot 2014-01-08 at 11 07 56 am](https://f.cloud.github.com/assets/3014917/1867346/01cde1a4-784d-11e3-95e7-1f2886af4a8c.png)

**Comment by janvojt** [comment]
I think it is a better solution than asking database upon every request...
Also, it is an unusual use case having two simultaneous sessions for the same user. What would be the scenario? Having 2 different browsers open? Sharing one account across multiple users (for this case actually I think current behaviour is better)?

**Comment by tomas-knap** [comment]
Yes, I am not saying it is a bug, just the clarification is needed

**Comment by tomas-knap** [comment]
So as it is implemented right now, if the user A changes anything in user settings, the same user A in a different session can see it only after the sesion is restarted?

**Comment by janvojt** [comment]
Yes, number of table rows is taken from User object kept in authentication context as logged user. Once User is added to authentication context, it becomes a detached entity and stays there as-is even if data in DB change. If a user changes his settings, this detached object is updated, and merged with the database. As authentication context is session-scoped, this object changes only for current session. Other sessions stay outdated.
