### ISSUE TITLE
Problem creating ttl dump when using localRDF

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1048]
When using localRDF, there is in the log:

See odcs, exec 201

![screen shot 2014-01-08 at 12 10 02 pm](https://f.cloud.github.com/assets/3014917/1867699/9a10b09c-7855-11e3-86b6-56ee75104cdd.png)

Can you please explain what does it mean and when it could happen? It seems that the file to which localRDF is dumped cannot be created, but it is strange that it is in the middle of the DPU execution.

**Comment by tomesj** [comment]
Raději česky:
Stalo se pravděpodobně to, že jsi nasadil tu novou verzi ještě během běhu této pipeline - došlo k restartu (viz DataUnitManager.reload), soubor, který byl již dříve vytvořen se zkoušel načíst - implementace se ale mezitím změnila (již se soubor neukládá ani nenačítá) a pravděpodobně byla v běhovém prostředí ještě stará verze - tedy se zkoušelo neúspěšně načíst (tak jak to fungovalo) předtím.

Jak je vidět na stejné pipeline (ID 205), která už celá běžela v nové verzi, tak tento problém již nemohl nastat a vše se chovalo podle nové implementace od začátku do konce.

**Comment by tomas-knap** [comment]
To ne, novou verzi jsem tam jeste nedaval.

2014/1/8 Jiří Tomeš notifications@github.com

**Comment by tomesj** [comment]
Tak to je divné, to potom moc nechápu.....

**Comment by tomas-knap** [comment]
Zkus na to prosim kouknout a vysvetlit cim by to mohlo byt

Diky,
Tomas

**Comment by tomesj** [comment]
No pokud máš starou verzi, tak se nabízí otázka, zda na té cestě máš ten soubor dump_dat.ttl ( který měl být pro každé DPUčko).

**Comment by tomas-knap** [comment]
Nemam ted a nevim jestli tam byl, bo to bezelo v rezimu normal, tedy nic
potom nezustalo. Mas nejake vysvetleni?

2014/1/8 Jiøí Tome¹ notifications@github.com

**Comment by tomesj** [comment]
Nemám pro to žádné vysvětlení - vlastně nechápu ani proč se tvořil/načítal soubor, když šlo o klasický běh.

**Comment by tomesj** [comment]
Když teď nad tím přemýšlím - možná je to kvůli tomu reload na DataUnitManager, protože pokud šlo o klasický běh, soubor se vůbec netvořil, pak se zavolal reload (pokud jsem dobře koukal na implementaci tak se pokoušel si data načíst a to skončilo chybou, protože soubor tam vlastně není.) 

To se tedy zeptej Petra @skodape jako autora DataUnitManager, jak to vlastně funguje. 
Já Ti k tomu asi více neřeknu. Tenhle případ asi není evidentně ošetřen.

**Comment by skodapetr** [comment]
@tomesj  Jirko mohl by jsi prosím říct, co bych měl okomentovat? Pochopil jsem, že nějakou část toho jak pracuje DataUnitManager, ale v jakém případě? Při pádu backendu? Nebo při prohlížení?

**Comment by tomesj** [comment]
Jde o to, aby se vysvětlilo, proč se při klasickém běhu při použití LocalRDF snažil (patrně při restartu běhu) pokoušet načítat soubor pipeline - při run by se nemělo nic ukládat. Navíc teď už se to neukládá ani při debug. 

Tomáš totiž zkusil klasický run, došlo k restartu a chtělo to po něm načítat ten soubor s daty, který tam vlastně ani nebyl. Tedy nějak vysvětlit/napravit v rámci DataUnitManager.

**Comment by skodapetr** [comment]
No protože když doběhne pipeline třeba od půlky, tak aby mohla pokračovat zase vpůlce, tak potřebuje načíst předhozí data. Tedy to by mohlo být ono?

**Comment by tomesj** [comment]
Jo, to bude přesně ono.

**Comment by skodapetr** [comment]
A v čem je tedy problém? nebo jaký z toho plyne závěr?

**Comment by tomesj** [comment]
Napiš Tomovi, on už Ti řekne, co a jak. Já tu mám teď celkem dost práce :-)

**Comment by skodapetr** [comment]
Tedy pro shrnutí: zřejmě šlo o změnu verze, se kterou se aplikace nedokázala sžít. Důvod pro objev v polovině execution byl popsán.
