### ISSUE TITLE
RDF File Extractor/Loader  problems

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#1049]
I tried to test on http://odcs.xrg.cz:8080/odcleanstore-test

I created new pipeline: file extractor ->sparql transformer -> file loader and tried to run it. I get failed execution because of error path to file of RDF File Extractor

Path to file "/home/knap/C:\ted\dbpedia2.rdf"doesnt exist

![extractor2](https://f.cloud.github.com/assets/3471169/1869472/ff569a14-787a-11e3-8e7f-361bae52634a.jpg)

![extractor1](https://f.cloud.github.com/assets/3471169/1869471/fe1e7b58-787a-11e3-99cb-bf016603b229.jpg)

When i used in RDF File Extractor "upload file" instead of path to file extractor was runned ok, but there was problem with file loader 
![extractor3](https://f.cloud.github.com/assets/3471169/1869570/1e59ae46-787c-11e3-85a4-61b44ad76b74.jpg)

You may look this pipeline on http://odcs.xrg.cz:8080/odcleanstore-test it named Test pipeline1

There was no such problems when i tested on local

**Comment by tomas-knap** [comment]
To je spravne, pokud zadavas cestu k souboru, tak musis brat cestu ve
vztahu k masine, na ktere bezi backend. Akorat nevim proc je tam /home/knap
zrovna
