### ISSUE TITLE
Transaction deadlocked and the SPARQL loader did not retry

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1056]
See ODCS, pipeline execution 235, 238. V obou pripadech to OPET skoncilo na SPARQL loaderu. 

Cim je to zpusobene? 

Chapu ze neni uplne trivialni zajistit, aby tam vsechny data byly, ale nechapu, proc se to proste nepokousi znovu a znovu pripojit, tak jak by se to melo chovat, kdyz je ve SPARQL loader konfiguraci -1? Cim si to vysvetlujes?

Jirko, podivej se na to. Nez neco zacnes opravovat, napis prosim ideu sve opravy. Nemuzem si to tou opravou dovolit zas rozbit nekde jinde. 

Diky

**Comment by tomas-knap** [comment]
Je to zase zpusobene tim, ze se "reconnect pokusy" nevztahuji napriklad na "add to", tedy kdy kopirujes data z temp grafu do ciloveho?

**Comment by tomas-knap** [comment]
Pripadne tim samym co u #1055

**Comment by tomesj** [comment]
Myšlenka:
Pro parametr (počet opakování) pro SPARQL loader přidám též opakování pro veškeré metody přípravy před loadem + move z temp grafu do cílového.

Tedy kdykoliv nastane nějaká chyba - bude se zkoušet stále znova získat nové connection a operaci, která se nepovedla zopakovat.

**Comment by tomas-knap** [comment]
Diky, zkusim
