### ISSUE TITLE
Check that the length limits are up-to-date

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1058]
In cz.cuni.mff.xrg.odcs.commons.app.constants
/**
- The enum contains length limits based on database schema limitations.
- @author Petyr
  */
  public enum LenghtLimits {
  DPU_NAME(1024),
  DPU_TOOL_TIP(512),
  DPU_JAR_DESCRIPTION(1024),
  DATAUNIT_NAME(2048),
  SHORT_MESSAGE(128),
  SCHEDULE_NAME(1024),
  PIPELINE_NAME(1024),
  LOGGER_NAME(254);

**Comment by skodapetr** [comment]
Well it looks they are. For those that are mentioned in the LenghtLimits  class.
