### ISSUE TITLE
SPARQL Loader not enough generic

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1061]
When loading to Virtuoso, SPARQL Loader works. However, the request has to be modified when dealing with other SPARQL endpoints.  And the goal of the SPARQL loader is to be a generic loader. 

Solution: 

1.To SPARQL Loader configuraiton, please add to the end of core tab in SPARQL Loader configuration checkbox group:

Virtuoso
Fuseki
4store
Bigdata

User has to always select one, virtuoso is selected as default. 
1. adjust creation of the query - method "getEndpointStreamReader" - for Fuseki and 4store 

To test connections to Fuseki: v7.xrg.cz/data/update:3030
To test connections to 4store: http://v7.xrg.cz:4040/sparql/
To test connection to bigdata: http://v7.xrg.cz:8080/bigdata/

**Comment by tomesj** [comment]
But it means implement whole SPARQL loader 2x more,because we use SPARQL 1.1 syntax for graph cleaning and for loading to SPARQL endpoint. This is W3C standard. 

These enpoints maybe used specific syntax :-)

It needs discusion - I will be for discuss about this face to face on next meeting.

**Comment by tomas-knap** [comment]
Well, that depends on the particular store. I think that Fuseki is supporting SPARQL 1.1 e.g. But it has to be tested. So please start by testing these stores and checking whether they support SPARQL 1.1. and all the queries you have to execute. For sure you will have to adjust the request's params.

**Comment by tomas-knap** [comment]
@jakubklimek Please write your findings, if any

**Comment by tomas-knap** [comment]
Jirko, tak pro zacatek prosim dej do konfigurace SPARQL loaderu, na konec details textboxy, ve kterem umoznis definovat ktery parametry se pouzijou v tom HTTP POST  requestu pri loadovani dat. Aktualne tam mas natvrdo: 

"default-graph-uri=" + endpointGraph
                + "&query=" + myquery
                + "&format=" + encoder;

Nicmene abys to zobecnil, pridej na konec details tab v nastaveni SPARQL loaderu dva labels a textboxy: 
<b>Query param: {query}
Default graph param: {default-graph-uri}, 
</b>
kde {x} znaci ze v textboxu je retezec "x". 

A obsah tech textboxu se pak pouzije pri definici toho HTTP Post requestu. Tedy kdyz nekdo zada 

<b>Query param: {update}
Default graph param: {default-graph-uri}, 
</b>

Udela se HTTP POST Request s retezcem: "default-graph-uri=" + endpointGraph
                + "&<b>update</b>=" + myquery
                + "&format=" + encoder;

**Comment by tomesj** [comment]
Zadání rozumím - tedy se to bude brát dle textboxu :-)
Asi dává smysl to i rovnou předvyplnit - tedy jako default to, co máme pro Virtuoso, ne ?

**Comment by tomas-knap** [comment]
JJ. presvypln to tim co pouziva virtuoso, tedy query param je "update" a default graph je tak je to ted. Tedy aspon pro Loader. 

Jinak to co jsem psal o loaderu by melo byt i pro SPARQL extraktor, tedy ze v details extraktoru muzu definovat Query param a default graph param. Uplne ve stejnem duchu, jen defaultni hodnota pro virtuoso bude "query" pro query

**Comment by tomesj** [comment]
Jo, chápu - tedy ten enum, co jsi tam původně měl můžu vyhodit :-)

**Comment by tomas-knap** [comment]
mno, jo. Delam ti mockup.

**Comment by tomas-knap** [comment]
for mockups, see #1069
