### ISSUE TITLE
DBPedia pipeline - SPARQL endpoint down

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1063]
Zkousim ted dbpedia pipeline, problem je zrejme v tom, ze jejich SPARQL endpoint je dole. Nicmene hlaska SPARQL extractoru je: 

![screen shot 2014-01-13 at 7 07 51 pm](https://f.cloud.github.com/assets/3014917/1903185/bde6a694-7c7d-11e3-9621-dc9ee9d2ea32.png)

Neslo by tam zobrazit neco lepsiho?

Diky

**Comment by tomesj** [comment]
Je to přesně tak - DBPedia endpoint není dostupný - viz problém 405 Not Allowed

Hláška vlastně představuje chybou zprávu + údaje o tom, co bylo posláno za dotaz (contruct query v tomto případě).

Používáme to takhle obecně - v metodě getEndpointStreamReader na repository.

Máš nějaké nápady nebo představu, co by bylo lepší ?

**Comment by tomas-knap** [comment]
Kdyz ten dotaz zadas do prohlizece rucne, dostanes: 

The web-site you are currently trying to access is under maintenance at this time. 
We are sorry for any inconvenience this has caused.

Ale jestli je to co tam zobrazujes vraceno v errorStreamu pri requestu, tak asi nic lepsiho nevymyslime.

**Comment by tomesj** [comment]
Jj, je to přesně to, co je obsahem error streamu při odeslání POSTem :-)
