### ISSUE TITLE
Question: What is the default size of the chunks when merging in case of localRDF?

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1064]
![screen shot 2014-01-13 at 7 11 09 pm](https://f.cloud.github.com/assets/3014917/1903200/211a3a64-7c7e-11e3-8e48-610bf28d917a.png)

**Comment by tomesj** [comment]
Velikost jednoho merge partu pro lokální repozitář je 1000 trojic.

**Comment by tomas-knap** [comment]
ok, predpokladam, ze je tam nejaka konstanta na localRDF repo?

**Comment by tomesj** [comment]
Je to přesně tak - jedná se o konstantu DEFAULT_MERGE_PART_SIZE
