### ISSUE TITLE
Configuration erased when renaming config property

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#1066]
![image](https://f.cloud.github.com/assets/718827/1909118/5b94091a-7cf9-11e3-941c-887a9a0cb472.png)

I renamed one property in DPU config and I lost all configuration, it did not even load the defaults.

What needs to be done is: Fill the fileds that are valid, skip those that aren't. For those fields that are not filled set defaults.

**Comment by tomas-knap** [comment]
ConfigWrap.deserialize seems to throw exception in case the configuration cannot be deserialized:

As a result, such exception is directly propagated to GUI and no default configuration (obtain by creating new instance) is used.

**Comment by skodapetr** [comment]
It looks like there are ways how to solve Jakub's use case. I will implement this ASAP.
As to the Tomas comment .. I'll check this.

**Comment by tomas-knap** [comment]
Thanks. So how would it now behave if I serialize conf, change one atribute in DPU's config, add one another, replace DPU? Would it be able to deserialize at least those atributs which did not change?

**Comment by skodapetr** [comment]
For the removed property .. the value is not loaded, and the situation is logged as

```
16:38:59.264 [http-apr-8080-exec-11] WARN  c.c.m.x.o.c.m.c.ConfigWrap - Skipped missing field: retrySize
16:38:59.264 [http-apr-8080-exec-11] WARN  c.c.m.x.o.c.m.c.ConfigWrap - Skipped missing field: retryTime
```

The newly added values are set to null. The fields that were unchanged should be loaded properly.
