### ISSUE TITLE
Problem with paging

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1068]
To reproduce:
1. Prepare the list of pipelines which exactly fit on one page in the pipeline list (the only page available). 
2. Copy any pipeline. 

As a result, no pipeline appears - but it is in the database and if the pipeline list is refreshed it correctly appears on the second page

**Comment by skodapetr** [comment]
The problem may be .. that in such case the ROC od better the underlying CachedSource is not invalidated .. the solution can be just to call invalidata on respective CachedSource.

**Comment by bogo777** [comment]
Fixed now...just one question regarding this - should we stay on the page with original pipeline(current), or go to the page where the created copy is?

**Comment by tomas-knap** [comment]
I think we should go to the page with the copy. This seems to be less confusing for the user.

**Comment by bogo777** [comment]
I tried it, but there is no easy way to get the page where the copy is - because of sorting and filtering...

**Comment by tomas-knap** [comment]
Just please describe what does it mean "because of sorting and filtering". And leave the user on the page where he copied the pipeline, so that we do not spend too much time on that

**Comment by bogo777** [comment]
Copied pipeline gets id from sequence, so for default sort, it would appear on the last page. But if the user chose different sort, it can appear on other page. 

We create the new pipeline through DAO layer and show it in table by refreshing the container, so we don't have any extra info about this particular pipeline.
