### ISSUE TITLE
SPARQL Extractor - support for more graphs 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1070]
SPARQL extractor allows to define more then one graph, but, as looking into the code, when you specify 3 graphs, it executes the extractor three times, always for one graph, which is not the same as executing one query over 3 graphs!

**Comment by tomas-knap** [comment]
Tak pripravuju jeste mockup

**Comment by tomas-knap** [comment]
Tak jsem to jeste upravil, viz: https://grips.semantic-web.at/display/LOD2/DPU+-+Extractor+from+SPARQL

![screen shot 2014-01-14 at 3 52 12 pm](https://f.cloud.github.com/assets/3014917/1911377/805e046c-7d2b-11e3-904f-6a41f5ea5f1c.png)

**Comment by tomas-knap** [comment]
Zmeny: 
1) Tedy uzivatel muze definovat nejen defaultni graf (tak jsme to ted meli), ale take named graph. 
2) Pokud specifikuje defaultni grafy (vic nez jeden), tak se pro kazdy graf udela default-graph-uri param. Tedy tech params tam muze byt vic! Pokud nespecifikuje zadny, tak se ten param vubec do requestu neprida
3) Pokud specifikuje uzivatel named graphs (klidne vice nez jeden), tak se pro kazdy takovy udela named-graph-uri param. Pokud nespecifikuje zadny, tak se ten param vubec do requestu neprida
4) Pokud nespecifikuje ani default ani named, tak se do requestu nepreda nic. 
5) Zpracovani vicero default/named graphs musi probihat v jednom HTTP POST/GET requestu! To je treba opravit

Vychazi to z te specifikace http://www.w3.org/TR/sparql11-protocol/#update-operation, sekce 2.1. a take z chovani default (clausule FROM)  a named graph (clausule FROM NAMED v requestu) - viz : http://www.w3.org/TR/sparql11-query/#specifyingDataset, 13.2

Kdyz kouknes na ten mockup, tak jsou tam dve varianty jak popsat totez - bud das default graph a named graph do parametru toho HTTP POST/GET requestu a nebo primo do query. Dle spec ma prednost to, co je v requestu, proto, kdyz uzivatel nespecifikuje default/named graph, tak tam v tom requestu nesmi byt zadny takovy param

**Comment by tomas-knap** [comment]
Na tohle koukni prosim az bude #1069 a #1061

**Comment by tomesj** [comment]
It´s supported using more graphs at once in SPARQL extractor for getting RDF data from endpoint.
