### ISSUE TITLE
Validation checked for SPARQL Loader but no event about the validation when executing pipeline

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1073]
See nsoud - daily updates pipeline na ODCS a trebas exec 313

Solution: If the validation for SPARQL loader is selected, it should publish proper event

**Comment by tomas-knap** [comment]
Jeste by to melo logovat chyby zjistene pri validaci rovnou do long message u published event.

**Comment by tomesj** [comment]
Toto je ale v kódu již obsaženo (tedy chyby se logují do long message)

Viz RDFLoader - řádek 90
context.sendMessage(MessageType.INFO, message, dataValidator.getErrorMessage());

**Comment by tomas-knap** [comment]
ok, diky
