### ISSUE TITLE
Build of module FileDataUnit-impl fails (because of failing test)

### ISSUE THREAD

**Issue by janvojt** [mff-uk/odcs#1074]
```
Tests run: 10, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.039 sec <<< FAILURE!
testIterator(cz.cuni.mff.xrg.odcs.dataunit.file.impl.FileDataUnitImplTest)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: expected same:<cz.cuni.mff.xrg.odcs.dataunit.file.impl.FileHandlerImpl@5725bb66> was not:<cz.cuni.mff.xrg.odcs.dataunit.file.impl.FileHandlerImpl@5725bb63>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotSame(Assert.java:737)
    at org.junit.Assert.assertSame(Assert.java:680)
    at org.junit.Assert.assertSame(Assert.java:691)
    at cz.cuni.mff.xrg.odcs.dataunit.file.impl.FileDataUnitImplTest.testIterator(FileDataUnitImplTest.java:109)
```

**Comment by tomas-knap** [comment]
U me OK, master branch mi jde zbuildovat, vcetne testu

**Comment by skodapetr** [comment]
@janvojt Koukl by jsi prosím u sebe na ty listy co se tam porovnávají? U mě to jde totiž také v pohodě, navíc by to mělo více méně projít. Ostatní testy z té sady ti projdou?

**Comment by janvojt** [comment]
Ked zakomentujem ten assert na equals tak mi vsetky testy prejdu OK. Z nejakeho dovodu mi for loop prehadze 2. a 3. objekt. Ked zmenim na nasledovny kod, tak to uz funguje:

``` java
Iterator<FileHandler> handlersIter1 = handlers.iterator();
Iterator<FileHandler> handlersIter2 = handlers.iterator();
while (handlersIter1.hasNext()) {
    Assert.assertSame(handlersIter1.next(), handlersIter2.next());
}
```

Ale idem ten iterator cely vyhodit, pretoze vlastne testuje implementaciu javovskeho iteratora. My nie sme testeri javy...

**Comment by skodapetr** [comment]
@janvojt No cílem nebylo testovat iterátor .. ale spíše tu FileDataUnit, že vrátí postupně všechny soubory, jenž jsou do ní přidané. Tedy nejsem si jistý, jestli se toho testu chceme nějak úplně zbavit. Možná nějakou jinou variantu, kde nebude záležet na pořadí.

**Comment by janvojt** [comment]
> vrátí postupně všechny soubory, jenž jsou do ní přidané

Inymi slovami sa tam testovalo, ze "LinkedList vrati postupne vsetky objekty, ktore donho pridas". Pozri sa ako som to zmenil, nevyhodil som cely ten test.

**Comment by skodapetr** [comment]
@janvojt No dal jsi tam "null" test. Což tady asi není tak nezáživné, ale chtěl jsem pak napsat test v podobném duchu třeba po Merge dvou FileDataUnit .. a tam už bych více ocenil nejen null ale přímo kontrolu, takže stejně budu muset přijít s něčím co je nezávislé na pořadí .. možná nasypat do hash setů .. a porovnat tam a zpět ..
