### ISSUE TITLE
DPU Template detail - broken buttons.

### ISSUE THREAD

**Issue by janvojt** [mff-uk/odcs#1077]
The first time I select a DPU template in DPU tree, all buttons in its detail are always disabled. When selecting different DPU templates, it seems buttons are updated to the state of previously selected DPU. I suspect when selection is made, first buttons are updated, and after that the reference to selected DPU is changed.

**Comment by bogo777** [comment]
Have you made some changes regarding this? I cannot reproduce it now.

**Comment by janvojt** [comment]
No, you can reproduce on odcs.xrg.cz testing instance:
1. Log in as "user".
2. Choose DPU Templates from menu.
3. Click any DPU Template.

Expected result: Button export is enabled.
Actual result: Button export is disabled.

Then if you click a different DPU Template and back again, button export is enabled.
