### ISSUE TITLE
Cancelling loader should clear the temp graph?

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#1085]
When I cancel a SPARQL loader while it is uploading, it leaves its temp graph as it is. This creates chaos. Shouldn't it be cleared? Not to mention that next time other data is added to this "temp" graph and I am not sure if it gets cleared before loading. Temp graphs should have a GUID in their URIs to avoid conflicts.

**Comment by tomas-knap** [comment]
Yes, if the loading is cancelled, temp graph must be cleared.

**Comment by tomas-knap** [comment]
When loading data to target SPARQL endpoint outside of ODCS, the name for the temp graph should be based on the current execution, so it should be specific for the given execution. What is the current situation?

**Comment by tomesj** [comment]
Problem was, that we loaded in case of SKIP_DATA_PART data direct in target graph (without using temp graph). 

I changed it now - In every case we use temp graph at first and after successfuly loading, we move data to target graph. If DPU is cancelled, temp graph is clear (same as after data moving).
