### ISSUE TITLE
RDF File Extractor - encoding of the Czech data stored to Virtuoso

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#109]
I have file in UTF-8 with Czech characters. When I try to extract it with RDF File extractor and looking into Virtuoso on the output graph from such RDF File Extractor, it shows that the data was inserted to Virtuoso under wrong encoding. So the problem is when storing the data from file to Virtuoso, not when the browser in the tool shows the data. Please consult ODCleanStore. 

![screen shot 2013-07-15 at 12 07 08 pm](https://f.cloud.github.com/assets/3014917/796997/9cc7558e-ed36-11e2-84c5-b14d50611ee1.png)

In virtuoso.ini, there is already Charset = UTF-8, but that is not enough.

**Comment by tomas-knap** [comment]
I created Scenario 0b (TED simple - encoding) in https://grips.semantic-web.at/display/LOD2/3.+iteration+-+June
Jirka, you are the responsible person.

**Comment by tomesj** [comment]
It could be solved by commit bcfc8581e7c6f24fb5f182d552ec3a57ebde2249 - Czech, German, Japan,..language....

In case DBPedia pipeline - Data in Virtuoso graphs stored without mistake. After all I will test scenario described on confluence.

**Comment by tomas-knap** [comment]
Jirka, please test also the scenario on the confluence and if ok, close the issue

**Comment by tomas-knap** [comment]
Jirka, when examining your commit, it will not solve the problem. The problem is not when loading RDF data to file (loadRDFfromRepositoryToFile), but when extracting data from file to intermediate storage - Virtuoso.  Test also please on the scenario 0b if the problem with encoding is also for the case when LocalRDF repository (not virtuoso) is selected

**Comment by tomesj** [comment]
I try described scenario Ob - no problems with encoding :-)

![image](https://f.cloud.github.com/assets/3481055/813236/b1d18616-eefd-11e2-8718-43b792d46e3b.png)
