### ISSUE TITLE
Data.sql - descriptions for core DPUs are "--null--"

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1094]
Adjust, so that descriptions makes sense. 

@skodape  Is this a consequence of the tries with NVARCHAR?

**Comment by skodapetr** [comment]
Yes probably it's. As the descriptions was empty or null .. and Virtuoso JDBC does not support null for NVARCHAR.nor empty for String as NVARCHAR

**Comment by tomas-knap** [comment]
So, Jirka,  please put some reasonable description there
