### ISSUE TITLE
Browse/Query in debug mode when using Virtuoso as storage of intermediate results

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#110]
When debugging with Virtuoso as as storage of intermediate results, no files should be used in backend/working/... to store the RDF triples. Everytime when I browse/query the data in debug view, Virtuoso (the proper named graph) should be directly invoked. So in case of browse, you directly invoke the query select \* from <GRAPH> where {?s ?p ?o} directly on Virtuoso, no file needed. 

Solution. Browse/Query in these cases should direclty query the Virtuoso used as storage of intermediate results.

**Comment by tomesj** [comment]
I know about it, I prepare it for using and then I contact with Bohuslav.... But when we have last skype call we spoke about it.

**Comment by tomesj** [comment]
Solved
