### ISSUE TITLE
Fitting the screen to lowe resolution monitors/projectors

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1103]
Pipeline canvase: when the resolution is low, I have to move the whole screen to get to the bottom of the DPU tree.  When the resolution is enough, I can only scroll the DPU tree if needed to get to lower parts of the tree. 

![screen shot 2014-01-24 at 9 39 59 am](https://f.cloud.github.com/assets/3014917/1993113/3e19fa02-84d3-11e3-9579-2b60de7b04c4.png)

Could we lower the minimum height of the screen? So that when presenting on projectors (1024x768), it still behaves in the same way as for higher resolutions - the screen is exactly filled with the content (this does not work right now) and if I need to add to lower parts of the DPU tree, there is a scrollbar in the DPU tree (which works already). 

Please discuss.

**Comment by tomas-knap** [comment]
This is associated with fixed length of the DPU tree?

**Comment by tomas-knap** [comment]
The idea is to have the length of the DPU tree, so that it fits to the screen. If not possible, it should have lower height.

**Comment by bogo777** [comment]
DPU tree is fitted to the screen, but its max height is set from the case, where the tree begins at the top of the screen - screen is scrolled to show only the canvas...

**Comment by tomas-knap** [comment]
Ok. And regarding the canvas, we use fixe sized canvas, right?

**Comment by bogo777** [comment]
Yes, canvas has fixed size.

**Comment by tomas-knap** [comment]
So basically what is missing is to adjust the size of the DPU tree based on the fact whether the header is present or not (hidden)?
