### ISSUE TITLE
Strange records in backend/working dir for DBPedia pipeline, wrong pipeline run!

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#111]
1. When debugging DBPedia pipeline with one RDF File extractor and RDF File loader as described in Iteration 1 and observe the backend/working directory, I can see:

![screen shot 2013-07-15 at 1 27 28 pm](https://f.cloud.github.com/assets/3014917/797292/997e1452-ed41-11e2-8eec-23dc999a8c2b.png)

dpu_1 -> dump.ttl (extractor) contains the extracted data from DBPedia, that is fine. But dpu_2 -> dump.ttl contains only namespace prefixes and NO data. 
1. When running DBPedia pipeline, the output file contains only namespace prefixes, no data.

**Comment by tomesj** [comment]
Problem solved by commit 3ea7c92479ff09ff5ed79a2363aa45aad8de36e7
