### ISSUE TITLE
Slow XSLT config dialog?

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#1110]
When trying to replace XSLT template in Gov.cz Instituce, the "details" button on XSLT dpu did not work and then opened multiple instances of the configuration window.

**Comment by tomas-knap** [comment]
Well, how big is the XSLT template? XSLT is stored to the configuration, so the deserialization could take a bit longer

**Comment by tomas-knap** [comment]
Bohuslav, please ensure that the DPU detail is shown only once even when user manages to click several times before the XSLT opens.

**Comment by tomas-knap** [comment]
What is the idea of the change? I cannot see any change in the code

**Comment by bogo777** [comment]
There is now only one DPUDetail dialog for pipeline edit and details button only sets its data and tells the app to show it. So where there are more requests for detail, only one dialog is shown, with the data of the last request...

**Comment by tomas-knap** [comment]
ok, we will test. Thanks!
