### ISSUE TITLE
Problem with GUI (canvas) when certain error occurs when designing the pipeline

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1116]
When some error occurs in the frontend, e.g., #1104, the canvas than behaves strange - e.g. only arrows appear, or no DPU appears at all. 

Please check the state of the canvas in case of an error. Is it initialized correctly next time pipeline is open?

**Comment by tomas-knap** [comment]
Tohle si nech na konec z tech high prio issues

**Comment by bogo777** [comment]
Whole canvas and all object on it are created each time pipeline is opened, so it should behave correctly for correct data.
