### ISSUE TITLE
Mandatory fields of DPUs

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#1118]
Some of DPUs have mandatory fields. This mandatory fields should be filled in DPU instance on canvas and may stay empty on DPU template in DPU Templates section. Also some of the fields should controlled the correctness of filling in both DPU instance and  template.
Take for example the SPARQL Extractor it contain the mandatory field "SPARQL endpoint" that should start with "http://"

Problem 1:
In DPU Templates section when i leave a mandatory field blank or with error value i get an exception 
![mandatory](https://f.cloud.github.com/assets/3471169/2010034/46b73afc-8768-11e3-986c-837391bd2ad6.jpg)

Problem 2:
Now when i would like to save DPU template with empty mandatory field and prefield any other field (like in the picture)
![mandatory2](https://f.cloud.github.com/assets/3471169/2010267/8842e82e-876b-11e3-9c93-263d59a7cdb5.jpg)
 i can't do that, the dpu template will be saved with all empty fields. Because empty mandatory field  on DPU calls ConfigException. 
I think for solving this it's need two different exception types for empty mandatory fields and error values in fields

**Comment by skodapetr** [comment]
The no-type exception is connected to using null value for NVARCHAR. Do you have current database schema?

**Comment by kukharm** [comment]
I tested on http://odcs.xrg.cz:8080/odcleanstore-test/

**Comment by skodapetr** [comment]
I've added the context which you can use to find out if you are template or not. Sample: (in dialog class)

```
if (getContext().isTemplate()) {
    // we are template      
} else {
    // we are intance
}
```

**Comment by tomas-knap** [comment]
@skodape Is this solved?

**Comment by skodapetr** [comment]
Welll I only add function isTemplate(), so I think from my side all done. But it's up to the Maria to use this function in dialogs.

**Comment by tomas-knap** [comment]
Marie, use this function. Ask Petr, if needed
