### ISSUE TITLE
Deterministic selection of edges/nodes

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1120]
How more than DPU can be selected? 

![screen shot 2014-01-27 at 5 31 08 pm](https://f.cloud.github.com/assets/3014917/2010641/7cdf9d7e-8770-11e3-919c-64e03d4d37f5.png)

**Comment by bogo777** [comment]
Multiple DPUs can be selected by holding CTRL key and clicking on them or by clicking on the "DPU formatting" from the DPU action bar and then clicking on DPUs. When at least 2 DPUs are selected, formatting menu is enabled.

**Comment by tomas-knap** [comment]
Well, that does not work in Safari/Chrome. When I click with CTRL pressed, nothing happens. WHich browser do you use?

**Comment by bogo777** [comment]
I use Chrome/Firefox. Both work for me, tested on odcs-test also.

![image](https://f.cloud.github.com/assets/1550848/2251586/2c16bd02-9d9e-11e3-81cb-e0b45c12503c.png)

**Comment by tomas-knap** [comment]
Thanks, will try to solve the CTRL key, problem on my site probably. 
But regarding the focusing of DPUs/edges, it seems to behave not perfectly deterministically. 

1) If I select one DPU, click on "DPU formatting icon", then what is the proper way to get back to the normal mode (when clicking on DPU causes that the DPU and its edges are emphasized)?

2) When switching to DPU layout formatting, I can get to the states like: 
![screen shot 2014-02-25 at 10 11 21 am](https://f.cloud.github.com/assets/3014917/2255938/e84b8434-9dfe-11e3-90c2-6fd56bb0d2ff.png)

![screen shot 2014-02-25 at 10 12 27 am](https://f.cloud.github.com/assets/3014917/2255939/ecb6c20e-9dfe-11e3-8341-835b57a546b7.png)

**Comment by bogo777** [comment]
After changes to canvas, focusing multiple DPUs can be done by mouse selection(rectangle) + adding/removing DPU by clicking on it with CTRL key held down.

1) After the changes it is simply by clicking on the empty canvas or unselected DPU.
2) This should not appear anymore.
