### ISSUE TITLE
Two buttons for improved usability

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1122]
Based of the usability feedback:

1) Please add button "detail" to exec monitor to the column "pipeline name" next to each record. Please suggest whether it should be on the left or right of the pipeline name. When clicking on that button, pipeline canvas is shown with a detail of the pipeline the button is next to. When closing (leaving the pipeline detail) the exec monitor should be again shown. 

When opening pipeline detail from pipeline list and clicking save/close, pipeline list is restored together with the filters (current functionality already in place)

The first point is important, it would spare minutes per day for both me and Jakob. 

2) Please add button "save & close & debug" to the pipeline detail, which is equivalent to clicking "save & close" and "debug" for the saved pipeline. It should be next to "save & close".

**Comment by bogo777** [comment]
2) Should the user be explicitly redirected to the execution list with debug execution detail open or return wherever he came to edit from?

**Comment by tomas-knap** [comment]
2) He should be switched to the open debug execution detail, as in case he clicks on "debug" button
