### ISSUE TITLE
Tab labels missing sometimes - exec record detail 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1123]
When I open the exec record detail:

![screen shot 2014-01-28 at 10 18 39 am](https://f.cloud.github.com/assets/3014917/2017551/3a842d40-87fd-11e3-983d-99a1b5dad56b.png)

**Comment by tomas-knap** [comment]
reproduced on ODCS

**Comment by tomas-knap** [comment]
Does not dissappear after reloading

**Comment by skodapetr** [comment]
Does this happen for all executions, or just one?

**Comment by tomas-knap** [comment]
Could be caused by: 
![screen shot 2014-01-28 at 10 23 41 am](https://f.cloud.github.com/assets/3014917/2017590/f43bd06c-87fd-11e3-93ea-171f5a9fae01.png)

which appear when clicking on "Logs" in the last column

**Comment by tomas-knap** [comment]
Actually only for "USA contracts- linking". But when I tried a different
one, the labels where missing for a while but then appeared (after one
second or so).
Afterwards, it starts to work also for "USA contracts- linking" execution

**Comment by tomas-knap** [comment]
It is happening on ODCS, try to click pipelines with more logs, e.g. _Krovak_

**Comment by bogo777** [comment]
Cannot reproduce now, please retest on version after f791c9c9e9ae372983ce505cc1d526f88dc99919 it could have solved it if it was related to #1101

**Comment by tomas-knap** [comment]
I will test, but I don't think it is related to this issue

**Comment by tomas-knap** [comment]
See it on ODCS-test. Just click on the first execution record. 

![screen shot 2014-02-05 at 10 13 58 am](https://f.cloud.github.com/assets/3014917/2085471/f8f64346-8e45-11e3-91cf-560c16fedfcb.png)

**Comment by tomas-knap** [comment]
You have to click a bit, it happens only sometimes

**Comment by tomas-knap** [comment]
click to different exec records and it should show finaly

**Comment by tomas-knap** [comment]
It seems to me that typically, it is missing for the first time when exec monitor detail is shown, but when clicking to a differernt exec record and back to the previous, everything is correct

**Comment by bogo777** [comment]
I can reproduce it on ODCS-test easily, but not on local. Is there any easy way to get log from odcs-test instance? It could help a bit.

**Comment by skodapetr** [comment]
You can connect directly to the odcs-database with local Frontend, is this enough?

**Comment by tomas-knap** [comment]
I already sent Bohuslav account to get to logs. But yes, if you need access
to the db, odcs.xrg.cz:8901/conductor

**Comment by skodapetr** [comment]
I meant use DB directly for frontend. So you can see data from odcs-test on your tomcat and replicate the issue ie. debug ... Bohuslav contact me or better Tomas for more info on skype.

**Comment by bogo777** [comment]
From logs it seems ok. Removed some duplicit/suspicious calls in DebuggingView, but don't believe the problem was there.

**Comment by tomas-knap** [comment]
Bohuslave, I did not deploy the version with logs on odcs-test yet, I will
do today and let you know

**Comment by tomas-knap** [comment]
Please check the deployment on ODCS (your logs are available there) . It must be solved, it looks really ugly. Right now, it always dissapers for the first time exec detail is shown. When clicking on different exec record, it reappears. Urgent issue

**Comment by bogo777** [comment]
I tried downgrading Vaadin version back to 7.1.8(last version used before 7.1.10) and it looks that tabs are working correctly again.

But this problem didn't occur on my local for some time, so I don't know, if it really helped. So, please deploy frontend with downgraded Vaadin and we'll see...

**Comment by tomas-knap** [comment]
Just tested on localhost so far. When opening exec record detail, fistly, the tab labels are hidden, but they appear after few seconds. Will test on odcs-test

Btw. What is the order in which the dialog is initialized? It seems to me that firstly the table with events is loaded and then the tab labels are set. It should be oposite.

**Comment by bogo777** [comment]
Was it detail of running execution? Automatical refresh fixes it like clicking on other detail.

Each component is added to TabSheet in one command with tab name:
tabs.addTab("Events", eventsTable);
So if the component occurs in tab sheet, the label should be there too.

**Comment by tomas-knap** [comment]
It seems that the downgrade works, tabs do not disappear. tested on odcs-test
