### ISSUE TITLE
Merging of data units does not support cancel

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1124]
LocalRDF

**Comment by skodapetr** [comment]
ODCS is not currently designed for that. IMHO we need at least 2 things:
1) support from dataUnits - at least in form of interface, we may use some Handler from commons 
- the handler can be used to cancel operations in DPU on DPU request (user request) as well as to cancel the merge operation
  2) add cancel support to backend

**Comment by ghost** [comment]
wontfix, merging is instant.
