### ISSUE TITLE
Chybejici dokumentace v PipelineGraph

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1125]
Jirko, prosim dopln co nejdriv, pouziva to slovensky kolega pro testy, tak at ma lepsi info

**Comment by tomesj** [comment]
Tome, o této části skoro nic nevím, nejsem autorem, možná by ses měl obrátit na Honzu nebo na Petra spíš :-)

**Comment by tomas-knap** [comment]
Ja ze jsi byl prvni autor

**Comment by tomesj** [comment]
Stránku jsem možná tak zakládal, to ano...Zakládal jsem jich spoustu :-) Ale s obsahem zase tak nic společného nemám :-)

**Comment by tomesj** [comment]
Navíc jsem se teď chtěl podívat na confluence, co se tam zatím píše a tu stránku tam nemůžu nikde najít. V sekci pipeline to není a jinde to taky nevidím

**Comment by tomas-knap** [comment]
Mno, tak kdyz to tam neni, tak je treba doplnit
