### ISSUE TITLE
Execution record detail - thread

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1128]
Pouziva se toto pole, co je jeho obsahem?

**Comment by tomas-knap** [comment]
pipeline exec -> detail -> detail logu. Je tam pole Thread

![screen shot 2014-01-29 at 2 47 27 pm](https://f.cloud.github.com/assets/3014917/2029801/e8c41a3e-88eb-11e3-86bc-130c7a7d6319.png)

**Comment by skodapetr** [comment]
Aktualne k nicemu, upravim.
