### ISSUE TITLE
Upravy gui dle pripominek Kuby

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1129]
Kuba delal celkovou revizi GUI a neni jeste spokojen s tim jak vypada. Meli by to byt vsechno drobnosti. Vetsi veci jsem dal zvlast. 
# Execution monitor:

Schovat sloupce:
- ID - dozvim se z pipeline event (starting execution ID #1127)
- user - kdyz bude v budoucnu potreba, pridame
- Start (dozvim se z detailu) 

Poradi sloupcu
- Tlacitka
- Status (uzky jen na iconu)
- Pipeline name 
- Duration 
- debugging, schedulled (uzky jen na iconu)
# Execution monitor detail: 

Schovat sloupec "Logs", "Source"

Poradi sloupcu
- Typ (uzky jen na sirku icony)
- Datum
- Instance
- Message

Odstranit carku mezi tisicema - v pocitani page. 
Zvetsit okno pro ukazatel page. Aby se tam vesly i desitky tisic stranek

Schovat tlacitko "close", schovat "Download" (see #1130)
# Pipeline list: 
- schovat columns: id, owner, description
- Tlacitko id musi byt v detailu, tam ho prosim pridej (zobrazi se jen pro jiz existujici pipeline)

Poradi sloupcu: 
- buttons (ikonky pro tlacitka - pouzij ikonky z exec monitoru/canvasu, texty z tlacitek v tooltipu)
- Name
- 3x last run..
# Scheduler: 
- schovat sloupec ID v prehledu, schovat description, owner
- ID pridat do detailu eventy (zobrazi se jen pokud otviram uz existujici event)

Poradi sloupcu: 
- tlacitka (ale ikony misto textu, text do tooltipu)
- Pipeline
- Rule
- Last, Next
- Last runtime
- Status (ale jen na sirku ikony)
# Settings:

Schovat tab "namespace prefixes"

**Comment by tomas-knap** [comment]
Pokud cokoliv neni jasne nebo se ti zda divne, pis

**Comment by bogo777** [comment]
Ok, neměl by tam být žádný zásadní problém.

Jen dotaz k těm sloupcům na šířku ikony - co se má stát s Headerem sloupce?

**Comment by tomas-knap** [comment]
Takhle, ta sirka by asi mela byt takova, aby se do combo boxu vesla ta ikonka + sipka pro zmenu vyberu. Kdyz se pak combo rozbali, tak tam bude ikonka a popisek, s tim, ze ten rozbaleny list klidne muze presahovat. Myslim ze u nejakeho combo boxu uz to tak i mame

**Comment by tomas-knap** [comment]
1) Sirka sloupce pro buttons by mela mit vzdy pevnou delku a to takovou, aby se tam akorat vesly buttons: 

![screen shot 2014-01-30 at 4 59 33 pm](https://f.cloud.github.com/assets/3014917/2041649/c2f64f20-89c7-11e3-83ca-e96901ef225e.png)

Podobne pro dalsi sloupce s jasnymi hodnotami a jasnou minimalni sirkou (trebas status, last status, atd.), ty by proste mely mit pevnou velikost. Nikdy by se automaticky nemely vykreslit sirsi, ikdyz mam 40ku monitor.

**Comment by tomas-knap** [comment]
2) Pipeline detail by mela obsahovat "Created by: {autorPipeline}". Pod visibility.

**Comment by tomas-knap** [comment]
3) Execution monitor - fixni velikost. Sirku jeste malinko vetsi, aby se tam vesel i label "STATUS" sloupce. Omlouvam se, spatna spec ;-)
![screen shot 2014-01-30 at 5 09 43 pm](https://f.cloud.github.com/assets/3014917/2041756/1a5045a4-89c9-11e3-8372-0bc15177a806.png)

Similarly for debug. Label for scheduled should be only "SCH."

**Comment by tomas-knap** [comment]
4) Protor nad tlacitky vypada hrozne prazdny: 

![screen shot 2014-01-30 at 5 11 10 pm](https://f.cloud.github.com/assets/3014917/2041761/2e3ab086-89c9-11e3-8d0b-32d30980fdac.png)

Co tam dat label "Actions"? U exec monitoru, pipeline listu.

**Comment by tomas-knap** [comment]
5) Ten sloupec tlacitek "Detail" u pipeline name u exec monitoru -> dej tam prosim nejakou icon. A umisti ten detail button (aktualne ve sloupci pipeline name) jako posledni action mezi tlacitkove actions. Opet s nejakou icon. Koukam totiz, ze je to u toho sloupce name trochu divne a hlavne pak divne funguje klikani na record (kdyz kliknes na record mimo sloupec pipeline name, tak ok, kdyz kliknes na pipeline name, tak to nejde) 

6) Pokazeny log message detail: 

![screen shot 2014-01-30 at 5 22 06 pm](https://f.cloud.github.com/assets/3014917/2041880/b4e8033a-89ca-11e3-9a0d-d3c17237caa3.png)

**Comment by tomas-knap** [comment]
7) pipeline exec detail -> zalozka log -> Dej prvni sloupec loglevel, prejmenuj prosim na "Type". Pridej tam taky ikonky jako u events. 

8) Scheduller - viz zadani

**Comment by tomas-knap** [comment]
9) Ikony - exec monitor - debug data/show log (ruzne ikony), cancel. Text opet do tool tipu

**Comment by tomas-knap** [comment]
10) Zkontroluj na zaver prosim, ze vsechny sloupce maji minimalni sirku nastavenou tak, aby se tam vesel header (label) sloupce.

**Comment by tomas-knap** [comment]
11) Please add back to exec monitor table the column "Started", which should be before the column "Duration". Sorry for that. Please add also column "Executed By" (instead of the original column "Author") to execution monitor. It should be the last column. It is needed because execution monitor is the only reasonable place where the user who executed the pipeline should be shown

**Comment by tomas-knap** [comment]
12) Regarding the action button for pipeline list, please order them as: Run, debug, schedule, copy, edit, delete. Delete icon should be red (the trash bin)

**Comment by bogo777** [comment]
Mělo by to být, až na:

5) Už jsem to upravil tak, že execution detail se zobrazí i po kliknutí na pipeline name, ještě by šel přes css přidat kurzor, aby byl stejný jako pro zbytek řádku, změnil bych header jen na pipeline a tlačítko detail nechal tam se standardní ikonou pro detail

nebo tedy přesunout a přidat novou ikonu, ale nenapadá mě žádná vhodná...

obecně k těm ikonám bych potřeboval napsat jakou z existujících použít, případně přímo poslat novou, přijde mi jako ztráta času nějakou hledat, která se pak nelíbí a hledat znovu, když se dá rovnou najít vyhovující, ideálně .png 16x16

Tedy pro dokončení prosím o upřesnění/ikonky pro: 9), 7) TRACE, 5) pipeline detail?, 12) red trash bin?

**Comment by tomas-knap** [comment]
Ad 5) ok, zkusim, diky. Nech to zatim tedy u toho pipeline name se standardni ikonou pro detail. Uprav jeste prosim ten kurzor v CSS, at je to jednotne. Zkusime a uvidime. 

9) Cancel - stejna jako ikona cancelled ve statusu, show log - http://findicons.com/icon/219135/view?id=219295  , debug view - to same co show log, ale s mensi "debug pipeline" icon v pravem dolnim rohu (tedy s tim broukem v pravem dolnim rohu, snad nebude moc maly). 
7) trace - https://www.iconfinder.com/icons/193069/hand_hands_logs_palm_prints_steps_touch_trace_icon
12) https://www.iconfinder.com/icons/32104/recyclebin_trash_icon#size=64  Ale podbarvi prosim nejak cervene ten kos

**Comment by tomas-knap** [comment]
Bohuslave, diky, jeste prosim:

**Comment by tomas-knap** [comment]
B) Id u pipeline detail dej prosim az za uzivatele, neni to tak dulezite, aby to bylo prvni. Pokud delam pipeline, nezobrazuj tam "ID New", ale proste tenhle radek schovej (klidne si tam na nej rezervuj misto, to je jedno). Kdyz dam save, radek s ID se objevi. 

U schedulled event detail dopln prosim "Schedulled by: {user}" a dej to za description. Az za to dej opet to IDcko. Opet pokud ID jeste neni prirazeno, radek s ID schovej. 

C) U schedulleru dej prosim status sloupec hned za actions. Za to se omlouvam, to je moje chyba.

**Comment by tomas-knap** [comment]
E) V Exec monitoru, kdyz kliknu na pipeline name, tak se zobrazi spravny kurzor, zobrazi se detail, ale nevybere se radek v exec monitoru. Kdyz kliknu na started, tak se vybere! To klikani na pipeline name sloupec v Exec monitoru funguje divne, obcas jo, obcas ne; jine sloupce se chovaji korektne. Vyzkousej si opet na odcs-test

**Comment by tomas-knap** [comment]
G) WHen opening exec monitor detail, it may happen that the pipeline name column dissapears: 

![screen shot 2014-02-05 at 12 36 33 pm](https://f.cloud.github.com/assets/3014917/2086566/d41783c8-8e59-11e3-8b87-14f305a9cc4b.png)

Solution: Pipeline name column should have certain minimal width

**Comment by tomas-knap** [comment]
H) When filtering logs in exec monitor detail, there should be icon + text in the combo box. Currently there is only text. 

![screen shot 2014-02-05 at 12 44 34 pm](https://f.cloud.github.com/assets/3014917/2086620/0e0d2ba4-8e5b-11e3-9a00-9c17351d494f.png)

**Comment by tomas-knap** [comment]
I) In scheduller, there is no space between actions icons (but in pipeline list/exec monitor there is a space). Put space in scheduler.

**Comment by tomas-knap** [comment]
J) Execution monitor, sometimes, when resizing, the column for action buttons is resized so that not all actions are visible. Actions column's size should be fixed, if possible. Or at least, the minimum width should be specified so that the buttons are always all visible

![screen shot 2014-02-05 at 2 14 14 pm](https://f.cloud.github.com/assets/3014917/2087214/abccfb24-8e67-11e3-9720-3ebfbc95bde2.png)

**Comment by bogo777** [comment]
C, E, H, I, J - done

G - this a problem, I didn't find solution yet. 
    - https://vaadin.com/api/com/vaadin/ui/Table.html#setColumnExpandRatio(java.lang.Object, float)
    - it looks like either expand ratio OR width can be set, NOT both

B - later tonight

**Comment by tomas-knap** [comment]
Ad G) Nepomohlo by nastavit minimalWidth cele tabulce? Tedy aby trebas vypadala takto nejhure: 

![screen shot 2014-02-06 at 8 36 12 am](https://f.cloud.github.com/assets/3014917/2096335/6eab9fa8-8f01-11e3-8542-7e104b7da5fb.png)

V pripade, ze ma tabulka jeste mene horizontalniho prostoru, tak se objevi horizontalni posuvnik. 

Jeste dotaz, executedBy je fixni sloupec? 

Ono kdyz na to ted koukam, tak bez toho minWidth se to chova divne, viz niz, headers nesedi:

![screen shot 2014-02-06 at 8 38 21 am](https://f.cloud.github.com/assets/3014917/2096342/cc0c0962-8f01-11e3-9d4f-c59ce6b9b41e.png)

**Comment by tomas-knap** [comment]
Tu minimalWidth pro table prosim nastav nejak rozumne (aby byly vsechny sloupce aspon trochu videt, neposouvali se headers) take pro pipeline list, scheduller, exec record detail

**Comment by tomas-knap** [comment]
Jeste drobnost, slo by do tech zavrenych comboboxu u uzkych sloupcu dava proste jen tu icon, bez nasledneho textu? Az kdyz se combo rozbali, tak tam bude videt to co ted (icon + text)

![screen shot 2014-02-06 at 9 15 47 am](https://f.cloud.github.com/assets/3014917/2096505/027a6228-8f07-11e3-9b62-70b46bbdb9f3.png)

**Comment by bogo777** [comment]
Pri nastaveni pevne sirky tabulky se v pripade, ze je k dispozici mene mista nez je sirka, zobrazi posuvnik pro cele okno/levou cast okna u execution listu a ne primo v tabulce, coz vypada take blbe.

Byl bych pro nastaveni pevne sirky u vsech sloupcu, kde je to rozumne - ikonky, tlacitka, duration, mozna i datumy...a pro zbytek sloupcu bych nechal "natural" width = min. sirka takova, aby se tam vesel obsah, pripadne misto navic se rovnomerne rozdeli mezi vsechny "natural" width sloupce v tabulce...

U comboboxu muze byt bud ikona + text vzdy nebo nikdy, nevim jak by to slo nastavit zvlast pro vybranou hodnotu...

**Comment by tomas-knap** [comment]
Bohuslave, k te sirce, urcite nastav prosim pevnou sirku vsude tam, kde to dava dobry smysl. To jsou vlastne vsechny sloupce (u pipelineList,execmonitor, scheduler) az na pipeline name, executedBy a rule u scheduleru. Bohuslave, ale kdyz ted koukam na tabulku exec monitor detail - events, tak tam se to chova rozumne. Jak je to tam nastavene? Bo standardne to vypada takto: 

![screen shot 2014-02-07 at 8 50 33 am](https://f.cloud.github.com/assets/3014917/2107538/94277308-8fcc-11e3-8403-a3a504ad290c.png)

A kdyz tu tabulku zmensim prilis, tak se objevi posuvnik:

![screen shot 2014-02-07 at 8 50 45 am](https://f.cloud.github.com/assets/3014917/2107542/b21f84ae-8fcc-11e3-8148-292714dc43dd.png)

Nicmene povsimni si, ze i v tom normalnim zobrazeni tam ta short message neni cela, tedy dlouha short message si nevynuti scrollbar. Na druhou stranu se nikdy nestane, ze by short message sloupec byl extremne maly. Neco podobneho bychom chteli pro pipeline name i v hlavni tabulce exec monitoru.

**Comment by tomas-knap** [comment]
K te pevne sirce, urcite prosim zmensi status a debug: 

![screen shot 2014-02-07 at 8 43 04 am](https://f.cloud.github.com/assets/3014917/2107505/8b78476a-8fcb-11e3-92f3-e7a7506a6207.png)

**Comment by tomas-knap** [comment]
K tem combo boxum jen s ikonou, udelal jsem #1195 jako future work

**Comment by bogo777** [comment]
Upravil jsem sirky sloupcu, snad uz to vypada docela dobre. U te "natural" width, ktera se pouziva i v te Events table, se zjevne pri pocitani minimal width neberou v uvahu vsechny/aktualni radky.

Nevim presne jak to funguje, ale da se to snadno vyzkouset resizem okna. Muzu se zkusit podivat, jestli o tom nekde neco nepisou.

**Comment by tomas-knap** [comment]
Takhle, podstatne je, aby to fungovalo nejak rozumne, tedy sloupce, ktere mohou mit pevnou sirku, necht ji maji. Ale nesmi se stat toto (viz sloupec pipeline name): 

![screen shot 2014-02-07 at 3 14 57 pm](https://f.cloud.github.com/assets/3014917/2110403/40cfc760-9002-11e3-92d4-b9faf02d37ad.png)

**Comment by tomas-knap** [comment]
Bohuslave, jeste bych poprosil udelat tam konstanty, ktere budou drzet aktualni pozadovane sirky sloupcu. At nemusim v budoucnu resit, ze chci upravit sirku, ale zapomenu to upravit na vice mistech. Tedy necht je v uvodu tridy serie konstant typu "COLUMN_PIPELINE_NAME_WIDTH"

**Comment by tomas-knap** [comment]
Dodelej prosim ty konstanty, at muzem uzavrit. Jinak jsem spokojen.
