### ISSUE TITLE
Adjust RDF module

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1138]
Adjust core interface methods, so that they:
- use the similar pattern as FileDataUnit (getGraph, collection of statements)
- do not use openRDF types in interfaces

Separate the logic for DPU from logic used by the app

**Comment by ghost** [comment]
? tomas-knap rethink this or close

**Comment by tomas-knap** [comment]
won't fix, we will use openRDF, at least for now. We may add support for Jena later.
