### ISSUE TITLE
Pipeline events should occur as they are emitted

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#114]
Problem: I implemented DPU extractor and forget to addDataUnit(). Then I create pipeline with such extractor and RDF file loader. When running/debugging pipeline, no events occur. When I was debugging the code, I realized that the first DPU (extractor) emitted two events - successful START, END and loader (the second DPU) emitted one error event (because method (RDFDataRepository) context.getInputs().get(0); throw OutOfBound exception, there was no data unit). However, no events appeared in the debug view dialog after pressing refresh.

Solution: New events should appear when button "refresh" is pressed and the event is available. No need to wait till the pipeline finishes. Similar as #113 

Bohuslav, let me know if this is complicated somehow.

**Comment by bogo777** [comment]
For fetching events, I use only pipeline execution instance, which I have from beginning. With every refresh, I ask dpuFacade for all events regarding current pipeline execution. So it is propably issue on backend, as to when these events are propagated to database. 

But when I debug DbPedia pipeline, I get Extractor started and Missing configuration ... events long before extract is completed...

**Comment by tomas-knap** [comment]
Yes, that is true. But for the case I described, i did not get any event and the pipeline remain unfinished, no events occur. So we should assign Jan to this task?

**Comment by bogo777** [comment]
Yes, or Petr, I do not know which one of them worked on this particular funcionality.

**Comment by skodapetr** [comment]
Tomas are there any other scenarios that can be used to replicate this or I must modify one DPU to not use addDataUnit?

**Comment by tomas-knap** [comment]
I do not know, I come across that during this scenario.

**Comment by tomas-knap** [comment]
Cannot reproduce right now, so I will close it. See #115
