### ISSUE TITLE
Count query on empty data unit

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1143]
When running select (count(*) as ?x) where {?s ?p ?o}
on empty data unit, it should show one cell with "0", not:

![screen shot 2014-01-30 at 4 39 22 pm](https://f.cloud.github.com/assets/3014917/2041411/dc7707da-89c4-11e3-8e9e-c45188cf28bd.png)

Please check what your methods return.

**Comment by tomesj** [comment]
Problem propably solved thanks solving issue #1172.

Sceen of empty DPU as a proof:
![empty](https://f.cloud.github.com/assets/3481055/2090931/d5264df8-8e9a-11e3-8f43-24923baa9d1e.jpg)
