### ISSUE TITLE
Log query used by core DPUs

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1148]
For every SPARQL extraction (and also SPARQL transformation and LOADER), there must be log.debug containing the request send to the SPARQL endpoint. This is missing.

This is needed so that I can debug why certain SPARQL query did not result any data

**Comment by tomesj** [comment]
SPARQL transformer never use SPARQL endpoint, it goes only about SPARQL extractor and loader. 

I add this log.debug message to every type of possible request (GET, URL encoded POST, direct POST).

**Comment by tomesj** [comment]
I add log.debug message to all possible request variants (include info about sparql endpoint, request content,response code,response message + uncoded query in direct POST case).

**Comment by tomas-knap** [comment]
Diky
