### ISSUE TITLE
NPE when setting "Status" filter to nothing

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#1151]
![image](https://f.cloud.github.com/assets/718827/2050502/4bd9a0f4-8a76-11e3-899d-fc75716b1635.png)

**Comment by tomas-knap** [comment]
Add steps to reproduce

**Comment by jakubklimek** [comment]
Click on running, click on “empty”.

**Comment by tomas-knap** [comment]
duplicates #1101
