### ISSUE TITLE
SPARQL loader needs to log (as INFO message) each loaded datapart

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#1152]
This way, I don't see whether it is loading or not.

**Comment by tomesj** [comment]
There are 2 possibilities using info message:
1] log.info(...) - you see in LOG tab -> log level INFO+
2] context.sendMessage(MessageType.INFO,...) - you see in EVENTS tab

What type did you mean ?

**Comment by jakubklimek** [comment]
Logger.info instead of logger.debug for the loadin part xxx log message

**Comment by tomesj** [comment]
OK, thanks :-)
