### ISSUE TITLE
Save action changes entity

### ISSUE THREAD

**Issue by ghost** [mff-uk/odcs#1157]
In the `PipelineFacade:154`, the save action actually changes the saved entity of foreign type `DPUTemplateRecord` (which should be managed in its own `DPUFacade` class).
When the pipeline is `PUBLIC` , it modifies all `DPUTemplateRecord`s in the pipeline to be at least `PUBLIC_RO` accessible. Without notifying the user of course. See the code:

``` java
    /**
     * Saves any modifications made to the pipeline into the database.
     *
     * @param pipeline
     */
    @Transactional
    @PreAuthorize("hasPermission(#pipeline,'save')")
    @Override
    public void save(Pipeline pipeline) {

        // If pipeline is public, we need to make sure
        // all DPU templates used in this pipeline are
        // public as well.
        if (ShareType.PUBLIC.contains(pipeline.getShareType())) {
            for (DPUTemplateRecord dpu : getPrivateDPUs(pipeline)) {
                if (ShareType.PRIVATE.equals(dpu.getShareType())) {
                    // we found a private DPU in public pipeline -> make public
                    dpu.setVisibility(ShareType.PUBLIC_RO);
                    dpuFacade.save(dpu);
                }
            }
        }
        pipeline.setLastChange(new Date());
        pipelineDao.save(pipeline);
    }
```

**Comment by tomas-knap** [comment]
It should be documented in the method description that it automatically changes the visibility of DPU. 

But on the other hand, facade may provide access to more than dao class

**Comment by ghost** [comment]
I would prefer to notify the user about errors in his pipeline design, rather than changing underlying things without user notification.

**Comment by tomas-knap** [comment]
User is notified about that, so at GUI, it is solved. When certain private
dpu is saved on the pipeline being public, user is notified that all DPUs
will become public

**Comment by tomas-knap** [comment]
Can we close this?

**Comment by ghost** [comment]
Yes.

**Comment by ghost** [comment]
Wontfix
