### ISSUE TITLE
Prepare RDF Repository facade for DPU developers, which is easy to use and will not change often

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#116]
It would be good to prepare special interface (facade) for DPU developers who would like to work with RDF data units - to extract RDF from file, execute sparql query, ...

Motivation 1: Jirka is still changing method extractRDFfromFileToRepository, which always invalidates all DPUs created. It is necessary to have rather simple interface with simple methods, which will not change - certain methods may be added, but they should not be deleted. Further, method extractRDFfromFileToRepository with 6 params (extractRDFfromFileToRepository(FileExtractType.UPLOAD_FILE, null, null, null, true, true) is really not something, which can be exposed to DPU developers. 

Motivation 2: Current interface to RDF repository is rather complex, certain methods are not needed for DPU developers

**Comment by skodapetr** [comment]
Current state: Jirka is working on implementation. I need from him detail about how to use new methods .. once I will have this information I will replace the RDFRepository with RDFDataUnit in Backend, module help classes, tutorial .. etc ..

**Comment by tomas-knap** [comment]
Ok, so when you arrive, please arrange discussion with Jirka

**Comment by skodapetr** [comment]
I do not know about nothing to do from my side. Reassign to Jirka. 
We may discuss the RDF interface/implementation on next meeting to decide/validate it's final architecture.

**Comment by tomas-knap** [comment]
This is already done
