### ISSUE TITLE
Adjust Devel Doc Chapter - Requirements

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1164]
https://grips.semantic-web.at/display/UNVI/2.+Requirements+Specification

Je potreba upravit tuto stranku a vsechny jeji podstranky (!) tak, aby: 
- obsahovali aktualni obrazky, obsahovali popis aktualniho stavu. 
- to, co se nakonec nestihlo, tak je treba presunout pod prislusny nadpis na stranku: 
  https://grips.semantic-web.at/display/UNVI/Future+Work
- Snaz se mazat co nejmene veci, jen co opravdu neni pravda/neni implementovano. Pokud nevis, tak se poptej prislusne osoby, ktera stranku delala, pripadne napis hromadny mail

Bude to druha kapitola ve vysledne vyvojove dokumentaci. 

Deadline: 10.2.

**Comment by tomas-knap** [comment]
Jaky je stav tohoto issues?

**Comment by kukharm** [comment]
vyreseno
