### ISSUE TITLE
Generate and check javaDoc

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1165]
Jirko, take je potreba nechat si vygenerovat javaDoc (do 11.2.), http://maven.apache.org/plugins/maven-javadoc-plugin/, a zkontrolovat vysledek. Pokud najdes nejake nedokumentovane public tridy/metody/atributy, tak je potreba doplnit, resp. kontaktovat autora a uhanet ho, aby to doplnil.

Prioritni je develDoc, tohle hned pote.

**Comment by tomas-knap** [comment]
Jaky je tedy stav?

**Comment by tomesj** [comment]
viz poslaný mail

**Comment by tomas-knap** [comment]
A ty problemy v tom mailu poslane uz jsou vyresene? Jaky ja aktualni stav?
