### ISSUE TITLE
Serialized configuration should use String instead of byte array

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/odcs#1167]
Based on #1155

**Comment by ghost** [comment]
Could we also take a look onto why we need to handle the serialization manually? 
Couldn't we use a library for serialization?
At least, there are plain java serialization capabilities, I mean the ObjectInputStream and the ObjectOutputStream (but I don't vote on these).
Why gobble around with things, which are probably solved somewhere already.
Lets do the research on this.

For example, what do you think of this: let the DPU programmer declare DPU configuration bean, then add our annotation onto it. Our framework will take care about persistence of the configuration bean, will provide a singleton read-only instance of the configuration bean to the DPU instance in the backend. Will provide a singleton read-write instance of the configuration bean to the configuration dialog in the frontend.

**Comment by skodapetr** [comment]
We are using XStream for serialization ( http://xstream.codehaus.org/ ).

DPU Programmer declare configuration class that implements DPUConfigObject (what is the different to the bean?)
Add annotation .. we may consider this, actually user can use XStream annotation, what annotations do you thing we should support?

You speak about read-only instance. Why read only? and how would you secure that it's read only? For example: you may prevent user for assigning new list into existing one (provide only getter) but if user call some method that modifies the content - how can we secure read-only access for such case?

**Comment by ghost** [comment]
Sorry, will take a better look on this. At this time, I accept everything you've stated.

**Comment by skodapetr** [comment]
Musel jsem nechat starý přístup k serializaci kvůli zpětné kompatibilitě a potížím s null value ve Virtuosu. Nicméně mimo metodu se nyní pracuje se String místo byte[].
