### ISSUE TITLE
TEST tool tip in case of logs

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1168]
See below:

![image](https://f.cloud.github.com/assets/718827/2058187/ddcd49f6-8b62-11e3-80d9-5b01a7b2ede5.png)

The tooltip should contain the long message. Or it should be removed.

**Comment by bogo777** [comment]
I removed the "TEST" label and set the message as content of tooltip. But it doesn't show anything for me.

**Comment by tomas-knap** [comment]
Tooltip currently not working, probably because of #1208
