### ISSUE TITLE
Log detail, long message should be wrapped

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1171]
![screen shot 2014-02-05 at 11 18 09 am](https://f.cloud.github.com/assets/3014917/2085961/e99f9f56-8e4e-11e3-95d2-d8a72ec6698a.png)

Currently: scrollbar occurs

**Comment by ghost** [comment]
resolved here:
https://github.com/UnifiedViews/Core/commit/369867885cb16031c01694a3c7574cb82e41402d
