### ISSUE TITLE
Browse/query - data is lost

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1172]
Happens on ODCS-test

To reproduce: Open dbpedia pipeline, debug the SPARQL extractor, go to browse/query, select SPARQL extractor, output data unit, click on "run query". It shows some data. Then try to filter predicates according to e.g. string Jirka. No data appears. 

Then switch to execution monitor, open the same exec record detail, go to browse/query - no data available. 

So something strange is happening to the data.

**Comment by tomesj** [comment]
This problem could be fixed now :-)

**Comment by tomas-knap** [comment]
Could be solved or is solved? ;)

**Comment by tomesj** [comment]
Is solved :-)
