### ISSUE TITLE
Execution monitor - debug data

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#1178]
Tabs on Debug data view are missed
![debug](https://f.cloud.github.com/assets/3471169/2086770/b760906c-8e5e-11e3-902d-9da9394ca3c1.jpg)
and also i can't find the Close button there

**Comment by kukharm** [comment]
It happens when i click on the debug data button on the first time, when i click after that to the other Debug data or Show log buttons, tabs appear

**Comment by bogo777** [comment]
Close button was removed as part of changes in #1129.
Tabs issue is duplicate of #1123.
