### ISSUE TITLE
Automatically create RDB schema and upload initial data when not present

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#118]
Automatically create RDB schema and upload initial data when not present.

No need to force potential users to do this manually.

**Comment by tomas-knap** [comment]
This should work for clean install. However, if the automatic creation realizes that certain crucial tables are already present, it should not try to adjust the database in any way. User should be able to manually either recreate the whole database or update from previous version if he encounters any problems later.

**Comment by tomas-knap** [comment]
will be solved when preparing installer

**Comment by janvojt** [comment]
I suggest closing this issue. Creating database schema during runtime is very uncommon and even if implemented well, it will be unstable. We do not know what is the state of database, if everything is broken, only certain part is missing, whole db is missing, etc. It would be pretty hard to guess from the exception caught.

For installing, we have issue #712.

**Comment by tomas-knap** [comment]
Initial sql execution by import script
