### ISSUE TITLE
Collapsing columns in Vaadin tables

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1188]
It seems that Vaadin has a direct support for the user to select which columns should be shown: 

https://vaadin.com/book/-/page/components.table.html

Collapsing Columns
When setColumnCollapsingAllowed(true) is set, the right side of the table header shows a drop-down list that allows selecting which columns are shown. Collapsing columns is different than hiding columns with setVisibleColumns(), which hides the columns completely so that they can not be made visible (uncollapsed) from the user interface.

Question: Can we use this to provide user a way to select which columns should be dispalyed?

**Comment by bogo777** [comment]
Yes, it can be done. I allowed it for our tables, it seems to work fine. Only downside is, that it hides part of the column header if the last columns header takes full width of the column...
