### ISSUE TITLE
Module Frontend documentation

### ISSUE THREAD

**Issue by bogo777** [mff-uk/odcs#1189]
Describe the important groups of classes in the package - components, views. Describe the use of all add-ons (PagedTable, ... ). Describe the idea of canvas, how it is implemented so that it fits to Vaadin framework. Describe a sequence diagram showing exactly what happens when certain table (e.g. pipeline list) is being prepared. How the container in commons-app is extended with Vaadin filters. MVP is discussed on a separated page.

https://grips.semantic-web.at/display/UNVI/Module+Frontend

**Comment by tomas-knap** [comment]
pridej prosim odkazy na ty addons zminene

**Comment by tomas-knap** [comment]
pak uzavri
