### ISSUE TITLE
Model View Pattern in Frontend

### ISSUE THREAD

**Issue by bogo777** [mff-uk/odcs#1190]
Describe general idea, describe pipeline list example in our case, describe for which views it was already applied 

https://grips.semantic-web.at/display/UNVI/Model+View+Pattern+in+Frontend

**Comment by tomas-knap** [comment]
class diagram urcite pridat

Take tam prosim dej sequence/activity diagram, aby bylo jasne, co se stane, kdyz se ma zobrazit pipeline list. A co se deje, kdyz se trebas kopiruje pipeline.
