### ISSUE TITLE
Developer Documentation - Core DPUs

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#1193]
Page: 
https://grips.semantic-web.at/display/UNVI/Core+DPUs

Describe all available core DPUs, Describe an idea of the implementation.

**Comment by tomas-knap** [comment]
Pripominky: Marie v nekterem z poslednich mailu psala, dle jake zasady se pouziva bolded font. To je treba dodrzet, nic dalsiho neztucnovat:

Pokud je to nazev  GUI sekce, tak je tucne a velkym pismem napr Execution monitor a i uprostred vety
Pokud je to nazev pole ci tlacitka v  dialogu, jsou tuna kurziva  a velkym pismem take (uprostred vety) napr Cancel button, Description field.
Pokud je to jen termin a tak to budu psat tucnym a s malym pismem uprostred vety (pipeline, execution record, dpu template...).

**Comment by tomas-knap** [comment]
Projdi znovu, neda se to cist, oprav preklepy

**Comment by tomas-knap** [comment]
oprav vsude to finded

**Comment by tomesj** [comment]
Má to být found nebo něco jiného ?

**Comment by tomas-knap** [comment]
jj

**Comment by tomesj** [comment]
Tak jsem opravil chyby, co jsi psal a ještě jsem našel a opravil další díky free-spell checkeru. Sám jsem našel jen 1 a check mi jich našel ještě dalších asi 6, které jsem předtím vůbec neviděl. 
Dám to pak pro jistotu ještě někomu přečíst. 

Jinak jsem tam použil ty styly fontování, co psala Marie. Doufám, že je to v tomhle ohledu vše dobré. Kdyby se něco nelíbilo, dejte mi vědět.

**Comment by tomas-knap** [comment]
Stale je tam zeleny text, co nejdriv doladit!

**Comment by tomas-knap** [comment]
Jirko, sparql transformer, v diagramu mas: "replace DPU name in query..." -> to by melo byt replace DU name, ne?

**Comment by tomas-knap** [comment]
Podobne v textu u sparql transf - Both types support DPU replacement feature - It allows using SPARQL queries variables in a special format.

Tahle veta neni jasna, vysvetli prosim lepe. 
To neni DPU replacement feature, to je maximalne DU name replacement.

**Comment by tomas-knap** [comment]
Pak zavri

**Comment by tomesj** [comment]
Přejmenovány na příslušných místech na DU
