### ISSUE TITLE
Developer Documentation - RDF-impl

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#1194]
Page:
https://grips.semantic-web.at/display/UNVI/RDF-impl
- Describe the idea of openRDF, its architecture, which modules it provides, which modules we use.
- Describe the idea of repositories -  localRDF, Virtuoso. How do these repositories differ. - Describe for both repositories how they are initialized, release, where the intermediate results are stored.

**Comment by tomas-knap** [comment]
Jirko, mas tam neco o openRDF, fine. ALe urcite tam musi byt prehled trid (class diagram) a musi byt popsano proc tam jsou jak tam jsou.

**Comment by tomesj** [comment]
Popis tam už je, též jsem tam přidal i názorné class diagramy :-)

**Comment by tomas-knap** [comment]
Jeste viz ten mail: tedy RDF data unit interface - methods for developers

**Comment by tomesj** [comment]
Tak stránka přidána.
