### ISSUE TITLE
Doc: Dao

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/odcs#1203]
https://grips.semantic-web.at/display/UNVI/DAO+Layer

**Comment by tomas-knap** [comment]
Toto nebude jasne ctenari: 
This object is a parameter in all interfaces, which should secure compile time control of the given dao layer implementation. The idea is to prevent user using dao layer for object A together with object B. It also specified that every object that can be possibly handled by dao implementation must provide some identification - id.

**Comment by tomas-knap** [comment]
Proc potrebujem data query a query count? "empty interfaces for data query and query for count. " To je treba vysvetlit

**Comment by tomas-knap** [comment]
Chtelo by to nejaky aktivity diagram, ktery ukaze, co se stane, kdyz se ta dao vrstva pouziva trebas pro naplneni nejake tabulky v GUI. Jinak neni jasna motivace tech jednotlivych trid. A tim diagramem ukazes pouziti dao i kontejneru. Je mozne ze to mas nekde u GUI, pak staci odkaz.
