### ISSUE TITLE
Doc: OSGi

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/odcs#1204]
Renamed to "Dynamic DPU loading"

https://grips.semantic-web.at/display/UNVI/Dynamic+DPU+loading

**Comment by tomas-knap** [comment]
Nechapu: The loading-unloading of DPUs on non-developer instance is rare. Thanks to this we may assume that the resources-services-classes will almost not be uninsulated. With this feature it may be easier to add some additional support-functionality without using the third-party framework.

Prosim vysvetli lepe

**Comment by tomas-knap** [comment]
Zminil bych tam, ze mame ten skript (zatim jen PowerShell?), ktery nam usnadni praci pri uspokojovani zavislosti.

**Comment by skodapetr** [comment]
Přidal jsem komentář ke skriptu. Na localu mám i bash .. nicméně tam mi maven spadne na access denied .. tedy nevím zda je to chybka někde, nebo zda na linuxu to poběží. Ale než si někdo z venku dokumentaci přečte, tak to již budeme mít odladěné. 

Zmatečnou část jsem vyhodil, ona tam byla stejně svým způsobem navíc.
