### ISSUE TITLE
Adjust DPU Template src file and tutorial 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#121]
zjednodusit rozhrani (resp. udelat facade, ktera uzmozni skryt detaily pro pokrocile uzivatele)
RDFDataRepository outputRepository = (RDFDataRepository) context.addOutputDataUnit(DataUnitType.RDF, "output");
-> dodat metody ktere primo pracuji s RDF repository typu: 
RDFDataRepository outputRepository = context.addRDFOutputDataUnit("output");
- [7/11/13 9:14:54 PM] Tomas "nappy" Knap: vysvetlit a pravdepodobne upravit dulezite metody contextu a dataUnit, ty metody na repository - ty jsou asi nejvic matouci. Kdyz mrknes na ty 3 metody, co tam ted Jirka ma a mame je vylistovane v tutorialu vubec nepusobi konzistentne a maji nektere mraky atributu - to je ok, ale musi tam existovat napr. i metoda extractFromFile s jednim atributem. Ja bych tam udelal to rozhrani metod, ktere autori DPU typicky muzou potrebovat, aby tam nebylo jedno velke repositiory API. Taky je problem, ze Jirka ten interface meni. Popsat dataUnit.getList().filterByName(), popsat praci s names. 
- abstract ConfigurableBase<T>, ktera by obsahovala metody configure(), getConfiguration() uz implemnetovane. 
  --Pridal jsem tuhle tridu do commons, Melo by pak stacit u vsech DPU extendovat tuhle tridu misto implementace Configurable interface. Zkus prosim, ale melo by to fungovat. ConfigurableBase by mela byt urcite v DPU template tutorial, tedy aby to mel developer co nejjednodussi.
- Vice prikladu do tutorialu pro tvorbu DPU (ted je tam jen ukazka jedne metody transform pro SPARQL)

**Comment by tomas-knap** [comment]
Petre, are all these comments relevant? If you have any idea to that, please discuss here

**Comment by tomas-knap** [comment]
Petre, regarding the ConfigurableBase, the protected T config, should work as expected, no need for the contstructor...if you extend ConfigurableBase<XXXConfig>, then the compiler will replace all occurences of T with XXXConfig, so the runtime does not even know that there was some type T. 

If there is a problem,e.g. when T does not extend Config, then the problem occurs during compilation.

So under the condition that engine always calls: configurable.configure(configuration) before executing DPU, DPU has all the configuration from the dialog (DPU Detail). If the DPU has further configuration not provided via DPU dialog, it should be stored internally in the DPU implementation class.

**Comment by tomas-knap** [comment]
Please also include sample use of DPU events and when these events should be used when compared with slf4j

**Comment by tomas-knap** [comment]
Petre, please summarize what is done, will be done and what is rejected ;)

**Comment by skodapetr** [comment]
1) RDF DataUnit class draft has been created and now it waits for implementation-changes in #208, but there will be some changes in draft probably - based on Thomas suggestions
2) class commons-module.ConfigurableBase is being prepared in my local branch and should be available (and used by core DPUs) in less then four days
3) nothing done in this yet ... I think it would be nice to show examples on some real DataUnit, but RDFDataUnit is not ready now ( #208 ) as far as I know

I would like to ask to change the target iteration from 0.3 to (early) 0.4
