### ISSUE TITLE
Download logs - not working properly?

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1211]
When launching pipeline from canvas and clicking on "download logs" as the pipeline is still running, nothing happens - tested for exec 348 on ODCS-TEST

Please test download logs, you can use ODCS-test

**Comment by tomas-knap** [comment]
Does not work anywhere

**Comment by skodapetr** [comment]
poznámka: zkoušel jsem na ODCS na exec 667 z monitoru a tam vše pracovalo jak mělo.

**Comment by tomas-knap** [comment]
Seems to be working again - on odcs-test

@bogo777  Did you change something?
