### ISSUE TITLE
Add replacement feature for SPARQL update queries in SPARQL transformer

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#1215]
Same as for Construct queries in SPARQL transformer

**Comment by tomas-knap** [comment]
Jirka:
Teď jsem se chtěl pustit do implementace té DPU replacement pro update query, ale má tam vůbec smysl ? 

Máme nějaké vůbec reálné využití toho pro update query ? Žádné mě totiž nenapadá. Myslím, že pro update to vůbec není potřeba. Update se provádí nad těmi data, co mám v transformeru. Když už tam vedu hranu, tak nad nimi dotaz provádět chci. 

Tomas:
To neni pravda. Update query ma tvar: 

Insert {triples}/ delete {triples} where {triplesInOrigGraphs}

A za tim where maji ty placeholders stejny smysl pro construct i pro update. Muzu napriklad vytvaret nove trojice na zaklade toho ze v jednom vstupu mam neco a v jinem neco. 

Jirko, v cem je tam problem? Ted ty placeholders resis jen pro ty CONSTRUCT queries. Nicmene, v cem je problem to aplikovat na vsechny queries? Vzdyt ty samotne metody co ti resi ty placeholders vubec nijak nesouvisi s tim jestli je to CONSTRUCT nebo SPARQL update query, ne? Nebo v cem tam vidis problem? Mne se zda, ze je to refactoring na 2h + 2h testovani (to je dulezite).

**Comment by tomesj** [comment]
Jako mě je jasné, jak to myslíš, jen se bojím, aby tam nebyl nikde zádrhel. 

Možná mi napiš příklad nějakého update dotazu,kde to bude použito, abych se přesvědčil, že to co už máme, můžeme použít i tady.

Teoreticky asi jo, ale chtěl bych mít jistotu, než tam budu něco měnit. Jinak pak bude asi potřeba změnit komentáře v dokumentaci a názvy metod, ale to nebude takový problém. 

Díky

**Comment by tomas-knap** [comment]
Jirko, to pouziti tech placeholderu je presne stejne jako u construct
queries. Tam neni zadny rozdil. Priprav prosim v tech JUNITech jeden
construct a jeden sparql update. Posli mi ten construct/sparql dotaz, ktery
chcec pouzit a testovaci data, na ktera ho chces pouzit a ja ti ho
zkontroluju.

2014-02-16 14:10 GMT+01:00 Jiří Tomeš notifications@github.com:
