### ISSUE TITLE
Pipeline executions and cancel

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1217]
Pipeline exec 687 ODCS - skoncila ve stavu failed, ale neni tam zadna event typu error. To je divne. Je tam jen ERROR. 

Jak k tomu doslo: Pipeline bezela, Kuba ji zrusil, nez dobehlo zruseni tak jsem restartoval backend. 

Jeste je tam jeden problem, kdyz je DPU cancelled, tak ikdyz to ruseni dobehne v pohode, tak pri restartu pipeline by se to DPU nemelo preskocit a melo by se znovu provest. Podle te exec 687 to vypada, ze se zrusene DPU uz znovu neprovedlo.

**Comment by skodapetr** [comment]
Ke druhé části, pokud je pipeline ve stavu cancelled a udělá se restart tak se DPU již neprovádí. Tedy tohle bychom museli zahrnout jako požadavek na novou feature.

**Comment by tomas-knap** [comment]
jj, tak to bylo myslene. Jelikoz tim, ze bylo zrusene, tak se da ocekavat, ze neudelalo spravny output a tudiz nema cenu pokracovat od dalsiho

**Comment by tomas-knap** [comment]
Slo mi o to, ze by se to melo chovat tak, ze kdyz nejakou pipeline chci zrusit a nez to zruseni probehne, tak restartuju backend, tak by se ta pipeline nemela znovu spustit. Pokud to takto funguje, muzem zavrit.

**Comment by skodapetr** [comment]
Mělo by se to chovat jak popisuješ.
