### ISSUE TITLE
Adjusting requirements

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1219]
For the pages below, it is necessary to read them through, check all the text and adjust if needed. Especially the red text has to be adjusted. 

https://grips.semantic-web.at/display/UNVI/Debug+Pipeline

https://grips.semantic-web.at/display/UNVI/DPU+Configuration

https://grips.semantic-web.at/display/UNVI/DPU+-+Validator+of+RDF+data

https://grips.semantic-web.at/display/UNVI/DPU+-+RDF+File+Extractor
https://grips.semantic-web.at/display/UNVI/DPU+-+SPARQL+Extractor
https://grips.semantic-web.at/display/UNVI/DPU+-+SPARQL+Loader
https://grips.semantic-web.at/display/UNVI/DPU+-+RDF+File+Loader

Je potreba udelat novou stranku o SPARQL transformer. Stavajici jsem dal do FW, bo jsou tam nejake veci co jeste ted nemame. Inspiruj se tou puvodni strankou

https://grips.semantic-web.at/pages/viewpage.action?pageId=42730318

**Comment by tomesj** [comment]
Stránky jsem si přečetl :-) To, co se mi nezdálo jsem opravil, přepsal na aktuální stav, případně napsal výtky do komentáře.

**Comment by tomas-knap** [comment]
Cist + 
https://grips.semantic-web.at/display/UNVI/Core+DPUs

**Comment by tomesj** [comment]
Číst - chápu to jako čtení dokumentů a dokumentace obecně (co vzniká)
Core DPUs - to jsi myslel jak ? Stránku jsem v poslední době upravoval mnohokrát. Doufám, že už tam chyby nebudou. Nyní jsou tam komentáře Petra a moje a čekáme až se k tomu vyjádří někdo další... Jak to vidíš ty ?

**Comment by tomas-knap** [comment]
To je poznamka pro me, tedy ted je to na me, abych to prosel. Jen se prosim ujisti, ze tam nejsou zadne nesmysly

**Comment by tomesj** [comment]
Díky za ujasnění.
No já doufám, že tam nesmysly nebudou. Projel jsem ti i spell checkerem a nic mi to už nenašlo, Petr si to také četl. Jak jsem psal - jsou tam akorát místy ty naše komentáře - záleží jak se to vyhodnotí.
