### ISSUE TITLE
Sparql Loader inserting problem

### ISSUE THREAD

**Issue by Jan-Marcek** [mff-uk/odcs#1222]
Hello,

I get this error message: Inserting failed to 1/13 data part. HTTP/1.1 400 Bad Request. Inserted data has wrong format. Caused by Virtuoso 22023 Error The request does not contain text of SPARQL query URL endpoint: http://localhost:8900/sparql-auth POST direct content: INSERT 

I have a problem with uploading rdf's file to a virtuoso server. I'm using the SPARQ loader. I created pipeline in the "http://odcs.xrg.cz:8080/odcleanstore-test/". The name of pipeline is "test org". You can see it there when you run the pipeline.
I don't know if it is some configuration problem or bug.

Can you explain to me the parameters in the SPARQL loader? I mean parameters such as "Query param", "Default graph param", "Use POST request with URL-encoded" and "Use POST with unencoded query". I haven't found any documentation for this module.

Thank you very much

**Comment by skodapetr** [comment]
Duplicit to #1222, closing
