### ISSUE TITLE
Popsat lepe role user/Admin v user doc, zkontrolovat v requirements spec. 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1224]
Koukni na to Petre prosim
1. Nejsou tam poradne nekde v uvodu vysvetlene ty role user/admin. To musi byt, nejlepe nekde dole na hlavni strane za popisem sekci

Potrebuju aby to mi nekdo vysvetlil. Honza, Petr? Kdo o tom nejvic vi? v requirements specification to take nepopsano poradne https://grips.semantic-web.at/display/UNVI/System+roles (na to jsem uz upozornovala v jednem z predhozich mailu)

**Comment by skodapetr** [comment]
Neco jsem zkusil, ale neni to zrovna moc ukecane tema ..
