### ISSUE TITLE
Pipeline edit

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/odcs#1225]
Nevim zda je aktualni ale:
1) Zalozim pipeline, nastavim ji na publiv_rw, prihlasim se jako jiny uzivatel (ne admin) a mam moznost zmenit (ten selectio je enabled) viditelnost na public_ro. 

2) Dalsi vec je, takovou pipeline nemohu smazat .. nemelo by se pak skryt to tlacitko pro mazani? (takhle mi to dovoli kliknout, pak nasleduje hlaska, ze to nelze).

@tomas-knap To by tak tusim byt nemelo.

**Comment by tomas-knap** [comment]
ad 1) To by nemelo jit. Menit by to mel mit moznost jen Administrator a autor pipeline. Tohle je na @janvojt 

ad 2) Uprav prosim @bogo777

**Comment by janvojt** [comment]
ad1) Hmm, implementacia nebude uplne jednoducha. Musel by som si pri volani save nacitat pipeline z db a porovnat ci user meni stav. Logicky to aj trochu dava zmysel tak ako to je - ak mozem napr z pipeline zmazat vsetky dpu, preco by som ju nemohil zmenit z rw na ro... Kazdopadne, nebude najjednoduchsie proste len v UI disablovat ten radiobox? Tympadom by to bolo na Bohuslava. :D

ad2) schovavanie delete tlacitka som doplnal vcera, mas aktualnu verziu?

**Comment by tomas-knap** [comment]
To by mi davalo smysl, tedy ze menit radiobox je k dispozici pouze autorovi pipeline/adminovi. Pro ostatni je taky k dispozici, ale greyed. To jsi myslel?

**Comment by skodapetr** [comment]
Je to zkoušeno na ODCS-test .. tedy je možné, že aktuální není a asi nebude pokud jsi tam dělal takovou změnu. Proto jsem tím ihned uvozoval začátek issue. 

Co se týče 1) byl bych spíše pro disable toho switche (tak jsem to i myslel) .. ke myslu po zamyšlení možná, ale když jsem tou aplikací klikal jako user tak mě to překvapilo. ppřeci jen že smažu vše pipeline dá to práci .. tak asi proč by né. Ale tohle .. byl jsem v pokušení na to zkusit kliknout, jen proto že to jde .. a tím bych si pod sebou podříznul větev.

**Comment by janvojt** [comment]
Ano.
