### ISSUE TITLE
Minor issues in exec detail tables

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1230]
1) Column type in log table should have the same size (minimum) as in case of exec detail - events table. 

2) When resizing exec monitor detail - the column date/timestamp on tables events/log should have fixed width

3) Use either date or timestamp as a label for column in both cases (logs/events table)

4) DPU instance column should have the fixed width based on the longest DPU instance name (if easy)

5) short message column should have natural width (events/logs) - Probably ok, just check

**Comment by bogo777** [comment]
Ad 4) We are providing own component as filter, so the table doesn't know the proposed width, but it will only be bigger, when the space is not needed by mesage column. Alternatively we could count the longest DPU label and guess the width...

**Comment by tomas-knap** [comment]
Ok, let's leave that for fw

**Comment by tomas-knap** [comment]
Not important
