### ISSUE TITLE
Query validator for sparql transformer must say which query was not valid

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1239]
If having more queries in SPARQL transformer, it is not clear where (in which query) the problem is if there is a problem 
![screen shot 2014-02-20 at 4 02 13 pm](https://f.cloud.github.com/assets/3014917/2219408/1962a830-9a40-11e3-8764-eb13169e3157.png)

Solution: Write something like: Validation of 1. query failed: ...

**Comment by tomas-knap** [comment]
Jirko, zkousim, kdyz se pokusim ulozit SPARQL transformer conf, tak dostanu: 

![screen shot 2014-02-24 at 11 10 07 am](https://f.cloud.github.com/assets/3014917/2244330/fba3d568-9d3b-11e3-82b6-2dc31588e7a1.png)

**Comment by tomesj** [comment]
O tomhle nic nevím, mě se configurace ukládá správně, jak má :-) Máš poslední verzi ?

**Comment by tomas-knap** [comment]
Spis je otazkou, zda jsi neco nezapomnel dodat na git. Zeptej se prosim na schuzce nekoho, at to zkusi u sebe

**Comment by tomesj** [comment]
Dobře, snad někdo bude mít s sebou PC.

**Comment by tomesj** [comment]
Tak tohle vypadá, že je OK - zkoušeli jsme teď přímo na schůzce
