### ISSUE TITLE
Issue when running frontend in Tomcat on Windows - Config properties on wrong location?

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#124]
Frontend was trying to search config.properties searching in C:.intlib\config.properties, this is wrong, right?

HTTP Status 500 - com.vaadin.server.ServiceException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configuration' defined in class path resource [commons-app-context.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [cz.cuni.xrg.intlib.commons.app.conf.AppConfig]: Constructor threw exception; nested exception is java.lang.RuntimeException: java.io.FileNotFoundException: C:.intlib\config.properties (The system cannot find the path specified)

**Comment by tomas-knap** [comment]
Kubo, is your user.home set correctly? It could be find out in JAVA by calling System.getProperty("user.home"). We suppose user.home points to "documents&settings/name"

**Comment by tomas-knap** [comment]
Petre, I would recommend to separate the settings of the connection to the relational database for frontend from the config.properties to its original location within the xml file of the war file. The reason for that is that Tomcat may run under a different user (and typically runs), which means that the config.properties the user sets up may be unreachable. 

Do you agree on that?

**Comment by jakubklimek** [comment]
The best location would be web.xml in the war file, not the original persistence.xml.

This was discussed last week, what is the progress?

**Comment by tomas-knap** [comment]
Jakub, in order to be able to continue with your work, are you able to prepare workaround - that means to copy config.properties to the home dir of the user tomcat is running under? (could be C:/.intlib probably, if no home dir is available, just guessing).

**Comment by jakubklimek** [comment]
I would rather test the fixed version. Should not take long to fix this.

**Comment by skodapetr** [comment]
Honza is probably better person for this as he is author of the current AppConfig class.

**Comment by tomas-knap** [comment]
Ok, but Honza is out till Monday, so please Jakob use the workaround, Honza will fix that next week
