### ISSUE TITLE
Finilizing user doc

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1241]
Prepare the word document, ktery jirka vytiskne. 

Final version - nedele 23.2.

**Comment by tomas-knap** [comment]
Pripominky: 
- INTRO, section I.2, mensi nadpis, nelze mit na stejne urovni I.2 a I.3
- Chybi cislovani hlavnich kapitol, Cislovani je divne, nerespektuje hlavni kapitoly. 
- Upravit INTRO page
- Osklive tabulky, ty je potreba upravit, viz PipelineCreation
- Podivne predsunute odrazky Run/Debug/ in PIPELINES section
- DPU TEMPLATES SECTION -> to section slovo nedavajte do nadpisu
- Particular DPUs - to by mela byt hlavni kapitola
- Glossary bych dal na konec sekce INTRO. 
- Rada uprav aby to trochu vypadalo

Marie, jsi zodpovedna za tyto upravy.

**Comment by kukharm** [comment]
"Chybi cislovani hlavnich kapitol, Cislovani je divne, nerespektuje hlavni kapitoly. "
- cislovani tam je, jen to nezobrazuje google docs, nevim proc, vsihni kapitoly jsou ocislovane,

**Comment by tomesj** [comment]
Tu nerozumieme co Ti vadi:

> INTRO, section I.2, mensi nadpis, nelze mit na stejne urovni I.2 a I.3
> Upravit INTRO page

**Comment by tomas-knap** [comment]
Mno, slo mi o to, ze je na stejne urovni sekce Roles a Conventions, nebo
tak nejak, coz je divne. Jsou to tematicky uplne odlisne kapitoly
