### ISSUE TITLE
Research namespace length limits

### ISSUE THREAD

**Issue by ghost** [mff-uk/odcs#1248]
At first sight, I think that namespace prefix name (the abbreviation itself) has no max length limit in W3C specification (see http://www.w3.org/TR/xml-names/#NT-NCName).
We have the limit set to 25 characters and it is questionable, if this is enough for regular use, especially when the namespace name can be the URI itself.

**Comment by ghost** [comment]
TODO: also find out if a namespace can be of different scheme than http://. According to
www.w3.org/TR/xml-names/
namespaces are URIs. So it could happen that it is not always a http:// scheme. If so however, get rid of `PrefixCreate:142` starts with http:// validation.

**Comment by ghost** [comment]
And is 255 length of URI enough?

**Comment by tomas-knap** [comment]
For the namespace prefixes, 25 should be in general enough, but we can increase the limit to 255, which is for sure enough. 

In Linked data environment, every ontology term must be available on the Web, must be dereferencable. So there is no big sense to introduce a different namespace prefix than http://

Regarding length of URI - 2048 would be better.

**Comment by ghost** [comment]
I will fix this issue according to your guidance.

**Comment by ghost** [comment]
Resolved here: https://github.com/UnifiedViews/Core/commit/92e2407f403f5e74f1a03c4a48f1d9cd23041617
