### ISSUE TITLE
SPARQL Loader does not display number of loaded triples correctly

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#1249]
See odcs executions 824 and 825.

In 824 Loader gets 39720 triples, but skips most of them because of errors. But reports it has loaded everything (39720 triples) which is not true.
In 825 Loader gets 39720 triples, does not skip anything and reports 39720 triples loaded, which is hopefully true.

Report only those triples that were actually loaded.

Even better, perform a count on the target graph before and after loading and report the results (and the difference). If there is the "overwrite" option selected, then the results of the count and the reported number of triples should match.

**Comment by tomas-knap** [comment]
This could be solved after the CD is prepared and before the end of the week. But it must be done, because Jakub will be checking that

**Comment by tomesj** [comment]
Jakub, I add the following info:
1) Size of target graph before loading
2) Size of target graph after loading
3) Count of triples which are prepared for loading
4) Count of triples which were really loaded
