### ISSUE TITLE
Incorrect links in tutorial

### ISSUE THREAD

**Issue by martinnec** [mff-uk/odcs#1250]
In http://www.ksi.mff.cuni.cz/~knap/odcs/practice.html there are several incorrect links:

1) link to vaadin leads to http://www.ksi.mff.cuni.cz/~knap/odcs/www.vaadin.com - it should lead to the developers guide which says how to write vaadin components

2) link to OSGi leads to http://www.ksi.mff.cuni.cz/~knap/odcs/practice.html#osgi which is nothing.

**Comment by tomas-knap** [comment]
Tutorial is now different
