### ISSUE TITLE
Tabs in execution detail are missin first time they are rendered.

### ISSUE THREAD

**Issue by janvojt** [mff-uk/odcs#1252]
I hope it is not a duplicate.

![screenshot from 2014-02-22 11 11 42](https://f.cloud.github.com/assets/2247062/2237489/ffbc6bf6-9bab-11e3-8743-a61ca86f6e95.png)

**Comment by janvojt** [comment]
I cannot reproduce any more. It is possible it was fixed in recent days.

**Comment by bogo777** [comment]
We had this problem, it is described in #1123 and it should be fixed. Could you have got it on older version(before downgrading Vaadin)?

**Comment by janvojt** [comment]
It is possible I reproduced on older version. However Petr also said he reproduced this few days ago. I will try to reproduce again and if it does not happen I will close this...

**Comment by janvojt** [comment]
It seems like I did not do clean&build on frontend, so downgrading Vaadin had no effect on my deployment.
