### ISSUE TITLE
For SPARQL Transformer, the default query must be valid SPARQL 1.1. query

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1256]
Currently: 

![screen shot 2014-02-24 at 12 06 58 pm](https://f.cloud.github.com/assets/3014917/2244787/cb42a7e8-9d43-11e3-9a4a-af393d39bb0d.png)

Must be valid SPARQL  query (no "modify" keyword): e.g. CONSTRUCT {?s ?p ?o} WHERE {?s ?p ?o} LIMIT 10.

So what should be done - replace the current MODIFY query with the simple CONSTRUCT query - in SPARQL transformer, doc (user,devel)

**Comment by tomesj** [comment]
Do you mean change "tool tip text" to CONSTRUCT {?s ?p ?o} WHERE {?s ?p ?o} LIMIT 10 or set as default value?

**Comment by tomas-knap** [comment]
yes, tooltip (greyed text which dissappears when user enters the field), as it was

**Comment by tomesj** [comment]
Použil jsem dotaz:

PREFIX s: http://schema.org
DELETE { ?address s:geo ?geo}
INSERT { ?place s:geo ?geo}
WHERE { ?address a s:postalAddress; 
^s:address ?place; 
s:geo ?geo .}

Ten má marie i v dokumentaci SPARQL transformeru, takže ho nemusí ani upravovat.
