### ISSUE TITLE
Empty DPU description replaced with description of another DPU

### ISSUE THREAD

**Issue by martinnec** [mff-uk/odcs#1260]
In [ehealth] SUKL - KLK pipeline, I have a loader with an empty description (let denote it A). I opened the dialog of another DPU (let it denote it B) which has a non empty description and then closed it. If I now open A, I see the description of B. I also opened another DPU C with a description, and closed it. If I reopen A, I can now see the description of C in the description of A.

**Comment by tomas-knap** [comment]
@martinnec  Can you also reproduce that on en empty new pipeline? I am trying that, but the problem does not appear

**Comment by martinnec** [comment]
Try this:
- new pipe
- new sparql extractor A
- give a description abc to A
- new sparql loader internal B
- open B, you can see description abc

**Comment by tomas-knap** [comment]
Thanks, @bogo777, proper initialization is missing?
