### ISSUE TITLE
DPU tree is without hierarchy when filter is used 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1261]
When creating new pipeline, I filtered the DPU tree. When I entered "Extractor" to the filter, everything worked well, the hierarchy was preserved. But when I input "Loader" to the filter, I got: 

![screen shot 2014-02-26 at 1 23 22 pm](https://f.cloud.github.com/assets/3014917/2269829/67361dd0-9ee1-11e3-8119-fea98592c724.png)

You can reproduce that on ODCS. 
@bogo777, any explanation for that?

**Comment by tomas-knap** [comment]
The same problem appears as Maria described: 

BUG! Jsem pridala na kanvas "SPARQL Loader completeness" DPU pak zmacknula Save as DPU template, potom nova dpu se pridala do DPU tree ale DPU tree ztratilo svou strukturu, vsechny DPU se zacali zobrazovat na 1-m levlu. Po opakovanem otevreni OK

![53b6f2e4-a34f-11e3-8de8-baa2109568e0](https://f.cloud.github.com/assets/3014917/2318779/8b4abece-a36e-11e3-9c2b-1ffb7a548a50.jpg)

**Comment by tomas-knap** [comment]
@kukharm Please describe how you manage to reproduce, to have guidance for Bohuslav

**Comment by kukharm** [comment]
I checked "Only private dpu template" filter, then put private DPU to the canvas, opened its details and pushed the button "Save as DPU template"
