### ISSUE TITLE
Adjust the way how execution monitor detail is shown

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1270]
Adjust the way how execution monitor detail is shown to the user based on the user's space in the browser being available in the horizontal direction. 

Current situation:
- open the execution monitor
- click on detail of any record
- you will get (the screen is divided and shows the main exec record table and the details): 

![screen shot 2014-02-27 at 4 47 36 pm](https://f.cloud.github.com/assets/3014917/2284198/83fc13ee-9fc6-11e3-8b23-883610e700f1.png)

Desired situation: 
1) When the width of the screen is higher than or equal to X  (must be set experimentally), then, when user opens execution monitor and clicks on detail, the detailed exec record appears as in the current situation (the screen is divided, both, the exec monitor main table and detail is shown)
2) When the width of the screen is less than X (must be set experimentally), then, when user opens execution monitor and clicks on detail, the detailed exec record appears instead of the the main execution record list, thus like this: 

![screen shot 2014-02-27 at 4 50 13 pm](https://f.cloud.github.com/assets/3014917/2284231/e2db9b1e-9fc6-11e3-8b24-6c0cf6422b2f.png)

X must be set experimentally, but in general, it makes sense to show the exec detail in mode 1) only when you can see most of the columns. If you can hardly see 3-4 columns of one table, mode 2) should be used. 

In case of 2), there must be "close" button somewhere on the exec record detail, which closes the exec record detail and returns user to the main exec record page.

**Comment by ghost** [comment]
resolved here: https://github.com/mff-uk/ODCS/issues/1295
