### ISSUE TITLE
What is exec_context_pipeline.directory(255) 

### ISSUE THREAD

**Issue by ghost** [mff-uk/odcs#1274]
What is exec_context_pipeline.directory(255) 
- does not seem to be JPA mapped. could it be removed? is it used somewere?

**Comment by skodapetr** [comment]
It originally was .. now the directory is computed on request from information about execution. I will remove this during(or after) the merge operation.

**Comment by ghost** [comment]
resolved here: https://github.com/UnifiedViews/Core/commit/4ce65260f8183b1daf50a04a46a7c85d9f3b9d1c
