### ISSUE TITLE
Native repository is used when it should not be used?

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1281]
On ODCS, I am running on top of virtuoso intermediate store (NO native rep). But when looking at execution 935, in browse/query tab, there is virtuoso graph and I can browse the data on virtuoso. So it is fine so far.  But when looking to the log, I got:

![screen shot 2014-03-03 at 10 08 10 am](https://f.cloud.github.com/assets/3014917/2307863/af38fad2-a2b3-11e3-8bd0-2acd24613628.png)

Based on that, it seems that native store is initialized and used as well (together with Virtuoso), which is wrong. Can you please explain, @tomesj  ?

**Comment by tomesj** [comment]
Problém nebude v mixování implementací, ale v tom, že autor, který psal DPU XSLT někde používá sám ve svém kódu lokální repozitář (např. pro nějaké mezivýpočty) a nevolá metodu (tuším getRepository), která sedí výše ve frontendu/backendu, která vrací repozitář na základě configurace - tedy Virtuoso nebo LocalRDF.

Nevím, kdo je autorem, ale v této věci bych se určitě obrátil na něj.

**Comment by tomas-knap** [comment]
Jirko, xslt jsem psal ja a nevim o tom, ze bych nekde pouzival natvrdo native repository. Resp. toho by ani autor DPU nemel mit moznost docilit, ne?

**Comment by tomas-knap** [comment]
Koukni prosim na XSLT kod ( je  v repozitari https://github.com/mff-uk/DPUs), koukni na hlavni tridu a projdi prosim volani RDF data unit metod, je jich tam par. Jestli neuvidis neco podezreleho. Tech volani je tam par

**Comment by tomesj** [comment]
Podívám se na to, jen co se vrátím z práce ke svému počítači :-)

**Comment by tomesj** [comment]
Tak důvod odhalen
- metoda OrderTupleQueryResultImpl executeOrderSelectQueryAsTuples totiž testuje, zda je daný dotaz validní - volá metodu isValid() - a ta ve své implementaci používá LocalRDF, která slouží jako pomocná repozitory pro tuto validaci.

Tím je to objasněné :-)

**Comment by tomas-knap** [comment]
Jirko, a jak to tam tedy funguje, inicializuje se native store a pak se jen
otestuje dotaz? Neda se to udela bez inicializace?

2014-03-03 17:09 GMT+01:00 Jiří Tomeš notifications@github.com:

**Comment by tomas-knap** [comment]
Resp. nedala by se na toto pouzit nejaka jedna native rep pripravena pro celou jednu instanci ODCS? Aneb je trochu neefektivni pokazde delat novou native store jen proto, aby se zkontroloval query

**Comment by tomesj** [comment]
Bohužel validace vyžaduje vytvoření dočasného repozitáře, ten se po provedení validace opět smaže. Takže na disku nic nezůstane. Vytvoření a mazání je rychlé a nestojí prakticky nic. 

Držet jednu instanci bychom asi mohli, ale nic bychom neušetřili. 

Naopak by přibyly zbytečné problémy se jak správně sdílet repozitář ve chvíli, když mi např. 2 různá vlákna volají validaci, protože validace na zamknutém repozitáři způsobuje exception. Byl by s tím celkem problém to správně odladit podobně jako to bylo u sdílené connection. 

Já bych se do toho asi nepouštěl, nic navíc tím nezískáme ani neušetříme, spíš se může stát, že to, co teď funguje správně, tak s tím budou problémy.

Co myslíš ?

**Comment by tomas-knap** [comment]
Takhle, urcite by stalo za to delat max jeden repozitar pro execution jedne
DPU instance. Ale nechme to pro ted.

2014-03-03 23:31 GMT+01:00 Jiří Tomeš notifications@github.com:

**Comment by tomas-knap** [comment]
Summary: For validating queries, local rdf store (native rep) is used
