### ISSUE TITLE
DPU configuration issue

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#1290]
When I click save on configuration that looks like this:
![image](https://f.cloud.github.com/assets/718827/2321938/0d3b97e6-a3ab-11e3-8caf-d761e7e126c6.png)

In the log I get:

<pre><code>
2014-03-04 15:38:35,817 [http-bio-8080-exec-360] DEBUG org.eclipse.persistence.logging.sql - 2014-03-04 15:38:35.817--ClientSession(719707410)--Connection(1494539966)--UPDATE dpu_template SET configuration = ? WHERE (ID = ?)
        bind =&gt; [&lt;object-stream&gt;
  &lt;cz.opendata.linked.metadata.form.ExtractorConfig&gt;
    &lt;datasetURI&gt;http://linked.opendata.cz/resource/dataset/&lt;/datasetURI&gt;
    &lt;creator&gt;http://purl.org/klimek#me&lt;/creator&gt;
    &lt;publisher&gt;http://opendata.cz&lt;/publisher&gt;
    &lt;licenses/&gt;
    &lt;sparqlEndpoint&gt;http://linked.opendata.cz/sparql&lt;/sparqlEndpoint&gt;
    &lt;dataDump&gt;http://linked.opendata.cz/dump/&lt;/dataDump&gt;
    &lt;exampleResources/&gt;
    &lt;modified&gt;2014-03-04 14:38:35.811 UTC&lt;/modified&gt;
  &lt;/cz.opendata.linked.metadata.form.ExtractorConfig&gt;
&lt;/object-stream&gt;, 750]
</code></pre>

Where did the data come from? It is in the config constructor, but it is not what is in the fields of the dialog...

**Comment by skodapetr** [comment]
It's for Metadata adder on ODCS?

**Comment by jakubklimek** [comment]
Yes

**Comment by jakubklimek** [comment]
This was caused by various Vaadin exceptions. It works now.
