### ISSUE TITLE
Problem running pipeline on ODCS-test

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1297]
On odcs-test (using Virtuoso 7), I have problem with running the pipelines. Although frontend is saying that backend is online and backend is online, when running certain pipeline, it remains in the status "queued". 

![screen shot 2014-03-05 at 4 17 54 pm](https://f.cloud.github.com/assets/3014917/2334537/ca227afe-a479-11e3-9f3d-f836f0ce097e.png)

The database was just created with the script, so it is clean and up to date.

Based on the backend's log, backend is checking for new executions, but it cannot find any, although frontend shows that there are some. 

@skodape Do you have any explanation for that? Please discuss with @janvojt if needed.

**Comment by skodapetr** [comment]
Can you specify the version of Virtuoso (or better provide link) so I can test on localhost.

**Comment by tomas-knap** [comment]
problem was in the configuration - wrong db was used
