### ISSUE TITLE
Frontend - import package problem

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#13]
Repair implementation problem in Frontend project (problem with import package cz.cuni.xrg.intlib.commons.app.dpu.DPUFacade) - classes App.java, AppEntry.java, DPU.java, PipelineEdit.java

**Comment by skodapetr** [comment]
What kind of problem exactly? The package name seems to be correct, the name is the same as the classname and path to the class (checked on git hub). Or do I missing something?

**Comment by tomesj** [comment]
Problem solved
