### ISSUE TITLE
Fix layout in all DPUs where it does not fill the window

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#1301]
![image](https://f.cloud.github.com/assets/718827/2356030/63c31756-a5e5-11e3-9903-f72413d92305.png)

**Comment by skodapetr** [comment]
I will prepare for this change, but as it may bring some bugs .. I will postpone the commit after the presentation.

**Comment by skodapetr** [comment]
It look's like there is challenge with initial size. In order to properly resize the dialog I have to choose fix initial size. As an enhancement we may compute the size if the configuration dialog provides it, ie. has other size then -1px and 100 percent.

**Comment by skodapetr** [comment]
Non core DPUs may also require configuration dialog update in order to work properly.
