### ISSUE TITLE
SPARQL Transformer - validations

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1307]
When there is an error in the query, there is exclamation mark

1) When I correct the query, it is still marked as having error. Solution: Immediately when the query is ok (Value in the text area changed), revalidation can be done and the error must disappear. 

For example, if I made an error in the first query, exclamation mark is shown, then I correct the error and click "+", it still shows an error, which is wrong.

**Comment by tomesj** [comment]
Tak jsem se na to koukal a věc se má následovně:

Mandatory field, které používáme ve všech DPUs si sám řídí Vaadin a ten pouští jejich validaci vždy po ztrátě focusu na dané komponentě - tedy například u SPARQL extractoru, když je špatná URL adresa, tak vykřičník zmizí až po překliknutí na jiné pole a ne ihned po vyplnění správné adresy, podobně je to tady u SPARQL transformeru. Stačí si to vyzkoušet

Co se týká toho, mám-li nevalidní dotaz, opravím na validní a dám (+), focus se ztratí, zvaliduje se to a vykřičník zmizí (teď jsem to zkoušel). Takže ta druhá část není toho co píšeš rozhodně není pravda.

Má smysl to měnit ? Navíc by to šlo pouze uměle, vyvolání ztráty focosu. Bych se do toho asi nepouštěl, když to nemáme ani jinde.

**Comment by tomas-knap** [comment]
@jakubklimek Please describe your issue with the sparql transformer validation. Currently, the validation is done when the component loses focus and we will not change that in the near future. In which situation you got wrong error message for certain  queries?

**Comment by jakubklimek** [comment]
Hmm... now it works for me too. I think the problem was that the query was valid, ran in Virtuoso, but was missing some prefixes (and Virtuoso had them predefined, that is why it worked). So I think it actually works, but could you display more detailed message than "query invalid"?
