### ISSUE TITLE
Virtuoso for querying.

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#131]
When I try query (select/construct) when I using Virtuoso as storage- there are any files to read yet (all in in this case saved only in Virtuoso) - in implementation is only use local RDF repository - load from given file....

Add please implementation for Virtuoso. 

For case Virtuoso just create instance of Virtuoso and set default graph calling method "setDataGraph"  (it is graph for querieng =name of graph for concrete DPU). others method are then the same (calling makeSelect/ConstructOverRepository)

![image](https://f.cloud.github.com/assets/3481055/811471/069216a2-eed6-11e2-8d2f-7834d31d3a0d.png)

**Comment by bogo777** [comment]
Solved by 5f7dbb1faf38d36ca3c1c95b31ff8dce3f180c40
