### ISSUE TITLE
Problem with dependency

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1310]
v DPU repo mam toto DPU:

extractor_tabular_czso_vdb

Nejde mi z nej ale udelat DPU Template. ODCS hazi chybu, viz screenshot. Muzes na to prosim mrknout? Potrebuju to rychle (zitra = v pondeli), musim tahat data ze stataku.

potíž je chybějící balíček .. junit.framework .. což asi už víš z popisu exception. Nicméně to jsou pokud se nepletu testy.

Není v pom.xml ten testovací balíček se špatným scopem - testovací by měl mít "test"?

DPU je v repo. (extractor_tabular_czso_vdb).

Pouzivam pro vas zrejme novou dependency 
<dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi</artifactId>
      <version>3.10-beta2</version>
    </dependency>
    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi-ooxml</artifactId>
      <version>3.10-beta2</version>
    </dependency>

**Comment by skodapetr** [comment]
Dependencies will be provided as OSGI bundle libraries.

**Comment by tomas-knap** [comment]
Tested, still having problem: 

![screen shot 2014-03-10 at 2 29 26 pm](https://f.cloud.github.com/assets/3014917/2373910/141a8be2-a858-11e3-9a59-786c086127e8.png)
