### ISSUE TITLE
Problems with session

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#1317]
The session fell out few times (the Interval of outages were different). The problem was most often while working with DPU on canvas when the pipeline was edited.

**Comment by ghost** [comment]
Trying to resolve here:
https://github.com/UnifiedViews/Core/commit/bde8d6ca3f980bcda212eec88dde4c80bb75b26a

test again if persist reopen.
According to Vaadin Book , given no settings, sessions never expire (nor they are cleared). So i don't understand how it could happen. But, they (of course) recommend to set basic session expiration settings, which I have employed (heartbeat at 5 minutes, expire after 30 minutes). I have tested expiration works as expected.
