### ISSUE TITLE
Extended connections

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/odcs#1319]
Loader by mel mit vystup a na nem to co mu prislo na vstupu - volitelne.

Aplikace dovoluje vest hranu z loaderu.

Podpora pro hrany pres ktere nejdou data, ale funguji tak ze se cilove dpu spusti po tom zdrojovem.

**Comment by ghost** [comment]
anybody can copy rdfdataunit to any writablerdfdataunit (method addAll). with "merger" dpu, it does not make sense to use it as 'clone', as merger dpu will be far more effective (faster).
