### ISSUE TITLE
Neprochazejici test u SPARQL extractoru - opravit prosim

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1320]
Results :

Failed tests: 
  SPARQLExtractorRequestTest.GetSimpleTest:91->extractFromEndpoint:67 HTTP/1.1 502 Bad Gateway. Caused by <html>
    <head>
    <title>Web Site Under Maintenance</title>
    </head>
    <body>
    <div><img src="data:image/gif;base64,R0lGODlhMgAyAOYAAO/v7+7u7u3t7f//AOzs7Ovr6+rq6unp6ejo6Ofn5+bm5uXl5eTk5ODg4N/f397e3t3d3dzc3Nvb29ra2tnZ2djY2NfX19PT09LS0tHR0dDQ0M/Pz87OzszMzMvLy8rKysnJycjIyMbGxsXFxcTExMPDw8LCwsHBwby8vLu7u7e3t7a2trW1tbS0tLOzs7KysqysrKqqqqioqKampqWlpaSkpKGhoZ2dnZycnJqampmZmZiYmJWVlZSUlJKSko6OjoyMjIuLi4qKioaGhoWFhYSEhIGBgYCAgH9/f319fXl5eXh4eHd3d3Z2dnJycm5ubm1tbWlpaWdnZ2VlZWNjY2JiYgAAAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEHAFcALAAAAAAyADIAAAf/gFeCg4SFhoeIiYqLjI2Oj5CRkVaUVpKXiJWVCQkIBgKYkpQDpAOUEhENDAYAoY6jpaSUGxcUDQqgroqwsbJWJB4XEQwEuplWvb2UKCIaEgwFxoW8yaWUKiUbE9DSgtSmlcpWLCYc29HG35rqVi0n5tyu3+CayZQu7+eh8/Th9lb44KGbhKzauoL/AuqDNOpgQ3/VwCmM1wgWwn4RDQLMR3EXwo/rMibkOPBYLGQHTYkcCa+YyZP9Cl7EqLGFiQ0SFuSaNjPmR3EQxbEooSFCglY8/zlcWu+fDBUiLjQwYIjaQ4gzQ2q8ASPFBwoMdnrr6TNiU40+bLwwgcEB1aRA/89mZHdESI4YKTpISGAoATuUQTWetHJEyRAeM1SAoLAA6aAEEqxa5Cfr3xEoTIr0oLEihAUGjgUhgLCBl7/AFlX6OjLliWHEihmHvlKgwQUSk2VKNr2aShQnSezi1cu3UIAFFDyguOprsFxKR6pIebKESNq1bd8WMmBbhIqHvnSnBBddCpQmRn5w9QpW7CAACSJoKMGiYfjwIaFLP38ESI6nUU2ViAALSLCBCS1QZhZh+zWBRBA6zDBUUUcpQgADE3BwggsKilPeeQ/uMINNOOnESAEYasghWR42GOIME7l0YoobdqifeQ4GIeJEJc2YYY0s3giijjCSJAmKP65oGcQVOL7IIyZIqigZa1E80cQRRD4ZSpRAanLZE04sYQQQEWrpCpcJVlIYE0okQcQPEbojUDdRmsCCDDj4IMQQRQwhhA84yEDOnN3QhuEGJagAgw068NADDzrYAAM22nREJwMSaDBCCi/EMEMNM8TwQgojOGNpoRdGcMEHJqSgwgoqpGDCB8IQU+ghAijgQAUZdABCCCB0kEEFDuByKyIAHMDAAxJUYEEFEjzAwAGzHVuIAAYowMC2CnxibSMABCButd+WK0ggADs=" style="float:left;"/>
        <div style="font-weight: bold; font-size:18px; font-family: verdana;">
        The web-site you are currently trying to access is under maintenance at this time. <br/>
        We are sorry for any inconvenience this has caused.</div></div>
    </body>
</html>

URL endpoint: http://dbpedia.org/sparql POST content: ?query=CONSTRUCT+%7B%3Fx+%3Fy+%3Fz%7D+WHERE+%7B%3Fx+%3Fy+%3Fz%7D+LIMIT+15&format=text%2Fn3
  SPARQLExtractorRequestTest.POSTEncodeDefaultGraphParamTest:150->extractFromEndpoint:67 HTTP/1.1 405 Not Allowed. Caused by <html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.4.2</center>
</body>
</html>

URL endpoint: http://dbpedia.org/sparql POST content: query=CONSTRUCT+%7B%3Fx+%3Fy+%3Fz%7D+WHERE+%7B%3Fx+%3Fy+%3Fz%7D+LIMIT+15&default-graph-uri=http%3A%2F%2Fdbpedia.org&format=text%2Fn3

**Comment by skodapetr** [comment]
Well the test should be marked as integration (at least) if it use some external sources.

**Comment by tomesj** [comment]
Důvodem  neprocházení testů byla údržba DBPedie, nikoliv nesprávnost. Test jsem zařadil do kategorie integračních testů, aby se nepouštěl při CLEAN & BUILD. Tím je to vyřešené
