### ISSUE TITLE
Filter components do not have the same size in the table header

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#134]
![screen shot 2013-07-18 at 10 55 43 am](https://f.cloud.github.com/assets/3014917/818065/e9390fcc-ef87-11e2-8cf2-d606851b4286.png)

Filters are great, really like it. The only think I do not like and looks strange, is the different height of combo boxes and text boxes. Would it be possible to e.g. have smaller combo boxes in the filters row so that their height is the same of the text boxes?

**Comment by bogo777** [comment]
I tried to do it, but my solution only works on pipeline list table and I don't know why. I will contact author of the plugin and ask for help along with reporting bug we found in issue #164.

**Comment by tomas-knap** [comment]
Any progress in this issue?
