### ISSUE TITLE
Buttons in GUI

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#137]
For all tables with more than 2 filtered columns, there should be: "clear filters" button in the upper right part

Pipeline executuon: refresh button in the upper right part of the page
Scheduller: add schedule rule button - upper right part of the page above the table
Pipeline list: button create pipeline - upper right part of the page above the table

**Comment by bogo777** [comment]
There is little space on DebuggingView for buttons "Clear Filters" for upper event table and for tables in lower tab. It is possible to put them there, but the amount of items displayed will be reduced...

**Comment by tomas-knap** [comment]
Ok, let's leave DebuggingView as it is. The experience will show if they are needed.
