### ISSUE TITLE
Filter with images - hide description when filter selected

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#139]
When the filter with images: 
- status,debug in execution monitor
- type in pipeline events

is selected, user can see all the available options - image as well as description. When certain option for the filter is selected, only the image appears in the filter row, so that the situation below is avoided:

![screen shot 2013-07-18 at 11 22 36 am](https://f.cloud.github.com/assets/3014917/818219/15161258-ef8c-11e2-8f60-36bb2874ea0a.png)

In the image above, only the image should appear when the filter is selected.

**Comment by janvojt** [comment]
Seems like fix would required som javascript coding - replacing selected  value when combobox is opened/closed, or completely rewriting the component.

Instead, would it be enough to simply left-align textual representation, so it starts with WARN...? I think it would be easy to implement, and even a better solution.

**Comment by tomas-knap** [comment]
Yes, that is also possible

**Comment by bogo777** [comment]
Solved by left-align of textual representation.
