### ISSUE TITLE
Communication between frontend and backend throws Exception

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#14]
When I create and save pipeline, then click on RUN button - "CommuticationException" is throws.
![backend exception](https://f.cloud.github.com/assets/3481055/491936/e5a9eea8-ba6c-11e2-9d74-917ae46e40f9.jpg)

**Comment by skodapetr** [comment]
It's not a bug it is a feature:) actually there is no easy way how to run pipeline now (without some non-system changes) To test the DPU implementation the fastest way is to run them in the release 0.1.1.
