### ISSUE TITLE
Problems building intlib. 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#153]
Od Kuby: Dneska jsem si updatnul ODCS a nějak se to rozbilo. Píše mi to errory v projektu RDF a frontend:

Description        Resource            Path      Location              Type
The method setFilterDecorator(FilterDecorator) in the type FilterTable is not applicable for the arguments (ExecutionMonitor.filterDecorator)       ExecutionMonitor.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/gui/views            line 225 Java Problem
LogMessageDetail cannot be resolved to a type              LogMessagesTable.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/gui/components              line 155 Java Problem
LogMessageDetail cannot be resolved to a type              LogMessagesTable.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/gui/components              line 156 Java Problem
LogMessageDetail cannot be resolved to a type              LogMessagesTable.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/gui/components              line 156 Java Problem
LogMessageDetail cannot be resolved to a type              LogMessagesTable.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/gui/components              line 174 Java Problem
LogMessageDetail cannot be resolved to a type              LogMessagesTable.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/gui/components              line 171 Java Problem
LogMessageDetail cannot be resolved to a type              LogMessagesTable.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/gui/components              line 177 Java Problem
VirtuosoRdfBrowser cannot be resolved to a type         DataUnitBrowserFactory.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/browser               line 65   Java Problem
VirtuosoRdfBrowser cannot be resolved to a type         DataUnitBrowserFactory.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/browser               line 65   Java Problem
IntlibFilterDecorator cannot be resolved to a type          ExecutionMonitor.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/gui/views            line 470 Java Problem
The method getBooleanFilterDisplayName(Object, boolean) of type ExecutionMonitor.filterDecorator must override or implement a supertype method     ExecutionMonitor.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/gui/views            line 462 Java Problem
IntlibFilterDecorator cannot be resolved to a type          ExecutionMonitor.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/gui/views            line 482 Java Problem
The method getBooleanFilterIcon(Object, boolean) of type ExecutionMonitor.filterDecorator must override or implement a supertype method             ExecutionMonitor.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/gui/views            line 474 Java Problem
IntlibFilterDecorator cannot be resolved to a type          ExecutionMonitor.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/gui/views            line 425 Java Problem
The method getEnumFilterDisplayName(Object, Object) of type ExecutionMonitor.filterDecorator must override or implement a supertype method             ExecutionMonitor.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/gui/views            line 421 Java Problem
IntlibFilterDecorator cannot be resolved to a type          ExecutionMonitor.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/gui/views            line 458 Java Problem
The method getEnumFilterIcon(Object, Object) of type ExecutionMonitor.filterDecorator must override or implement a supertype method             ExecutionMonitor.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/gui/views            line 429 Java Problem
MyRDFHandler cannot be resolved to a type    LocalRDFRepo.java                /RDF/src/main/java/cz/cuni/xrg/intlib/rdf/impl              line 659 Java Problem
IntlibFilterDecorator cannot be resolved to a type          ExecutionMonitor.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/gui/views            line 418 Java Problem
MyRDFHandler cannot be resolved to a type    LocalRDFRepo.java                /RDF/src/main/java/cz/cuni/xrg/intlib/rdf/impl              line 659 Java Problem
MyRDFHandler cannot be resolved to a type    LocalRDFRepo.java                /RDF/src/main/java/cz/cuni/xrg/intlib/rdf/impl              line 1841              Java Problem
IntlibFilterDecorator cannot be resolved to a type          RecordsTable.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/gui/components              line 154 Java Problem
MyRDFHandler cannot be resolved to a type    LocalRDFRepo.java                /RDF/src/main/java/cz/cuni/xrg/intlib/rdf/impl              line 1841              Java Problem
The method getEnumFilterIcon(Object, Object) of type RecordsTable.filterDecorator must override or implement a supertype method         RecordsTable.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/gui/components              line 157 Java Problem
The method setFilterDecorator(FilterDecorator) in the type FilterTable is not applicable for the arguments (RecordsTable.filterDecorator) RecordsTable.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/gui/components              line 115 Java Problem
Plugin execution not covered by lifecycle configuration: com.vaadin:vaadin-maven-plugin:7.1.0:update-theme (execution: default, phase: generate-sources) pom.xml             /frontend           line 247 Maven Project Build Lifecycle Mapping Problem
Plugin execution not covered by lifecycle configuration: com.vaadin:vaadin-maven-plugin:7.1.0:resources (execution: default, phase: process-resources)               pom.xml             /frontend           line 247 Maven Project Build Lifecycle Mapping Problem
Plugin execution not covered by lifecycle configuration: com.vaadin:vaadin-maven-plugin:7.1.0:compile-theme (execution: default, phase: generate-resources)            pom.xml             /frontend           line 247 Maven Project Build Lifecycle Mapping Problem
Plugin execution not covered by lifecycle configuration: com.vaadin:vaadin-maven-plugin:7.1.0:update-widgetset (execution: default, phase: process-classes)     pom.xml             /frontend           line 247 Maven Project Build Lifecycle Mapping Problem
LogMessageDetail cannot be resolved to a type              LogMessagesTable.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/gui/components              line 33   Java Problem
IntlibFilterDecorator cannot be resolved to a type          IntlibPagedTable.java                /frontend/src/main/java/cz/cuni/xrg/intlib/frontend/gui/components              line 18   Java Problem

**Comment by tomas-knap** [comment]
Kuba: No mozna to bude u me.

Chyby u RDF mi zmizely, ale pise to 4 errory na pom.xml u frontendu.

„Plugin execution no covered by lifecycle configuration: com.vaadin:vaadin-maven“

**Comment by skodapetr** [comment]
It looks like some "error" in Frontend which is more familiar to Bohuslav then to me. Similar situation is with RDF (Jirka). So reassigned to Bohuslav. Or we can discuss it on meeting?

I try install (without clean) and the result is: [INFO] BUILD SUCCESS

**Comment by tomas-knap** [comment]
It is working outside of eclipse via mvn install, not in eclipse.
