### ISSUE TITLE
Scheduler event dialog - Autocomplete for Pipeline selector

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#156]
The pipeline selector (combo box) should support autocomplete. When I start writing, list of matching pipeline names appear in the list. Currently, all pipelines appear. 

![screen shot 2013-07-22 at 11 07 29 am](https://f.cloud.github.com/assets/3014917/833899/735d3aa6-f2ae-11e2-928a-37615b93ba66.png)

**Comment by bogo777** [comment]
I think current funcionality is fine. If you start writing, only matching pipelines are displayed in the automatically showed list. If you explicitly open the list via arrow, all pipelines appear.

**Comment by tomas-knap** [comment]
Yes, it is fine.
