### ISSUE TITLE
Combo box with INFO+ etc. moved to filters

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#161]
![screen shot 2013-07-22 at 12 16 10 pm](https://f.cloud.github.com/assets/3014917/834185/d2e2ffac-f2b7-11e2-8ab1-4ecdcb6e077f.png)

Combo box and filter for log level is redundant, there is also a problem when filters are set and comb box reselected. 

Solution: Combo box with INFO+ etc. should be a filter in the column level in the table. There will be no combo box above the table. For debug DEBUG+ filter is preselected, for run INFO+ is preselected.

**Comment by bogo777** [comment]
I got this solved, but until lazy-loading is used for loading log messages, it is very slow. See #197.

**Comment by tomas-knap** [comment]
Bohuslav, thanks!

Could you please adjust it, so that filter INFO+ is selected by default as the filter from the combo box?

**Comment by tomas-knap** [comment]
Correction, could you please adjust it, so that:

when debugging, DEBUG+ is selected by default as the filter 
when running in normal mode WARNING+ is selected by default as the filter

**Comment by bogo777** [comment]
It is adjusted.
