### ISSUE TITLE
module.File_loader

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/odcs#17]
I open the configuration dialog then click save and get fallowing exception:
Caused by: java.lang.NoSuchMethodError: cz.cuni.xrg.intlib.commons.configuration.Configuration.setValue(Ljava/lang/String;Ljava/lang/Object;)V
    at gui.ConfigDialog.getConfiguration(ConfigDialog.java:59)
    at module.File_loader.saveConfiguration(File_loader.java:80)

If I fill the values into configuration dialog I also get the same exception.

**Comment by janvojt** [comment]
I suspect the cause of this might be change of signature for Configuration#setValue, where second argument is Serializable (not Object as before). Therefore make sure your Object implements this interface, or use typecasting.

**Comment by skodapetr** [comment]
Jan: Yes this can be ... so it's necessary to do this update for almost all DPUs. RDF_Extract/loader is working properly I think.
Maria could you please take care about this?

**Comment by janvojt** [comment]
Well, I typecasted all those IDE complaint about. I also tested some modules by creating new pipeline. It worked, so most of it should be fine. I don't know if anyone was making changes, or added new modules since.
