### ISSUE TITLE
No DPUs on the canvas

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#171]
When importing  shema.sql and data.sql, open dbpedia pipeline, there are no DPUs on the canvas:

![screen shot 2013-07-24 at 1 21 46 pm](https://f.cloud.github.com/assets/3014917/848108/3c0d5760-f453-11e2-83e7-b6bbd1dfaf17.png)

**Comment by bogo777** [comment]
Is importing successful or are there any errors? I cannot reproduce it on my computer, after importing I have DbPedia with 2 DPUs as always.

**Comment by tomas-knap** [comment]
I prepared fresh Virtuoso (6.1.6) - deleted everything except of virtuoso.ini, started virtuoso, imported schema.sql, data.sql, started frontend and open DBPEdia pipeline

**Comment by tomas-knap** [comment]
import was successful. Also when I try to create new pipeline, it is not possible to drag&drop DPUs on the canvas, drag&drop finishes, but there is no DPU on the canvas as a result

**Comment by tomas-knap** [comment]
So it seams that canvas it not showing anything

**Comment by tomas-knap** [comment]
Problem is in Chrome, 28.0.1500.71 (latest), in SAFARI, it works. Decreasing priority of this

**Comment by bogo777** [comment]
Today I prepared fresh Virtuoso (6.1.7), imported database and started frontend. DbPedia pipeline opened just fine, with Chrome 28.0.1500.72 m.

If problem prevails, could you please look for javascript errors in chrome JS console?

**Comment by tomas-knap** [comment]
No error/warning in the console. I would leave this with low priority, could be problem just in my case. Bohuslav, could you please ask other to test it in chrome?

**Comment by tomas-knap** [comment]
Now it seems to work agains, am closing this issue
