### ISSUE TITLE
Context should contain information about the last execution

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#172]
Scheduller should give info to the DPU executed (in the object Context) when pipeline was successfully finished, finished with error. Based on that, extractor can e.g. compute the time interval for which new data should be obtained.

I would expect something like context.getLastExecutionStatus().getExec(), context.getLastExecutionStatus().getSuccessfulExec()

**Comment by skodapetr** [comment]
It's possible to provide DPU with the last successful execution time. (for the whole pipeline, not a single DPU)

I'm do not know why it needs information about last exec. status or result?

**Comment by tomas-knap** [comment]
Ok, lastSuccessfullExecution is good enough for now
