### ISSUE TITLE
File Extractor - mandatory field not checked

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#175]
Mandatory field is not checked

![screen shot 2013-07-24 at 3 45 33 pm](https://f.cloud.github.com/assets/3014917/848732/750bc7d6-f467-11e2-939c-ca4e775e8159.png)

**Comment by kukharm** [comment]
It was made in accordance with  Issue #82. Mandatory fields don't check in template configuration. In Pipeline Edit it checked if the field is empty
![mandatory](https://f.cloud.github.com/assets/3471169/851983/0dca1e5c-f4a7-11e2-968f-b747cc8a6945.jpg)
