### ISSUE TITLE
Logging named graphs which are created between DPUs when using Virtuoso and running pipeline

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#176]
Could you please add logging of the named graphs names used when running pipeline? I would like to see in the log of the pipeline information about every created graph, information that the graph was output/input of certain DPU and also information that the graph was deleted.

**Comment by tomas-knap** [comment]
Please also emphasize whether it is output or input graph in the log

**Comment by tomesj** [comment]
Every DPU has only 1 graph - it is input and output together. 

If more than one edge go to DPU (more INPUTS} - every graphs from previous DPUs merge into graph for actuall DPU. 

If DPU has more than one edge goes to next DPU (more OUTPUTS)- data of this DPU are add (merge) to the next DPU graph (goal of edge between them).

**Comment by tomas-knap** [comment]
Well, but this will not work. 
1. In the debuger, you have to be able to query input and output of the debugged DPU (it is already prepared in gui), so they cannot be the same. For example for SPARQL transformer, you expect that input graph will be the original graph entering DPU, output is the changed graph. 
2. In many cases, input graph could be completely different than output graph, e.g., in case of linker where two data sources form input and links form output.

So they has to be different. If the user (autor of DPU) would like to copy input to output, he has to do it explicitely.

**Comment by tomas-knap** [comment]
I think that for local RDF, the input and output are also different, right?
