### ISSUE TITLE
File Loader - does not respect the extension of file when AUTO rdf format selected

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#177]
Setting of DPU as below:

![screen shot 2013-07-25 at 10 46 51 am](https://f.cloud.github.com/assets/3014917/854506/e5bbeeee-f506-11e2-9bf5-035433480a81.png)

Result: It generates RDF/XML file, which is wrong. We were discussing that AUTO format will take the extension of the file and based on that selects the format, right? Or did we discuss something else?

**Comment by tomesj** [comment]
You right :-) How I change implementation using handler for supporting for big files- this cause I dont fix. Thank you.

**Comment by tomas-knap** [comment]
Jirko, please adjust also test, which checks that AUTO is working correctly, so that next time you will be alarmed.
