### ISSUE TITLE
SPARQL extractor - no default SPARQL query

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#186]
When creating SPARQL extractor (just specifying the core part), error occurs:

![screen shot 2013-07-26 at 2 27 20 pm](https://f.cloud.github.com/assets/3014917/862362/28fad60a-f5ef-11e2-8f57-148ea771d381.png)

Probable solution: No default query obtaining everything is executed against the given graph!

**Comment by tomesj** [comment]
Construct query and URL endoint are checked by validator on canvas and in method again.

Before trying functionality is necessary clean all pipeline using this DPU and trying it create again. 
I tested it and it works fine :-)
