### ISSUE TITLE
Browse/Query in debug not working with Virtuoso

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#187]
Petre, is it a problem of backend or RDF module or GUI? Please assign the person responsible for that

To reproduce: Debug from canvas, DPU selected, no way how to work with browser/query tabs

**Comment by skodapetr** [comment]
Jirka, could you please confirm this? 
Maybe you could add logging like create/setGraphName to RDF repositories. This can help use to identify the problem.

**Comment by skodapetr** [comment]
Jirka, we could also log the size of the DataUnit (in merge method for example) .. this could also help for issue #187. When logging you could use id to identify DataUnit as It's posible to assign DataUnit to DPU input/output based on DataUnit's id.

**Comment by bogo777** [comment]
Browse/Query in debug with Virtuoso works fine for me. I debug DbPedia pipeline.

**Comment by tomesj** [comment]
Browse/Quiry on canvas forks fine by me. Comments to setGraphName in local repository were added some time ago.  I added logging for merging.
