### ISSUE TITLE
Strange RDF data processing - too many triples in the output

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#190]
Suppose pipeline as:

![screen shot 2013-07-26 at 3 02 22 pm](https://f.cloud.github.com/assets/3014917/862585/0d94e390-f5f6-11e2-9aef-7928b422827b.png)

Every SPARQL extractor is extracting data from one named graph, every named graph (1-3) contains the same data from ted2.ttl, viz Scenario 0b in iter 3. SPARQL loader is loading data to the forth named graph. 

When I run the pipeline (I have to put the sparql select query, see #186 ), although every input graph has approx 600 triples (ted2.ttl), output graph has 3000+ triples. I would expect     approx 800triples, because most of the triples are the same, only the triples with blank nodes will appear in the resulting named graph more times. Where is the problem?

**Comment by tomesj** [comment]
I tried it used Scenario 0b (TED) and I had no problem - result has 600 triples.

![image](https://f.cloud.github.com/assets/3481055/867289/4f77ff40-f6e6-11e2-973f-a431b1c16672.png)
![image](https://f.cloud.github.com/assets/3481055/867291/67b6f62e-f6e6-11e2-8cf6-92144ae342fa.png)

I found out, that i can SPARQL_loader i cant debug - I create new issue for Bouslav :-)
