### ISSUE TITLE
SPARQL_Loader is not possible to debug/browse

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#191]
If I create pipeline using SPARQL_Loader, I can debug it although pipeline finished succesfully. Other DPUs are OK.

![image](https://f.cloud.github.com/assets/3481055/867314/3e36178e-f6e7-11e2-8cf2-58e53f53ffa3.png)

**Comment by tomas-knap** [comment]
Jirka, please check the current version of 0.3 release if the problem persists. If yes, please explain better where the problem is. And assign Bohuslav
