### ISSUE TITLE
Mandatory fields not checked when DPU details not open 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#192]
To reproduce: When I put DPU on the pipeline, do not open DPU details and save the pipeline, I do not get any error/warning that certain mandatory DPU settings are missing

Solution: When saving pipeline, an error occurs if certain mandatory fields in DPU details are not filled.  It woudl be also nice to have small exclamation mark next to DPU on the canvas, where certain error (in this case missingconfiguration which is mandatory) occurs.

**Comment by bogo777** [comment]
Should it be error which prevents saving pipeline or only warning?

**Comment by tomas-knap** [comment]
The best behaviour would be as follows: 

If I am creating a pipeline, I may press validate button (see #706 ) to check that mandatory fields are ok. As a result, either notification that it is ok is shown or all problematic DPUs on the canvas are emhasized somehow (e.g. red exclamation mark in the corner of DPU or drawing red border around DPU). When directly pressing save or save & close button, validation takes place and notification is shown "Do you really want to save pipeline although there are validation errors"? If yes, pipeline is saved and problematic DPUs are emhasized. 

If I open already created pipeline, validation should take place as part of the opening process. As a result, any problems, typically in configurations of DPUs, which another person has changed, are again emhasized somehow (e.g. red exclamation mark in the corner of DPU or drawing red border around DPU). No notification about errors. 

Checking that mandatory fields are ok would require to open one and every DPU configuration when validation button is pressed or pipeline is open, and try to re-save the dialog - if there would be a problem, then there is also problem with the validation. Then you have to somehow emphasize which DPUs have problems by show e.g. red exclamation mark in the corner of DPU or drawing red border around DPU. 

Let's discuss on the meeting

**Comment by tomas-knap** [comment]
First try how long does it take to validate all confiugration dialogs. Then we can decide whether it is a good idea to validate automatically when opening pipeline detail / saving pipeline detail.

**Comment by bogo777** [comment]
When the configuration dialog is loaded for the first time, it takes about 0.6 second per DPU. The next time it's fast(0.3s for 6 different DPUs).

**Comment by tomas-knap** [comment]
Ok, so I would suggest validate the pipeline only on request (validate button is pressed), not automatically when opening/saving.
