### ISSUE TITLE
Output RDF data should contain only namespace prefixes needed, not all namespace prefixes from Virtuoso

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#195]

**Comment by tomesj** [comment]
Problem is, that the Rio implementation of openRDF create and write all namespace automatically to output file (there is no possible how to set it manually, change it or something like that). 

OpenRDF contains more implementation for writing RDF data, but only Rio support no problem using for large data collection (from big files, etc...).  We can actually use nothing else implementation than Rio thanks this reason.

**Comment by tomas-knap** [comment]
Jirka, 

could you please send me link to the documentation of that Rio impl you are describing? Some user guide would be good. 

could you please also send me link to all these available approaches, and mark for each where the problem when working with big data is.

**Comment by tomesj** [comment]
Sesame book of using Rio:
http://www.openrdf.org/doc/sesame2/2.7.0-beta1/users/ch09.html

Java doc of Rio:
http://www.openrdf.org/doc/sesame2/api/org/openrdf/rio/package-summary.html

For writing in file we use concrete imlementation of interface RDFWriter 
one as example - write as TTL (turtle):TurtleWriter
http://www.openrdf.org/doc/sesame2/api/org/openrdf/rio/turtle/TurtleWriter.html

Others ways:
1) Create RDF handler for exporting data and set triples to export to file (problem - if there is many triples in repository, it causes memory heap exception) 

Advantages of Rio:
Rio - all triples of given graph or whole repository save into file automatically. Its used implementation of RDFWriter as special type of RDF handler. On repository connection is then call method export.

**Comment by ghost** [comment]
je to jeste aktualni?

**Comment by tomas-knap** [comment]
Yes

**Comment by tomas-knap** [comment]
won't fix
