### ISSUE TITLE
Intelligent loading of logs to the table

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#197]
Motivation: When user switches from INFO+ to DEBUG+, it may take tens of seconds even more before anything is displayed. 

Solution: Load only debug records which fits to the first couple of pages and last page of the table and the total amount of logs. If the user needs different pages, the needed pages are loaded. If the user requires filtering, all log records must be loaded (if the number of logs is below certain experimentally set threshold) or the results may be obtained by directly executing SQL query to the database with the filters set (if the number of logs is above certain threshold).

Related with #193

**Comment by bogo777** [comment]
We should be able to solve this by using lazy-loading container. I found https://vaadin.com/wiki/-/wiki/Main/Lazy%20Query%20Container , but I don't know, if it is suitable for us. I need Honza to address this first.

**Comment by bogo777** [comment]
Some indexes on log table shloud help too, querying is now very slow.

**Comment by bogo777** [comment]
Will be solved by #220.

**Comment by bogo777** [comment]
Closed by 33b83b5762dbf7de97a5d2636a30b418cc86e256
