### ISSUE TITLE
Asynchronous Loading - Possibility to "cancel" request in GUI (e.g. to show DEBUG+ logs)

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#199]
When GUI become irrespondible due to e.g. loading bigger amounts of data/logs, there should be possibility to cancel the request. Bohuslav, is that possible to realize easily?

**Comment by tomas-knap** [comment]
We had some discussion around this, what were the results?

**Comment by bogo777** [comment]
It is not possible to explicitly cancel Vaadin request. For similar long lasting situations, asynchronous loading is recommended. For loading logs and other data to tables it should be solved by #220, but for other cases asynchronous load with server push is the way to go.

**Comment by tomas-knap** [comment]
OK, let's focus on #220 first. Regarding the asynchronous loading, so the client registers request on the server and when it is ready, it is pushed to the client?

**Comment by tomas-knap** [comment]
Lazy loading should solve this
