### ISSUE TITLE
DPUs list

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/odcs#20]
When I select a single DPU from list on  "DPUs" page the "Visibility" has no value and it is in enabled state.
If I select private and click save then after reloading page I can't change the value, this is OK. But if select public and click save, reload I can change the value to private. I believe that there should be possibility to change from public to private.

**Comment by tomas-knap** [comment]
Petr, it should be in an opposite way. If it is public, it cannot be changed to private. Hm?
