### ISSUE TITLE
Creating Container for Settings

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#202]
Prepare dialog with settings, accessible from Settings menu item. The dialog with settings will contain tabulator, with tabs being on the left, according to mockup 1: https://grips.semantic-web.at/display/LOD2/User+settings

Continue with #203 to test first setting dialog in the container.

**Comment by tomas-knap** [comment]
Maria, when trying to access Settings menu item, it does not show anything. It is clearly stated it has to work from the settings menu. Does that work in your case?

The problem in my case: 
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'userFacade' is defined at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:553) at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1095) at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:277) at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193) at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1098) at cz.cuni.xrg.intlib.frontend.AppEntry.getUsers(AppEntry.java:161) at cz.cuni.xrg.intlib.frontend.gui.components.UsersList.buildUsersListLayout(UsersList.java:111) at cz.cuni.xrg.intlib.frontend.gui.components.UserSettings.<init>(UserSettings.java:103) at cz.cuni.xrg.intlib.frontend.gui.MenuLayout$1.menuSelected(MenuLayout.java:86) at com.vaadin.ui.MenuBar.changeVariables(MenuBar.java:178) at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:403) at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:228) at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:158) at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:289) at com.vaadin.server.communication.PushHandler.onRequest(PushHandler.java:308) at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:259) at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:166) at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:137) at org.atmosphere.container.Tomcat7AsyncSupportWithWebSocket.service(Tomcat7AsyncSupportWithWebSocket.java:59) at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1448) at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:219) at org.atmosphere.websocket.DefaultWebSocketProcessor$2.run(DefaultWebSocketProcessor.java:183) at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101) at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:178) at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:167) at org.atmosphere.container.TomcatWebSocketHandler.onTextMessage(TomcatWebSocketHandler.java:92) at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:74) at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:187) at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:135) at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:83) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:587) at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:722)

**Comment by kukharm** [comment]
yes it works in my case. Do you have the last version of DB?

![settings](https://f.cloud.github.com/assets/3471169/968089/f5d899b6-0592-11e3-9f3a-b3dbbdb3b0e7.jpg)

**Comment by tomas-knap** [comment]
Maria, yes, problem was on my site, sorry ;)

Comments: 
- There should NOT be two menu items: Administrator & Settings. Everything should be under Settings (it will contain my account, notifications, users management, pipeline, records, ..). If Administrator is logged in, the content of the settings menu will have more options. Now you can suppose that admin is logged in. Solution: Delete Settings menu item, rename Administrator -> Settings. Move scheduler Notifications and Account Info tabs from the old Settings to new Settings.
- There has to be space between the menu and the container like in other windows. 
- The tab names should NOT have the bluer rectangle around.

**Comment by tomas-knap** [comment]
What is the motivaiton for records settings? What does it mean "records"??

![screen shot 2013-08-15 at 1 32 19 pm](https://f.cloud.github.com/assets/3014917/968371/5bde58a8-059e-11e3-8701-c8120a5587d4.png)

**Comment by kukharm** [comment]
I create this tabs: records, pipelines, users in accordance with https://grips.semantic-web.at/display/LOD2/Administration+interface

records - delete records from monitor https://grips.semantic-web.at/display/LOD2/Delete+records+from+monitor

**Comment by tomas-knap** [comment]
Sorry, I closed it by accident

**Comment by tomas-knap** [comment]
Ok, now I know what you mean with records. Then please put there "prune execution records" instead of "records"  - to the app and also mockup. Also instead of pipeline put there "release locked pipelines". To dialog and mockup

**Comment by tomas-knap** [comment]
When I click on setting menu item, the tab my account is preselected, but email accounts cannot be changed!

![screen shot 2013-08-16 at 10 04 33 am](https://f.cloud.github.com/assets/3014917/974124/b87b1f54-064a-11e3-9b75-f3a194c39279.png)

**Comment by tomas-knap** [comment]
Save button missing for users tab

**Comment by kukharm** [comment]
For what purposes need button save for users tab, what it will save?  This tab is only show the list of users in the system. In create user dialog there is save button.

**Comment by tomas-knap** [comment]
You are right, the save button is not needed on the user tab. 

But please, when the user is leaving from one tab to another and he has done some changes, ask the user whether he would like to save the changes or discard via a simple dialog. If he says he would like to save, the changes are saved. If he says withdraw, the changes are forgotten, the original values are restored. 

Such dialog must not destroy the application flow, so suppose I am e.g. working on the My Account tab, change something and then I click on the user tab. As a result, dialog occurs, because I did some change but did not press save. Then I confirm that I would like to save my changes. As a result, dialog disappears and my chosen tab (users) is open. Similarly, if I edit something on the My Account tab and click on the DPUs main menu item, the dialog appears and after closing the dialog, the desired menu item (DPUs) is automatically opened. If certain error occurs during saving certain settings tab (e.g. certain validation reveals some errors), my action (clicking on DPUs menu item, clicking on different tab) is cancelled and the tab with error is shown. Consult with Bohuslav if needed.

**Comment by kukharm** [comment]
Do I understand correctly:
If i create user and save it to the user table, then when i click to another tab should open confirmation window and if i won't confirm changes, created user will delete?
Or this confirmation window is only for My account and Schedule notification tabs?

**Comment by tomas-knap** [comment]
Only for those tabs, which directly contain save button. if there is an extra dialog (like for users tab), than any verification is not needed, because user is forced to save the newly created/adjusted users in order to close the dialog with user creation/adjustment.

**Comment by kukharm** [comment]
I have a problem with this confirmation. Under section Settings is ok, when i go from one tab to another i used button.ClickListener and on dependence of  my account or scheduler notification layouts state i show confirmation window.
Problem is when i click on the main menu. I didn't find click listener for menu bar.And i don't know what type of listener i should use in case when i go from settings/my account section to another for showing this confirmation.

**Comment by tomas-knap** [comment]
Ok, i will close this issue and create new for the switching between tab in settings and main menu item
