### ISSUE TITLE
Create scheduller notification settings dialog for settings container

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#203]
In the settings container (#202 ), new dialog appear containing what is described adn illustrated in https://grips.semantic-web.at/display/LOD2/Email+notifications

See specification and mockup there. In case of questions, write

Goal: 
1. prepare dialog based onthe mockup, put the dialog to container ( #202  )
2. implement functionality for checking values of the dialog according to mockup 
3. prepare object for holding the settings for scheduler notification in the memory. This object will be used by Jan when storing to db.
4 discuss with Petr (will be available till Friday only) how he can support this functionality (email notifications) in backend. 

Requires #202 to be ready

**Comment by kukharm** [comment]
Could you please describe more detail 2 and 3 points? According to 2 i should check that: 
"To save the settings, at least one email address must be set when at least one radio button group has different value than "no report". If email is not specified, error occurs and user cannot save the settings. Email has to be in correct format (checked!)"
or something else?

 According to 3: where should i place that object in project (frontend, commons-app?). Could you please give mi an examples of something like this in the project? I'm not sure that I understood what i need to do.

Thank you.

**Comment by tomas-knap** [comment]
Maria, 

yes, you are right with point 2.

Regarding 3, please contant Petr, he should be able to help you with that, mainly with the proper location of the class. In general, it is a class holding you configuration in the dialog.

**Comment by tomas-knap** [comment]
When adding new email as you can see below, there is a warning that email must be filled. When I fill email and move focus to the first original email, the warning is still there. 

![screen shot 2013-08-15 at 1 33 01 pm](https://f.cloud.github.com/assets/3014917/968376/c2a517f2-059e-11e3-899e-03cc53783789.png)

Solution: It should behave as described in #216

**Comment by tomas-knap** [comment]
instead of franta@test.cz as suggestion of the e-mail notification value, use something more serious, e.g. user@email.com

**Comment by tomas-knap** [comment]
When there is no email filled, an error occurs. This is fine, but the error must tell the user which tab contains an error and it has to be more descriptive

In this particular use case, it could be: Sheduler Notifications - At least one mail has to be filled, so that the notification can be send.

**Comment by tomas-knap** [comment]
If I save email in wrong format, the application has to provide error message from which it is clear that certain email XXX is incorrect because YYY. Error message must provide such information. 

![screen shot 2013-08-15 at 1 40 38 pm](https://f.cloud.github.com/assets/3014917/968399/a6001038-059f-11e3-9979-e7d5749f91a6.png)

**Comment by tomas-knap** [comment]
Email notificaitons should appear only on one place (now they appear in my account tab and also scheduller configuration, which is really confusing). We were discussing email notification will apppear in tab "My Account". Solution: remove "Email notification to" from "Scheduller notifications" tab.

**Comment by kukharm** [comment]
comment to email in wrong format: in your case error message is appear because of 2 empty fields after xxx. In case of absence this empty fields will be message "wrong e-mail format"

**Comment by tomas-knap** [comment]
Well, to solve that, the error message has to be more descriptive. And you should check and report all errors at once not just some errors.

**Comment by tomas-knap** [comment]
Please report me the progress on this

**Comment by kukharm** [comment]
"Email notifications to" was removed from "Scheduller notifications" tab  within a solution part of #202.

"When adding new email as you can see below, there is a warning that email must be filled. When I fill email and move focus to the first original email, the warning is still there. " 
in your case warning was there because of the wrong e-mail format of "a@". If you move the mouse to exclamation mark will be shown message about it. If e-mail will be in right format and you will move focus from this textfield, the warning disappears.

Now i solving checking all error at once.

**Comment by tomas-knap** [comment]
Maria, thanks. 

Regarding the errors presented to users, the following is not acceptable:

![screen shot 2013-08-19 at 12 32 43 pm](https://f.cloud.github.com/assets/3014917/985370/c596e886-08ba-11e3-94a6-5c5e57add9fa.png)

Instead of that, something like: 
-  Email "ab.cz" has wrong format. 

Further, if user create new field for new email but leaves it empty, when saving, empty field is automatically removed. Can you pls adjust it in that way?
