### ISSUE TITLE
Support for storing scheduller notification settings

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#205]
Database must support:
- storing of default settings for email notificaitons (see #203 ). Marie should prepare an object she would like to store to db. Please check that and add Hibernate annotations. 
- storing of particular settings for each schedulled event (if not specified, default settings are used) (see #204 ). This requires to extend SchedullerEvent representation and storage to db. 

Maria should have prepared dialogs for that by Monday 5.8.

**Comment by janvojt** [comment]
General notification settings for user are not implemented yet, as class `User` itself is not implemented yet. Setting priority to normal.
