### ISSUE TITLE
bigdata.ttl

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/odcs#21]
Should we use http://maven.apache.org/plugins/maven-dependency-plugin/examples/unpacking-artifacts.html to unpack zip with bigdata?
Classic zip reduce the size of bigdata.tll significantly and so decrease the amount of data stored on github.

**Comment by janvojt** [comment]
I would not include big files used only for testing in the repository at all. It should not be a part of tests that are run after each build, because test lasts long and it would slow down the development process.

**Comment by tomesj** [comment]
Solved
