### ISSUE TITLE
DPU tree component - handle longer DPU names

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#210]
![screen shot 2013-08-01 at 11 15 22 am](https://f.cloud.github.com/assets/3014917/892706/ee5c18ba-fa8a-11e2-8db5-008789f5f15f.png)

Solution: the width of the DPU tree component on the canvas should be define as % of the width of the whole window, but having certain minimal width (current width can be considered as minimal) 
Motivation for that: If the monitor permits, it should be able to enlarge the tree width. 

If the name is still longer, horizontal scrollbar should occur for the DPU tree component

**Comment by bogo777** [comment]
Width of the DPU tree is now set from width of items in tree. If the DPU tree is too wide, there will be option to minimize it soon.

**Comment by tomas-knap** [comment]
Bohuslav, please close when minimize is ready, just not to forget
