### ISSUE TITLE
When restarting pipeline, new execution record should be created

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#215]
Suppose that backend crashes. When the backend is again up, it should check which pipelines were running when it crashed and finish these pipelines with error and also sends an event to the end of the pipeline events telling that backend  crashed. Further, new execution should be run, with new number. 

Currently, when restarting, pipelines which were executed during crashing are restarted, but under the same execution number, which means that certain logs appear twice and it is confusing

**Comment by skodapetr** [comment]
Is the new execution record really what we want?
I mean restart is just temporary solution .. it should restart just one DPU in future (1 week). Then it may be better to not restart the whole execution as it could be running for long time and by this we lost the progress.

Does that change your opinion?

**Comment by tomas-knap** [comment]
Yes, that is true, but still, would it be confusing? There coulld be logs for the same DPU twice as its execution failed and then was restarting? On the other hand, if you create new execution record, than it would be strange that it starts from e.g. transformer, not extractor if new execution record is always created. So I would suggest to keep it as it is, we will see what is better.
