### ISSUE TITLE
Validation in GUI - should exclamation mark should dissappear when the value is filled

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#216]
When I e.g. create new pipeline and write the name of the pipeline, still, the red exclamation mark is there and if I point over the text field something like "Name must be filled" is there. This is a bit confusing

Solution: When the validation condition (e.g. that certain label is available) is satisfied, green tick could appear (or the red exclamation mark should at least dissapear).

**Comment by bogo777** [comment]
Exclamation mark dissappears when text box is left. Solved by 5bf5dab169a3e4d5b762cc92336e4475fb0a2ec4

**Comment by tomas-knap** [comment]
Bohuslav, is that fixed only for pipeline name field or also for the other, e.g. in DPU configuraitons?

**Comment by bogo777** [comment]
It is the way Vaadin works, only requirement is, that the validated field must be set immediate via field.setImmediate(true) for it to dissapear when field is left, otherwise it dissapears after next postback.
