### ISSUE TITLE
ctx.getWorkingDir() should return the trailing \\ or /?

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#217]
When calling ctx.getWorkingDir() to get a directory where to put temporary files, the method returns the path without the trailing \ or /. So if I want to use it for absolute file name generation, I need to know if I am on linux or windows to add either \ or /.

I would prefer to use it like this: ctx.getWorkingDir() + "sbirka.ttl" so I don't need to care about the platform.

Or is there any better solution? Can I use / no matter the platform?

**Comment by tomas-knap** [comment]
+1

It is better not to force the DPU developer to put "/" there.

**Comment by skodapetr** [comment]
getWorkingDir()  return type File
you can use 
`'File sbirka = new File(getWorkingDir(), "sbirka.ttl");`

I did not find a function that return path ending on trails (for File). But adding a support method that return such string is easy: 
`getWorkingDirPath()`

Or maybe adding whole class that manage this, like FileManager .. with methods  like`
createTmp(String fileName)  : File
getPathToTmp(String fileName) : String`

**Comment by tomas-knap** [comment]
Petr, if you proper comment what is the difference e.g. between getWorkingDir a getWorkingDirPath, that it is fine. Another question is that 'File sbirka = new File(getWorkingDir(), "sbirka.ttl"); looks like a reasonable approach to hide technical details about separators. So please choose some approach, comment that in the code and here and close this issues,.

**Comment by skodapetr** [comment]
I have created a help class in commons.module.file.FileManager. I thing it can be better solution than adding special methods and that it can be more user friendly to users.

Tomas can you please take a look on this and give me feedback?
