### ISSUE TITLE
DPU Extractor from PSP.CZ Configuration null problem

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#219]
DPU Extractor from PSP.CZ I am experiencing a configuration problem. There is no configuration dialog yet. But the Config class has defaults for all attributes, which should be used.

However, when the DPU runs, something calls its Configure method with a null for config, overwriting the defaults.

I tried extending ConfigurableBase instead of implementing Configurable interface with no effect.

**Comment by tomas-knap** [comment]
Please test and update the issue

**Comment by tomas-knap** [comment]
The problem still occurs based on Jakub's info, could you please check that? Do you need more information where the problem is?

**Comment by tomas-knap** [comment]
Jakub is testing once again
