### ISSUE TITLE
ExecutionMonitor, delete button

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/odcs#22]
It would be nice to have "delete" button. The button delete certain PipelineExecution from database and if the PipelineExecution has been in debugMode then also delete the context.

To delete context from disk use: 
ExecutionContextFactory.delete(execution.workingDirectory);

**Comment by tomas-knap** [comment]
Probably we could have button "Prune", which will removes all execution records older than X days.

**Comment by tomas-knap** [comment]
I would opt fo Prune button, which hides older pipeline executions, however, the executions remain in the database for further use (by scheduler when the pipeline was last run,...)

**Comment by tomas-knap** [comment]
duplicates #294
