### ISSUE TITLE
Table lazy-loading with filtering

### ISSUE THREAD

**Issue by bogo777** [mff-uk/odcs#220]
PagingComponent (https://vaadin.com/directory#addon/pagingcomponent:vaadin)

Target is to have Table with lazy-loading pages where it is possible to use filters while maintaining lazy-loading of filtered table records.

**Comment by bogo777** [comment]
Jan:
PagingComponent - posielal som Bohuslavovi odkaz, vyzera to slubne, ale hrozi, fasady by museli obsahovat extra metody s argumentami na strankovanie (inak este by sa mohol predavat nejaky objekt s info o strankovani v ramci session, ale to by bolo treba premysliet...)
Najst/napisat komponentu pre strankovanie, ktora by vyuzivala QueryBuilder. Tu by sa porusil design s oddelenymi vrstvami, ale na druhu stranu by sme mali komponentu ktora by fungovala vsade bez dalsich uprav. Problem by bol potom aj s autorizaciou, kedze frontend by sahal priamo do db.
Nejak skombinovat oba pristupy - namiesto pouzitia querybuilder, predavat frontendu nejaky vlastny objekt, kde by uz bola vybrana entita, predfiltrovany vysledok autorizatorom len na povolene objekty. Na tomto objekte by potom mohol frontend dalej filtrovat, ale nemohol by zrusit uz zadane kriteria.

Tomas:
Ad 1), to ale neresi problem efektivniho filtrovani, ne? Sice budu mit nactene jen nejake stranky, ale jakmile dam filtr trebas do tridy na kterou je log vazany, tak budu cekat. 

Asi by se mi libila varianta 3, tedy QueryBuilder, s tim, ze si to query nebuildi frontend sam, ale pouziva k tomu tridu a jeji exposnute metody, tedy frontend nepotrebuje znalost DB, resp. SQL query dela prostrednik. Tedy frontend si jen rekne, ze napriklad chce nastavit filter X pro sloupec gui tabulky Y a prostrednik pripravit fyzicky dotaz do DB. Chapu spravne? 

Jan:
1) Resi, ta PagingComponent pouziva nejaky FakeList. Ten potom vola nieco ako getItems(startIndex, endIndex), kde sa uz z DB nacitavaju len dane zaznamy. Takze tie zaznamy su do kontajnera lazy loadovane podla potreby.
3) Mne by sa to tiez najviac pacilo, bolo by to ale najviac zlozite na implementaciu. Musim sa pozriet na ten QueryBuilder ako funguje v Hibernate. Ideu chapes spravne.

**Comment by bogo777** [comment]
V te PagingComponent je takovy basic priklad vlastniho containeru, ktery strankuje podle te komponenty. To vidim jako cestu kudy se vydat. Ani bychom nemuseli pouzit primo tu pagingcomponent, pokud by bylo pouzitelne to strankovani z PagedTable co mame ted, coz by melo byt.

Predstavoval bych si vlastni container, ktery jako parametr dostane treba Facade a diky nejakemu rozhrani bude vedet jakou zavolat metodu, aby ziskal data pro aktivni stranku. Parametrem by se nejakym zpusobem predaly filtry a vysledka query by se sestavila ve facade a zustalo by to oddelene. Mozna by nebylo spatne zacit QueryBuilderem a zkusit vyuzit ten LazyQueryContainer, tady jsem nasel jeste jeden clanek o jeho nasazeni: http://devblog.mycorner.fi/34/using-appfoundation-together-with-lazyquerycontainer/

Myslim, ze bysme pak cely ten QueryBuilder pouzili i v tom custom containeru ve facade, ale mozna nebude o tolik pracnejsi to udelat rovnou.

**Comment by tomas-knap** [comment]
Kluci, co jste se tedy dozvedeli posledni tyden? Porad to vypada na tu variantu:

3) Nejak skombinovat oba pristupy - namiesto pouzitia querybuilder, predavat frontendu nejaky vlastny objekt, kde by uz bola vybrana entita, predfiltrovany vysledok autorizatorom len na povolene objekty. Na tomto objekte by potom mohol frontend dalej filtrovat, ale nemohol by zrusit uz zadane kriteria.

Napiste mi tu prosim jaky je progress.

**Comment by bogo777** [comment]
Zmergoval jsem svou branch s lazy-loadingem do masteru. Aktualne je to pouzite na: seznam pipeline, execution monitor, execution records, log messages. 
Meli bychom rozmyslet, kde lazy-loading pouzijeme. Pokud nekde bude relativne malo zaznamu, bylo by vyhodnejsi pouzit inmemory container, ktery ma tu vyhodu, ze po uvodnim nacteni uz veskere filtrovani probiha take inmemory, naopak pri nasem pristupu znamena kazde filtrovani dotaz do databaze.

Jinak zatim pouzivam upraveny LazyEntityContainer, ale uprava na variantu 3) bude jednoducha a vyuziji se veskere upravy, ktere jsem v tom containeru musel provest.

**Comment by tomas-knap** [comment]
Test that

**Comment by tomas-knap** [comment]
Bohuslav, Jinak zatim pouzivam upraveny LazyEntityContainer, ale uprava na variantu 3) bude jednoducha a vyuziji se veskere upravy, ktere jsem v tom containeru musel provest. Uprava na variantu 3) uz je?

**Comment by tomas-knap** [comment]
Outdated
