### ISSUE TITLE
Prepare Users/Roles functionality

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#222]
1. Adjust mockup in confluence, prepare dialog, interconnect dialog (if I click add, it is working, dialog for adding user occurs). Values are checked, if needed.
2. Discuss with Jan how the data will be stored in DB. Interconnect with DB, test (it is possible to add/delete/edit user)

**Comment by janvojt** [comment]
User/Roles are already persisted in DB. It was needed for user notification settings, so this part should be ready.

**Comment by kukharm** [comment]
Yesterday i started interconnection user/roles its ok. Нow can i get data to the column total pipelines? It's number of pipelines that was run by this user?

**Comment by tomas-knap** [comment]
Maria, ask honza to prepare SQL query which takes this info from execution
records.

**Comment by tomas-knap** [comment]
- Warnings that certain values are not filled MUST behave as in #216. Ask bohuslav how to do that. 
- When I select roles to be set, and click on >>, strange blue border appears around textareas and the whole dialog is resized. Resizing must be avoided, blue border removed. 
- Make sure that there cannot be two users with the same name!
- When "Change settings" button is pressed, the current values about the user has to be prefilled!
- When pressing "Delete user" a warning should be presented

**Comment by kukharm** [comment]
I tried to remove this blue border (in my case its yellow..) but I was not able to change it. Its something in chrome  browser, because in fierfox its all right. In my case this borders appears in all focused elements in chrome.

**Comment by tomas-knap** [comment]
Regarding the blue border, it should be definitely thiner, when I look e.g. to DPU templates menu item and to some DPU field, it is much thiner. That is the problem I think.

**Comment by kukharm** [comment]
I agree with you, but TwinColSelect component that i used for selecting roles is also standard vaadin component and i don't know how to change it behaviour. I am afraid that the solution of this border will take a lot of time now.

**Comment by tomas-knap** [comment]
Ok, please solve the rest of the issues and then create new issue just for the blue borders (with reference to this one) and assign Bohuslav

**Comment by tomas-knap** [comment]
Report please the progress on this today

**Comment by kukharm** [comment]
Uzivatele lze vytvorit a ulozit, pak smazat. 
Nefunguje zatim automaticke generovani hesla a sloupec total pipeline (ale to napravim)

```
Make sure that there cannot be two users with the same name! - funguje
When "Change settings" button is pressed, the current values about the user has to be prefilled! -funguje
When pressing "Delete user" a warning should be presented - funguje
```

**Comment by tomas-knap** [comment]
Great, looks nice. 

Comments: 
- when changing details of existing user, do not show any value for the password (the problem is that it shows useless hash of the password). If admin would like to change the password of certain user, he may simply start writing new one. 
- when creating new user, please put there also field for password. if this password is left empty, random password is generated (current functionality). If certain password is filled, this password is used. 

One question, how is the password generated? Can you please describe here a bit? Could you please solve that before leaving tomorrow?

**Comment by tomas-knap** [comment]
You may leave the functionality of showing total pipelines to September, I will create for that special issue

**Comment by kukharm** [comment]
point 1.  It need to discuss with Jan,  he prepared method UserFacade.createUser(), that hash password. This function used in new user creation. But i don't know how to dehash it, that's why when changing details of existing user it shows hash of the password.  If administrator changing the password used user.setPassword() method for saving record that don't hash password and then the value will be shown ..  

point 2 i try to solved now.

Password generated by method createPassword(), that generate random password of 6 symbols from a-zA-z0-9. Method return string with this password.

```
private static final String allowedcharacters= "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWZXY0123456789";
private String createPassword(){
    int passwordSize = 6;
    Random rnd = new Random();

    StringBuilder result = new StringBuilder();
    int randomIndex;
    while (passwordSize>0)
    {
        randomIndex = rnd.nextInt(allowedcharacters.length());
        result.append(allowedcharacters.charAt(randomIndex));
        passwordSize--;
    }
    return result.toString();
}
```

**Comment by tomas-knap** [comment]
Maria, 

ad point 1) You do not need to dehash it, it is not possible for security reasons. I would suggest the following solution and then we can close this issue. When admin click on the button "change details" of user, all the fields will be prefilled, the password field will be filled with couple of stars (typical behaviour for password protected fields). If admin does not enter the password fields (for example he just edits the user's email), when saving the changes, the password will not be changed and the original remains valid. If admin enters the password field, the password field will become empty and admin can create new password. As he is writing the password, it is normally visible. When saving the record, the new password is set. If admin enters the field password, but did not fill any, new automatically generated password will be set to the given user's email (as in case of new user creation). What do you think?

**Comment by kukharm** [comment]
"If admin enters the password field"  it means that administrator put focus on this field?

**Comment by tomas-knap** [comment]
yes. If admin puts focus by mistake, he can always cancel the change details dialog.
