### ISSUE TITLE
Users and authorization - approach 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#224]
Notion of user:
Normal user & admin (can everything)
I would suggest to keep the notion of roles, not just testing isAdmin(). Now we have only two roles, but may be more later. 
- Every user may list,edit,run,schedulle,delete... only pipelines accessible for him, admin may see/edit everything
1. Output: Adjusted confluence, opinions of Jan/Petr. 
2. Plan and estimate what needs to be done (in the comments under the issues) 
3. create more fine grained issues if needed, distributed among Jan/Petr if it makes sense

**Comment by tomas-knap** [comment]
What is the status? Is it ready in confluence?

**Comment by tomas-knap** [comment]
Honzo, mame v confluence nejaky zaznam o tom jak to funguje? Pokud ne, tak rychle dopln, at na to muzu mrknout a muzem kdyztak jeste korigovat. Jinak tedy tento task chces mit dnes hotovy, vcetne implementace toho approach jako je v bodu 1 v iteration 4 na confluence? <b> Tohle potrebuju vedet, abych mohl planovat.</b>

**Comment by janvojt** [comment]
Sharing and permissions for DPUs and Pipelines are documented in [confluence](https://grips.semantic-web.at/pages/viewpage.action?pageId=42730318). As documented, pipelines have a special Access Control List with permissions defined explicitly for each user.

I plan to finish general security restrictions based on entity ownership tonight/tomorrow, including restrictions for public/private DPUs and general admin privileges on all entities. Special case for pipelines will require more work, I plan to implement this till the end of the week (probably thursday).

Implementation will use spring security based on annotations. Security context will be defined in frontend. Backend will have no security context defined, as it is not applicable. Tests will have the possibility to define a security context specifically for each test suite as needed. Thus it should be clean and flexible.
