### ISSUE TITLE
Login screen, possibility to log into the system

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#225]
Dialog for logging into the system.

When user accesses certain page and his session has timeouted, login dialog should appear (it should appear instead of the main window)

 Please provide first draft implementation or mockup, then we can discuss details.

Needs cooperation with Petr/Jan.

**Comment by bogo777** [comment]
Available at /#!Login
I wanted to make the content vertically and horizontally centered on page, but failed to do so yet.

**Comment by bogo777** [comment]
Login screen is present, it is shown instead of any page if user is not logged or his session expired. Information about logged in user are shown in top right corner with possibility to log out of the system.
