### ISSUE TITLE
Prepare DPU which validates RDF data

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#227]
Prepare special DPU, which validates the incoming data. The general idea is that the incoming RDF data are validated using Apach Fuseki - to check datatypes of the literals and form of the URIs (identifiers) of subjects/predicates/objects. User may specify what should happen when data has certain errors (possibilities - pipeline finishes with error/ warning is displayed and processing continues). Output of the DPU is formed by the data itself and also a summary report. 

 If there are more named graphs forming input, the dpu should be possible to say: data unit named X is valid, data unit named Y contains this/this/this error. Everything should be in log and in the final report. 
1. Please prepare mockup, we can discuss about. 
2. Implement what we have discussed.

**Comment by tomesj** [comment]
Add page to confluence with mockups
https://grips.semantic-web.at/display/LOD2/DPU+-+Validator+of+RDF+data

**Comment by tomas-knap** [comment]
Jirka, it is not clear to me:
- how the report will be presented to the user? How will be the table with the resulting status (File Extractor OK etc.) presented? One way is to log it with INFO/WARNING/ERROR level, but it would be also good to add one extra output -> RDF report which descripes in RDF (turtle e.g.) the content of the table (File extractor OK etc.) 
- what happens if the DPU1 has more output data units (more named graphs with data?) I need to know which named graph has error.
- !! Please sketch the configuration of the validation DPU - this is crucial and this is what I though you will do !!
- !! Please sketch the sample Turtle file containing the final report

If something is not clear, just ask

**Comment by tomas-knap** [comment]
Jirka wrote in email: 

#227 - Co udělat jako výstup XML soubor, kde by byl zaznamenám DPU, jména grafů a stavy o chybách. Tedy vlastně to, co je v tabulce rozšířené o názvy grafů....

Něco jako:

![screen shot 2013-08-16 at 11 18 54 am](https://f.cloud.github.com/assets/3014917/974449/e112ff2c-0654-11e3-987a-22c9ecd55c96.png)

Napiš mi, co a jak, resp. zda je to OK. Já k tomu udělám pak mockupy :-)

**Comment by tomas-knap** [comment]
Jirka, that would require that also other formats than RDF may be send along data unit. Since I have more use cases for this, we will need also other data units, probably just XML data unit as part of the project, rest will be future work. 

But, why cannot you store the the data as RDF, e.g. based on your example: 

http://.../reported_item1 xx:context http://graph1 .
http://.../reported_item1 xx:dpu http://.../File_extractor/0.0.1 .
http://.../reported_item1 type http://..../types/OK .
http://.../reported_item1 message "No problem - valid" .

I would prefer to store it as RDF. Can you please propose 3-4 different examples how the result of the validation can be stored as RDF, including full HTTP URIs (not just ... as in my example). Think also about naming rules for  URIs for dpus/named graphs, they should be accessed according to some methodology. Write the examples (in TURTLE syntax) + methodology to confluence to the DPU validator page. 

What do you think? Is it clear?

**Comment by tomesj** [comment]
I thought, that report will be only create as output - if there is an idea to send it along data units, I prefer of cource RDF variant - there is no problem with compatibility. I prepare some variant of storing, but I don´t known what you do mean if you speak about methodology. Give me please more information about it :-) 

I will add then all to confluence page.

**Comment by tomas-knap** [comment]
This should work as validation of SPARQL extractor - it uses statistical and error handler. And it has two outputs -> The original (and validated data) and errors, which should form the second output. Discussing is needed how to represent the errors find out during validation (problematic triple, errror description)

**Comment by tomas-knap** [comment]
Suggested way how to output the errors (the second output data unit of the DPU):

@prefix odcs-val: http://linked.opendata.cz/ontology/odcs/validation/
@prefix exec-error: http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/282/dpu/182/validation/error/

http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/282/dpu/182/validation/error/1 rdf:type odcs-val:Error ;
     odcs-val:subject  http://...public-contract/..2012 ;
     odcs-val:predicate http://...tenderDeadline ;
     odcs-val:object "Date2012...00" ;
     odcs-val:reason "Date2012...is not a valid value for a datatype .." ;
     odcs-val:sourceLine "71"^^xsd:integer   . 

The above is a way how to write the first error in the screenshot: https://f.cloud.github.com/assets/3014917/1492726/367d5024-47c4-11e3-8952-34ebd3f198ec.png

So every error will be written in the same way and outputted to the proper output as RDF data.

**Comment by tomesj** [comment]
RDF Data validator finished and prepare for using. Issue for close.

**Comment by tomas-knap** [comment]
Jirka, what is the purpose if validation report path in the configuration? 

The ida was that RDF data validator provides two output data units -> one with the validated data and one with the report. There is no need to store the report to a file. Could you please adjust that?

**Comment by tomesj** [comment]
From what I understand, how RDF Data Validator DPU works: 

There are 1 (or more) input(s)
- with RDF data you want to validate

There are 2 outputs
1) RDF data that are valid (data which dont passed are not send to output)
2) File with report in TTL format (contains problems triples, case of invalidation,describe message,..) 

But do you want to make 2) as second output of this DPU ? 
And what about GUI form for this - it could be empty, if I will delete to make report to file ?

**Comment by tomas-knap** [comment]
Yes, that was the idea, because typcally you would like to e.g. load the generated report via a loader to some repository with reports. GUI may remain empty, thats fine

**Comment by tomesj** [comment]
RDF Data Validator updated (GUI + logic) 

Now we use 2 outputs:
1) Validated_Data
2) Report 

Issue finished and prepare for close :-)

**Comment by tomas-knap** [comment]
Please test the data validator (the report ouput) on ted.ttl -
https://grips.semantic-web.at/download/attachments/45647302/ted2.ttl?version=1&modificationDate=1373889358000&api=v2

I have a pipeline with data containing errors - extractor can reveal such problems but data validator is not reporting anything. 

RDF data validator should log all the problems revealed at the debug level

Also please mark Output containing validated data as optional, report is mandatory.

**Comment by tomas-knap** [comment]
Sorry, it is working, the problem was that extractor took and removed all the problematic triples

but this remains: 
- There should be always a single event saying - Validation Successfull - NO ERRORs, or summary report
- Also please mark Output containing validated data as optional, report is mandatory.

**Comment by tomas-knap** [comment]
Regarding the format of the report:

PREFIX declaration is missing. @prefix odcs-val: http://linked.opendata.cz/ontology/odcs/validation/
-> ztrati se pri mergovani native repositories - reseni: bud predavat namespaces (krome kopirovani dat) a nebo mit namespace prefix nahodny pri ulozeni do souboru. 

You have:

http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/177/dpu/146/du/0 rdf:type odcs-val:ERROR ;
    odcs-val:subject/1 "http://ld.opendata.cz/resource/ted.europa.eu/public-contract/76ce4558-c4ec-4c4a-88cd-19293bffd675-1295-2012" ;
    odcs-val:predicate/1 "http://purl.org/procurement/public-contracts#tenderDeadline" ;
    odcs-val:object/1 "\"Date2012-02-09T10:00:00\"^^http://www.w3.org/2001/XMLSchema#dateTime" ;
    odcs-val:reason/1 "'Date2012-02-09T10:00:00' is not a valid value for datatype http://www.w3.org/2001/XMLSchema#dateTime" ;
    odcs-val:sourceLine/1 "37"^^xsd:integer ;

You should have: 

http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/282/dpu/182/validation/error/1 rdf:type odcs-val:Error ;
odcs-val:subject http://...public-contract/..2012 ;
odcs-val:predicate http://...tenderDeadline ;
odcs-val:object "Date2012...00" ;
odcs-val:reason "Date2012...is not a valid value for a datatype .." ;
odcs-val:sourceLine "71"^^xsd:integer .
