### ISSUE TITLE
Building project on DEBIAN failed - RDF module encoding

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#228]
It is not possible to build RDF module on Debian due to encoding. Jirka, please check that. Discuss with others in case of problems. When adjusted, please verify in the lab on linux.

[INFO] ------------------------------------------------------------------------
[INFO] Building RDF
[INFO]    task-segment: [install]
[INFO] ------------------------------------------------------------------------
[INFO] [resources:resources {execution: default-resources}]
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/knap/tools/ETL/0.3/intlib/rdf/src/main/resources
[INFO] [compiler:compile {execution: default-compile}]
[INFO] Compiling 21 source files to /home/knap/tools/ETL/0.3/intlib/rdf/target/classes
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Compilation failure

/home/knap/tools/ETL/0.3/intlib/rdf/src/main/java/cz/cuni/xrg/intlib/rdf/enums/RDFFormatType.java:[10,45] error: unmappable character for encoding ASCII

/home/knap/tools/ETL/0.3/intlib/rdf/src/main/java/cz/cuni/xrg/intlib/rdf/enums/RDFFormatType.java:[10,46] error: unmappable character for encoding ASCII

**Comment by tomas-knap** [comment]
Jirka, so did you find where the problem is?

**Comment by tomesj** [comment]
Honza sent mail about it.
