### ISSUE TITLE
Problem with config.properties

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#229]
When checkouting and trying release 0.3.0, the prepared config.properties file in conf folder contains only settings: module.path, which points to "target". Which is fine. However, when launching backend, error occurs saying that module.lib configuration option is missing. So probably the config reader is expecting two options module.path and module.lib

Jirka, please test that and let us know.

**Comment by tomesj** [comment]
The main problem is, that file config.properties in actuall version has less configuration setting than in release 0.3.0 (modulule.lib, some frontend/backend expose are missing, etc...) 

See actuall version:
https://github.com/mff-uk/intlib/blob/master/conf/config.properties

See version in release 0.3.0
https://github.com/mff-uk/intlib/blob/release-0.3.0/conf/config.properties

Petr made all changes in this file. Try to ask him. 

I think, that we should to support all our releases with 1 configfile - it´s better to have more configuration setting than less. It will solve the problem with using different releases.

**Comment by tomas-knap** [comment]
Jirka, 

it should be ok, when creating release 0.3 branch, config.properties is frozen with the values being valid when 0.3 is created, so separate config.properties for different versions is not needed imho. Petre, when you return, please check that. Probably there are some inconsistencies.

**Comment by tomas-knap** [comment]
Solved, two paths - target/dpu target/lib is ok in 0.3
