### ISSUE TITLE
Config properties - trailing "/" in module path

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#230]
In release 0.3, if I define module path as ..../target/dpu, than it appears: 

![screen shot 2013-08-12 at 9 56 22 pm](https://f.cloud.github.com/assets/3014917/950109/64949c58-0389-11e3-81ae-b48ca8999664.png)

It should automatically add the trailing "/" when resolving the path. Please correct that in release 0.3 and check it does not occur in 0.4

**Comment by tomas-knap** [comment]
How is it with config properties in release 0.3? Should be both module path and module lib included? Or just one path?

**Comment by skodapetr** [comment]
0.3: I believe that just one according to comments in prepared config.properties.

In 0.4 no trailing is required, but it may be good idea to update code that it can survive when user use one.

**Comment by tomas-knap** [comment]
Ok, leave it as it is in 0.3
In 0.4, adjust the code, so that user can use the path with/without the trailing "/". then close this issue

In release 0.3, if i am looking on the conf/config.properties template, there are two paths. So 0.3 requires both paths. But it is ok, it is then improved in 0.4
