### ISSUE TITLE
Error when loading DPU, exception is not much expressive

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#231]
The exception below, which occurs probably because of problem in config.properties is not very expressive - should be more concrete if possible, so that the user can further adjust the given bundle/config.properties

![screen shot 2013-08-12 at 10 03 38 pm](https://f.cloud.github.com/assets/3014917/950179/7aa8592a-038a-11e3-9259-152d5a486a4b.png)

**Comment by tomas-knap** [comment]
It seems to me that this problem occurs when I accidently put non-OSGi bundle to the folder target/dpu. As a result, no bundle, even the valid one, cannot be loaded.

**Comment by skodapetr** [comment]
Can you be more specific? Just place a single non-java file into target/dpu ? 
This should not cause the problem as bundles from target/dpu are loaded on demand.

I will add more concrete exception.

**Comment by tomas-knap** [comment]
Thanks, otherwise it is working now
