### ISSUE TITLE
Problem with DPU tree depiction when resolution is low, 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#232]
When resolution is low, se below, there is not way how to see certain parts of the DPU tree. IT may be problem during presentation of the project on low resolution projector. 

![screen shot 2013-08-12 at 10 12 57 pm](https://f.cloud.github.com/assets/3014917/950248/b7aae792-038b-11e3-8611-97c535a8d8a8.png)

Solution 1: Vertical scrollbar for DPU tree

Solution 2: There upper part (pipeline name & description & permissions in the future) should be hideable

I would prefer Solution 2. Especially when there will be permissions, the upper part should be hidable because it may take most of the screen height. Bohuslav, what do you think?

**Comment by bogo777** [comment]
Pipeline detail(name, description, ..) is now hideable. Also DPUTree changes height with window's height change. There is still the problem with button bar ober the tree though.
