### ISSUE TITLE
Problem with config.properties - Invalid lib path

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#233]
Ahoj, 

Petre, mrkni prosim na ten problem s konfiguraci a napis jim. 

Diky, Tomas
---------- Forwarded message ----------
From: cammeronm@gmail.com
Date: 2013/8/5
Subject: Re: ODCleanStore chyba front-endu po deploy na Tomcat
To: intlib@googlegroups.com
Cc: Jindřich Mynarz mynarzjindrich@gmail.com

Ahoj,
mám stejný problém (https://www.dropbox.com/s/ul27fjx06rdrnzm/intlib-error.html)

intlib, který instaluju jsem z gitu stáhl dnes.

v souboru $HOME/.intlib/config.properties by s tím mohl souviset řádek:
module.path = /home/cammeron/Java-Workspace/intlib/target

tam mám ale cestu nastavenou přesně podle pokynu.

V adresáři intlib/target/lib mám akorát:
commons-module-0.0.1.jar
/backend

ve složce /backend je dále:
commons-web-0.0.1.jar                     vaadin-shared-7.1.0.jar
com.springsource.javax.servlet-2.4.0.jar  vaadin-shared-deps-1.0.2.jar
jsoup-1.6.3.jar                           vaadin-theme-compiler-7.1.0.jar
vaadin-client-compiled-7.1.0.jar          vaadin-themes-7.1.0.jar
vaadin-server-7.1.0.jar

mvn install proběhl jinak úspěšně a backend běží.
Nevíte co s tím frontendem?

Díky

Michal

Dne čtvrtek, 11. července 2013 17:30:07 UTC+2 Tomas Knap napsal(a):

> A co mas v adresari intlib/target/lib za knihovny?
> 
> Tom
> 
> 2013/7/10 Jindřich Mynarz mynarzj...@gmail.com
> 
> Ahoj,
> 
> nakonec jsem ODCleanStore zkompiloval (možná byste mohli uživateli dát radu, že při kompilaci musí běžet Virtuoso), ale po deploynutí přes Tomcat manager jsem dostal následující chybu: https://dl.dropboxusercontent.com/u/893551/pracovni/LOD2/Extraction/ODCleanStore/intlib_error.html
> 
> Any idea what might be wrong?
> - Jindra
## 

Tuto zprávu jste obdrželi, protože jste přihlášeni k odběru skupiny intlib ve Skupinách Google.
Pokud chcete zrušit odběr skupiny, aby vám z ní již nechodily e-maily, zašlete e-mail na adresu intlib+unsubscribe@googlegroups.com.
Další možnosti najdete na adrese https://groups.google.com/groups/opt_out.

**Comment by skodapetr** [comment]
From email conversation: ...stačilo umístit konfigurační soubor do adresáře /usr/share/tomcat7/.intlib
Podle původních instrukcí jsme jej měli umístit pouze do $HOME/.intlib, ale u mě ho hledá i v adresáři tomcatu.
Už jsem tam ten soubor měl z dřívějška (podoba konf. souboru za tu dobu prošla změnami), ale zapomněl jsem na to a zůstala tam stará verze - proto ta divná hláška.

Maybe we should update tutorial? Unfortunately this does not seem to be Win OS ..

**Comment by tomas-knap** [comment]
Ok, yes, Petre, does it write to the application log which config.properties is used? It also happened to me that I have forgotten old config.properties on the right location and updated wrong location (on Linux, running under different user, updating my own homedir)
