### ISSUE TITLE
Loading of DPU modules fails.

### ISSUE THREAD

**Issue by janvojt** [mff-uk/odcs#239]
I cannot get DPUs to work. I believe my configuration is correct, because filepath in the error message is correct. Jar file exists in given path and is world-readable.
![screenshot from 2013-08-15 22 50 11](https://f.cloud.github.com/assets/2247062/971772/b93401b6-05ed-11e3-949d-fef9b3f54976.png)

**Comment by tomas-knap** [comment]
Honza, this problem occurs on the master branch, right?
