### ISSUE TITLE
Missing configuration for use statistical handler

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#240]
When I launch the fresh release 0.3 install with sample dbpedia pipeline and run the pipeline, the log shows: 

![screen shot 2013-08-16 at 10 30 25 am](https://f.cloud.github.com/assets/3014917/974272/6afb045c-064e-11e3-9b7d-0a3db6a2d720.png)

Does that mean that the implementaiton of SPARQL Extractor does not explicitely set false to configuraiton option "use statistical handler"? If yes, correct that Jirka. 

Further, when I explicitely save use statistical handler to true via DPU details dialog and then back to false, the warning above appears again. Why?

**Comment by tomesj** [comment]
There are may be problems with null configuration or something like that. I try to find potencial problem and correct them, or contact responsible person :-) Then I test it, if this problem are solved.

**Comment by skodapetr** [comment]
To my knowledge: DB dump does not contains option for UseStaticalHandler .. which mean that in configuration this value is null .. I have added this message to prevent DPU from crash .. 

Actually the wrong DB dump is I believe in release 0.4 too .. but I have removed the message

To fix: Repair the DB dump (Honza) best for release 0.3 and 0.4

Why the warning appears after saving is good question. It can be useful to check the DB if the setting has been really stored and then add some log message to the DPU to find out the real value of configuration when the DPU starts. Jirka if you need assistance with this issue feel free to contact me.

**Comment by tomesj** [comment]
I think, that old pipeline had no option for UseStatisticalHandler in DB (how Peter wrote) - it cause problems, but I think in actuall version release 0.3 is it solved yet (I check DB one more time for sure). I tested dialog manualy and boolean value is in dialog always set (never null value). I will delete warnings message (case null pointer) - if there is no problem in DB its all what to can change. 

And for using without problem I recommend to create new pipeline (contains new configuration set).

**Comment by tomesj** [comment]
I added it (remove warning commit) to release 0.3 (in master is other implementation and using) - I tested bouth extractors - SPARQL and File (creating and run pipeline) and it there was no problem. I checked DB.INTLIB.DPU_INSTANCE and there is all without problem :-)
