### ISSUE TITLE
DPU template - user should be warned when he did some changes and leaves the given tab/selected dpu template

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#246]
In a similar way as #244. When you come back end of August

**Comment by kukharm** [comment]
Probably will require a method for getting data from configDIalog from Petr. Now there is no possibility to check configDIalog for changes. We agreed to discuss this at the meeting 10.9. Confirmation dialog now responding to changes in tab General only.

**Comment by tomas-knap** [comment]
It also not possible to provide readonly dialog (DPU detail) when user does not have rigths to change the dialog

**Comment by tomas-knap** [comment]
What is the status? It is marked as solving

**Comment by kukharm** [comment]
Resolved in #502  (viz last comment). Changes in configDIalog controls by method hasConfigChanged()
