### ISSUE TITLE
Adjust HTTP URIs created in virtuoso as the pipeline is executed

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#250]
Currently, URI is of the form: http://ex3_dpu4_du0

Prefix is needed: http://linked.opendata.cz/resource/....

**Comment by skodapetr** [comment]
Should the prefix be adjustable by user (in configuration file) ?

**Comment by tomas-knap** [comment]
No, if the user (admin) changes the default internal named graph prefix when certain named graphs are alraedy in database, it will bring problems. So we can fix the prefix, it is our internal stuff more or less.

**Comment by skodapetr** [comment]
Ok ,in that case .. I believe it's just minor change in Jirka's code.

**Comment by tomas-knap** [comment]
Jirka, please change the named graph names of type "http://ex3_dpu4_du0" to "http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/3/dpu/4/du/0"?

**Comment by skodapetr** [comment]
It's more issue for me as the graph url is set from backend. So I reassign it.

**Comment by skodapetr** [comment]
Tomas please check if that is what you want. Also the browsing of previously created DU won't work.

**Comment by tomas-knap** [comment]
Yes, that is fine, thanks also for writing the test :)
