### ISSUE TITLE
Better error reporting in GUI

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#251]
When certain problem appears, e.g. DPU impl does not properly implement setConfiguration in DPUConfigDialog (or just throws exception there), the exception below occurs. Really verbose and looks confusing. Could you please catch these exceptions and show to the user the original source of the problem, e.g. in this case the red dialog will be shown with the message e.g. Method for storing configuration threw exception: "Not supported yet".

com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method click in com.vaadin.shared.ui.button.ButtonServerRpc at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:170) at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:214) at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111) at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:158) at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:289) at com.vaadin.server.communication.PushHandler.onRequest(PushHandler.java:308) at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:259) at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:166) at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:137) at org.atmosphere.container.Tomcat7AsyncSupportWithWebSocket.service(Tomcat7AsyncSupportWithWebSocket.java:59) at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1448) at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:219) at org.atmosphere.websocket.DefaultWebSocketProcessor$2.run(DefaultWebSocketProcessor.java:183) at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101) at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:178) at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:167) at org.atmosphere.container.TomcatWebSocketHandler.onTextMessage(TomcatWebSocketHandler.java:92) at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:74) at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:187) at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:135) at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:83) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:587) at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:722) Caused by: java.lang.reflect.InvocationTargetException at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:601) at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ... 26 more Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method buttonClick in cz.cuni.xrg.intlib.frontend.gui.components.DPUDetail$2 failed. at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:528) at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:968) at com.vaadin.ui.Button.fireClick(Button.java:368) at com.vaadin.ui.Button$1.click(Button.java:57) ... 30 more Caused by: java.lang.UnsupportedOperationException: Not supported yet. at cz.cuni.mff.xrg.intlib.extractor.jtaggerExtractor.JTaggerExtractorDialog.getConfig(JTaggerExtractorDialog.java:115) at cz.cuni.xrg.intlib.frontend.auxiliaries.dpu.DPURecordWrap.saveConfig(DPURecordWrap.java:127) at cz.cuni.xrg.intlib.frontend.auxiliaries.dpu.DPUInstanceWrap.saveConfig(DPUInstanceWrap.java:13) at cz.cuni.xrg.intlib.frontend.gui.components.DPUDetail.saveDPUInstance(DPUDetail.java:205) at cz.cuni.xrg.intlib.frontend.gui.components.DPUDetail$2.buttonClick(DPUDetail.java:148) at sun.reflect.GeneratedMethodAccessor108.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:601) at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ... 34 more

**Comment by bogo777** [comment]
There is way in Vaadin to process uncaught exceptions and customize how they are displayed, instead of the very long error window that appears now. I made first attempt to customize it and now only short error dialog is displayed. But there are maybe too few infromation now.

Also for more precise description of errors, as in example:
e.g. Method for storing configuration threw exception: "Not supported yet".
, more individual solutions must be done.

**Comment by tomas-knap** [comment]
Ok, can you point me please to the code where some individual solution is used?

**Comment by bogo777** [comment]
Ok, look at last commit regarding this issue. There was try-catch block for ConfigException, but not for general exceptions. So exception at this level was processed at application level.

So what I actually meant is, that we need right try-catch blocks, where we want more customized error mesages.

**Comment by tomas-knap** [comment]
Test that
