### ISSUE TITLE
Frontend out of memory

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#252]
After a few (20?) cycles of Stop backend, mvn install DPU, replace DPU JAR, run backend, refresh frontend the following error occured in the frontend:

HTTP Status 500 - com.vaadin.server.ServiceException: java.lang.OutOfMemoryError: PermGen space

type Exception report

message com.vaadin.server.ServiceException: java.lang.OutOfMemoryError: PermGen space

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: com.vaadin.server.ServiceException: java.lang.OutOfMemoryError: PermGen space
    com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
root cause

com.vaadin.server.ServiceException: java.lang.OutOfMemoryError: PermGen space
    com.vaadin.server.VaadinService.handleExceptionDuringRequest(VaadinService.java:1387)
    com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1341)
    com.vaadin.server.VaadinServlet.service(VaadinServlet.java:236)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
root cause

java.lang.OutOfMemoryError: PermGen space
    sun.misc.Unsafe.defineClass(Native Method)
    sun.reflect.ClassDefiner.defineClass(Unknown Source)
    sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
    sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
    java.security.AccessController.doPrivileged(Native Method)
    sun.reflect.MethodAccessorGenerator.generate(Unknown Source)
    sun.reflect.MethodAccessorGenerator.generateMethod(Unknown Source)
    sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    java.lang.reflect.Method.invoke(Unknown Source)
    org.apache.commons.logging.LogFactory.directGetContextClassLoader(LogFactory.java:901)
    org.apache.commons.logging.LogFactory$1.run(LogFactory.java:862)
    java.security.AccessController.doPrivileged(Native Method)
    org.apache.commons.logging.LogFactory.getContextClassLoaderInternal(LogFactory.java:859)
    org.apache.commons.logging.LogFactory.getFactory(LogFactory.java:423)
    org.apache.commons.logging.LogFactory.getLog(LogFactory.java:685)
    org.springframework.core.env.AbstractEnvironment.<init>(AbstractEnvironment.java:90)
    org.springframework.core.env.StandardEnvironment.<init>(StandardEnvironment.java:54)
    org.springframework.beans.factory.support.AbstractBeanDefinitionReader.<init>(AbstractBeanDefinitionReader.java:96)
    org.springframework.beans.factory.xml.XmlBeanDefinitionReader.<init>(XmlBeanDefinitionReader.java:135)
    org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:82)
    org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:131)
    org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:527)
    org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:441)
    org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
    org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
    cz.cuni.xrg.intlib.frontend.AppEntry.init(AppEntry.java:96)
    com.vaadin.ui.UI.doInit(UI.java:603)
    com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:223)
    com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:73)
    com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37)
    com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1329)

**Comment by jakubklimek** [comment]
When running "find leaks" on Tomcat, I get:

<pre><code>The following web applications were stopped (reloaded, undeployed), but their
classes from previous runs are still loaded in memory, thus causing a memory
leak (use a profiler to confirm):
/odcleanstore</code></pre>

So there is definitely something wrong.

**Comment by tomas-knap** [comment]
Does not happen now
