### ISSUE TITLE
Debugging of Dialogs

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#253]
I am unable to debug an issue with ExtractorDialog in PSP_CZ DPU.
minYear.setMin(1918); for a minYear Vaadin slider causes an exception, but it is hard to debug for 2 resaons:

1) Even when backend is running in debug, the breakpoints dont work (as they do with execution)
2) I can only see the exception stack trace when I add another DPU to a pipeline and hover over it. Otherwise I only see a red triangle and no description.

**Comment by tomas-knap** [comment]
Will be solved by #251
