### ISSUE TITLE
Default Values for DPUs

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#257]
When user creates new DPU bundle, then imports to the tool, he would like to see certain default configuration in the dialog. Should we provide method like getDefaultConfiguration, which the user may implement and provide ConfigObject with default values for DPU details dialogs/when running pipeline?

Currently, default values can be specified directly in the initalization of the dialog. 
Alternatively, user can specify default values as default values of attributes in COnfigObject, but this will  not be taken into account by DPU details/DPU template detail? It would be nice to have one place from which default values can be stored as default settings for DPU detail and also during execution

**Comment by skodapetr** [comment]
I would rather use ConfigObject. It's in my opinion better solution. I implement this solution for testing purpose.

**Comment by tomas-knap** [comment]
Petre, ok. But the default configuration has to work when importing new DPU template. When importing, the DPU template configuration (configuration for the template) must be prefilled with these default values. Can you please do that?

**Comment by skodapetr** [comment]
Well it should .. or you have different experience?

**Comment by tomas-knap** [comment]
just tried :)
