### ISSUE TITLE
Strange exception when adding a TextChangeListener to a TextField

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#259]
I added this piece of code (minYear is a textfield):

<pre><code>minYear.addTextChangeListener(new TextChangeListener() {
        @Override
            public void textChange(TextChangeEvent event) {
                minYear.validate();
            }
            
        });
</code></pre>

And with this change when clicking on the affected DPU, I get the Failed to load configuration dialog because the bundle cannot be resolved exception
![image](https://f.cloud.github.com/assets/718827/992441/4aecaa3e-097e-11e3-828d-802f7c0efaa5.png)

**Comment by skodapetr** [comment]
Well we should discuss this with Tomas.
Basically user can use limited set of packages from Vaadin. These packages are those specified in config.properties. If other are used it ends up with this exception.

The problem in my opinion can be solved by adding record for this package to cofiguration.properties.
Something like 
com.vaadin.PACKAGE;version\="7.1.0"\
right after the line 
com.vaadin.ui;version\="7.1.0",\
But this can solve problem only on single PC. Every user of such DPU must do the same modification.

1) We can add names or all packages into configuration file ,but it's about 20,0 KB .. for all packages that are located in Vaadin related jar files. We can probably pick only some reasonable subset.
2) Other solution is to add this directly into code, but then it have to be update with Vaadin.
3) The last and most expensive solution will be using Vaadin bundles in frontend.

Imho for now probably the best is the solution number 2

**Comment by tomas-knap** [comment]
I would add all packages, it is acceptable for the comfort that everything in Vaadin is available. But I would suggest to put: 
- module.frontend.expose
  module.backend.expose

To separate configuration file, so that new users are not scared. Petr, what do you think?

**Comment by tomas-knap** [comment]
Petre, is it possible to add all vaadin packages at once somehow? Problem is when we switch e.g. from v 7.1.0 to 7.2, than, everything has to be changed - I mean every package name?

**Comment by skodapetr** [comment]
Yes this is issue .. I think it is not possible :( that is why the packages are enumerated in cofig.property file.

I'm not sure if the separate file is the best solution .. the whole configuration will be moving into slq maybe .. 

What I can try is to inspect jar-files in the frontend.jar .. and get the list of packages from vaadin files automatically. But I would prefer discussion before writing such thing.

**Comment by tomas-knap** [comment]
Please add all Vaadin packages/reasonable subset into configuration file ,but it's about 20,0 KB .. for all packages that are located in Vaadin related jar files. 

Check also if newer version of Vaadin is not available.

**Comment by skodapetr** [comment]
The list of packages in now in commons.app.com.vaadin.PackageList.
I think we can update version later as now we have more important issues?

**Comment by tomas-knap** [comment]
So the list of packages is hardcoded and admin have to update it in the code when new release of vaadin occurs or when certain packages is miising?

**Comment by skodapetr** [comment]
Yes. actually for missing packages the configuration file can be used, so it is not necessary to recompile. 
But when update Vaadin version then all DPUs have to be updated as well, from that point of view the recompilation of Intlib does not look as a big deal to me.
