### ISSUE TITLE
Timeout when clicking on "Show log" of a running pipeline in Execution Manager

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#270]
When I click on show log of a long running pipeline in Execution monitor (e.g. in state of transferring large data to a remote Virtuoso), it takes a long time and then it times out.
![image](https://f.cloud.github.com/assets/718827/1000526/f9aa4688-0a4d-11e3-8f7f-52b808002fc3.png)

**Comment by tomas-knap** [comment]
Will be solved by #220
