### ISSUE TITLE
Deleting a running pipeline

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#273]
Deleting a running pipeline is possible. It runs anyway, but is not showing in the execution monitor.

In addition, deleting a pipeline should have a confirmation dialog.

**Comment by tomas-knap** [comment]
Solution: When clicking on delete, there should be confirmation dialog. The confirmation dialog should ask whether the usr would like to really delete the pipeline and all associated records (DPU instances e.g.). If the pipeline is currently schedulled, user should be warned about that fact. If the pipeline is running currnetly, the user has to be warned that the current run will be cancelled. If other users are running this pipeline, user should be warned as well. If user confirms that the pipeline should be deleted, the pipeline is deleted, together with DPU instances on the pipeline, schedulled events, if it is running, it is stopped. Honza, you are responsible for the task, ask Bohuslav to assist you with the dialogs.

**Comment by janvojt** [comment]
I am assigning Bohuslav to finish dialogs. All needed methods should be ready. I already fixed backend so that it does not die if it is working with deleted entity.

**Comment by tomas-knap** [comment]
Kubo, test that

**Comment by tomas-knap** [comment]
when deleting running pipeline, no message box telling that the pipeline is running is not shown. 

Solution: User should be notified about that. If the user still requires to delete the pipeline, the running executions should be cancelled.

**Comment by skodapetr** [comment]
Shouldn't we rather use some .. hide and toDelete = true strategy? waiting for pipeline to stop .. can take a while
also if we delete running pipeline .. backend can detect that pipeline has been deleted and do clean up .. 
but if the backend crash before the clean up phase .. there is no record anymore .. and so the data will not be released (well for virtuoso they will be, thanks to pruning component .. but there can be others sources in future .. )

on the other side ... this is little more expensive for implementation require db change .. so please take it just as note for further generations ..

**Comment by tomas-knap** [comment]
I run the pipeline, delete it and then in the execution monitor there was a record about the pipeline exec. When clicking on that record:

![screen shot 2013-11-15 at 11 02 24 am](https://f.cloud.github.com/assets/3014917/1549128/58350e40-4ddd-11e3-95d6-278f3b7a6237.png)

**Comment by tomas-knap** [comment]
hide and toDelete would be nicer. But I think we can also start with a simple functionality: When trying to delete pipeline, it cannot be deleted (dialog is shown) if it is currently running (in the status QUEUED or RUNNING). What do you think?

**Comment by janvojt** [comment]
The last screen is probably caused by me stopping the database on odcs.xrg.cz. I just stopped the relational DB with SIGTERM, copied it, and started again after few minutes (did not stop backend process). If the pipeline was running at a time, it might have broken. But it is still a bug.

**Comment by janvojt** [comment]
Also, if view with logs throws an exception, it is not displayed again (for any other execution) until application is reloaded in tomcat.

**Comment by bogo777** [comment]
simple functionality: When trying to delete pipeline, it cannot be deleted (dialog is shown) if it is currently running (in the status QUEUED or RUNNING).

This is done.

**Comment by tomas-knap** [comment]
Please add warning if the pipeline being delete is schedulled, show something like " Pipeline XX is schedulled by user YY. Delete anyway? " If the user clicks yes, pipeline is deleted and apart from other things, all scheduled event  of that pipeline are deleted.
