### ISSUE TITLE
Frontend canvas: DataUnit and edge confusion

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#274]
When pointing at an edge in canvas, it says Set name of DataUnit. When opened, the dialog is named Edge details and contains textfield Data Unit Name and button Remove Data Unit.

This needs to be sorted out.

Also, enter does not work in the text field to confirm changes.

**Comment by tomas-knap** [comment]
Yes, I will propose the mockup for the data unit mapping dialog, then assign to Bohuslav
