### ISSUE TITLE
NumberFormatException when log as 4690 pages (probably > 1000)

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#280]
![image](https://f.cloud.github.com/assets/718827/1008368/579a6eba-0b22-11e3-93b1-398d0a45dbc1.png)

**Comment by jakubklimek** [comment]
This is getting annoying -> priority bump

**Comment by tomas-knap** [comment]
I got this as well, 

![screen shot 2013-09-11 at 4 30 58 pm](https://f.cloud.github.com/assets/3014917/1123419/ea3c15bc-1aee-11e3-8208-d266aeab0f0e.png)

**Comment by tomas-knap** [comment]
Sorry, will test the latest commit and let you know
