### ISSUE TITLE
There should be a new pipeline state in Execution Monitor: Finished with warnings

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#282]
When a pipeline finishes, but had some problems which it handled but still wants to let it know, there should be a state like Finished with warnings (yellow). Finished (green) should be the case when there is no attention needed and red should be when there was some serious problem like that it crashed or did not finish.

**Comment by tomas-knap** [comment]
There is "finished with Warnings status" in the list of possible statuses, but probably not used. Such state should be used if at least one WARNING+ occurs in the log.
