### ISSUE TITLE
Scheduler: Wrong behavior with missed events

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#283]
I scheduled an event to run at 8:15 every day. I did this in the afternoon.

1) It started immediately - probably was seen as missed

2) It got scheduled 24 hours after the start, not at 8:15 the next day

![image](https://f.cloud.github.com/assets/718827/1014538/1693e27a-0bbd-11e3-8f02-3c8a885d9d87.png)

**Comment by tomas-knap** [comment]
So the problem is that the time for which the event was schedulled was not successfully recorded. Petre, can you please check that? Probably it is a problem on Maria's side, but Maria is out till end of August.

**Comment by jakubklimek** [comment]
The problem is visible when you look at the screenshot: Scheduled for 8:15 AM, next run 1 PM.

**Comment by skodapetr** [comment]
Can I ask if the issue is still "active" or the problem has been solved?

**Comment by jakubklimek** [comment]
Tested OK
