### ISSUE TITLE
Scheduler: Scheduled pipeline did not run

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#285]
Look at ARES 5000., located at odcs.xrg.cz:8080/odcleanstore This was taken 23.8. 8PM.
It says it ran yesterday at 6PM and next should have been today (23.8.) 6:15PM. But it didn't (it would have been shown in "last run").
So the scheduler only worked once - yesterday.
![image](https://f.cloud.github.com/assets/718827/1017954/5f7d1b4a-0c1d-11e3-8ce1-361e0dd8ade2.png)

**Comment by skodapetr** [comment]
Time for next run is used to determine also to decide if execute pipeline or not. This change has been made as noted in #283. So is this issue still relative to the current version?

The true is, that if backend is offline the execution can be possibly scheduled into past.

**Comment by tomas-knap** [comment]
Petre, I do not understand, can you please describe how does it work:
1) If I plan certain event to the past
2) If I plan event but at the time when it should start, backedn is offline

Just to have better idea how it should work.

**Comment by skodapetr** [comment]
It is basically the same .. so I give single answer:
The next execution time is computed according to formula: 
next = start + period \* i  where: min i that next > last
So if the last execution is yesterday and the period is one hour .. then next schedule will be yesterday  + 1 hour 

When the Backend is running he just check: next.before(now) and if it true then start the execution and update last execution time to now.
