### ISSUE TITLE
Do we need to distinguish between extractors and transformers?

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#286]
Motivation:

[8/23/13 9:47:12 PM] Jakub Klímek: prakticka vec: jedna pipeline mi dela ty buyer profiles, druha pro dany ica stahuje ARES
[8/23/13 9:47:49 PM] Jakub Klímek: a ja bych chtel v odcs zautomatizovat to, aby se po dokonceni buyer-profiles vzaly ica z nich (1 sparql) a nejak se predali tomu ARESu ke zpracovani

1) jak predat data z jedny pipeline do druhy? Jedna moznost je v prvni zadat dalsi loader do daneho endpointu s danym grafem a v druhy napsat na to samy extractor, ale je to takhle idealni?
2) V druhy pipeline bude ten extraktor co mi ica vezme (at uz odkudkoliv - tzn. z danyho grafu, pripadne jinym mechanizmem) a potrebuje je predat dalsimu extractoru, coz ted asi nejde. Ale podle me by melo...

**Comment by tomas-knap** [comment]
od Honzy: Nemam presnu predstavu o co presne tam ide. Ak ten RDF vstup nejak ovplyvnuje pracu extractora (napr co extractovat a co nie), tak je to sucast extractora. Ak su RDF data len nejak spracovavane spolu s ostatnymi datami, tak by tam mali byt 3 extractory a spracovavanie az v transformeri.

**Comment by tomas-knap** [comment]
Viz popis issue, jedna pipeline stahuje profily zadavatelu (firem co zadavaji verejne zakazky) a druha pro ica v techto profilech stahuje ARES (tedy informace o te firme). Tedy z povahy veci jsou to dva extraktory, jen ten druhy jeste potrebuje nejak na vstupu dostat ty ica, tedy asi nejlepsi reseni:

Dve pipeline, jedna nahraje data z profilu zadavatelu do db, druha pipeline (je naplanovana po te prvni) ma SPARQL extractor (tim si ziska ic) a pak je tam DPU, co si vezme tyhle ic a stahne data z ARESu. AKorat ze v soucasnem navrhu to DPU co stahuje data z ARESu musi byt oznaceno jako transformer

**Comment by tomas-knap** [comment]
nicmene z logickeho pohledu je ARES DPU spise Extractor (tedy davalo by smysl aby byl oznacen jako extractor), jelikoz stahuje externi data

**Comment by tomas-knap** [comment]
Tedy jde o to, co vse je treba upravit aby to fungovalo tak, ze : 
- Extractor muze mit vstup, tedy interne se chova jako transformer, rozliseni je pouze na logicke urovni (V DPU tree ma uzivatel zvlast extraktory a transformery) -> tedy:
  -  je treba vyhodit omezeni, ze extraktor nemuze mit vstup, coz se kontroluje na canvasu.
  - ?je treba rozsirit extraktor context, aby take obsahoval metodu getInputs()?
- Na pipeline stale musi existovat aspon jeden extraktor, ktery nema vstup, aby se dala pustit. 

Je potreba jeste neco menit?

**Comment by skodapetr** [comment]
Zdravím .. z pohledu backendu: 
DPU jsou spouštěna z jedné funkce podle implementovaného interface .. tedy zde není problém. 
Každé DPU má přiřazený kontext .. již v současné době jsem při úpravách sloučil kontexty do jednoho, tedy z tohoto pohledu zde není také problém. Vlastně se jen zahodí všechny kromě Transformeru a z toho se se udělá prostě context.

Co se týče toho jak pouštět DPU to je v implementaci DepenedcyGraph jenž psal Hozna. Nicméně myslím, že zajistit aby v Pipeline bylo jedno DPU ke kterému nevede vstupní hrana by nemělo být problémem.

Ohledně Eventů .. tam jsem již provedl úpravy tímto směrem.

Rozlišení Extraktor, Transformer, Loader bych pak nechal na autorovi DPU aby nastavil jen enum, nebo spíše property pom.xml.

Tedy z mého pohledu jde o úpravy realizovatelné během jednoho dopoledne.

Co vím o frontnedu: tak tam by snad problém být nemusel. Rozlišení ve stromě i barvy mohou zůstat stejné, snad jen upravit validaci při sestavování pipeline, což si myslím bude asi lokalizované v jedné třídě

**Comment by tomas-knap** [comment]
Petre, diky za info. 

K tomu "bych pak nechal na autorovi DPU aby nastavil jen enum, nebo spíše property pom.xml": Bud by to uzivatel explicitne rekl, trebas pres nejakou metodu getType, pripadne jak pises v tom pomu, pripadne by se ten typ dal odvodit z zvoleneho rozhrani, pokud bychom zachovali interfaces Extract/Transform/Load. Mne se docela libi ta moznost definovat to v pomu, bo to je dobre pristupne pri nahravani DPU do app.

Tedy kdyz to shrnu, je potreba udelat:
- pri spousteni si najit, ktery extraktor nema vstup a od toho pipeline poustest (Honza)
- upravit validace pri sestavovani pipeline, tedy aby to umoznil udelat hranu do extraktoru (Bohuslav)
- upravit pom.xml, kde uzivatel definuje jstli je to extraktor/transformer/loader, sjednotit rozhrani pro extraktor/transformer/loader (jedna metoda execute()?, jeden kontext) .

Vynechal jsem neco? Zkusite to prosim behem dopoledne upravit, tyhle 3 body?  Pokud by se vam neco nezdalo, piste.

**Comment by janvojt** [comment]
Ahoj,

co sa tyka DependencyGraph, tak ten nerozlisoval medzi ETL. Pouzival len Nodes, a poradie pre iterator sa doteraz zostavovalo len na zaklade zavislosti, a nie typu DPU. Takze toto uz bolo OK. Aby kod odpovedal konvenciam, premenoval som akurat metodu findExtractors() na findStarters(), apod. Inac logicky sa nic nezmenilo.

Co sa tyka validacii v canvas, tak som odstranil kontrolu na vstupnu hranu do extractoru. Uz je mozne ulozit pipeline, kde su hrany medzi extractormi. Aspon jedno DPU musi byt bez vstupnej hrany, pretoze toto by mala osetrit validacia na cyklus.

Mozno trochu problem je, ze toto vstupne DPU nemusi byt extractor. Takze mozeme ulozit napr. pipeline s konfiguraciou T -> E -> L. Avsak toto sa ani doteraz nevalidovalo a bolo mozne ulozit pipeline T -> L. Ja to vnimam ako nedokoncenu pipeline. Jedna otazka je ci taku pipeline povolime ulozit, druha otazka co ak taku pipeline niekto spusti...

Dalej momentalne chovanie je, ze legalne zapojenie je aj E -> T -> E ->L. Neviem ci toto je OK, ak nie tak pls Tom dospecifikuj.

Ak som teda spravne pochopil Petrov komentar, ostatne az na vyssie uvedene detaily by mal zvladnut. Rano vstavam o 5 na vlak a pridem do Prahy o 12 naobed. Pocas cesty teda budem dostupny max na chate cez mobil.

**Comment by tomas-knap** [comment]
Honza, 

so the remaining issues here: 

1) not finished pipeline may be stored, but should not be able to be executed. 
2) E -> T -> E ->L

?

**Comment by janvojt** [comment]
Yes, provided Petr implements support in backend.
1. I can create PipelineValidator and set a flag whether pipeline is runnable. This flag could be updated upon each save. Then we could disable button "run" in frontend if pipeline is not runnable. Furthermore, just before pipeline is executed, backend should check whether it is currently runnable (or possibly even validate it). I can do all this myself. Is this OK? If so we should also update the specification in confluence.
2. The question for you Tom is, whether such setup is valid. Should we allow it (current behaviour) or should we forbid it (add a validation rule).

**Comment by skodapetr** [comment]
Backend can check the pipeline .. but .. if the backend is offline then the user can start the pipeline "as soon as possible" and then .. when backend gets online the execution failed. I'm not sure if that is the behaviour that the user will expect.

**Comment by janvojt** [comment]
Well, we can never completely prevent execution of broken pipeline. We can only accomplish this by validating pipeline just before we run it. E.g. imagine user schedules a pipeline run while pipeline is valid and perfectly runnable. Then user may edit pipeline and break it (let's say he removes all extractors for example). When scheduled run executes, pipeline is broken even though it was OK when schedule was created. Because of this, we should ideally validate pipeline before each run.

**Comment by skodapetr** [comment]
Sorry I miss the idea ... as I understand it now you propose two step validation .. 
1) when the pipeline is saved
2) just before the pipeline is executed
I'm OK with this.

For the schedule : we can .. but I understand that asking query for every pipeline usage .. like "pipeline is broken and used .. you can not save this" is not optimal solution. But still we can thing about it .. as user should be warned that he broken scheduled="important" pipeline

**Comment by tomas-knap** [comment]
I would suggest to distinguish these states of pipeline:

1) pipeline can be saved but cannot be launched (work in progress state) 
2) pipeline can be launched

Saving pipeline:
WHen I save the pipeline, which is not schedulled by ME to be executed, it is checked against condition one. When I save the pipeline which is schedulled by ME to be executed, it is checked against condition two (when there is a problem which violatest stronger condition 2, user is reported about that).

When I save&commit (when devel mode ready) the pipeline, if the pipeline is not schedulled by NOBODY to be executed, it is checked against condition one. When I save the pipeline which is schedulled by ANYBODY to be executed, it is checked against condition two (when there is a problem which violatest stronger condition 2, user is reported about that). Save&commit differes, because when saving and devel mode is ready, the changes are visible only to me. 

Furthermore, always when the pipeline is about to be run physically in its PipelineWorker thread, it should be checked agains condition 2 anyway. 

What do you think?

**Comment by tomas-knap** [comment]
2) E -> T -> E ->L

I think we can allow that, just please document in the code where the validation is happening so that it can be adjusted in the future. So the intermixing of extractors and transformers should be allowed. 

However, loader should be the last one and there shouldn't be any edge from loader to any other DPU. THis should be checked
