### ISSUE TITLE
Pipeline canvas detects 2 consecutive clicks instead of double click when opening DPU instance configuration

### ISSUE THREAD

**Issue by janvojt** [mff-uk/odcs#29]
I found a minor low priority bug in UI. If I click any place on canvas, quickly move the mouse onto DPU instance and click again, instance configuration dialog pops up.

It is a little annoying when quickly connecting DPUs with edges and configuration dialogs keep poping up. It is also a little confusing, because I am never sure whether it is configuration for source or target DPU.

**Comment by bogo777** [comment]
It is behaviour coming from KineticJS and its events. I was yet not able to change event processing to act better. I'll look into it some more.

**Comment by bogo777** [comment]
Solved by self evidence of clicks.
