### ISSUE TITLE
Possibility to browse resulting triples

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#302]
Data browser/query:

Every URI resource - result of the browser/query - is clickable - when clicking on that URI X, query  DESCRIBE <X>
is executed which provides me with all data about X in the same graph. 

Jirka: Implement method "describeURI", Bohuslav: call "describeURI", allow to click on the URI resources

**Comment by tomesj** [comment]
Method describeURI tested and available for using. Issue prepare for close.

**Comment by tomas-knap** [comment]
Well, Bohuslav should make the URIs in the query/browse result clickable.

**Comment by tomas-knap** [comment]
Before that, as looking to the commit, the query "DESCRIBE <%s>" should restrict on the examined named graph in the browse/query. This should be an extra param to your method, which restricts the describe query to be executed on top of the desired named graph (data unit)

**Comment by tomesj** [comment]
This method describeURI is called on concrete RDFDataUnit - it used graphs that are actually set to this DPU (it´s  the same as using for SELECT, CONSTRUCT, or UPDATE queries).

**Comment by tomas-knap** [comment]
ok, fine

**Comment by tomas-knap** [comment]
Clickable URIs in the result of browse/query -> after clicking, describe  method from Jirka is called

**Comment by bogo777** [comment]
I need paging support for DESCRIBE query too. I would like to call the method with query(already with LIMIT/OFFSET set) parameter as in select/construct cases.

Also, how do I discover which URIs are "describable"? Is it every entry with format http://something... ? Or is there some rule to this?

**Comment by skodapetr** [comment]
side note (to discuss): we may want to use DataAccesRead like wrap for RDF .. as with this the container can work

As the gui should probably does not do any complicated "data magic". It should just take data source .. pass it to the container, set container to table .. and done.

**Comment by tomesj** [comment]
For describe you dont need LIMIT/OFFSET. In your table from SELECT/CONSTRUCT you get only concrete URI (I tell you which) get this URI and call method describeURI - it return graph with triples (same result as in CONTRUCT case)

Now to URI:
You can use only Resource URI - does mean only for subject or object, if there are in URI representantion (starts with http://). Nothing else.

**Comment by tomesj** [comment]
For calling my method use 

<pre><code>
Resource uriResource=new URIImpl("http://my.uri.to.describe);
repository.describeUri(uriResource);
</code></pre>

**Comment by tomas-knap** [comment]
Jirka, just to add, you can also use predicate URI (call describe on predicate URI) , but such URI will typically not be involved in the data unit itself, so DESCRIBE will not return any data

**Comment by bogo777** [comment]
Should the URIs in table be styled somehow? (To look like link? Underline and blue?)

**Comment by tomas-knap** [comment]
Well, it should be highlighted as a link, so that it is obvious you can click on that. The link should have a different color, but I would not underline the link, that could be quite awful, because there will be lots of links in the table
