### ISSUE TITLE
Define Data Unit names for DPUs 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#304]
How the DPU developer can define which names of output data units DPU is producing and which names of input data units DPU is supporting?

Using annotations?

Test annotations, implement, and adjust DPU tutorial

**Comment by skodapetr** [comment]
Tomas please check the annotations .. I implement just simple input/output annotations these annotations are used to explore DPU and get list of inputs/outputs. So it is not possible to specify inputs/outputs without annotations. Please also check #308.

**Comment by tomas-knap** [comment]
Ok, thanks, I will check late this evening or early morning and let you know
