### ISSUE TITLE
Annotations for mandatory/optional inputs/outputs, types of data units

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#308]
When #304 ready and when it looks as a good approach. Relates also to #306 

Each DataUnit is annotated not just with name, but also type (RDF, XML, ..). Each input/output is annotated as mandatory/optional.

**Comment by skodapetr** [comment]
Currently I implement only mandatory annotations, I add optional this evening. Only simple annotations are implemented yet.
But we can come up with more complex solution that enable lines like this: List<RDFDataUnit> inputs. 

Maybe we should discuss this on next meeting?

**Comment by skodapetr** [comment]
I discuss the needs of annotation for List<> with Jakub. The conclusion is that such annotation could be helpful when we have for example XMLDataUnits .. so I don't think we need additional annotations right now.

Based on this I suggest closing this issue.

**Comment by tomas-knap** [comment]
Ok, we do not need to annotate types, but what about mandatory/optional i/o?

**Comment by skodapetr** [comment]
Well optional output is not supported .... we would need some support from DataUnit how to recognize that it has been used. 
The inputs can be optional by using "optional=true" as annotation parameter. Or should we have special annotation or this?

**Comment by tomas-knap** [comment]
Lets discuss optional/mandatory data units when 0.4.1 is done

**Comment by skodapetr** [comment]
Iteration 0.4.1 is done.
We have optional inputs .. and as far as I know there is no evidence that this solution insufficient for our needs. So I suggest close this issue and create new if needs of new annotation arise.
