### ISSUE TITLE
PipelineWorker rozdelit do vic trid

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#309]

**Comment by skodapetr** [comment]
There is now separate package that execute DPU .. and the pipeline itself. 

The DPU is executed in 3 phases as PreExecutor, Executor, PostExecutor .. the execution can be easily extended in terms of Pre/PostExecutors.

For the pipeline there is just one class Executor, maybe I can split that class to into smaller pieces. If we still need a issue for that .. is a question as it's not so bad with this class as it was with PipelineExecutor.

**Comment by skodapetr** [comment]
Pipeline Executor also split and support pre/post executors.
