### ISSUE TITLE
LocalRDFRepo, VirtuosoRDFRepo - needs refactoring

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#311]
Current state: 

LocalRDFRepo implements most of the methods, VirtuosoRDFRepo only adds couple of more methods. So when we will be adjusting code in the future, it is not obvious which code is common to all repositories and which is specific for local repo 

Solution: It would be nicer to have a class (e.g. AbstractRDFRepo) from which both localRDFRepo and VirtuosoRDFRepo inherit. Thus, add one class which is a common parent of localRDFRepo and VirtuosoRDFRepo

**Comment by tomesj** [comment]
Add common parent abstract class BaseRDFRepo - add implementation, update Local/VirtuosoRDFRepo classes.
