### ISSUE TITLE
Refactor RDFDataUnit, RDFDataRepository 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#314]
Mame interface DataUnit, pak interface RDFDataRepository a pak Local/Virtu impl RDFDataRep. A krom toho mamRDFDataUnit, coz ma byt rozhrani, pres ktere kouka na pro nej zajimave metody DPU developer. Ale realita je jina. 

RDFDataUnit implemmentuje vsechny metody, i ty, co s DPU developerem nesouvisi. To je blbe. 
navrhuju tedy, aby RDFDataUnit nebyla trida co extenduje DataUnit, ale aby RDFDataRepository extendovalo interface DataUnit a RDFDataUnitHelper (napr.). RDFDataUnitHelper by byl interface, ktery by obsahoval jen ty metody z RDFDataUnit, ktere jsou smysluplne pro DPU Developera. Dale bych RDFDataRepository prejmenoval na RDFDataUnit. Tedy: 

DataUnit <- RDFDataUnit, RDFDataUnitHelper <-RDFDataUnit (vse interfaces) a pak mit konretni implementace toho RDFDataUnit (stavajici trida RDFDataRepository), a to Local/Virtuoso Rep

Co vy na to?

**Comment by tomesj** [comment]
Jsem pro - jdu to udělat. Co s původní třídou RDFDataUnit - tu smazat ?

Jestli to chápu správně, tak 
a) RDFDataUnitHelper - metody pro developera
b) RDFDataRepository extends DataUnit,RDFDataUnitHelper
c) Smazání původní RDFDataUnit
c) přejmenování RDFDataRepository na RDFDataUnit.

Je to v tak v pořádku ?

**Comment by tomas-knap** [comment]
Jeste pockejme na nazor Petra, Petre? :)

Kdyz se nevyjadri do zitrejsiho poledne, tak na to prosim vlitni.

**Comment by tomesj** [comment]
Už jsem na to vlítl - je to už naimplementované a vyřešené. Udělal jsem to, jak bylo řečeno výše. V DPU je správně volána RDFDataUnit.

Přidal jsem navíc novou ještě RDFDataUnitFactory třídu pro vytváření instancí a nahradil předchozí použivání.

Myslím, že by to mělo být OK, jsou-li nějaké nedostatky či připomínky, tak sem s nimi :-)
