### ISSUE TITLE
Update OpenRDF to latest release 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#317]
Currently, latest is 2.7.5

**Comment by tomesj** [comment]
I tried to use version 2.7.5, but I found out, that some method I used there are not yet (or their eqvivalent). 

Problems are found with:
1) GraphQueryResult class - method asGraph();
2) TupleQueryResult class -  methods C addTo(C arg0), asList(), asSet(), singleResult(), ...

What do you mean ?

**Comment by tomas-knap** [comment]
So did you leave the previous version?

**Comment by tomesj** [comment]
No, we use 2.7.0-beta1 version. 

If you want to have 2.7.5 then is neccessary to implement missing methods or stay on current version.

**Comment by tomas-knap** [comment]
We can stay on the current version
