### ISSUE TITLE
Backend should be more robust when Virtuoso throws an exception

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#320]
Tady by to chtělo probrat s Honzou ... pro mě by bylo nejhezčí .. kdyby se tohle řešilo ve facadách .. tj. nejde DB - Hibernate .. tak začnou blokovat a zkoušet po třeba 20 vteřinách 

Přijde mi to hezčí a bezpečnější než při každém get-save .. používat try catch a nějaký čekací mechanismus .. pak se to někde zapomene, nebo neupraví ... kdežto fadady jsou na jednom místě a většina App přistupuje k DB jen přes ně.

Suggestion (needs discussion):
When virtuoso throws connection exception,engine should try to reconnect (e.g. 10x). It should also send an email that such problem with connection occurs. 

Honzo, please discuss

**Comment by janvojt** [comment]
What is the use case for this?

I am not sure if catching and absorbing exceptions in the facade is correct. Do you mean, e.g. when fetching an entity, just absorb the exception and return null? How would we differentiate between "entity is not in the db" and "something is broken and db threw exception"?

About reconnecting when db is not available, is that not current behaviour? I believe a new connection is established whenever user opens application in browser (or just opens the top level address).

**Comment by tomas-knap** [comment]
The motivation is the reconnect issue. Reconnecting probably works in gui, but not in backend. But it should work for both. In particular, if backend cannot connect to DB, it should try more times and also send email about this problem. So one option is to adjust backend, another option is too adjust facade, so that it is applicable for both

**Comment by tomas-knap** [comment]
Should not end with exception, just log that there is an error when trying to connect to db and sleep for e.g. 30 minuts and try again. 

![screen shot 2013-09-05 at 10 57 18 am](https://f.cloud.github.com/assets/3014917/1086930/2c103e12-160a-11e3-88ff-90438b657184.png)
