### ISSUE TITLE
What should debug show when loader has multiple inputs?

### ISSUE THREAD

**Issue by bogo777** [mff-uk/odcs#328]
I have pipeline with multiple inputs for loader. When I select loader in debug dialog, loader's input graph should be shown, but there are multiple graphs.

Should I just merge them every time(I should be able to do that personally) or should there be merged graph already in the context(this would be work for someone else)?

**Comment by tomas-knap** [comment]
This also applies to data units with more outputs

**Comment by skodapetr** [comment]
Personally I thing that "merge" is not what user always expect. If DPU has multiple IO .. there is probably reason for that. 
Use case: I have input A and input B .. and output C .. I know that output C is wrong, for example (log, validation , etc .. ) and then it may be vital to know which data are on which input as they probably have different meaning.

**Comment by tomas-knap** [comment]
Just to recap, Petre, one data unit may contain more named graphs or just one in case of RDF Data unit? Otherwise I would also prefer to have e.g. combo box with data unit names, so that user who is debugging may observe the output of the particular DPU flowing over particular data unit.

**Comment by skodapetr** [comment]
This is more question on Tomas as he is responsible for current RDF
implementation.

2013/8/29, Tomas Knap notifications@github.com:

**Comment by tomas-knap** [comment]
Solved, see https://grips.semantic-web.at/display/LOD2/Pipeline
