### ISSUE TITLE
Test more complex pipelines

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#329]
Test pipelines, which contain 5+ DPU, more complex workflow, not just Extractor1 -> Transformer1 -> T2 ->T3 -> Loader, ale trebas E1 -> T1 -> T3 -> L1, E1 -> T2 -> T3 -> L1, T2 -> L2.

Co se tyce dat, muzes vyjit z toho male souboru ted2.ttl, ktery jsem myslim daval k nejakemu akceptacnimu scenari, myslim u iter3?

Zkus take ruzne volby extractoru a loader, tohle musime mit perfektne protestovane.

**Comment by tomesj** [comment]
I tested complex pipeline like this:

![complex_pipeline](https://f.cloud.github.com/assets/3481055/1067179/4695cfb2-13c7-11e3-967b-425242dc54fd.jpg)

Pipeline finished sucessfull, but I found out there are problems:

1) If DPU has more input edges (=more than one grahs we need to merge to this DPU), we use only one merge calling.

(example of this pipeline - no data from File_Extractor to TRANSFORMER III - they merge only data form SPARQL extractor)  

´= problem of merge, but not in implementation, but in logic - we need to call it for every input to the DPU.

2) Edge list of this pipeline, where data from source DPU are not used (merge to target):
a) File_extractor -> Transformer III
b) File_extractor -> Transformer II
c) Transformer II -> Transformer II

3) Thanks 1) and 2) we have in loaders less data, than we expected to have.

Pipeline in this case has behavior as pipeline 

![complex_pipeline_problem](https://f.cloud.github.com/assets/3481055/1067289/3f489ca0-13ca-11e3-8905-7d99499cfbf0.jpg)

And this is not correct !!!

I saw that Peter may be change logic of merge - I remember something like List of DPUInputs.

**Comment by skodapetr** [comment]
The merge behaviour is actually correct, I think, I give a demostration:
S2 -> T1 <- S1
S1 has DataUnit output
S2 has DataUnit output
Then T1 recieve two DataUnits named output .. the data do not merge into single one. So i current implementation the T1 takes only one of those DataUnit and the other one is lost.

But this is expected behaviour.

With this are there any other problems?

**Comment by tomas-knap** [comment]
Jirka, can you please explain for me what is the problem in case of:

2) Edge list of this pipeline, where data from source DPU are not used (merge to target):
a) File_extractor -> Transformer III
b) File_extractor -> Transformer II
c) Transformer II -> Transformer II

**Comment by tomesj** [comment]
Problem was that DPU used only one input edge and other edges (data merging) from 2) were ignored.

**Comment by tomas-knap** [comment]
Jirka, please test today (if possible) this scenario, if it works after the update of Petr based on our yesterday's discussion. And let me know.

**Comment by tomesj** [comment]
I will test it and then write here my result.

**Comment by tomesj** [comment]
I am actually waiting for solving #375 - I can no add DPUs, on the pipeline.

**Comment by tomas-knap** [comment]
Jirka, can you please update me on this?

**Comment by tomesj** [comment]
I can not actually working on this - I have clean my DB and now when I created complex pipeline and I got save I got this exception:

![image](https://f.cloud.github.com/assets/3481055/1102210/46b83aca-1804-11e3-9e27-b5035d3337ca.png)

**Comment by tomesj** [comment]
When I tried to create pipeline once again, I got this:
![image](https://f.cloud.github.com/assets/3481055/1102240/922116b4-1807-11e3-91a8-2abd33652dac.png)

**Comment by tomesj** [comment]
At the end I finally created and saved pipeline. Then I tested funkcionality and merging is right now - without  problems. I got data equals to my expected result. 

![image](https://f.cloud.github.com/assets/3481055/1102339/264ba7b2-1814-11e3-9902-e1a6f4b40d8e.png)

But is necessery to solve 2 describes above errors problems.

**Comment by tomas-knap** [comment]
Jirka, thanks, when I deploy the tool on odcs.xrg.cz, I will let you know, so that you can prepare the pipeline for me there.

**Comment by tomas-knap** [comment]
Test the pipeline on odcs.xrg.cz:8080/odcleanstore
