### ISSUE TITLE
Pipeline canvas has 3 sliders for scrolling

### ISSUE THREAD

**Issue by janvojt** [mff-uk/odcs#33]
This is very annoying especially since in FF scrolling with mouse wheel does not work.

![screenshot](https://f.cloud.github.com/assets/2247062/593678/7bc51976-ca3f-11e2-95cf-3a93f05d98d3.png)

**Comment by bogo777** [comment]
Bug appeared when experimenting with VerticalSplitPanel, issue resolved.
