### ISSUE TITLE
Create pipeline - uncaught exception

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#332]
When I create pipeline, I got this exception:

![image](https://f.cloud.github.com/assets/3481055/1051811/ca13c9d2-10d1-11e3-9dfc-5f5155466c42.png)

Please start backend then - I dont run pipeline without it.

Thanks.

**Comment by janvojt** [comment]
Looks like broken database. I am closing this. If you have more specific steps to reproduce, please reopen and comment.
