### ISSUE TITLE
Be able to specify that given Pipeline should not run in multiple instances

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#333]
Be able to specify that given Pipeline should not run in multiple instances

For example - in my ARES pipeline, there is a limit of 1000 downloads per day. I accidentally ran the pipeline twice (it really happend to me several times - don't know why exactly... probably one click on run was interpreted as 2 or something) which is a problem in a case like this. It would be better to have a setting disabling the possibility to run the pipeline more than once.

**Comment by jakubklimek** [comment]
Related https://github.com/mff-uk/intlib/issues/491

**Comment by tomas-knap** [comment]
duplicates #491
