### ISSUE TITLE
Unsaved changes monitoring and notification

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#340]
When there are unsaved changes and you don't implement the autosave mechanism, the user should be notified before leaving the page like it is done in gmail, for example, to avoid loosing the changes because one forgets to click Save. At the same time, Save should be disabled when there are no changes.

**Comment by bogo777** [comment]
There are currently two mechanism for this:
1) in Settings, if changes are detected, dialog asking user for save/cancel pops up
2) in PipelineEdit, if changes are detected, navigation is disabled until save/cancel
Could you please test this and say which is better/how to improve it?

**Comment by jakubklimek** [comment]
This: https://github.com/mff-uk/intlib/issues/395 is basically the same thing.

I prefer the way it is now in pipeline editor. The dialog is too annoying for a web application I think

**Comment by jakubklimek** [comment]
Even better solution would be for the notification not to disappear and contain another set of Save, Discard, Cancel buttons.

In addition, the lower button should not be labeled Cancel, but Discard changes.

**Comment by jakubklimek** [comment]
Now I had a pipeline where I changed one DPUs property in its dialog. When I clicked on Save there, the Pipeline save buttons were still disabled, so I was unable to save what I did in the DPU dialog.

**Comment by tomas-knap** [comment]
Bohuslav, please write us when ready, this is really annoying ;)

**Comment by bogo777** [comment]
Well notification with buttons is basically dialog, or not?
For now, there is dialog, it can be styled in the future, to be less annoying. Also addon is used for ConfirmDialog and it doesn't support three buttons yet. It may be possible to modify it in the future but probably not till 11.9.

**Comment by jakubklimek** [comment]
OK. Could you please switch the two buttons so that on the left is save and on the right is discard?

**Comment by jakubklimek** [comment]
OK, but... the Save button is much smaller than the Discard changes one. So it is more probable that I will click on Discard changes. They should be at least the same size. In addition, the dialog says cancel or apply. It should say "There are unsaved changes. Do you wish to save them or discard?"
