### ISSUE TITLE
Initializing and Destroying repositories should log their names (urls)

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#341]
When there is "repository destroyed successfully" in the log, there is no name (url) so it is not clear which repository is destroyed.
The same goes for init.

<pre><code>IX 02, 2013 9:03:48 DOP. cz.cuni.xrg.intlib.commons.app.conf.AppConfig <init>
INFO: Loading configuration from: C:\Users\Kuba/.intlib/config.properties
SLF4J: The following loggers will not work because they were created
SLF4J: during the default configuration phase of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
SLF4J: virtuoso.ConfigurableDataSource
IX 02, 2013 9:03:50 DOP. cz.cuni.xrg.intlib.commons.app.conf.AppConfig <init>
INFO: Loading configuration from: C:\Users\Kuba/.intlib/config.properties
09:03:50 [main] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider
09:03:55 [main] INFO  c.c.x.i.backend.AppEntry - Configuring dynamic module worker ...
09:03:55 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Starting module facade
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading libs from C:\Users\Kuba\Documents\GitHub\intlib\target\lib\backend
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading lib 'C:\Users\Kuba\Documents\GitHub\intlib\target\lib\backend\com.springsource.javax.servlet-2.4.0.jar'
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading lib 'C:\Users\Kuba\Documents\GitHub\intlib\target\lib\backend\commons-web-0.0.1.jar'
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading lib 'C:\Users\Kuba\Documents\GitHub\intlib\target\lib\backend\jsoup-1.6.3.jar'
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading lib 'C:\Users\Kuba\Documents\GitHub\intlib\target\lib\backend\vaadin-client-compiled-7.1.0.jar'
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading lib 'C:\Users\Kuba\Documents\GitHub\intlib\target\lib\backend\vaadin-server-7.1.0.jar'
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading lib 'C:\Users\Kuba\Documents\GitHub\intlib\target\lib\backend\vaadin-shared-7.1.0.jar'
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading lib 'C:\Users\Kuba\Documents\GitHub\intlib\target\lib\backend\vaadin-shared-deps-1.0.2.jar'
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading lib 'C:\Users\Kuba\Documents\GitHub\intlib\target\lib\backend\vaadin-theme-compiler-7.1.0.jar'
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading lib 'C:\Users\Kuba\Documents\GitHub\intlib\target\lib\backend\vaadin-themes-7.1.0.jar'
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading libs from C:\Users\Kuba\Documents\GitHub\intlib\target\lib
09:03:56 [main] INFO  c.c.x.i.c.a.m.ModuleFacade - Loading lib 'C:\Users\Kuba\Documents\GitHub\intlib\target\lib\commons-module-0.0.1.jar'
09:03:56 [main] INFO  c.c.x.i.b.execution.Engine - Configuring engine ...
09:03:56 [main] INFO  c.c.x.i.b.execution.Engine - Working dir: C:\Users\Kuba\Documents\GitHub\intlib\backend\working
09:03:57 [main] INFO  c.c.x.i.backend.AppEntry - Starting TCP/IP server ...
09:03:57 [main] INFO  c.c.x.i.backend.AppEntry - Heartbeat is running ... 
09:03:57 [main] INFO  c.c.x.i.backend.AppEntry - DPURecord directory: C:\Users\Kuba\Documents\GitHub\intlib\target\
09:03:57 [main] INFO  c.c.x.i.backend.AppEntry - Listening on port: 5010
09:03:57 [main] INFO  c.c.x.i.backend.AppEntry - Running ...
09:08:51 [pool-2-thread-1] DEBUG c.c.x.i.b.e.p.Executor - Started
09:08:52 [Thread-5] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
09:08:52 [Thread-5] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Set new data graph - http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/4/du/0
...
09:24:25 [Thread-9] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository successfully incicialized
09:24:25 [Thread-9] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Set new data graph - http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/5/du/3
09:24:25 [Thread-9] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - START merging 411827 triples from <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/4/du/3> TO <http://linked.opendata.cz/resource/odcs/internal/pipeline/exec/1/dpu/5/du/3>.
09:24:40 [Thread-9] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Merged SUCESSFULL
09:24:40 [Thread-9] INFO  c.c.x.i.b.e.d.i.AnnotationProcessor - Assign DataUnit names: input for field: rdfDataUnit
09:24:43 [pool-2-thread-1] DEBUG c.c.x.i.b.e.p.Executor - Execution failed
09:24:44 [pool-2-thread-1] DEBUG c.c.x.i.b.e.p.Executor - Clean up
09:24:44 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:24:44 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
09:24:44 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:24:44 [Thread-11] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
09:25:08 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:25:08 [Thread-12] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
09:25:15 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:25:15 [Thread-13] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
09:25:15 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:25:15 [Thread-14] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
09:25:15 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:25:15 [Thread-15] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
09:25:23 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:25:23 [Thread-16] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
09:25:29 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:25:29 [Thread-17] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
09:25:29 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:25:29 [Thread-18] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
09:25:29 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:25:29 [Thread-19] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
09:25:35 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:25:35 [Thread-20] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
09:25:38 [pool-2-thread-1] INFO  c.c.x.i.r.i.VirtuosoRDFRepo - Virtuoso repository succesfully shut down
09:25:38 [Thread-21] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Repository destroyed SUCCESSFULL
</code></pre>

**Comment by tomas-knap** [comment]
Solution: Add name of the named graph or file (in case of local repository), which was destroyed
