### ISSUE TITLE
SPARQL extractor query validator not working

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#347]
In SPARQL extractor I use query:
<pre><code>prefix adms: http://www.w3.org/ns/adms#
construct {?id skos:notation ?ic} from http://linked.opendata.cz/resource/dataset/buyer-profiles/profiles/cz 
where {?id a adms:Identifier; skos:notation ?ic.}</code></pre>which is valid. It says it is not a construct query. When I remove the prefix declaration, it says that skos is an undefined prefix.

**Comment by jakubklimek** [comment]
The query still does not pass due to skos:notation - undefined prefix. But in Settings -> Namespace prefixes there is nothing, so I cannot even create that prefix. Could you please remove (comment) this check for now?

**Comment by tomas-knap** [comment]
Jirka, I have commented isValid method, it is a temporary hack, please remove the hack when this issue is solved.

**Comment by tomesj** [comment]
Ok, you was faster than me...Thanks. But if I tested validation, I have no problems....

Can you add here code, which dont passed ?

**Comment by tomesj** [comment]
When I was written last update of SPARQL query validator, I try validate this:

prefix adms: http://www.w3.org/ns/adms#
prefix skos: http:/defined/skos/prefix/

construct {?id skos:notation ?ic} from http://linked.opendata.cz/resource/dataset/buyer-profiles/profiles/cz
where {?id a adms:Identifier; skos:notation ?ic.}

And there was no problem.

**Comment by jakubklimek** [comment]
I see... OK, when I defined the prefix in the query, it worked.

The "problem" is that some SPARQL endpoints (like Virtuoso) have their own map of prefixes and then it is not necessary to specify the prefix in the query. So the question is whether we force the DPU designer to specify all the prefixes or not. If yes, then we can be sure there will be no errors from missing prefixes. Else it can be more comfortable, but the "missing prefix" error needs to be handled during execution. In Payola, we went the latter way but later redesigned it and we have our own prefix management which deals with this, connected to prefix.cc. However, rewriting SPARQL queries using the prefixes or adding prefix declarations where necessary is not completely trivial.

**Comment by tomesj** [comment]
OK, thank you, Jakub. 

Actually is necessary to define all used prefixes. In the future (after we will finish issue namespace prefixes) you dont need define the prefixes which have been defined in the namespace prefix table yet.

Tom, can I revert changes (hacking) in SPARQL query validator ?
