### ISSUE TITLE
No canvas on the pipeline (in chrome)

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#349]
This bug appears once again for me and Jakub. Collect javascript debug notes.

**Comment by bogo777** [comment]
I have sometimes same problem, looked around and found this:
https://github.com/ericdrowell/KineticJS/issues/585
and then this:
https://code.google.com/p/chromium/issues/detail?id=278940
So hopefully it will be resolved by new version of Chrome.

**Comment by tomas-knap** [comment]
Is this solved in the current version of CHrome?

**Comment by bogo777** [comment]
Yes, bug in Chrome was fixed in version 29.0.1547.76 m and it works since.
