### ISSUE TITLE
Error indicator is displayed after navigating to 2nd page in paginator

### ISSUE THREAD

**Issue by janvojt** [mff-uk/odcs#35]
Steps to reproduce:
1. Run pipeline at least 21 times, so execution listing takes 2 pages.
2. Open execution monitor.
3. Change page number from 1 to 2 in paginator input box.
4. Navigation does not change and error indicator is displayed (without error message).

Note: In step 3, if you click on ">" arrow, navigation works, however error indicator is stil displayed. Therefore I believe the problem lies in input box validation.

![screenshot1](https://f.cloud.github.com/assets/2247062/601779/2378609c-cc89-11e2-9fb5-7bdb5d8a0a3e.png)

**Comment by tomas-knap** [comment]
The same problem occurs for pipeline events when debuging pipeline having more than 5 pipeline events!

To Reproduce: 
1. Debug pipeline with at least 3 DPUs, so that 6 events occur. 
2. Navigate to the second page with events., error occurs.

**Comment by bogo777** [comment]
Fixed by using newer version of PagedTable Addon from https://github.com/ondrej-kvasnovsky/PagedTable
