### ISSUE TITLE
Canvas: DPU alignment not working

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#352]
When I select multiple DPUs on canvas using ctrl and click and then click on any of the alignment and distribution buttons, nothing happens.

**Comment by bogo777** [comment]
Could you please test that/describe it more? For me, it works fine.(But I tested latest version on 2 DPUs only, because of #375.)
DPUs selected for formatting have wider border, and only selected DPUs are formatted.

**Comment by jakubklimek** [comment]
OK, now it works for me too. The weird thing is that first you need to "activate" alignment mode and then click on DPUs you want to align. Usually it is the other way around... you select the DPUs and then you click on align.

**Comment by bogo777** [comment]
You can "activate" alignment mode without clicking on menu icon by clicking on DPU with CTRL key pressed.

**Comment by jakubklimek** [comment]
OK, I couldnt test that yet due to the current authentication error issue

**Comment by jakubklimek** [comment]
I tested it. It is almost OK, but there is still a problem. When I hold down CTRL and select DPUs, the alignment buttons get in my way when selecting another DPU and I often click by mistake on some of the alignment buttons instead of the DPU I want to select

**Comment by bogo777** [comment]
I changed conditions when alignment buttons appear: 
1) If CTRL key is held, they don't appear
2) They appear only upon entering selected DPU
This should make selecting DPUs easier and avoid alignment by mistake.

**Comment by tomas-knap** [comment]
Jakub, please test that, assign back if needed

**Comment by jakubklimek** [comment]
Still not as usual, but better. Usually, I would single-click on a DPU, which would select it. This is now used for edge selection, but it could do both. Then I would singleclick on another dpu with ctrl and I would have 2 selected. Then it works OK, so what still needs to be done is to select (wide border) DPU on single click and combine it well with the other functionalities.

**Comment by jakubklimek** [comment]
OK, now it works more or less as expected. When you play with it long enough, sometimes it gets "stuck", but that is OK for now.
