### ISSUE TITLE
Backend still writes out exception when internet connection is interrupted

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#353]
Pipeline was in state of uploading data to remote Virtuoso when internet connection failed. The following was in the log. I am not sure whether this is OK and ODCS will recover (reattempt the upload) or not. This has to be clearer, ideally, no exception should be written, it should be handled. ODCS should be resilient and retry failed pipeline operation as well.

<pre><code>10:25:12 [Thread-5] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - virtuoso.jdbc4.VirtuosoException: Connection failed: Software caused connection abort: socket write error
org.openrdf.repository.RepositoryException: virtuoso.jdbc4.VirtuosoException: Connection failed: Software caused connection abort: socket write error
    at virtuoso.sesame2.driver.VirtuosoRepositoryConnection.commit(VirtuosoRepositoryConnection.java:844) ~[virtuoso-sesame-7.0.1.jar:na]
    at virtuoso.sesame2.driver.VirtuosoRepositoryConnection.add(VirtuosoRepositoryConnection.java:1034) ~[virtuoso-sesame-7.0.1.jar:na]
    at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.addInputStreamToRepository(BaseRDFRepo.java:1901) [classes/:na]
    at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.addFileToRepository(BaseRDFRepo.java:1926) [classes/:na]
    at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.extractFromFile(BaseRDFRepo.java:254) [classes/:na]
    at cz.cuni.xrg.intlib.rdf.impl.BaseRDFRepo.extractFromLocalTurtleFile(BaseRDFRepo.java:167) [classes/:na]
    at cz.opendata.linked.buyer_profiles.Extractor.execute(Extractor.java:141) ~[na:na]
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.executeInstance(Executor.java:278) ~[classes/:na]
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.execute(Executor.java:400) ~[classes/:na]
    at cz.cuni.xrg.intlib.backend.execution.dpu.Executor.run(Executor.java:430) ~[classes/:na]
    at java.lang.Thread.run(Unknown Source) ~[na:1.7.0_25]
Caused by: virtuoso.jdbc4.VirtuosoException: Connection failed: Software caused connection abort: socket write error
    at virtuoso.jdbc4.VirtuosoConnection.commit(Unknown Source) ~[jdbc-driver-4.jar:na]
    at virtuoso.sesame2.driver.VirtuosoRepositoryConnection.commit(VirtuosoRepositoryConnection.java:841) ~[virtuoso-sesame-7.0.1.jar:na]
    ... 10 common frames omitted
10:25:54 [Thread-5] ERROR c.c.x.i.commons.dpu.DPU - Cannot put TTL to repository.
10:26:01 [Thread-4] WARN  o.h.e.j.s.SqlExceptionHelper - SQL Error: -3, SQLState: 42000
10:26:01 [Thread-4] ERROR o.h.e.j.s.SqlExceptionHelper - Connection failed: Connection timed out: connect
10:26:01 [Thread-4] WARN  c.c.x.i.b.f.PipelineFacade - Database is down after 1 attempts.
</code></pre>

**Comment by jakubklimek** [comment]
In addition, no retry attempt was made.

**Comment by jakubklimek** [comment]
In addition, the pipeline is RUNNING in the execution monitor, but it is not running when it was interrupted this way.

**Comment by janvojt** [comment]
I will look into this. I implemented reconnection attempts, however only when trying to persist objects through PipelineFacade. This seems like connection failure was detected when trying to save RDF data, which I believe uses a completely different connection. I will discuss this with Petr, as he knows how backend accesses RDF database.

**Comment by skodapetr** [comment]
RDF database is accessed through the RDFDataUnit (Jirka).

From my point of view .. I can to add more try-catch blocks .. on the other hand I would expect that the DataUnit should throw DataUnitException in case of problem  not .. VirtuosoException .. but I do not know if Jirka can manage this?

**Comment by skodapetr** [comment]
But it would be better it this situation would be properly handled in RDFDataUnit .. so in case of connection error .. RDFDataUnit just try .. and sleep .. and try .. until the connection is available or the pipeline execution is aborted by user.

**Comment by tomas-knap** [comment]
Jirka, can you please look on that? Discuss please your solution with Honza and Petr.

**Comment by tomas-knap** [comment]
What should be done:
1)  try to reconnect to target SPARQL endpoint if not being successfull, 
2) proper handling of error, so that stack trace is not produced, but only a standard log.error("Connection to ... was not successfull after ... attempts, because ...")

**Comment by janvojt** [comment]
I am working on this, that is why I had "solving" tag on this. I am reassigning this back to me. I started working on a wrapper for VirtuosoRepository to handle exceptions. Also, I moved AppConfiguration to commons, so that it is accessible from rdf module and retries and timeouts are configurable from config.properties.

**Comment by tomas-knap** [comment]
Sorry,  I have to get used to that tag ;)

**Comment by janvojt** [comment]
Well, backend survives when RDF repo is down now. However exceptions are still produced, so I must reopen. I think in some cases this is OK, so even if there is a short connection failure, you can find it in the log so you know something broke and you can investigate further.

There are actually 2 kinds of exception stacktraces that appear in the log:
1. Exceptions I logged intentionally at INFO level, written to stdout - I can remove these if you want without any problems.
2. Exceptions from Spring's JPA transaction manager, when it tries to start/end a transaction, but connection is lost, written to stderr - this might be little more complicated and would most likely require implementing a custom transaction manager.

I think we should resolve number 2. Both these stack traces are logged, but backend continues running when connection is restored, and also finishes all started pipeline runs. Therefore I am lowering priority to normal.

**Comment by tomas-knap** [comment]
Yes, the most important is that backend continues when certain errors occurs

**Comment by tomas-knap** [comment]
In general, I would suggest to log.error("SImple error message"). Log.debug("detailed message, stack trace"). If third-party library is logging differently, I would create issue for that, but it is definitely not issue for 0.4.1. SO I would change the target milestone to 0.4 for this?

**Comment by tomas-knap** [comment]
So the problem to check - logging of the backend

**Comment by ghost** [comment]
je to aktualne?

**Comment by tomas-knap** [comment]
backend logs reasonably
