### ISSUE TITLE
Tests calling external virtuoso must be adjusted

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#354]
Jirko, there are tests, which are calling http://ld.opendata.cz/...
Such testing is not acceptable, for all Virtuoso tests, you have to use the Virtuoso the user specifies in config.properties.

Solution: Adjust the tests calling external virtuoso, so that only the virtuoso specified in config.properties is used

**Comment by tomesj** [comment]
We actually have in RDF module class called  GraphUrl
and here set fixed prefix like
http://linked.opendata.cz/resource/odcs/internal/pipeline/

Do you want this prefix set via variable defined in config. properties ? It´s going about prefix we set as graph name in Virtuoso ? Is it true ?

**Comment by tomas-knap** [comment]
Yes, I think it makes sense to execute the tests agains the repository the user is configured. If we use current approach and change the repository at ld.opendata.cz:8894, tests will fail to everybody

**Comment by tomesj** [comment]
OK - So I implement, that this prefix is set via variable defined in config.properties :-)

**Comment by skodapetr** [comment]
Actually accessing configuration.properties during test phase is not easy as the config.properties is defined in commons-app while RDF see only commons, so it hasn't a clue that some configuration file exists.

How high priority does it have and what is the deadline? I personally prefer discuss the solution before implementing it. 
The simplest solution (and probably the only one.. ) is to add dependency RDF - commons.app But what if the user do not want to use the {HOME}.... location for configuration.properties? The test fails anyway in such scenario.

**Comment by tomas-knap** [comment]
ok, let's discuss that during f2f meeting
