### ISSUE TITLE
DataUnitBrowserFactory refactoring

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#355]
// TODO Bohuslav: Why is this method here? It's almost the same as the one above.  
    /**
     \* Return repository for specified DataUnit.
     *
     \* @param context       The pipelineExecution context.
     \* @param execution     Respective PipelineExecution.
     \* @param dpuInstance   Owner of DataUnit.
     \* @param dataUnitIndex Index of data unit.
     \* @return Repository or null if there is no browser for given type.
     *
     */
    @Deprecated
    public static RDFDataUnit getRepository(ExecutionContextInfo context,
            PipelineExecution execution,
            DPUInstanceRecord dpuInstance, DataUnitInfo info) {

**Comment by bogo777** [comment]
This method is used in QueryView for getting data source for querying. The method above constructs whole visual component for Browsing triples, but in this case only the data source is needed. If only one method should remain, it should be this one, and the creation of browsing component should be adjusted to using this method.

**Comment by tomas-knap** [comment]
Ok, than please put common parts to an extra private method and remove @Depracated annotaiton

**Comment by skodapetr** [comment]
The DataUnitBrowser factory class should directly create a Browser for given DataUnit .. so I'm not sure if it's good solution use it to obtain "access" to some source. If yes then the class should have different name.

Maybe we can add the QueryView under the RDFBrowser? It can be then not so easy to adjust the application graphical interface. 
But from the concepts of DataUnits: not every DataUnit has to be RDFDataUnit and then there may be no possibility to execute "query" over such DataUnit.

**Comment by tomas-knap** [comment]
Is this still relevant?

**Comment by skodapetr** [comment]
I think that Bohuslav removed the Browser completely from code. So probably no .. as there are no browsers any more. Even when we decide to revive them ... this will probably still won't be relevant.
