### ISSUE TITLE
The location for config.properties should be adjustable and loadable by backend

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#357]
Motivation: Two instances of ODCS on one machine

It should be possible to give the backend the config.properties location as a parameter. 
As a result, backend automatically write all params (except of connection to db) from config to certain table in DB. Think what will happen if backend is launched twice with different config.properties, will the second launch overwrite the first or reject it? 

Regarding the frontend, it should use web.xml for holding connection to DB. For other settings, it should use the table created by backend. As a result, backend should be always launched first (this could be ensured - or at least written in the install guide)

Relates to issue #207

**Comment by skodapetr** [comment]
User can define position of config.properties file using -c "path backend" parameter. Frontend now have it's own config.properties. 

So I think it's possible to have two instances of ODCS on one machine with two different configurations.

Store configuration into database .. I think it is not life critical .. and there are probably other issues that are more important. So I suggest close this issue and leave the current solution.

**Comment by tomas-knap** [comment]
Yes, current situation is enough

**Comment by tomas-knap** [comment]
Just please document that -c param may be used
