### ISSUE TITLE
SPARQL loader slow

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#358]
<pre><code>c.c.x.i.r.i.VirtuosoRDFRepo - Data 176/72114 part loaded successful
13:16:32 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 177/72114 part loaded successful
13:16:32 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 178/72114 part loaded successful
13:16:32 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 179/72114 part loaded successful
13:16:33 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 180/72114 part loaded successful
13:16:33 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 181/72114 part loaded successful
13:16:33 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 182/72114 part loaded successful
13:16:33 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 183/72114 part loaded successful
13:16:34 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 184/72114 part loaded successful
13:16:34 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 185/72114 part loaded successful
13:16:34 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 186/72114 part loaded successful
13:16:34 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 187/72114 part loaded successful
13:16:34 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 188/72114 part loaded successful
13:16:35 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 189/72114 part loaded successful
13:16:35 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 190/72114 part loaded successful
13:16:35 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 191/72114 part loaded successful
13:16:35 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 192/72114 part loaded successful
13:16:36 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 193/72114 part loaded successful
13:16:36 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 194/72114 part loaded successful
13:16:36 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 195/72114 part loaded successful
13:16:36 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 196/72114 part loaded successful
13:16:36 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 197/72114 part loaded successful
13:16:37 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 198/72114 part loaded successful
13:16:37 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 199/72114 part loaded successful
13:16:37 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 200/72114 part loaded successful
13:16:37 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 201/72114 part loaded successful
13:16:37 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 202/72114 part loaded successful
13:16:38 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 203/72114 part loaded successful
13:16:38 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 204/72114 part loaded successful
13:16:38 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 205/72114 part loaded successful
13:16:38 [Thread-10] DEBUG c.c.x.i.r.i.VirtuosoRDFRepo - Data 206/72114 part loaded successful</code></pre>

**Comment by tomas-knap** [comment]
Possibility to set the chunk size, closing.
