### ISSUE TITLE
Resize of the pipeline event detail - the content does not resize

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#36]
When clicking on the pipeline event in the debug view, dialog appears. When resized, content does not resize. 

Minimal size of the dialog should be introduced. If the dialog is bigger, there should be more space for the full messsage (thus full message text area should always take the whole space being available in the dialog)

**Comment by bogo777** [comment]
Content is resized now, full message textarea takes whole space available. Vaadin does not support minimum size for windows and css atributtes for this also does not work in Vaadin.
