### ISSUE TITLE
Canvas: ???

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#361]
![image](https://f.cloud.github.com/assets/718827/1073130/702f6c7c-14a1-11e3-89f4-2568427eb3af.png)
![image](https://f.cloud.github.com/assets/718827/1073100/cb19969a-14a0-11e3-8a65-19c875eccd30.png)

**Comment by tomas-knap** [comment]
Bohuslav, this is really critical, it is also on the demo available on: http://odcs.xrg.cz:8080/odcleanstore

Just open the Ares 5000 pipeline.

**Comment by tomas-knap** [comment]
I have deployed an update on odcs.xrg.cz, but Kubo, can you please recreate ARES pipeline? It seems that as there was the problem with canvas, it was wrongly saved
