### ISSUE TITLE
DPU movement on the canvas really slow

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#363]
zkousim na http://odcs.xrg.cz:8080/odcleanstore/ ten canvas, zobrazuje uz se to ok, ale co mi vadi, ze presuny DPUcek jsou hrozne pomale, aneb zkus si zalozit novou pipeline a posouvat si DPU po canvasu, je to hrozne trhane a nekopiruje to pohyb mysi. 

Co by tam mohlo byt tak vypocetne narocne? Ty presuny se resi jen na urovni javascriptu, ne?

Zkus si to demo a dej mi vedet jestli by te nenapadlo jak to zrychlit.

**Comment by bogo777** [comment]
Mel jsem rozdelany standard/develop mode v javacriptove casti canvasu a jak jsem opravoval to copy button, tak jsem to commitnul s tim v nefunkcnim stavu.
