### ISSUE TITLE
Virtuoso - default named graph http://default 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#364]
When launching dbpedia e.g., then when the pipeline is done, there is log message: 

![screen shot 2013-09-03 at 10 56 57 pm](https://f.cloud.github.com/assets/3014917/1076038/87b1d80a-14db-11e3-9a2e-0c02d77e021d.png)

What is the purpose of the default named graph?

**Comment by tomesj** [comment]
Each repository have one default graph - all data, queries,etc...are used with data in this set graph. When we change it to another, we become data set in that graph.

**Comment by skodapetr** [comment]
Maybe we can adjust the code to solve this.
Now the graph name is set after the RDFDataUnit is created by calling setGraphName method. 

Can you update RDFDatUnit::ctor to take graphName optionally as a parameter and use it instead of default graph? So we don't have to call setGraphName and also there will be no issue with default graph.

**Comment by jakubklimek** [comment]
Either eliminate the need for default graph (URI mandatory) or, if you insist that you need a default graph, give it a proper URI like <pre><code>http://linked.opendata.cz/resource/odcs/.../default-graph</code></pre>

**Comment by tomas-knap** [comment]
Jirka, but that basically means that http://default is a default graph for all create RDF data units, thus, all data units by default work with the same graph? But does it make any sense? Every data unit involves at least one named graph, where the data resides, so is there any need for any default named graph?

**Comment by tomas-knap** [comment]
As Petr was commenting, I think there is no need for default graph.

**Comment by tomesj** [comment]
Default graph we mean graph, where RDF data are stored and all operation over repository are about only this set graph. We dont add all to http://default....We call setDataGraph(http://something) and than set it our graph. Reason of this is, that we can something create new repository, but we dont know graphName. It is specificated later before calling operation. 

Of cource if we specific graphName immediately in constructor.

**Comment by tomas-knap** [comment]
Jirka, but we know named graphs in advance, so there is no reason for reseting the name later from default to the named graph contained within the data unit, right?

**Comment by tomas-knap** [comment]
Solution, based on the discussion on skype: Remove http://default from config.properties, do not use default graph, assign the graph when you know with which graph the data unit is working. Discuss with Petr when commiting this, so that you do not have conflicts

**Comment by tomesj** [comment]
Yes, I know about it. I change it today and close this issue.
