### ISSUE TITLE
Stopping DPUs: Should DPU.execute() throw InterruptedException, DPUException or nothing?

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#365]
When DPU is stopped (detects InterruptedException), should DPU.execute() throw InterruptedException (needs interface update), DPUException or just handle it and stop as soon as possible normally? Will the pipeline stop anyway now?

**Comment by skodapetr** [comment]
The pipeline should stop anyway so it's up to the DPU programmer what he decide to do. The true is that we do not have cleanUp method yet ... I can add it today, but it will make existing DPU's non-functional. I will discuss with Tomas.

**Comment by tomas-knap** [comment]
Petre, please commit that, I will then redeploy on the server.
