### ISSUE TITLE
openRDF packages cannot be used in DPUs

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#367]
I would like to use import org.openrdf.model.Statement; but it again causes the cannot resolve bundle exception.

This means that it is not listed in the allowed packages list somewhere in configuration - related to https://github.com/mff-uk/intlib/issues/259

**Comment by jakubklimek** [comment]
The project is in DPUs here on github, mvn install creates the JAR file

**Comment by skodapetr** [comment]
In #259 only the list on vaadin package was included. The openrdf .. is another story. Fast solution is add the
org.openrdf.model into configuration.propoerties as 

module.frontend.expose = org.openrdf.model 
module.backend.expose =  org.openrdf.model 

I try to list the all org.openrdf packages and add them to the application.

**Comment by jakubklimek** [comment]
as? :)

**Comment by skodapetr** [comment]
Sorry for that .. I hit crt+enter and send comment instead of new line  ... I updated the code, so please try the current version from git it should work without any modification in config.propoerties file

**Comment by skodapetr** [comment]
Could you please confirm that you can use your DPU now?

**Comment by jakubklimek** [comment]
Yes... until I use some other package I guess :)

**Comment by skodapetr** [comment]
Well I believe that I added all packages from org.seasame that are located in used jar-files. So I do not expect similar problem with this packages. But there may by additional complication with packages as OSGI is really strict with this. 
There were two ideas that can help with this.
1) Run whole Intlib in OSGI environment
2) Provide some way how to say to the user (in case that DPU is not working) .. "based on examination of manifest .. the package x.y.z is probably not presented in the system" .. 

We can discuss this f2f, but both solutions would not save the day completely at the end ...
