### ISSUE TITLE
RDF compilation

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/odcs#368]
I do not know if it is only my problem, but since yesterday:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project RDF: Compilation failure: Compilation failure:
[ERROR] intlib\rdf\src\main\java\cz\cuni\xrg\intlib\rdf\impl\LocalRDFRepo.java:[29,7] error: LocalRDFRepo is not abstract and does not override abstract method loadtoSPARQLEndpoint(URL,List<String>,String,String,WriteGraphType,InsertType) in RDFDataUnitHelper
[ERROR] intlib\rdf\src\main\java\cz\cuni\xrg\intlib\rdf\impl\VirtuosoRDFRepo.java:[22,13] error: VirtuosoRDFRepo is not abstract and does not override abstract method loadtoSPARQLEndpoint(URL,List<String>,String,String,WriteGraphType,InsertType) in RDFDataUnitHelper

Clean and rebuild does not help.

**Comment by tomesj** [comment]
Try to get last version from github, compile and write result :-)

Thanks.

**Comment by skodapetr** [comment]
It's ok now ..
