### ISSUE TITLE
Cannot compile commons-app

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#369]
<pre><code>[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.
5.1:compile (default-compile) on project commons-app: Compilation failure
[ERROR] C:\Users\Kuba\Documents\GitHub\intlib\commons-app\src\main\java\cz\cuni\
xrg\intlib\commons\app\module\ModuleFacadeConfig.java:[135,41] error: package or
g.openrdf does not exist
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :commons-app</code></pre>

**Comment by skodapetr** [comment]
Sorry ,my fault I miss that file in commit. Should be fine now.
