### ISSUE TITLE
Date format - pipeline event detail & filters

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#37]
When clicking on the pipeline event in the first table in the debug/show log view, format of the date in the pipeline event detail must be aligned with the format in pipeline monitor and pipeline event table.

Similarly the calendar filter in the pipeline monitor should show the date (not the time) in the same format as the first column of the table.

**Comment by kukharm** [comment]
I can not catch this bug, i have in all fields the same  format

![date](https://f.cloud.github.com/assets/3471169/692291/d0449b5a-dc16-11e2-83b8-f8572f11e6aa.jpg)

**Comment by tomas-knap** [comment]
Ok, so the calendar component is setting the data based on the local settings. If you try english version of e.g. firefox, the data selected by the filter will be in the different format. Can the column date in the tables reflect the local settings as the calendar component is doing?

**Comment by tomas-knap** [comment]
Maria, is there any progress??

**Comment by kukharm** [comment]
I don't know if this problem was solved after I changed type of data on the columns with date from string to date. Now I have on this columns date format as dd.mm.yyyy hh.mm.ss (Execution Monitor & Scheduler).  I changed date format  on my computer to dd-Mon-yyyy hh.mm.ss, but in this columns  format has not changed. I can't open Debug view for compare format  because of exception #138.

**Comment by tomas-knap** [comment]
Maria, could you please describe a bit more what is the current status? From your last message I do not know if the problem was solved, does not occur more or if there is still the problem but you do not know how to solve it

**Comment by kukharm** [comment]
I can't check  if the problem was solved. Because I can't open debugger view and compare the date format is in it with  date format in other tables  because of exception #138

**Comment by kukharm** [comment]
I checked the date format and I have the same in all tables and setting the date on my computer is do not influence on it.
![intlib](https://f.cloud.github.com/assets/3471169/849261/50e425f6-f471-11e2-9f04-20966b699262.jpg)

I ask you to check it on your PC. And if problem is solved then close this issue.

**Comment by tomas-knap** [comment]
Please check pipeline event detail and log detail. Otherwise ok.

![screen shot 2013-07-24 at 5 19 09 pm](https://f.cloud.github.com/assets/3014917/849451/828740d6-f474-11e2-8a31-6e467a3122c9.png)

![screen shot 2013-07-24 at 5 20 25 pm](https://f.cloud.github.com/assets/3014917/849455/95bf3a78-f474-11e2-9798-bf873e9ceed8.png)

**Comment by kukharm** [comment]
Could you please specify in what format have you got date in tables? This will help me to understand if date in tables respond to the local computer settings or set strongly.

**Comment by kukharm** [comment]
I made data format similar. Check please if it work on your PC

**Comment by tomas-knap** [comment]
It is ok
