### ISSUE TITLE
Cannot compile core DPUs due to missing implementation of getDescription()

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#370]
<pre><code>[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
1:compile (default-compile) on project File_extractor: Compilation failure
[ERROR] /C:/Users/Kuba/Documents/GitHub/intlib/module/File_extractor/src/main/ja
va/cz/cuni/mff/xrg/intlib/extractor/file/FileExtractorConfig.java:[12,8] cz.cuni
.mff.xrg.intlib.extractor.file.FileExtractorConfig is not abstract and does not
override abstract method getDescription() in cz.cuni.xrg.intlib.commons.configur
ation.DPUConfigObject
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :File_extractor</code></pre>

**Comment by skodapetr** [comment]
At least now I know which file I committed instead of seasame-package list. Should be fine now. 

Actually this interface should be committed today at 22:00 so please have all DPUs to committed to  GIT by 21:00 so we can update their code.

**Comment by jakubklimek** [comment]
All my DPUs are committed.
