### ISSUE TITLE
Show Notification messages when certain user action is provided

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#374]
Motivation: When user clicks on "Stop" in execution monitor, there should be simple information (not that intrusive as red/yellow message of Vaadin?), that the Pipeline is being stopped. Because currently I do not know if some action takes place when clicking on STOP. Also the button stop should be then disabled. 

Motivation2: When clicking on button save on the pipeline edit, I do not know if the pipeline was saved really, or there was e.g. problem with database. Again, certain message would be useful. 

I would opt for a status row under the main menu where notice will occur after the actions of the user? Alternatively, we can use the Vaadin dialog (as e.g. when pipeline is run), but I am worried that this is too visible and distracting.

**Comment by bogo777** [comment]
There is one more Vaadin notification - it is used when debug/run is started from PipelineList, would that be sufficient? I can add it on these two places for now, and, if it is not good enough, later replace it with something different.
