### ISSUE TITLE
Pipelines list: Access denied

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#377]
I login as user/test, click on Pipelines and this is what I get.
![image](https://f.cloud.github.com/assets/718827/1087569/47e9bd3c-161b-11e3-96c8-00342d6df67c.png)

**Comment by jakubklimek** [comment]
In addition, Access is denied should be the main message, not "Uncaught exceptinon" - this applies in general to all exceptions

**Comment by janvojt** [comment]
I cannot reproduce this. Please try to retest, commit 6b5b92a5 might have fixed it.

**Comment by jakubklimek** [comment]
OK
