### ISSUE TITLE
Frontend restart

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/odcs#378]
Is there possibility to restart frontned? 

Like for example .. I forgot to put a value into configuration.property and even when I fix this .. the frontend do not register this change and restarting tomcat is really unpleasant with my computer ... 

The missing property was "email.admin"  

Or the source of this "error" is somewhere else?

**Comment by janvojt** [comment]
Try reloading application in tomcat manager. If it works and is sufficient please close this issue.
