### ISSUE TITLE
Bad login exception when database is incorrectly configured

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#381]
When database is incorrectly configured, frontend receives VirtuosoException. However, when this is caught on the login screen, it is shown as Bad Login.

1) Distinguish among different exceptions
2) Bad login should not be the big red exception that the user needs to close to try again. It should be written in a red box above the login form or something more common like that

**Comment by tomas-knap** [comment]
Do we need to discuss something here? Or is it clear?

**Comment by bogo777** [comment]
I get same exception regardless of what happens in login process so I have no way to detect this. Reassigning to Honza for propagating different exceptions to me.

**Comment by janvojt** [comment]
I do not remember how exactly was this simulated. I tried removing some columns from `usr_user` table, but SQLException is shown, which is correct. I suppose it is already resolved then?

![screenshot from 2013-11-28 00 24 26](https://f.cloud.github.com/assets/2247062/1635905/5f8f41a0-57bb-11e3-8833-85eb88b3a471.png)
