### ISSUE TITLE
Execution monitor automatic refresh works only once

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#383]
Execution monitor automatic refresh when showing log works only once - it refreshes and then nothing (at least in the version currently at odcs.xrg.cz:8080/odcleanstore)

**Comment by bogo777** [comment]
For me it works fine on this URL, if I select ALL in level filter, new logs are appearing again and again.

**Comment by jakubklimek** [comment]
Hm... that is weird. I am looking at the currently running ARES 1000 pipeline, ALL selected, but the last log entry I see is from 9:36 (9 minutes ago)

**Comment by bogo777** [comment]
Ok, I look at the same pipeline and it works for me. But there were big changes in refreshing since the version deployed on the server(judging from not seeing an icon for backend status)...

**Comment by jakubklimek** [comment]
OK, let's wait with this issue until the current master is working again

**Comment by jakubklimek** [comment]
I checked today, it does not refresh for me in Chrome nor Internet Explorer.
