### ISSUE TITLE
Logovaci okno v debug dialogu 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#39]
Posuvnik u textearea s logem na zalozce log u debug/show log dialogu musi vzdy vyplnit cely prostor ktery ma, ale nesmi mit tato textarea posuvnik. Lze nastavit minimalni velikost textarea. Pokud je dialog mensi, tak se objevi posuvnik u dialogu. Pokud je dialog vetsi, tak textarea s logem vyplni prostor co vyplnit muze. 

Take logovaci okno je readonly.

**Comment by bogo777** [comment]
Upravil jsem to tak, že textarea s logem v execution monitoru vyplnuje cely prostor a pokud je text delsi, ma posuvnik. V pripade debug dialogu v edit pipeline se textarea resizuje podle okna a pripadne ma opet posuvnik. Pri dodrzeni minimalni velikosti okna u debug dialogu by ani dialog ani okno v execution monitor nemeli mit posuvnik. Jedinym posuvnikem je tedy ten u textarey, prijde mi to lepsi, nez aby tam byla dlouhatanska textarea.

**Comment by tomas-knap** [comment]
Diky. Vidim tam dva problemy s tim textarea posuvnikem: 
1. Pokud to chapu spravne, tak tam temer vzdy na mensich monitorech/projektorech bude posuvnik horizontalni na urovni celeho debug view dialogu a pak vertikalni jen na urovni textarea? 
2. Taky tam vidim trosku problem v tom, ze zatimco u zalozky log bude posuvnik jen u textarea, tak u zalozky browse/query je strankovani (pripadne v budoucnu volitelne), tedy stejne tam bude muset byt posuvnik vertikalni celeho dialogu, ne? 

Tedy ja bych byl pro posuvnik vert/horiz na urovni celeho okna a nic vic, s tim, ze log zabere vzdy zbytek velikosti okna, pokud bude delsi, tak tam bude posuvnik. Ale pojdme probrat na schuzce, mrknem jak to vypada ted a proberem.

**Comment by tomas-knap** [comment]
Summary: It is ok as explained by Bohuslav.
