### ISSUE TITLE
When pipeline execution is stopped, use a different icon than in case of "errror"

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#390]
Firstly, I would suggest to rename button stop to cancel.

When pipeline is cancelled, a proper icon should be assigned in the execution monitor. 

Further in pipeline event, there is a message that it was aborted: 
![screen shot 2013-09-06 at 1 04 37 pm](https://f.cloud.github.com/assets/3014917/1095355/6f696514-16e4-11e3-9269-88d9db63e9fa.png)
But icon for pipeline_info is missing (which could be same as for DPU info)

**Comment by bogo777** [comment]
When stopping pipeline from frontend, I added setting execution status to CANCELLED, until now, only backend was doing that. So when you had scheduled pipeline and cancelled it while backend was offline, it remained there as scheduled, which was weird.
But I don't know what to do about execution record with mesage about aborting pipeline?
Now only backend puts one there, so if you cancel pipeline before backend starts it, there is no execution record.
But if I add it from frontend too, then for already running pipeline, there would be two records about abort.(one from frontend and one from backend)

**Comment by tomas-knap** [comment]
I have created #392, so that we can close this one.
