### ISSUE TITLE
Confirmation to save changes when moving between menu items

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#395]
I changes something in DPU templates. Then I clicked on Pipelines main menu item. As a result, screen occurs:

![screen shot 2013-09-06 at 6 17 03 pm](https://f.cloud.github.com/assets/3014917/1097361/04408e8a-1710-11e3-9d2e-0cab21a9c986.png)

The problem is that the confirmation dialog appears too late, with the background being already filled with the new context. So I would prefer to firstly show the confirmation dialog (with the original window in the background) and then automatically switching to the new context

**Comment by tomas-knap** [comment]
And the confirmation does not work properly, I just tried to modify DPU template configuration of some DPU, then saved it and moved to pipelines item and the confirmation occured again! Bohuslav, please delegate task partially to Maria if needed.

**Comment by skodapetr** [comment]
I even get the "save dialog" after automatic logout ..

![logout save changes](https://f.cloud.github.com/assets/3341693/1101551/c87f579e-17cf-11e3-8f4b-45c83e6af29b.png)

**Comment by bogo777** [comment]
Confirmation should occur before loading new view now. Result of work on #340.

**Comment by jakubklimek** [comment]
Works
