### ISSUE TITLE
Status of the executed pipeline in the record

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#399]
In the monitor below, the resulting status of the pipeline run is "Warning" But there are errors in the pipeline events:

![screen shot 2013-09-06 at 6 47 58 pm](https://f.cloud.github.com/assets/3014917/1097803/e5ec4284-1715-11e3-8ee5-6e83ead97611.png)

 Therefore, the resulting status should take into account pipeline events as well as logs -> if there is Error+ in the events/log, then the resulting state is error. If there is Warning+ in the events/log, then the resulting state is Warning.

**Comment by bogo777** [comment]
Ok, but execution status is resolved in backend and saved to db, on frontend it is only loaded and shown, so I am reassigning Petr

**Comment by tomas-knap** [comment]
Ok, thanks, you are right

**Comment by tomas-knap** [comment]
If there is an error event -> end the execution in the same way as if cancelled. If log.error(), then it will end with error, but the pipeline will finish (reason: external libraries may use log.error())
