### ISSUE TITLE
SPARQL loader - details tab - label which is not clear to the user

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#400]
![screen shot 2013-09-06 at 7 03 40 pm](https://f.cloud.github.com/assets/3014917/1097829/62294c16-1716-11e3-8184-b161f774f39c.png)

User does not know anything about some PARTs, what is bad insert part? Think as the user, he has to understand what the choices mean.

**Comment by tomesj** [comment]
OK. And what about "SKIP adding incosinstend data" ? Is it clear to user ?

**Comment by tomas-knap** [comment]
- In case of data errors, continue with the loading process, resulting data will be incomplete.
- In case of data errors, stop the loading process and end with an error. 

And I would set the second option as default choice.
