### ISSUE TITLE
RDF loader - Stop when bad part occurs 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#401]
Jirka, radsi v cestine. To si delas srandu?? Ty tam pouzivas pro KAZDY beh jeden temporary graph:

![screen shot 2013-09-06 at 7 20 17 pm](https://f.cloud.github.com/assets/3014917/1097943/a6237228-1718-11e3-826a-b93b1aa8da48.png)

Tedy kdyz pobezi paralelne dvakrat loader, tak ten prvni trebas smaze temp graf tomu druhemu pod rukou?? Tedy kazdy beh, kazda data unit musi mit vlastni temp graf, napr. graphName/temp

Druhy problem je ze je to totalne neefektivni. Proc kdyz uz to nahrajes do toho temp grafu, tak pak jen neprekopirujes data z toho temp grafu do target grafu? Cetl jsi tu specifikaci SPARQL 1.1 Update? http://www.w3.org/TR/sparql11-update/ Tu specifikaci nemusi znat vsichni clenove tymu ale ty ano..tedy minimalne abys vedel, ze je tam trebas nejaky INSERT query

**Comment by tomesj** [comment]
Specifikaci pro insert znám - zjistil jsem ale, že kdy insert, resp. kopírování z temp grafu je pomalejší než nové vkládání přes http. Navíc ten příkaz pro insert funguje dobře pro malá data, pro velká je už potřeba udělat connection a brát to jako graph query - tam se postupuje jako v případě mergování velkých souborů.

Je pravda, že jsem zapomněl na to, že i temp graph by měl být unikátní. Takže při paralelním běhu by se to přepsalo, to beru na sebe.....

Jak bych to tedy měl udělat ?

**Comment by tomas-knap** [comment]
Jirko, tak jen oprav ten temp graph a poznamenej do kodu, zes to udelal takhle bo je to rychlejsi nez INSERT a pak to zavri. 

Ikdyz teda o tom pochybuju. Kdyz misto druheho volani zavolas query ve stylu INSERT INTO <grafFinal> {GRAPH <graphTemp> {?s ?p ?o}}, tak to proste musi byt rychlejsi nez potencialne stovky/tisice HTTP connections ;-) Udelam ti issue na tohle, abys to vyzkousel.

**Comment by tomas-knap** [comment]
Jirko, tak nove issue delat nebudu, proste zkus vzit nejaky soubor co ma aspon 10000 trojic a zkus stavajici zpusob a pak  INSERT INTO {GRAPH {?s ?p ?o}} misto druheho volani insertParts. A vysledek mi prosim napis sem. Az pak to zavrem

**Comment by tomesj** [comment]
Dobře. Udělám to tedy tak, že ten stávající temp graph budu generovat - odvodím z názvu skutečného cílového grafu, který je unikátní. Jinak co se týká insertu, je stejný příkaz přímo pro virtuoso ADD &lt;jmeno_grafu&gt; TO &lt;cilovy_graf&gt;, který v podstatě odpovídá INSERT INTO {GRAPH {?s ?p ?o}} , tedy vložení všech trojic do daného grafu. Pro větší grafy totiž Virtuoso odpoví na to, že skončil timelimit pro execution a příkaz se neprovede. Jak jsem říkal, tak alternativa je přes connection - tam už problémy nejsou, jen bych to musel napsat celé znovu. 

Já tu mám jeden graf se 7 miliony trojic, na kterém jsem to zkoušel. Vyzkouším ještě jednou tedy všechny varianty...I když možná by stálo za to použít to connection, protože je pravda, že v případě velkých dat to bude lepší než po částech :-)

**Comment by tomas-knap** [comment]
Jirko, k tomu "Jak jsem říkal, tak alternativa je přes connection - tam už problémy nejsou, jen bych to musel napsat celé znovu." To je to, co by melo byt predmetem #372 ?

U tohohle issue mi slo o to zkusit, zda je lepsi volat dvakrat getInsertedParts(), nebo jen jednou a pak Add<graph> to <graph>.

**Comment by tomas-knap** [comment]
Na co jsi prisel s temi 7 milony trojic? ZKus jen dve moznosti - 2x getInsertedParts a jednou getInsertedParts + prekopirovani. Jak ti to vychazi?

**Comment by tomesj** [comment]
Ne, to nemá s #372 nic společného, To se zase bavíme úplně o ničem jiném. Zlobilo mě tu rozhraní, dělám teď na complex pipeline, protože tam vidím větší prioritu. Až bude vše OK, tak pak se podívám na toto :-)

**Comment by tomesj** [comment]
Pro graf se 7 mil trojic v případě vkládání příkazu INSERT INTO {GRAPH {?s ?p ?o}} či ADD &lt;jmeno_grafu&gt; TO &lt;cilovy_graf&gt; přes SPARQL endpoint dostanu vždy:

Virtuoso 40005 Error SR325: Transaction aborted because it's log after image size went above the limit.

Jinak zde je asi hlavní problém ten, že jde obecně o libovolný SPARQL endpoint -může to tedy být ne naše, ale vzdálené Virtuoso, tedy by bylo nejlepší, mít něco, co by nám poskytno connection a metody pro danou repository toho endpointu. Tedy 3.varianta co jsem původně navrhoval funguje dobře pro přidávání či mergování ale nad naším Virtuosem.

V minulosti jsem zkoušel už SPARQLRepository, ale tam byla řada problémů (včetně autentizace).

Jinak to vkládání po částech funguje vždy, ale už pro větší data to selže na JAVA heap space a to v místě, kde se mají vrátit všechny trojice, které je potřeba nahrát.... Hledal jsem nějakou alternativu, ale nenašel.

**Comment by tomas-knap** [comment]
Jirko, tak zkusi mene trojic, trebas jen stovky tisic pro zacatek. 

Virtuoso 40005 Error SR325: Transaction aborted because it's log after image size went above the limit.
-> Mas spravne nastavene log_enabled()? Pokud jo, tak se ti tohle neobjevi. Myslim, ze se to log_enabled() da nastavit i jako soucast query? <pre> SPARQL DEFINE sql:log-enable 3 
INSERT INTO <graph-name> ...  </pre>

Jinak zde je asi hlavní problém ten, že jde obecně o libovolný SPARQL endpoint -může to tedy být ne naše, ale vzdálené Virtuoso, tedy by bylo nejlepší, mít něco, co by nám poskytno connection a metody pro danou repository toho endpointu. 
-> To ne, tobe staci udelat HTTP connection a tomu predat dotaz typu INSERT INTO {GRAPH {?s ?p ?o}} či ADD <jmeno_grafu> TO <cilovy_graf>, pripadne tez s nastavenim logovanim (tedy je to Virtuoso specific myslim)

Jinak to vkládání po částech funguje vždy, ale už pro větší data to selže na JAVA heap space a to v místě, kde se mají vrátit všechny trojice, které je potřeba nahrát.... Hledal jsem nějakou alternativu, ale nenašel.
-> Tohle musi byt ale zcela jiste chyba tveho kodu..jakmile dodelam jeden chunk, tak rozhodne nepotrebuju drzet si ho v pameti.

**Comment by tomas-knap** [comment]
Tedy kdyz to shrnu, tohle je dulezite issue, nahravani vetsich dat musime umet, a to stavajicim druhem loaderu.
1. Je treba odladit getInsertedParts - tedy aby to proslo pro tech 7 milionu trojic. Klidne zacni od statisicu, ale musi to fungovat i pro miliony. Urcite bude potreba zvetsit chunk z 10 na tisice aspon pro vetsi data. Zkousej to zatim v tom rezimu BEZ temp grafu. Napis mi prosim v prubehu dneska vysledky. Kdyz se ti to nepodari, tak se na to budem muset zitra podivat spolu.  
   1b. Zkus verzi s temp graf a dvojitym getInsertedParts. 
2. Az odladis getInsertedParts bez tempGrafu, opakuj test pro variantu s TEMP graf, pro ty dva pripady, klidne zas nejprv pro mensi data (stovky tisic). Pokud se prokaze ze insert into nebo add je lepsi nez dvojite volani getInsertedParts, tak bych to udelal tak, ze se zkusi zavolat getInsertedParts a pak insert into. Kdyz insert into selze, tak se zavola podruhe getInsertedParts.

Bod 2 delej striktne az bude bod 1. Je totiz zasadni aby to fungovalo, kdyz to nebude dodelane do patku pro TEMP, nevadi tolik, ale bod 1 musi byt

**Comment by tomesj** [comment]
Dneska budu pracovat převážně jenom na tomto a pokusím se to dát nějak zprovoznit.

Jinak to vkládání po částech funguje vždy, ale už pro větší data to selže na JAVA heap space a to v místě, kde se mají vrátit všechny trojice, které je potřeba nahrát.... Hledal jsem nějakou alternativu, ale nenašel.
-> Tohle musi byt ale zcela jiste chyba tveho kodu..jakmile dodelam jeden chunk, tak rozhodne nepotrebuju drzet si ho v pameti.
---> Jde o to, že to neselže na chunk části, ale na tom, když si vyžádám všechny trojice  (a ty chci dále rozdělovat na ty části), tedy při tom, kdy se mi má vrátit kolekce se všemi daty. Zkusím to udělat nějak iteračně, aby tento problém odpadl....

**Comment by tomas-knap** [comment]
Jo tak, jasne, chapu. Mno, muzes urcite ty data ziskat nejak jinak, trebas construct {?s ?p ?o} where {?s ?p ?o} LIMIT 1000 OFFSET 0. A pak zvedat OFFSET o 1000. Ale mrkni jestli openRDF nema pro toto primo nejakou metodu, ktera ti vraci jen casti dat z RDF uloziste.

**Comment by tomas-knap** [comment]
Jirko, zkusil jsem deployovat na odcs.xrg.cz:8080/odcleanstore. Kdyz tam zkusis dbpedia pipeline, kterou jsem obohatil o SPARQL loader, tak nahravani selze:

![screen shot 2013-09-09 at 11 33 32 pm](https://f.cloud.github.com/assets/3014917/1110662/130e6146-1998-11e3-86a4-32be15a0968d.png)

Zvlastni je, ze to vypise - 1/10 part loaded successfully, ale pak dalsi debug hlaska napise execution failed ;-)
Mrkni na to prosim, tohle specha.

**Comment by tomesj** [comment]
Tak jsem to zkoušel na odcs.xrg.cz:8080/odcleanstore a nejprve to nemělo dost práv - (bylo tam sparql místo spaql-auth). 

Je zajímavé, že to umře na autorizaci, tedy to že se po 1 úspěšném nahrání to vrátí HTTP 401 - Unauthorized.

Podívám se, jak se to chová u mě a dám vědět....

**Comment by tomesj** [comment]
U mě to nahraje též 1/10 parts a pak to rovněž spadne na HTTP 401 - Unauthorized.

**Comment by tomesj** [comment]
Tak už jsem zjistil, kde je problém....Při tom nahrávání totiž záleží na délce toho URL. Je-li moc dlouhé, potom to skončí výše zmíněnou chybou. 

Tady v tom případě je hodně i 10 trojic na jedno nahrání, protože jejich texty jednotlivých trojic jsou příliš dlouhé. Když si to ale zkusíš nastavit velikost PARTS na 3, je to už OK.

**Comment by tomesj** [comment]
Tak mám nakonec skvělou zprávu - stačí zaměnit metodu get za post a už to bere libovolně velké úseky :-) Takže skvělá zpráva :-) Můžeš hned zkusit a jde to i pro velká data

**Comment by tomas-knap** [comment]
Ok, super. Jeste te poprosim o jednu vec, pridej prosim do dialog pro SPARQL loader - na zalozku details jeden text box, ve ktere bude velikost te part. A odstran to z BaseRDFRepo. Defaultne to nech trebas na 100. Tohle bude hlavne pro nas, pro testovani jak se zvysi rychlost, kdyz se zvetsi chunky. Pro ruzna data - ruzne velka se to bude chovat ruzne. Implementace SPARQL loaderu si pak vezme tu velikost parts prave z toho textboxu. Mrknes na to prosim? To by melo byt rychle a umozni nam to lepsi testovani.

**Comment by tomas-knap** [comment]
A jeste mam jednu vec, posledni snad :) Kdyz si nastavim, aby to skoncilo po vyskytu chyby, tak to spravne skonci chybou cele to nahravani kdyz je v datech nejaky problem, akorat ta chyba neni intuitivni, je to stack trace. Melo by byt jasne recono, ze chyba je: Data obsahuji tuto chybu XX a proto cele nahravani fails.

**Comment by tomesj** [comment]
Přidám textbox pro ten SPARQL loader, aby se to dalo nastavit. Jinak věc těch hlášek je taková, že já tam předávám přesně tu chybu a její message, ale ten kdo programoval pak ty případné chyby - reporty (nejspíše Petr) tam z toho pak dělá stacktrace ....Už jsem se na to jednou díval a přišlo mi to divné, jen jsem to nechtěl nějak měnit, protože to není můj kód....Je to tuším někdy v commons-app....Teď si přesně nejsem jistý, každopádně by se to možná mohlo dnes taky probrat a posléze upravit :-)

**Comment by tomesj** [comment]
More detailed information was added in confluence page - https://grips.semantic-web.at/display/LOD2/Experiments+-+Playground

**Comment by jakubklimek** [comment]
Please do not close issues until they are tested by the person who reported them.
