### ISSUE TITLE
RDF loader - fails but there is no reason for that

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#402]
Jirka, I am sending to the SPARQL loader the following data, which I load to the data unit via outputConfirmed.addFromTurtleFile(new File("/Users/tomasknap/.silk/output/confirmed.ttl"));: 

![screen shot 2013-09-06 at 7 26 20 pm](https://f.cloud.github.com/assets/3014917/1097982/8f3c9232-1719-11e3-88e5-5d6264b5f98e.png)

10 triples, which are correct. 

Configuration of the loader is, which is correct:

![screen shot 2013-09-06 at 7 29 41 pm](https://f.cloud.github.com/assets/3014917/1098002/f6422b04-1719-11e3-8972-653ed56a60f2.png)

But an error occurs: 

![screen shot 2013-09-06 at 7 27 31 pm](https://f.cloud.github.com/assets/3014917/1097989/a5289c8a-1719-11e3-9473-2b48f8256021.png)

Can you please explain that?

**Comment by tomesj** [comment]
Can you please send me the file. The problem is described as "invalid character in SPARQL expression at %", but I dont know why a what is source of this problem. I try to debug it and solve it.
