### ISSUE TITLE
Problems with bunde

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#404]
When I create new pipeline and I add file extractor and SPARQL loader. When I try to add an edge between DPUs I get this exception:

![image](https://f.cloud.github.com/assets/3481055/1098736/8a640692-1727-11e3-8935-c3efe4096e5a.png)

I tried rebuild project, tomcat, database, but this problem was not solved.

**Comment by jakubklimek** [comment]
+1
I cannot even load my DPUs
![image](https://f.cloud.github.com/assets/718827/1099206/45e415ec-1732-11e3-87aa-50bb3464d025.png)

**Comment by skodapetr** [comment]
Jakub: the missing package in your case is javax.net.ssl so please add to the config.property file as package to export. Unfortunately after Jan's update the config.property file is not reload with new session so you have to manually restart application.

**Comment by skodapetr** [comment]
Please test now also with #406 

The source of error was one and the same for both issue and it takes me few hours to find it .. actually the OSGI was implemented to work per session, but some time ago Jan update the Spring context .. and now OSGI work per Tomcat. 

This cause thing like .. that the old session close OSGI for the rest of the application ("null" exceptions) same bundles were loaded twice ("can not resolve" exceptions).

Unfortunately thanks to this we also lose possibility to update export.package list in config.properties or simply rewrite a jar-dpu .. and then apply this changes by creating new session. 

We have to also be more careful when loading bundles "create module" as when we damage OSGI the only possibility is to restart the application from tomcat. 

Maybe we can discuss solution where user can choose if he want to create OSGI per session (as it used to be) or per serverlet (as it is now). The second solution is probably better for "business" environment  where user know what they are doing and thy do not add DPU's much. The first solution is in my opinion better for DPU developer as they may experiment with different libraries, packages and so no .. 

To give the whole image .. when solving "bundle can not be resolved" exception I need to reset OSGI about five times per minute .. and it makes me not happy that I have to reset the whole application as it's much more complicated and takes a longer time.

**Comment by jakubklimek** [comment]
It is not clear to me what excatly was Jan's update. It seems from your description that it brought lots of problems. Did you discuss all this with Tomas?

Aren't all this the advantages we had for all the trouble with osgi and libraries etc.?

Do I still need to add the ssl package, or is it by default now?

**Comment by skodapetr** [comment]
Sorry .. ssl package in still not by default ... I discuss with Thomas how to solve such issues .. I can add this package simply but this scenario will repeat for every single new package .. :( nevertheless if you really want I can add it.

Jan change the Spring context scope from per session to per serverlet.
The source of problem was that on the start/end of every session the OSGI start (create new instance)/stop was called .. and this was not updated when the scope was changed.

Simply to say .. the resource that has been written to be used per thread were use as singleton in concurrent environment.

OSGI advantages: well we can discuss this f2f

**Comment by jakubklimek** [comment]
Now it says 
![image](https://f.cloud.github.com/assets/718827/1101549/bae0279e-17cf-11e3-9c41-89907f889c61.png)

If the problem is the ssl package, why it worked before?

**Comment by tomas-knap** [comment]
Kubo, regarding unknown DPURecord type, do you have proper annotation for the DPU main executive class?

**Comment by tomas-knap** [comment]
Based on what you said Petr, it is of utmost importance to provide possibility to reload bundle, see #249 . It is not acceptable to  restart the whole app when DPU is changed and I would like to test the change. Please discuss to #249. We can also provide a button in DPU templates which reloads all the dpu bundles, what do you think?

On the other hand, when loading per servlet, we speed up a bit the first user's request. Can you quantify the speed up?

The most important is for 0.4.1 to have it stable.

**Comment by skodapetr** [comment]
Tomas the speed is .. actually negligible as the size of core-DPUs and Jakub's DPUs are reasonably small. 

But for example if you use SILK library .. that can take some time .. but it's only per first request in new session. The more important is that it may strongly help with permGen problem as we significantly decrease the number of loaded classes.

The change itself is generally not bad .. bad is the way in which it has been made .. and also we can thing about per session mode for DPU developers. To the reloading .. see in #249.

**Comment by tomas-knap** [comment]
Yes, you are right, permGen issue is a problem. We will test and let you know

**Comment by tomas-knap** [comment]
PermGen issues is being solved in #434
