### ISSUE TITLE
Problems with DB Pipeline 

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#405]
Our DB pipeline, we use as default after updating database has this problems:

1] This pipeline I can not change - e.g path to file_loader are set for UNIX. I have to possible change it and save.  Actually I can not use button save, save&close, only close.
2] In SPARQL extractor is bad char "," in text box named graph - it will be remove. Right is http://dbpedia.org 

3] Mapping between DPUs is not set - red edge (is necessary to have a consistend pipeline able to run)

**Comment by tomas-knap** [comment]
Jirko, can you please look on that? Honza will have lots of work with authentication issues

**Comment by tomas-knap** [comment]
Jirko, check also that SPARQL loader works correctly, in my case it produced an error with username/pass autentication, ale to je nesmysl

**Comment by tomesj** [comment]
It is fine, now :-) It was caused by too long URL - fixed using POST method. See #401
