### ISSUE TITLE
Null pointer exception originating from canvas after playing with edge mappings

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#406]
I opened the pipeline, click on the DPUs details, everything was working. Then I deleted and again added edge, was adjusting edge mappings and then, tried to open DPU detail but:

![screen shot 2013-09-07 at 11 58 42 am](https://f.cloud.github.com/assets/3014917/1101047/3130594a-17a4-11e3-9535-5114ce835150.png)

The GUI error dialog as in #398

**Comment by tomas-knap** [comment]
Please let me know if you can reproduce this Bohuslav

**Comment by tomas-knap** [comment]
When I create new pipeline the problem appears again and again

**Comment by tomas-knap** [comment]
Hmm, tried to restart tomcat and it seems to be working again, could be a problem with PermGen space on Tomcat?

**Comment by skodapetr** [comment]
It looks like that this issue is somehow related to the sessions and calling OSGI stop function .. reassign to me for further exploration.

**Comment by jakubklimek** [comment]
Happened to me also when adding an edge, Tomcat freshly restarted:
![image](https://f.cloud.github.com/assets/718827/1101219/0d647f54-17b4-11e3-9ab3-ebf106dccd26.png)

The interesting thing is that when I closed the exception message, the edge was not there. I clicked save and close and then edit again and the edge was there. However, I cannot open the mapping dialog - the exception keeps reappearing.

**Comment by jakubklimek** [comment]
After adding 

<pre><code>-XX:MaxPermSize=128m</code></pre>

to Tomcat startup and clicking the edge I get:
![image](https://f.cloud.github.com/assets/718827/1101233/381bb396-17b6-11e3-80a8-eea4c779dedd.png)

**Comment by jakubklimek** [comment]
It works with <code>-XX:MaxPermSize=512m</code>, so possibly related to https://github.com/mff-uk/intlib/issues/252

**Comment by skodapetr** [comment]
Merge under #404
