### ISSUE TITLE
More descriptive messages "Bundle cannot be resolved"

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#407]
Ask Petr Parizek and please discuss here his opinion. 

The basic idea is that it will not show only exception "Package cannot be resolved" but: "Package org.openrdf.rio cannot be imported, thus bundle cannot be resolved."

**Comment by jakubklimek** [comment]
Now it says 
![image](https://f.cloud.github.com/assets/718827/1101547/a7906898-17cf-11e3-8cc0-8c914c5fc564.png)
which is equally not helpful

**Comment by skodapetr** [comment]
I agree basically .. to what to do .. has the DPU proper annotation (ie. AsExtractor, AsLoader ..) ?

**Comment by jakubklimek** [comment]
You're right, this is missing (due to conflicts when you updated my DPUs ;)). Nevertheless, this should be described in the error message.

**Comment by skodapetr** [comment]
I'm not sure if this window is suitable for longer messages. 

Maybe we can add some interpreter which provide user with more details based on exception as writing such story (probably with html marks) into exception message in code, is that what we want?

Thomas .. f2f discussion?

**Comment by jakubklimek** [comment]
Nevertheless, when I added the @AsExtractor annotation, I still get the same error

**Comment by jakubklimek** [comment]
But, when I restarted Tomcat, it was OK. But that is not OK :)

**Comment by skodapetr** [comment]
I check this .. I thing that Maria is probably not using OSGI#uninstall method properly, which is now even more important as we have single OSGI class.

**Comment by tomas-knap** [comment]
Any info from Petr Parizek?

**Comment by skodapetr** [comment]
Unfortunately no .. but I start every bundle before use. So user get proper message missing XY package. It may decrease security a little bit. Just try some DPU with missing packages ..
