### ISSUE TITLE
Logging debug messages from frontend to the file 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#408]
When logging from gui, the problem is that standard logging mechanisms to output stream does not provide debug messages (and should not provide, because user should not be provided with detailed log message while he is using gui). On the other hand, such detailed log messages should be put to some file, because they might be needed when debugging problems for the users.

**Comment by skodapetr** [comment]
Where should this file be located?

**Comment by tomas-knap** [comment]
Probably the best would be to create a custom log reporting dialog, which may hide stack trace by default. So I will close this issue?

**Comment by skodapetr** [comment]
In frontend's configuration is new property that set log's directory.
