### ISSUE TITLE
Scheduled record in execution monitor does not have time associated

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#409]
When I run the pipeline but backend is offline, pipeline run may be schedulled. In that case the pipeline execution monitor with the status schedulled occurs, but time is missing for the execution records of this type.

**Comment by bogo777** [comment]
Start time is assigned by backend upon starting of execution. Scheduled executions which have not yet started don't have time assigned. With this, real duration of execution can be captured. Is it ok? Or should it be measured from the creation date of execution? Any difference for planned/scheduled executions?

**Comment by tomas-knap** [comment]
Ok, could be counted as a feature.
