### ISSUE TITLE
DPU file upload issue

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#413]
When I upload a DPU jar in the Create DPU template dialog and it is wrong somehow (displays error message), I select another one (or the same one I meanwhile recompiled) but it is not uploaded again.

**Comment by skodapetr** [comment]
Maria do not call unistall on bundle if the import process failed .. for example due the missing annotations.Please test it now. In case of any problems please provide information about the exceptions.

**Comment by tomas-knap** [comment]
Jakub, please test

**Comment by jakubklimek** [comment]
Now it works when I select different file. But if I recompile the one I selected and select it again, it does not reupload.

**Comment by skodapetr** [comment]
The problem that the same file can not be reload after the first load failed is I believe not in my code. The FileUploadReciever class has been created by Maria. I thing we may need to rework and test this class (#510).

So reassigned back to Maria.

**Comment by kukharm** [comment]
I have made some changes in FileUploadReciever class, so test, please now. 

I tested it in a way that i get wrong jar and named it as File_extractor-0.0.3, then when i tried to replace jar in RDF File Extractor the load was fail. Then after fail i got File_extractor-0.0.1 renamed it to File_extractor-0.0.3 and tried to replace ones again. Replace was successful.

**Comment by tomas-knap** [comment]
Problem: When I select jar file to be uploaded, it fails. THen I try again to select another, save, but it is not saved
