### ISSUE TITLE
RDF Parser which validates data as part of RDF loader

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#414]
1. Write parser which processes the data before they are loaded. 
2. Test on ted2.ttl (see iter3 on confluence), which errors/warning are thrown (please report here the list of errors/warn encountered).

**Comment by tomesj** [comment]
I tried to use RDF parser for described ted file and I got this as report:

WARNINGS:
1]Message: 'http://purl.org/procurement/public-contracts-datatypes#percentage' is not recognized as a supported xsd datatype. LINE:100 COLUMN:-1
2]Message: 'http://purl.org/procurement/public-contracts-datatypes#percentage' is not recognized as a supported xsd datatype. LINE:570 COLUMN:-1
3]Message: 'http://purl.org/procurement/public-contracts-datatypes#percentage' is not recognized as a supported xsd datatype. LINE:579 COLUMN:-1

ERRORS:
1]Message: 'Date2012-02-09T10:00:00' is not a valid value for datatype http://www.w3.org/2001/XMLSchema#dateTime LINE:63 COLUMN:-1
2]Message: 'Date2012-02-09T10:00:00' is not a valid value for datatype http://www.w3.org/2001/XMLSchema#dateTime LINE:64 COLUMN:-1
3]Message: '2012-01-27TLhůta pro doručení žádostí o dokumentaci nebo pro přístup k dokumentům: 27.1.2012:00' is not a valid value for datatype http://www.w3.org/2001/XMLSchema#dateTime LINE:65 COLUMN:-1
4]Message: 'Date2012-02-09T10:00:00' is not a valid value for datatype http://www.w3.org/2001/XMLSchema#dateTime LINE:66 COLUMN:-1
5]Message: 'Number of tenders:17' is not a valid value for datatype http://www.w3.org/2001/XMLSchema#integer LINE:123 COLUMN:-1
6]Message: '2.099.417.01' is not a valid value for datatype http://www.w3.org/2001/XMLSchema#float LINE:146 COLUMN:-1
7]Message: 'OPrice:2099417.01' is not a valid value for datatype http://www.w3.org/2001/XMLSchema#float LINE:151 COLUMN:-1
8]Message: '20' is not a valid value for datatype http://www.w3.org/2001/XMLSchema#duration LINE:205 COLUMN:-1

**Comment by tomas-knap** [comment]
Thanks! Can you please further introduce the following URIs (blue one) to certain resources (subjects, predicates, or objects)  in ted2.ttl and test whether all the errors below are also reported?

Bad IRI: http://www.-marches06.fr Code: 33/DNS_LABEL_DASH_START_OR_END in HOST: A DNS name had a - at the beginning or end.
Count: 3

Bad IRI: http://http:/marchespublics.nantesmetropole.fr Code: 12/PORT_SHOULD_NOT_BE_EMPTY in PORT: The colon introducing an empty port component should be omitted entirely, or a port number should be specified.
124

Bad IRI: http://www.kommersannons.se:80/engelholm/Notice/NoticeOverview.aspx?ProcurementId=251 Code: 13/DEFAULT_PORT_SHOULD_BE_OMITTED in PORT: If the port is the default one for the scheme it should be omitted.
30

Bad IRI: http://www..strassen.nrw.de Code: 28/NOT_DNS_NAME in HOST: The host component did not meet the restrictions on DNS names.
56

Bad IRI: http://public_procurement@sibelga.be Code: 58/PROHIBITED_COMPONENT_PRESENT in USER: A component that is prohibited by the scheme is present.
32

Bad IRI: http:////www.fz-juelich.de/gm Code: 57/REQUIRED_COMPONENT_MISSING in HOST: A component that is required by the scheme is missing.
17

22:52:22 WARN  riot                 :: [line: 9730239, col: 18] Bad IRI: http://www2.kommersannons.se:80/eLite/Notice/NoticeOverview.aspx?ProcurementId=165 Code: 14/PORT_SHOULD_NOT_BE_WELL_KNOWN in PORT: Ports under 1024 should be accessed using the appropriate scheme name.
30

rnationalized Domain Name check failed. Contains non-LDH characters
22:52:20 WARN  riot                 :: [line: 9623118, col: 12] Bad IRI: http://www.melt.gr/ Code: 8/NON_INITIAL_DOT_SEGMENT in PATH: The path contains a segment /../ not at the beginning of a relative reference, or it contains a /./ These should be removed.
5

22:52:19 WARN  riot                 :: [line: 9528958, col: 18] Bad IRI: http://ehpad_simonviolet_pere.e-marchespublics.com Code: 35/BAD_IDN in HOST: The Internationalized Domain Name check failed. Contains non-LDH characters
1

**Comment by tomesj** [comment]
What I should do with these URIs ? I dont understand what you want from me. Try to explain it better.

**Comment by tomas-knap** [comment]
Ok, the motivation is to try how the parser (your parser) behaves  (which exceptions/warnings will be thrown), when the parser processes such URIs. Ideally, errors should occur as in the comment above, which is output of Apache Fuseki.

**Comment by tomesj** [comment]
I added next triples to file:

<pre><code>
&lt;http://www.-marches06.fr&gt; &lt;http://hasEdge&gt; &lt;http://http:/marchespublics.nantesmetropole.fr&gt; .
&lt;http://www.kommersannons.se:80/engelholm/Notice/NoticeOverview.aspx?ProcurementId=251&gt; &lt;http://myURI &gt; "myLiteral" .
&lt;http://www..strassen.nrw.de&gt; &lt;http://nextProblem&gt; &lt;http://public_procurement@sibelga.be&gt; .
&lt;http:////www.fz-juelich.de/gm&gt; &lt;http://next&gt; &lt;http://www2.kommersannons.se:80/eLite/Notice/NoticeOverview.aspx?ProcurementId=165&gt; .
&lt;http://www.melt.gr/&gt; &lt;http://aaa&gt; &lt;http://ehpad_simonviolet_pere.e-marchespublics.com&gt; .
</code></pre>

And there were no errors/warning using parser and thats correct - I tried to add triples throught SPARQL endpoint like:

<pre><code>
insert data {
&lt;http://www.-marches06.fr&gt; &lt;http://hasEdge&gt; &lt;http://http:/marchespublics.nantesmetropole.fr&gt; .
&lt;http://www.kommersannons.se:80/engelholm/Notice/NoticeOverview.aspx?ProcurementId=251&gt; &lt;http://myURI&gt; "myLiteral" .
&lt;http://www..strassen.nrw.de&gt; &lt;http://nextProblem&gt; &lt;http://public_procurement@sibelga.be&gt; .
&lt;http:////www.fz-juelich.de/gm&gt; &lt;http://next&gt; &lt;http://www2.kommersannons.se:80/eLite/Notice/NoticeOverview.aspx?ProcurementId=165&gt;.
&lt;http://www.melt.gr/&gt; &lt;http://aaa&gt; &lt;http://ehpad_simonviolet_pere.e-marchespublics.com&gt; .
}
</code></pre>

And inserting has no problems.

**Comment by tomas-knap** [comment]
Well the user should be at least warned that  there is a problem with URI. That is what apache fuseki is doing. Thanks for testing.

**Comment by tomas-knap** [comment]
Jirko, please try validation features of apache jena: 
http://jena.apache.org/download/

So you may create a separated project (could be just normal java app), where you test the validation features in the same way as for openRDF. I know that when using fuseki - SPARQL endpoint, there is very nice build-in validation for which JENA is probably responsible. 

Write your findings to the experiments separated confluence page

**Comment by tomesj** [comment]
I downloaded Jena and used in to file TED2.ttl via http://jena.apache.org/documentation/inference/#validation

But I get no errors - result was OK.

Here is my code :

<pre><code>
InputStream in=new FileInputStream(new File("C:\\intlib\\ted2.ttl"));
        
        Model data = ModelFactory.createDefaultModel();
        data.read(in, "", "TURTLE");
        
        Reasoner resoner= ReasonerRegistry.getOWLReasoner();
        InfModel infModel = ModelFactory.createInfModel(resoner,data);
        ValidityReport validity = infModel.validate();
        if (validity.isValid()) {
            System.out.println("OK");
        } else {
            System.out.println("Conflicts");
            for (Iterator i = validity.getReports(); i.hasNext();) {
                System.out.println(" - " + i.next());
            }
        }
</code></pre>

I checked some variants, but the result was the same. 

I thought that may data problem, but all data were loaded successfully, because when I tried to print count of statement or all statements, I got same result as it is in TED 2 file.

**Comment by tomas-knap** [comment]
Jirko, probably you are using wrong model - the default one:

Model data = ModelFactory.createDefaultModel();

Default model probably does not support reasoning, so no validation error is reported. Try as in the example:

<pre><code>Model data = FileManager.get().loadModel(fname);
    InfModel infmodel = ModelFactory.createRDFSModel(data);
    ValidityReport validity = infmodel.validate();
    if (validity.isValid()) {
        System.out.println("OK");
    } else {
        System.out.println("Conflicts");
        for (Iterator i = validity.getReports(); i.hasNext(); ) {
            System.out.println(" - " + i.next());
        }
    }</pre></code>

**Comment by tomesj** [comment]
I tried this code yesterday, today once again for sure, but the result is still OK. I dont know why ?

**Comment by tomas-knap** [comment]
Jirka, was discussing with Alex, could you please try to play a bit with openRDF ParseErrorListener and ParserCOnfig? You should be able to configure openRDF parser to provide you with more messages about data problems. Could please test that on the data above? In case of any question, write me.

If this will not work anyhow, we will look on Jena/Fuseki

**Comment by tomesj** [comment]
ParserErrorListener I have just used. Thanks that I got report - warnings, errors, fatal errros (with message, line, column)....I try to test ParserConfig and than I write here result of this :)

**Comment by tomas-knap** [comment]
So what is the result of the testing?

**Comment by tomas-knap** [comment]
File extractor, sparql extractor, pouziva defaultne statistical and error handler, rename to "use statistical and error handler", vyhodit vypisovani jednotlivych triples,

**Comment by tomas-knap** [comment]
SPARQL loader a RDF File Loader ma volitelny checkbox (defaultne nezaskrtnuty) - "Validate data before loading" . Funguje to tak, ze se vysypou data do tmp adresare loaderu, pak se nactou pres parser a zahodi.

**Comment by tomas-knap** [comment]
Jirko, kdyz koukam na vypis: 

2013-11-03 17:51:52,111 [dpu: XSLT] WARN  exec:242 dpu:105 o.o.r.helpers.ParseErrorLogger - [Rio error] '' is not a valid value for datatype http://www.w3.org/2001/XMLSchema#date (53, 77)
2013-11-03 17:51:52,113 [dpu: XSLT] WARN  exec:242 dpu:105 o.o.r.helpers.ParseErrorLogger - [Rio error] '' is not a valid value for datatype http://www.w3.org/2001/XMLSchema#date (59, 77)
2013-11-03 17:51:52,115 [dpu: XSLT] WARN  exec:242 dpu:105 o.o.r.helpers.ParseErrorLogger - [Rio error] '' is not a valid value for datatype http://www.w3.org/2001/XMLSchema#date (77, 77)
2013-11-03 17:51:52,116 [dpu: XSLT] WARN  exec:242 dpu:105 o.o.r.helpers.ParseErrorLogger - [Rio error] '' is not a valid value for datatype http://www.w3.org/2001/XMLSchema#date (83, 77)
2013-11-03 17:51:52,118 [dpu: XSLT] WARN  exec:242 dpu:105 o.o.r.helpers.ParseErrorLogger - [Rio error] '' is not a valid value for datatype http://www.w3.org/2001/XMLSchema#date (101, 77)
2013-11-03 17:51:52,120 [dpu: XSLT] WARN  exec:242 dpu:105 o.o.r.helpers.ParseErrorLogger - [Rio error] '' is not a valid value for datatype http://www.w3.org/2001/XMLSchema#date (107, 77)

Chtelo by to urcite pridat info o tom, ktery literal byl spatne a jaka trojice byla spatne, tedy neco v duchu:

2013-11-03 17:51:52,120 [dpu: XSLT] WARN  exec:242 dpu:105 o.o.r.helpers.ParseErrorLogger - [Rio error] '' is not a valid value for datatype http://www.w3.org/2001/XMLSchema#date. The literal with error: '', triple: http://x http://y/date ''.

Obecne tedy vzdy uvest ktera hodnota a v jake trojici byla spatne.

**Comment by tomesj** [comment]
Bohužel, z toho co mám k dispozici můžu zjistit pouze
1) Typ chyby, sloupec + řádek, kde nastala - tento výpis je při použití celeho add (bez parseru) - my jak jsme říkali budeme parser používat vždy, takže to bude mít nějakou formu.

Jaká je to trojice to bohužel nevím jestli půjde zjistit - podívám se na to :-)

**Comment by tomas-knap** [comment]
Ok, pak bych tedy navrhoval, aby to pri pouziti celeho add (tedy neni zaskrtnuto use error and statistical handler) jen  napsalo jeden warning, ze data obsahuji chyby, pokud se nejaka chyba objevi. Detailni vypis v tom duchu jak jsem psal pak ale prosim, vcetne te trojice pokud pujde, udelej pro ten error and statistical handler, tedy aby to vypsalo neco jako:

2013-11-03 17:51:52,120 [dpu: XSLT] WARN exec:242 dpu:105 o.o.r.helpers.ParseErrorLogger - [Rio error] '' is not a valid value for datatype http://www.w3.org/2001/XMLSchema#date. The literal with error: '', triple: http://x http://y/date ''.

Take prosim v dialogu vsude dej ten statistical and error handler defaultne jako zaskrtnuty.

**Comment by tomas-knap** [comment]
Nezapomen taky upravit ten statistical error handler aby nevypisoval kazdou trojici

**Comment by tomesj** [comment]
1)
Úprava extrakce - file/SPARQL - vždy se použije nějaký handler. Je-li zvolena možnost statistical and error handler - loguje průběžně počet trocic, na konci, jsou-li chyby (errors/warning) vše vypíše, včetně trojic, kde k problému došlo.

hlavní commit: c1e03adc62bfae5cc8b34a2f13b10aa5f3036848

2)
Statistic a error handler jako defaultně zaškrnutý 
commits: b94992eb18a3ec0db979a70e05fdd1f296391863 , 07e3e06057b748877d4abd0302e301d6e8ffc8d0 , 07e3e06057b748877d4abd0302e301d6e8ffc8d0

Vše potřebné tedy vyřešeno, připraveno k zavření :-)

**Comment by tomas-knap** [comment]
a pro ten loader to mas take jak jsme se bavili? Tedy je tam nove checkbox "Validate data before load" a ten je defaultne nezaskrtnuty. Pokud se zaskrtne, tak se take validuji data, coz znamena, ze se data serializuji do souboru, ten se pak zkusi nahrat, vyhodnoti se chybi a nahrany soubor se zahodi.

**Comment by tomesj** [comment]
Tento loader zatím ještě celý nemám, vyřešené jsou zatím jen ty extraktory. Až to budu mít, tak sem napíšu :-)

**Comment by tomesj** [comment]
Tak mám hotový i ten loader a jeho validaci dat. Takže asi hotové vše :-)

**Comment by tomas-knap** [comment]
Ahoj, super, mam drobnosti:

Kdykoliv to pri extrakci/loadovani s validaci najde aspon jednu chybu, vyhod prosim take DPU event at WARN level. A do detailu te event dej ten seznam chyb co ted davas do log.error(). Tohle prosim udelej pro extractory i loadery.

V detailu chyb vyhod to source_column a misto "No added triple contains ERROR:" tam dej "Error in triple: "

Take prosim pridej do RDF FIle extractor a SPARQL extractor checkbox (defaultne NEzaskrtnuty): "If there is an error in some of the extracted triples, extractor ends with an error and no data is send further". Podobne pro SPARQL loader a RDF loader, kde pridej neco ve stylu "If the validation before loading fails, the loading fails immediately". 

V RDF loaderu taky prosim pridej statistical and error handler a checkbox "If the validation before loading fails, the loading fails immediately". Pak uz budu spokojen :)

![screen shot 2013-11-07 at 4 49 25 pm](https://f.cloud.github.com/assets/3014917/1492726/367d5024-47c4-11e3-8952-34ebd3f198ec.png)

**Comment by tomesj** [comment]
Pár poznámek, ještě před tím než začnu:

1)  DPU event typu WARN kdy je nalezena alespoň 1 chyba 
Pro loadery to nebude problém - pro SPARQL to tam přidám bez problémů. Mám přidat možnost validace této i pro File loader ? 

Pro extractory to moc dobře nepůjde - je to zanořené uvnitř v kódu BaseRDFRepo...Nepoužívá se tady třída  RepositoryDataValidator, která by mohla být přímo v tom DPU - musel bych do všech metod přidat context a to není dobré řešení...Jinak u všech DPU, když dojde k výjimce, je pak zapsána pomocí context.sendMessage(...). Tak bych to nechal i tomto případě a už do toho dál nezasahoval. Jen přídám chybovou hlášku s chybami přímo v kódu do třídy - ten probublá až do DPU a ta to se pak pošle contextu - asi nejlepší řešení.

2) Vyhodit sloupec + změnit error hlášku
- oboje bez problémů

3)  Extractory - nezaškrnutý checkbox "If there is an error in some of the extracted triples, extractor ends with an error and no data is send further"

Přijde mi to trochu nelogické - je to totiž závislé na zašknutí "Use statistic and error handler", protože jen v tomto případě se kouká na nějaké chyby. Jinak to projde přes standardní handler a nedá se to ani poznat, kolik těch chyb bylo (nahrají se jen správné trojice, chybné se ignorují, ale nemám o nich přehled).

Mě přijde logické tedy jen ten 1 check box - "Use statistical and error handler"
1) Nepoužiju "Statistic and error" - nahrají se mi jen data bez chyb, budu znát jejich počet, pokračuje se dál
2) Použiju "Statistic and error" - stejné jako 1), hned potom seznam všech chyb s popisem (tyto špatné trojice se nenahrávají), pokračuje to dál

Aktuálně je to udělané tak, aby se špatné trojice vůbec nepřidávali do repositáře - proto to nově dělají pouze handlery.

Pro loadery - přijde mi že opět stačí 1 checkbox typu "Validate data before loading - if validation fails, the loading fails immediately"

1) Začkrtuto - provede se validace všech dat v repozitáři, které se mají nahrát
a)  žádné chyby v datech- vše se nahraje...
b) nějaké chyby - zalogují se/vypíšou/pošlou DPU, konec procesu- žádný load dat.

2) Nezaškrtnuto - provede se rovnou load bez kontroly.

Co ty na to ?

**Comment by tomas-knap** [comment]
Jirko, 

1) Ano, kdyz narazis na chybu v base rdf repo, posli si vyjimku, tu si odchyt a posli context.sendMessage(). Udelej to prosim jednotne pro 2xloader a 2xextractor

3) Ano, mas pravdu, nechtel jsem ti to komplikovat. Muze se to chovat tak, ze ten checkbox "If there is an error in some of the extracted triples, extractor ends with an error and no data is send further" bude enabled jenom tehdy, kdyz je zaskrtnuty "statistical and error handler" Pokud je odskrtnuty, tak se automaticky disabluje ten checkbox  "If there is an error in some of the extracted triples, extractor ends with an error and no data is send further". Prijde mi to tak lepsi, bo ty muzes chtit obe veci - zfailovat kdyz jsou tam chyby a nebo proste pokracovat kdyz narazis na chyby

**Comment by tomas-knap** [comment]
Co ty na to?

**Comment by tomesj** [comment]
1) Myslel jsem to přesně tak, jak píšeš, takže tenhle bod je OK
3) To, co píšeš mi dává smysl jen u loaderu - když data neprojdou validací - můžu/nemusím dál pokračovat, nikoliv u extraktoru - když tam se ty chyby nikdy nedostanou do repozitáře - v žádném případě. A když to chyby nemá, nemá smysl asi extrakci a následný běh zastavovat. Navíc by se všechny ty metody museli rozšířit o ten příznak (boolean proměná) zda skončit či ne když při extrakci byly zjištěny chyby (které tam vlastně stejně nebudou) ? To asi není moc dobré - spíše bych řekl, že pak bude ten kód, resp. velký počet proměnných dost matoucí. Ale jestli na tom bezpodmínečně trváš, tak to tak tedy udělám....

**Comment by tomas-knap** [comment]
U toho extractoru mi slo o to, ze v nekterych pripadech nema smysl mit 95% dat, jedine co ma smysl je mit bud vsechna data a nebo zadna, kdyz jsou v nich chyby. Tak to tedy udelej u toho loaderu jak pises a u tech extraktoru: 

Misto "If there is an error in some of the extracted triples, extractor ends with an error and no data is send further" tam dej moznost zaskrtnout "If there is an error in some of the extracted triples, extractor ends with an error". Tzn. ze to neskonci s warning, ale s error. To by melo mit za nasledek, ze zbytek pipeline uz ani nepobezi, cela execution skonci jako error, ne?

**Comment by tomesj** [comment]
OK, myslím, že si s tím nějak poradím, aby to bylo k tvé spokojenosti :-)

**Comment by tomesj** [comment]
Věřím, že budeš spokojený :-) Myslím, že už je to všechno :)

**Comment by tomas-knap** [comment]
Second choice in RDF File extractor (details tab) may dissapear. Check the second check box, uncheck the first

![screen shot 2013-11-21 at 4 14 22 pm](https://f.cloud.github.com/assets/3014917/1592669/a8f26648-52bf-11e3-9f19-67bd083e5420.png)

It would be better to just diable the choice

**Comment by tomas-knap** [comment]
If there is error in the log due to some validation issue and the extractor should not end with ERROR, there is no WARN event for the Extractor. There should be  one such event.

**Comment by tomas-knap** [comment]
The problem with certain triples should NOT be logged as a short message of event but as a detail (appears in a details dialog when clicking on it), so that it does not spoil the event table

**Comment by tomas-knap** [comment]
Check the problems above also for other DPUs

**Comment by tomas-knap** [comment]
We will disuss on the meeting radio button group with two choices - END with error when error discovered and Log all errors and extract only those data do not containing errors

**Comment by tomas-knap** [comment]
TODO:
- If there is error in the log due to some validation issue and the extractor should not end with ERROR, there is no WARN event for the Extractor. There should be one such event.
- The problem with certain triples should NOT be logged as a short message of event but as a detail (appears in a details dialog when clicking on it), so that it does not spoil the event table
- radio button group with two choices - END with error when error discovered and Log all errors and extract only those data do not containing errors
- radio button groupu should not dissapear but should be only disabled
- udelat pro FIle/SPARQL extractor zmeny vyse
- rdf file loader - to same co SPARQL loader

**Comment by tomesj** [comment]
All described TODOs solved.
