### ISSUE TITLE
Go away from settings: NullPointerException

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#417]
I logged in, went to settings and clicked on Execution Monitor or any other menu item:

![image](https://f.cloud.github.com/assets/718827/1102761/f65f951a-1857-11e3-8596-2620d6e7c5d4.png)

**Comment by bogo777** [comment]
It seems that for account "user" there is no email in db filled. While it was tested when loading data(and default username@example.com) was prefilled, it was not tested when determining if changes happened.

**Comment by jakubklimek** [comment]
OK, now it does not write the NullPointerException, but it asks me whether to save changes when there were not any. But that is another issue like https://github.com/mff-uk/intlib/issues/395 or https://github.com/mff-uk/intlib/issues/340

**Comment by bogo777** [comment]
It was because account "user" didn't have initial notification settings in db. They are there for "admin" account and are automatically created for any new user. So I filled them to db for "user" account too, so this should not occur again.

**Comment by jakubklimek** [comment]
OK, that is provided that I reload the database, right? And as always, the exception should be handled better even though it is fixed by fixing the database
