### ISSUE TITLE
Execution Monitor load is extremely slow when heavy logging on backend + Show log does not respond, see the end of the discussion

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#418]
My DPU, buyer profiles, logs a lot. When it has its cache, it is the main bottleneck. When it runs and logs and I click on Execution monitor, it takes up to a minute to load it, which is unacceptable.

**Comment by tomas-knap** [comment]
Related to issue #412, which helps. Bohuslav, can you please check that, I thought that with lazy loading these problems should not occur?

**Comment by jakubklimek** [comment]
Actually, it seems that the issue is not related to logging. Clicking on execution monitor simply takes forever. What is the problem here? There is only 8 records shown, that should be instantaneous.

**Comment by tomas-knap** [comment]
Bohuslav, do you have any explanation?

**Comment by bogo777** [comment]
I have no explanation yet, will test that. Will I be able to use DPU buyer profiles from mff-uk/DPUs for testing? Or do I need some special configuration/pipeline?

**Comment by jakubklimek** [comment]
See https://github.com/mff-uk/intlib/issues/100#issuecomment-24055759 for buyer-profiles DPU usage

**Comment by bogo777** [comment]
It seems, that this problem is caused by combination of issues:
1) heavy logging strains database, so queries are slower
2) if component is refreshed before it is loaded for the first time, it gets stuck in loop of reloading, which sometimes ends after while and sometimes it goes on and on.

I changed when automatical refresh on execution monitor is started, so this issue should not occure there. But DebuggingView is loading slowly, so I increased interval between automatic refreshes, and it works for me now.

It still takes up to 10 seconds to load, but I have slow laptop with CPU Usage 100% when running frontend and buyer-profiles on backend, so hopefully it will be faster on other PCs.

**Comment by tomas-knap** [comment]
muzes prosim ologovat a dat casy? Jak co dlouho trva? abychom vedeli

**Comment by tomas-knap** [comment]
add 2) vyresils to?

**Comment by tomas-knap** [comment]
Bohuslav, you may add one simple flag variable, which is set to true, e.g., when the dialog is loaded?

**Comment by bogo777** [comment]
Well the initializing code is executed on server, there is no problem, it is about displaying on client. I found Refresher add-on, it makes refresh request from client side, it might help in this case.

**Comment by tomas-knap** [comment]
Yes, refresh from the client side is more natural

**Comment by bogo777** [comment]
Changed to refresh from client, but in result this issue occured #478

**Comment by jakubklimek** [comment]
Works when DB is clean, will retest when DB is more populated.

**Comment by jakubklimek** [comment]
However, show log still does not respond 2 times out of 3

**Comment by tomas-knap** [comment]
Kubo, can you please paste the error shown in apache tomcat?

**Comment by jakubklimek** [comment]
There is no error regarding this issue in the log.

There is 

<pre><code>IX 15, 2013 2:47:36 ODP. org.atmosphere.cpr.DefaultBroadcaster perRequestFilter
WARNING: Request is not longer valid f9b5ecca-d241-46b0-a8db-5d879d9a8b40</code></pre>

but I think that is related to https://github.com/mff-uk/intlib/issues/488 or something else.

**Comment by tomas-knap** [comment]
Bohuslav, do you experience the same issue with Show log? that it does not respond 2 times out of 3?

**Comment by tomas-knap** [comment]
Duplicated with #477, please contribute there
