### ISSUE TITLE
Add menuitem "ODCleanStore" as the first one, leading to the homepage

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#425]
Add menuitem "ODCleanStore" as the first one, leading to the homepage so that it is consistent with our other applications (based on Twitter Bootstrap).

**Comment by tomas-knap** [comment]
Now there is no way to see the the homepage.

**Comment by jakubklimek** [comment]
Almost OK. Could the text for ODCleanStore be bigger than the rest so that it is clearer that it is the name of the app? And, but only if it is not too much work, could the black menu bar itself be higher so that it looks more like <a href="http://live.payola.cz">Payola</a>, <a href="http://wealthofnation.com">Wealth of Nation</a>, <a href="http://getbootstrap.com/">Bootstrap</a> itself or even <a href="https://www.google.com">Google</a>?
