### ISSUE TITLE
Backend online/offline notification not working

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#428]
I stopped the backend and the frontend kept showing the "green light"
![image](https://f.cloud.github.com/assets/718827/1103468/2e347d2c-18ab-11e3-8c8f-9ba3b3a9677d.png)

**Comment by tomas-knap** [comment]
Bohuslav please test that if you can reproduce, if not, reject.

**Comment by bogo777** [comment]
Same issue as #397.

**Comment by jakubklimek** [comment]
Unable to reproduce, will reopen if it happens again.
