### ISSUE TITLE
Buttons (filters) are not aligned with the table of events

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#43]
See below, the line with filters should end at the same moment as the table for pipeline events (so that the right part of the pipeline event dialog is alighned)

![screen shot 2013-06-20 at 11 25 51 am](https://f.cloud.github.com/assets/3014917/680300/78ee978a-d98b-11e2-840b-9dbcf251edd7.png)

**Comment by tomas-knap** [comment]
See #53

**Comment by bogo777** [comment]
Solved by introducing PagedFilterTable from FilteringTable addon. Filters are now part of the header row of table, and are resized with table.
