### ISSUE TITLE
Frontend cannot start

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#431]
Well, now when I deploy to tomcat, I get the following error so something is definitely wrong:
![image](https://f.cloud.github.com/assets/718827/1105500/d133f7c4-1927-11e3-92fb-4fc6094cc10b.png)

<pre><code>INFO: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: C:\Program Files\Apache Software Foundation\Tomcat 7.0\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseHg\;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\semweb\bin\;C:\apache-maven-3.1.0\bin;C:\Program Files\TortoiseSVN\bin;;.
IX 09, 2013 10:11:20 DOP. org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
IX 09, 2013 10:11:20 DOP. org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["ajp-bio-8009"]
IX 09, 2013 10:11:20 DOP. org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 1642 ms
IX 09, 2013 10:11:20 DOP. org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
IX 09, 2013 10:11:20 DOP. org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.37
IX 09, 2013 10:11:20 DOP. org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory C:\Program Files\Apache Software Foundation\Tomcat 7.0\webapps\manager
IX 09, 2013 10:11:21 DOP. org.apache.catalina.util.SessionIdGenerator createSecureRandom
INFO: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [228] milliseconds.
IX 09, 2013 10:11:21 DOP. org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory C:\Program Files\Apache Software Foundation\Tomcat 7.0\webapps\ROOT
IX 09, 2013 10:11:21 DOP. org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
IX 09, 2013 10:11:21 DOP. org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-bio-8009"]
IX 09, 2013 10:11:21 DOP. org.apache.catalina.startup.Catalina start
INFO: Server startup in 1159 ms
IX 09, 2013 10:11:31 DOP. org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive C:\Program Files\Apache Software Foundation\Tomcat 7.0\webapps\intlib.war
IX 09, 2013 10:11:50 DOP. cz.cuni.xrg.intlib.commons.configuration.AppConfig <init>
INFO: Loading configuration from: C:\/.intlib/config.properties
IX 09, 2013 10:12:38 DOP. com.vaadin.server.DefaultDeploymentConfiguration checkProductionMode
WARNING: 
=================================================================
Vaadin is running in DEBUG MODE.
Add productionMode=true to web.xml to disable debug features.
To show debug window, add ?debug to your application URL.
=================================================================
IX 09, 2013 10:12:38 DOP. org.atmosphere.cpr.AtmosphereFramework addAtmosphereHandler
INFO: Installed AtmosphereHandler com.vaadin.server.communication.PushHandler mapped to context-path: /*
IX 09, 2013 10:12:39 DOP. org.atmosphere.cpr.DefaultBroadcaster <init>
INFO: /* support Out Of Order Broadcast: false
IX 09, 2013 10:12:39 DOP. org.atmosphere.cpr.AtmosphereFramework autoDetectWebSocketHandler
INFO: Auto detecting WebSocketHandler in /WEB-INF/classes/
IX 09, 2013 10:12:39 DOP. org.atmosphere.cpr.AtmosphereFramework initWebSocket
INFO: Installed WebSocketProtocol org.atmosphere.websocket.protocol.SimpleHttpProtocol 
IX 09, 2013 10:12:39 DOP. org.atmosphere.cpr.AtmosphereFramework autoDetectContainer
INFO: Atmosphere is using async support: org.atmosphere.container.Tomcat7AsyncSupportWithWebSocket running under container: Apache Tomcat/7.0.37
IX 09, 2013 10:12:39 DOP. org.atmosphere.cpr.AtmosphereFramework configureAtmosphereInterceptor
INFO: Installed Default AtmosphereInterceptor [Android Interceptor Support, SSE Interceptor Support, JSONP Interceptor Support, Atmosphere JavaScript Protocol, Browser disconnection detection]. Set org.atmosphere.cpr.AtmosphereInterceptor.disableDefaults in your xml to disable them.
IX 09, 2013 10:12:39 DOP. org.atmosphere.cpr.AtmosphereFramework init
WARNING: No BroadcasterCache configured. Broadcasted message between client reconnection will be LOST. It is recommended to configure the org.atmosphere.cache.UUIDBroadcasterCache
IX 09, 2013 10:12:39 DOP. org.atmosphere.cpr.AtmosphereFramework init
INFO: Shared ExecutorService supported: true
IX 09, 2013 10:12:39 DOP. org.atmosphere.cpr.AtmosphereFramework init
INFO: HttpSession supported: true
IX 09, 2013 10:12:39 DOP. org.atmosphere.cpr.AtmosphereFramework init
INFO: Using BroadcasterFactory: org.atmosphere.cpr.DefaultBroadcasterFactory
IX 09, 2013 10:12:39 DOP. org.atmosphere.cpr.AtmosphereFramework init
INFO: Using WebSocketProcessor: org.atmosphere.websocket.DefaultWebSocketProcessor
IX 09, 2013 10:12:39 DOP. org.atmosphere.cpr.AtmosphereFramework init
INFO: Using Broadcaster: org.atmosphere.cpr.DefaultBroadcaster
IX 09, 2013 10:12:39 DOP. org.atmosphere.cpr.AtmosphereFramework init
INFO: Atmosphere Framework 1.0.14.vaadin3 started.
IX 09, 2013 10:12:39 DOP. org.atmosphere.cpr.AtmosphereFramework interceptor
INFO: Installed AtmosphereInterceptor  Track Message Size Interceptor using |. 
IX 09, 2013 10:12:39 DOP. org.atmosphere.cpr.AtmosphereFramework addAtmosphereHandler
INFO: Installed AtmosphereHandler cz.cuni.xrg.intlib.frontend.IntlibPushHandler mapped to context-path: /*
IX 09, 2013 10:12:40 DOP. com.vaadin.server.DefaultErrorHandler doDefault
SEVERE: 
java.lang.Error: Unresolved compilation problem: 
    RequestHolder cannot be resolved

    at cz.cuni.xrg.intlib.frontend.AppEntry.init(AppEntry.java:116)
    at com.vaadin.ui.UI.doInit(UI.java:603)
    at com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:223)
    at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:73)
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37)
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1329)
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:236)
    at cz.cuni.xrg.intlib.frontend.IntlibApplicationServlet.service(IntlibApplicationServlet.java:64)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
</code></pre>

**Comment by bogo777** [comment]
I cannot reproduce it, I made clean&build on whole intlib without frontend and deployed frontend and it runs fine. I have class RequestHolder in frontend. Since it is Jan's class, maybe he will know more.

**Comment by janvojt** [comment]
The message is clear, class RequestHolder cannot be resolved. I checked in the repository, and the class is there in the same namespace as IntlibApplicationServlet, where it is called. Therefore there must be something wrong with your build. It worked yesterday and there were no changes in these files for 5 days.

I am guessing your build did not succeed for some other reason. Please make a clean install on the whole project. Check you have BUILD SUCCESS on all modules. Redeploy, and if the problem persists, make sure class RequestHolder exists.

**Comment by jakubklimek** [comment]
The WAR was a result of <code>mvn clean install -DskipTests</code> but OK, I will do that again. However, the mentioned class is in the WAR. And yes, all modules had SUCCESS after compilation.

**Comment by jakubklimek** [comment]
OK, did the same thing and this time it worked. Strange. Just FYI, the resulting WAR and the erroneous one have different sizes - really weird when I just ran <code>mvn clean install -DskipTests</code> twice...
