### ISSUE TITLE
Too many scrollbars

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#44]
For pipeline execution dialog:
- if the width of the dialog is too low, ONE scrollbar should occur for the WHOLE dialog, no scrollbar for the table. (see below)
  ![screen shot 2013-06-20 at 11 21 21 am](https://f.cloud.github.com/assets/3014917/680276/f2ab731e-d98a-11e2-8985-02266bc47cc6.png)
- For debug view, there should be NO scrollbar for the table with events, but if the width is too low, there should be one horizontal scrollbar for the whole debug view (see below)
  ![screen shot 2013-06-20 at 11 24 08 am](https://f.cloud.github.com/assets/3014917/680284/3d48965e-d98b-11e2-9f93-b8bacf0fa638.png)
- List of pipelines: horizontal scrollbar should not appear in the table but for the whole window if needed. 
  ![screen shot 2013-06-20 at 11 29 21 am](https://f.cloud.github.com/assets/3014917/680313/f99f94b0-d98b-11e2-9ed5-6351e73a2246.png)
- Pipeline edit: Too many scrollbars - for the dialog and browse window - just the scrollbar for the browser window is enough.
  ![screen shot 2013-06-20 at 11 35 35 am](https://f.cloud.github.com/assets/3014917/680344/d53b5324-d98c-11e2-9968-cc947f487fb3.png)

**Comment by tomas-knap** [comment]
Scrollbars for tables, textareas, no scrollbar for the window/dialog

**Comment by bogo777** [comment]
Extra scrollbar in execution monitor is caused by filters and it will be solved by solving #53 
Scrollbars in pipeline edit will be solved by #45 
Other scrollbars as Tomas wrote in last comment.
