### ISSUE TITLE
RDFDataUnitHelper - method getTriples, which allows iteration over results

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#441]
List<Statement> triples = inputRdf.getTriples();

There should be also a version of getTriples() method, which allows to iterate over smaller chunks of data as in case of the loader getting only XX triples at once.

**Comment by tomas-knap** [comment]
By lazy implementation I mean that user (DPU author) may use certain iterator (in his DPU) to iterate himself over all triples in the rdf data unit. So from his execute method, he may call it.next() to get next couple of triples.

**Comment by tomesj** [comment]
Yes, I mean the same. Class LazyTriples has behavior as iterator, And if you call getTriples() on the instance, it returns next X triples defined by splitSize (or is used default splitValue). 

Class has boolean method hasListTriples(), to find if next list with triples exists or not :-)

**Comment by tomas-knap** [comment]
But RDF data unit helper ma jen metodu List<Statments> getTriples(). Mela by mit jeste methodu getTripesIterator() napriklad.

**Comment by tomesj** [comment]
Má teď metodu getLazyTriples(). Můžu to klidně přejmenovat na getTriplesIterator jestli chceš.

**Comment by tomas-knap** [comment]
Jasne, ja ji tu nemam, bo nemam posledni commit. Ale stejne ji prosim prejmenuj. getLazyTriples je trosku divne
