### ISSUE TITLE
When deleting pipeline, it is not deleted completely

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#446]
I copied my pipeline and then wanted to delete it. I clicked on delete and all the buttons from the pipeline disappeared, but the pipeline record is still visible. When I clicked on it, I got to the login screen. When I logged in, the pipeline was gone.
![image](https://f.cloud.github.com/assets/718827/1120521/5ddac2f6-1aa5-11e3-9ea2-330a2579c395.png)

**Comment by tomas-knap** [comment]
Bohuslav, is this relevant for you? If not, please switch to Honza

**Comment by bogo777** [comment]
Cannot reproduce it, has the confirm dialog showed properly? Or did it failed even before that?

**Comment by jakubklimek** [comment]
It did not fail, it went OK.

**Comment by tomas-knap** [comment]
I will postpone this, if it happens again, increase prio
