### ISSUE TITLE
Email fails to validate

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#452]
![image](https://f.cloud.github.com/assets/718827/1121885/0e1f3644-1acc-11e3-8e82-7c5b410b5a15.png)

**Comment by kukharm** [comment]
Closed by commit https://github.com/mff-uk/intlib/commit/9455aa0ebded5f2cfea565331d5274e642867943

**Comment by jakubklimek** [comment]
Still not valid

![image](https://f.cloud.github.com/assets/718827/1131530/b053d858-1bbb-11e3-9612-0082382c8037.png)

In addition, password should be hidden

**Comment by kukharm** [comment]
We discussed this with Tomas.  It is work according to the scenario:  when user enters the password it is visible, then when the user open this form for editing, the password is hidden. it was discussed in #222 

"When admin click on the button "change details" of user, all the fields will be prefilled, the password field will be filled with couple of stars (typical behaviour for password protected fields). If admin does not enter the password fields (for example he just edits the user's email), when saving the changes, the password will not be changed and the original remains valid. If admin enters the password field, the password field will become empty and admin can create new password. As he is writing the password, it is normally visible. When saving the record, the new password is set. If admin enters the field password, but did not fill any, new automatically generated password will be set to the given user's email (as in case of new user creation)."

**Comment by kukharm** [comment]
Please test email one more time, as i saw my previous changes of  regular expression was missing...i commit it one more time.

**Comment by tomas-knap** [comment]
Maria, please hide the password any time. But please provide the field for one more input of the password. When storing, you check that both password fields are the same. If not, error is shown to the user.

**Comment by jakubklimek** [comment]
Still not good.
First, the password confirmation is not visible at all:
![image](https://f.cloud.github.com/assets/718827/1145091/a2da0f9e-1df0-11e3-87ec-4a20704ba065.png)
and when I start typing the password, it shows up
![image](https://f.cloud.github.com/assets/718827/1145093/b9094d66-1df0-11e3-87cb-3d1626282e9f.png)
but it is skipped when I press "tab"

**Comment by tomas-knap** [comment]
Maria, when I write two diff paswords, it shows: 

![screen shot 2013-09-15 at 1 13 59 pm](https://f.cloud.github.com/assets/3014917/1145177/0bc792b8-1df8-11e3-9e39-183a1d85bf77.png)

Should describe why the error occured, thus: "The typed pasword is different than the retyped password"

**Comment by kukharm** [comment]
Test, please
