### ISSUE TITLE
When replacing DPU template (or editing it) Save button is always enabled.

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#456]
When replacing DPU template (or editing it) Save button is always enabled.

It should be consistent everywhere and save buttons should be disabled when there are no changes.

Also, changes should be detected better, which means when the text somewhere is changed, not when user leaves the textbox. This happens for example with pipeline description.

**Comment by kukharm** [comment]
9455aa0  closed #452 сommit for this issue was made incorrectly
