### ISSUE TITLE
Add "Last run time" column to pipelines, execution monitor and scheduler

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#458]
Measure how long pipelines run and display this in Pipelines, Execution Monitor and Scheduler.

**Comment by bogo777** [comment]
Ok,
for execution monitor it is clear. But for Pipelines, should the last successful execution runtime be shown? And last execution of given rule in Scheduler?

**Comment by jakubklimek** [comment]
This is related to https://github.com/mff-uk/intlib/issues/455 - there needs to be more info in those places. Some of it will be in multiple places so that the user has a good overview.

**Comment by tomas-knap** [comment]
Yes, every row in pipeline list should contain extra last column "Last successful run time", which contains how long the pipeline run during the last sucesfull run. in hh:mm:ss format. In case of schedulled event, it shows the last successful run time (hh:mm:ss) of that scheduled event. The same for execution monitor, but in that case it shows for every record.

**Comment by jakubklimek** [comment]
This is Tomášes fault :) but it should be "last runtime" regardless of how the pipeline ended.

**Comment by bogo777** [comment]
Does it concern only label of column or the way execution for this data is selected too(should run times from failed execution be used)?

**Comment by jakubklimek** [comment]
I concerns the way you get the data. This data item goes with the execution state, therefore, if the pipeline fails, the time will be of the failed execution. Simply put, it is the last run time, regardless of the result, as I said before.

**Comment by jakubklimek** [comment]
OK. But now when I look at it, one more enhancement. When pipeline is running, this column should have its current runtime.

**Comment by tomas-knap** [comment]
Od BohusL: Run time je generovaný sloupec, který se aktualizuje/znovu generuje pouze při změně dat, není tedy možné ho jednoduše aktualizovat při každém refreshi(pokud nedochází k načtení execution záznamů z db), ale určitě to půjde nějak vyřešit, jen jsem to kvůli poměru pracnost/přínos zažadil až za ten debug

**Comment by tomas-knap** [comment]
Is that ready for testing?
