### ISSUE TITLE
Strange Pipeline Execution Behavior - debug data missing!

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#46]
Look at http://odcs.xrg.cz:8080/etl-manager/, there are two pipelines having the same Extractor. 

When debugging pipeline "DBPedia", the extractor extracts certain data. When debugging pipeline "DBPedia", I can browse the intermediate results of extractor/loader. When debuggin pipeline "DBPedia with SPARQL", the pipeline works (it extracts, transforms, and loads the data), however, the debugger (debug window-> browse/query) does not show any data for EXTRACTOR and TRANSFORMER, only for LOADER. 

When examining backend/working dir, there is no dump-dat.ttl for EXTRACTOR (so that is the reason why there is no data to be browse when selecting EXTRACTOR in debug view), but there is dump-dat.ttl for TRANSFORMER, so the problems are:
- For Bohuslav, why the results of the TRANSFORMER on the pipeline is not available in debug view in the browser?
- For Jirka, why the results of EXTRACTOR are not available (there is no data-dump.ttl)?

**Comment by tomas-knap** [comment]
To reproduce on the local, create pipeline DBPedia. Save the extractor/loader as a new DPU. Create new pipeline where you use the saved extractor/loader and transformer. Try to debug the second pipeline

**Comment by bogo777** [comment]
There was mixup in used indexes for directories with debug data. In resolving directory name in frontend, index from debug context was used, but in backend dpu index was used. When there were only 2 dpus, extractor and loader, the bug didn't show. I fixed that and now I can display data from any dpu, and for transformer for both input and output graph in query tab.
