### ISSUE TITLE
Experiments on the Conflunce + create new Virtuoso SPARQL loader

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#465]
Put SPARQL loader experiments to a separated page

Specify the configuration of the machine you were testing on

Can you please add new section, where you test processing of these 7 milions of triples using different chunk sizes, e.g. 100, 1000, and 10000?

Why the disadvantage of the second approach for temp graph is that it has to be Virtuoso? I though that insert into ... where ... nebo load to are in SPARQL 1.1,thus, arbitrary store will work?

**Comment by tomesj** [comment]
Added to page: https://grips.semantic-web.at/display/LOD2/Loading+data+to+SPARQL+endpoint

**Comment by tomas-knap** [comment]
Jirka, machine configuration?

4] Chunk size = 10 000
"SQL text doesnt exceed 10000 lines of code." -> Who is throwing such exception and when?

**Comment by tomas-knap** [comment]
Jirka, i do not understand: 

1] ADD<temp_graph> TO <target_graph>
2] INSERT INTO {TARGET_GRAPH {?s ?p ?o}} where  {?s ?p ?o} 

WHy we cannot call such queries over HTTP?? DId you try that?

**Comment by tomesj** [comment]
4] Chunk size = 10 000
It return Virtuoso as exception - when I POST query containts 10 000 triples at once.

I can not call queries over HTTP, because Virtuoso is not able to do it for big data and after while returns error code.

**Comment by tomesj** [comment]
I added machine configuration.

**Comment by tomas-knap** [comment]
Jirka, can you please send me your virtuoso.ini file?

**Comment by tomesj** [comment]
File was sent by email :-)

**Comment by tomas-knap** [comment]
Jirka can you pleaes explain me, I was already asking couple of times:

Jirka, i do not understand:

1] ADD TO 
2] INSERT INTO {TARGET_GRAPH {?s ?p ?o}} where {?s ?p ?o}

WHy we cannot call such queries over HTTP instead of loading the data twice?? DId you try that? Where is the problem?

**Comment by tomesj** [comment]
This approach I have tested yet. The main reason why it couldnt be used we dont have virtuoso connection and if we call 1] or 2] as query thanks HTTP POST/GET we always became:

Virtuoso 40005 Error SR325: Transaction aborted because it's log after image size went above the limit

I tried to set log as you advised me, but it is still bad.

It is thanks big data set - see page http://wikis.openlinksw.com/dataspace/owiki/wiki/VirtuosoWikiWeb/SPARQLLoadFailureWithSuccessMessage

There advise to use function like TTLP_MT() or RDF_LOAD_RDFXML() - but data are in this case in file - we have data in repository - we have to use another approach.

Log_enable using:
http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtTipsAndTricksGuideDeleteLargeGraphs

Log_function:
http://docs.openlinksw.com/virtuoso/fn_log_enable.html

**Comment by tomas-knap** [comment]
Jirka, have you tried this: 

<pre><code>
SPARQL DEFINE sql:log-enable 2 
ADD/LOAD...</code></pre>

**Comment by tomas-knap** [comment]
Please test that and report here

**Comment by tomesj** [comment]
I will try it using calling HTTP, but using through SPARQL endpoint form it returns:
Virtuoso 37000 Error SP030: SPARQL compiler, line 3: syntax error at 'SPARQL' before 'DEFINE'

**Comment by tomesj** [comment]
I have very good news:

<pre><code>
DEFINE sql:log-enable 2 
ADD &lt;http://merge&gt; TO &lt;http://test&gt;
</code></pre>

This code passed and load all triples we want :-) I will implement it and test again, than add to master :-)

**Comment by tomesj** [comment]
Solved by commit: 932460b98437a784676b5eb461bccc6b41674cfb

**Comment by tomas-knap** [comment]
Jirko, 

the problem is that "DEFINE sql:log-enable 2" is Virtuoso specific and 
"ADD http://merge TO http://test" is not from the latest SPARQL 1.1. spec (so it is also more or less virtuoso specific). THerefore, I would suggest to have  one loader as was before the commit 932460b (please adjust that) and then second loader (called Virtuoso SPARQL Loader), which will have the same functionality as the normal SPARQL loader but implements the last commit 932460b - Add to query.

**Comment by tomesj** [comment]
Do you mean to create new DPU or only new similar method for loading data associate with Virtuoso ?

**Comment by tomas-knap** [comment]
New DPU. So next to current SPARQL Loader, there will be Virtuoso SPARQL Loader. The non-Virtuoso SPARQL loader will not use e.g. ADD x TO <graph>, but rather call loadDataParts twice.

**Comment by tomas-knap** [comment]
If ADD x To is not virtuoso specific, no new SPARQL loader is needed

**Comment by tomas-knap** [comment]
See #640
