### ISSUE TITLE
Save button disabled when description changed, dpus moved

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#467]
If I open pipeline, organize the dpus a bit, I cannot save it. Similarly, if I just change the description. 

Also if I create new pipeline with empty canvas, it cannot be saved.

**Comment by bogo777** [comment]
When creating new pipeline, detection of changes was broken. Added detection of DPU move on canvas for both saving/undo. After changing any text field, only after it looses focus is change detected.

**Comment by jakubklimek** [comment]
Well, this is a problem. Because when I only change one field e.g., description, I often don't loose focus and want to save and I can't. This has to be done on text change, not lost focus.
