### ISSUE TITLE
Multiple problems with authentication in BaseRDFRepo

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#474]
There are multiple serious problems with BaseRDFRepo.

1) On line 676 you use hardcoded default virtuoso username and password "dba" "dba" regardless of the actual username and password. SERIOUSLY???!!! You don't even pass the configured username and password to this method!

2) Please check all communication with target endpoint, are you using correct SPARQL endpoint from configuration and not the default ODCS connection?

3) Do you authenticate properly when you clear graphs, merge graphs etc. besides loading data?

**Comment by tomesj** [comment]
When I last tested, I added some logs and auxiliary methods calls to resolve problems. I forgot remove this one calling. Is my mistake.  Thanks for the warning.

**Comment by tomesj** [comment]
Removed by commit 4166d1f7072359a9ca4c3d8108487105da13e711

**Comment by tomas-knap** [comment]
Jirko, is this issue prepared for testing? If yes, put the test that label there.

**Comment by jakubklimek** [comment]
SPARQL loader now seems to work as expected, will reopen if necessary.
