### ISSUE TITLE
High network activity when frontend runs in Tomcat

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#479]
My setup is that I have frontend and backend on one machine and the database on another.

I noticed that when I deploy frontend on Tomcat and start playing with it (most noticably when I first click on Execution monitor), suddenly my network activity is enormous even though I do nothing. I suspect wrong refresh behavior but I cant be sure.

The network activity is 3 Mbit/s upload (tomcat -> database) and 4 Mbit/s dowload (database -> tomcat), which is not acceptable when there is nothing happening.

**Comment by jakubklimek** [comment]
Maybe related to https://github.com/mff-uk/intlib/issues/477 as I discovered when I tried to restart Tomcat that it actually crashed and I had to kill it. Which means that frontend does not handle well database connection errors.

**Comment by bogo777** [comment]
Is this new? I made changes in refresh today, only pushed them a while ago and I need to know, if this is from current version of frontend?

**Comment by tomas-knap** [comment]
Bohuslav, please check that. But it could be also causedby constantly renewing hibernate session? Although in this case I would not expect 3Mbit/s

**Comment by jakubklimek** [comment]
I noticed high network activity before, but I don't remember how much. My current version is dfa891a35369fc4d17711d7072408a1f71c60d54, which is before the refresh changes today.

**Comment by jakubklimek** [comment]
You can use my remote database for testing: internal.opendata.cz:1112 dba/dba

**Comment by bogo777** [comment]
If it is from last version, it may be related to #478. Currently execution monitor is refreshed every 5 seconds regardless wheter there are some execution running or not. But this behavior was in the past refresh version too.

**Comment by jakubklimek** [comment]
It seems to me as if you did not shutdown the refreshing  when user navigates to another page, causing more and more refreshing requests, but I am not sure. It is not caused by todays commits, because I did not update yet.

**Comment by jakubklimek** [comment]
Actually, now I only need to start Tomcat, login, click on Execution monitor and the first show log button and Tomcat freezes (but still generates network activity).

**Comment by jakubklimek** [comment]
OK, now I tested the new version and it repeatedly shows the waiting symbol and also downloads all the time.

And because when the waiting symbol is displayed, none of the buttons work, Show log doesn't work.

How many items do you have in your Execution monitor?

I suggest you use my remote testing database, generate 5000 entries to the table storing the execution monitor results (just copy one of the records) and then implement it so that it is fast. You don't need to refresh by downloading everything all the time. Just check with a single simple query whether there is a record newer than the last one you are displaying and if yes, download only those.

**Comment by tomas-knap** [comment]
When Honza is ready with switching from EAGER to LAZY loading, he will test the performance, see #209 
Closing this one
