### ISSUE TITLE
Saving DPU instance as new DPU template to the tree

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#48]
When DPU instance is saved as new DPU template, it should appear at the third level in the tree (as a child of the DPU template representing the common JAR (module) file). E.g. If I create specific SPARQL Extractor X, it should appear as a child of DPU SPARQL Extractor. 

If I create new SPARQL Extractor Y being derived from SPARQL Extractor X, it should appear a child of SPARQL Extractor again (not as a child of SPARQL Extractor Y).

**Comment by bogo777** [comment]
Solved. May need database representation improvement from Honza.
