### ISSUE TITLE
MenuItems are <span> elements, not <a>, which is wrong.

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#481]
Browser then does not see them as links and does not offer link-related functionality.

In addition, it is wrong from usability view and HTML semantics view. Make them links (<code>&lt;a&gt;</code>)

**Comment by bogo777** [comment]
Menu's html is generated by Vaadin, looked for any arcticles/info about this, haven't found any yet.

**Comment by tomas-knap** [comment]
Motivation: New tab cannot be created

**Comment by tomas-knap** [comment]
tohle je dané Vaadinem a nikde se to nedá přenastavit, nejspíš to znamená nutnost napsat si celé vlastní menu

**Comment by tomas-knap** [comment]
TODO: Check the news regarding this problem, possibly rewrite the menu with links (we do not use submenus, so it could be easy)

**Comment by tomas-knap** [comment]
will be solved by #1134
