### ISSUE TITLE
When browsing logs, certain page cannot be accessed, filter INFO not working

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#484]
The log table shows 3 pages, but the second cannot be access and the following error occurs:

![screen shot 2013-09-13 at 6 41 45 pm](https://f.cloud.github.com/assets/3014917/1139824/82414d1e-1c93-11e3-8280-1f1e820a7871.png)

**Comment by tomas-knap** [comment]
Further, filter info is not working

**Comment by janvojt** [comment]
I cannot reproduce this. Could you please specify exact steps how to achieve such situation starting with empty database?

**Comment by jakubklimek** [comment]
Probably related: https://github.com/mff-uk/intlib/issues/488

**Comment by jakubklimek** [comment]
Still happening. Caused by large log messages (whole documents, for example)
![image](https://f.cloud.github.com/assets/718827/1192754/fcf1ed04-2466-11e3-91f6-793b66256aa6.png)

**Comment by janvojt** [comment]
Again, I cannot fix this, if I cannot reproduce it. At least a stacktrace would be helpful. The attached screenshots do not tell much. To resolve this issue, please reproduce it and send me an email with database dump.

It would be better if you try to reproduce on version with eclipselink.

**Comment by tomas-knap** [comment]
THis exception does not appear further
