### ISSUE TITLE
Disable sorting by "Short message" in Execution Monitor's log.

### ISSUE THREAD

**Issue by janvojt** [mff-uk/odcs#485]
Short message data type is too big for Virtuoso to use it in ORDER BY clause. Also, it is pretty much pointless to do so. Please disable sorting by this column in table.
![screenshot from 2013-09-14 13 45 10](https://f.cloud.github.com/assets/2247062/1143331/5dbcb8f2-1d33-11e3-8e1e-b3c69f05dabb.png)

**Comment by janvojt** [comment]
I wanted to disable only sorting (not filtering) only for one column - "Short message". Not disabling sorting and filtering on all columns of the table.

The reason why to disable sorting is simple - column data type is too long, so Virtuoso does not support it in ORDER BY clause.

To enable sorting, we would need to shorten the column data type to varchar. This might cause some long error messages to be trimmed, as logback's documentation recommends this column to allow longer text. Also, I do not think it makes any sense to sort table by message. Please note, that I am talking only about sorting. Filtering on the other hand is useful and possible without changing data type.

**Comment by jakubklimek** [comment]
I agree with Jan here. Sorting by the message is not important. Filtering is.

**Comment by bogo777** [comment]
Reenabled filtering on "message" columns in Records and Logs table.
