### ISSUE TITLE
Parallel running of the Scenario

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#49]
When running Scenario 1 (See iteration 2 in confluence) once, it was successfully executed in approx 2mins. There was still the problem already described by bug #46 .

However, when running Scenario 1 three times, there is no result after 40mins. 

It was tested on odcs.xrg.cz:8080/etl-manager.

To try that, create a pipeline for Scenario 1 in confluence, containing extractor, 3x SPARQL transformer, and loader and launch it 3 times.

**Comment by tomesj** [comment]
Parrallel running tests for simple pipeline using Local/Virtuoso repository were executed successfully.

**Comment by tomas-knap** [comment]
And what was the problem?

**Comment by tomesj** [comment]
I don´t know. Maybe bad using of repository. When I tested parralel running functionally I never had problems with throwing exception or wrong behavior.
