### ISSUE TITLE
Add DPUDataUnit "Description"

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#492]
Add DPUDataUnit "Description"

Now we have DPU input/output naming, but we also need Description where some details about the data provided (consumed) are written.

**Comment by skodapetr** [comment]
And who should provide this description, the programmer directly in code (annotation)? 
Should it be customizable by an user?

**Comment by jakubklimek** [comment]
This needs to be done by the DPU Developer in the code the same way as the DPU input/output name.

**Comment by tomas-knap** [comment]
Well, so we can extend the annotation from 
@OutputDataUnit("name=x, description=Mydescription") ?

**Comment by skodapetr** [comment]
There now should be full support from commons and database. So now we need frontend support for this.

**Comment by tomas-knap** [comment]
Regarding GUI, so there could be extra tab with inputs/outputs and their descriptions? Or we can have the first tab with core information about DPU - name, descriptiuon, inputs/outputs and second tab will be the configuration?

**Comment by tomas-knap** [comment]
Maria, could you please prepare mockup for that and prepare the dialog when we agree on the mockup?

**Comment by kukharm** [comment]
https://grips.semantic-web.at/display/LOD2/DPU+instance

**Comment by tomas-knap** [comment]
THe mockup has to be clarified before the issue may be solved

**Comment by tomas-knap** [comment]
see #768
