### ISSUE TITLE
Error when using DPU template created in Pipeline

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#494]
I put SPARQL Loader DPU Template on canvas, then, in the dialog, filled some values and clicked "Save as DPU Template", first with unchanged name. Then I renamed it and clicked again. Then, when saving the pipeline, I got the following error:

![image](https://f.cloud.github.com/assets/718827/1147414/2eadb8d2-1ea4-11e3-83d6-c9d69fdc5fbf.png)

**Comment by jakubklimek** [comment]
When I clicked on Save again, i got: (I found out this is probably not related to the new DPU Template)
![image](https://f.cloud.github.com/assets/718827/1147423/af778d3a-1ea4-11e3-8922-c7ddfe0a9b72.png)

**Comment by jakubklimek** [comment]
When I removed the suspected DPU, I got:
![image](https://f.cloud.github.com/assets/718827/1147434/db10e77a-1ea4-11e3-9e9b-ac46b321770d.png)

**Comment by bogo777** [comment]
Related to #495 , new DPU Template isn't saved when created.

**Comment by bogo777** [comment]
Closed by solving #495.
