### ISSUE TITLE
When saving new DPU template from canvas, it is not visible in DPU Tree

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#495]
I put SPARQL Loader DPU Template on canvas, then, in the dialog, filled some values and clicked "Save as DPU Template". In this moment, I would expect to see my new DPU Template in the DPU Template Tree.

**Comment by bogo777** [comment]
It works for me under admin account, but not under user account. In that case, the new DPU Template isn't saved due to Access is denied on save. (Which is not shown to user, it is only in log). Will discuss with others and probably disable the button "Save as DPU template" in such case.

**Comment by jakubklimek** [comment]
No. Why would you solve it by disabling the feature? Rather solve the problem. We need this to work, that is why it is there. Obviously it is something with access rights.

**Comment by bogo777** [comment]
I didn't meant it as disabling the feature. Only in case, when user doesn't have the right to create new DPU Template(I want to discuss with others when and why this is.) I wanted to hide/disable the button. I think everything for deciding if the user has such right is known at the time of opening the DPU detail, so I would rather disable it(maybe with tooltip with information about why it is disabled) that to have user click the button and get error message.

**Comment by jakubklimek** [comment]
Ok, then yes, I agree.

**Comment by bogo777** [comment]
The result from discussion is, that the user can always create new DPU Template and there was just error in its creation(owner was not assigned).
