### ISSUE TITLE
Error when copying pipeline - limit in pipeline name

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#497]
Seems that someone limited pipeline name to 45 and the "Copy of" text of the new (copied) pipeline exceeds that? 

1) The limit shoud be much higher (2048)?
2) This should be checked better.

![image](https://f.cloud.github.com/assets/718827/1147486/d45aef0a-1ea6-11e3-9db7-d2003adaca41.png)

**Comment by tomas-knap** [comment]
Od Bohuslava: Zvedl jsem max délku na 256 znaků a přidal validátor. U komentářů jsem nastavil délku na 512. Chtěl jsem změnit i délku jména u DPU, ale to pak vypadalo blbě v DPU Tree. Poprosím Honzu o vyjádření, zda to prodloužení neovlivní výkon db, případně na jak moc by se to ještě dalo prodloužit. A ostatní, jestli má smysl mít možnost ještě delších jmen/komentářů s tím, že u DPU tree by se jména zkracovala.

**Comment by tomas-knap** [comment]
Bohuslave, for descriptions, I would remove any restriction. In terms of pipeline name, is there any performance impact for Strings above 256 chars? Or why such number?

**Comment by tomas-knap** [comment]
As also confirmed by Honza, there is no big performance loss. So the description should not be restricted, name should be longer, e.g. 2048 as proposed by Jakub

**Comment by tomas-knap** [comment]
So now the max length is 2048?

**Comment by bogo777** [comment]
Yes, it is for pipeline name, and it is unlimited for description. Requires db reset with files after 70b2600b40b299d54adbeed3e1d935e7b918599c commit.
