### ISSUE TITLE
Various layout issues (random)

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#499]
![image](https://f.cloud.github.com/assets/718827/1147563/732a9750-1ea9-11e3-95f5-f2b7ac7ac508.png)

**Comment by jakubklimek** [comment]
![image](https://f.cloud.github.com/assets/718827/1147559/61fe2c26-1ea9-11e3-8bcf-fa3a0174a65b.png)

**Comment by jakubklimek** [comment]
![image](https://f.cloud.github.com/assets/718827/1147565/92c6b224-1ea9-11e3-87e1-70d5e931bd83.png)

**Comment by jakubklimek** [comment]
![image](https://f.cloud.github.com/assets/718827/1147573/da7d175c-1ea9-11e3-9337-65827a8430a7.png)

**Comment by tomas-knap** [comment]
This could be hard to reproduce. Please leave this to the end of all high prio tasks
