### ISSUE TITLE
Test alignment of DPUs on the pipeline

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#500]
Bohuslave, 

Check if issue #496 is not your fault. 

Further, test the alighnment of DPUs - please put 7-10 DPU on the canvas, create edges between them and test the alignment. 
1. Try to allign all to the left/right/bottom/up. Undo. 
2. Take three of them, again align in all directions. Undo. 
3. Move the DPUs a bit, delete/create edges, and repeat steps 1 and 2

**Comment by tomas-knap** [comment]
Test everything on http://odcs.xrg.cz:8080/odcleanstore

**Comment by bogo777** [comment]
If the problem was with Undo -> only single DPU was moved to original position after clicking it, then it should be resolved.
