### ISSUE TITLE
Replace DPU GUI: Do I need to press Save after replace upload is done?

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#502]

**Comment by jakubklimek** [comment]
Which also means that there is no change detection there.

**Comment by bogo777** [comment]
I don't know, this part of GUI is Maria's work. Reassigning.

**Comment by skodapetr** [comment]
I thing you do not. If the replace has been successful it should save automatically. But I have new version of replace/create method prepared. There will be notification like, "replace finished successfully". And yes .. there is no way back when the replace is done. But if we want it would be just minor change to my code to allow that ie. "reload" the old version after replace.

The new version is waiting for new release to be committed and tested by you.

**Comment by kukharm** [comment]
initially did it in a way that didn't need to press Save after replace.

**Comment by tomas-knap** [comment]
So it is not needed to press save button?

**Comment by skodapetr** [comment]
Yes, you do not have to press save. The DPU template is saved automatically after replace is finished.

**Comment by tomas-knap** [comment]
Please document in confluence on the page with DPU details that you do not need to save when updating jar.

**Comment by jakubklimek** [comment]
OK, so what about the change detection and enabling/disabling save button accordingly? This should be consistent with the rest of ODCS.

**Comment by skodapetr** [comment]
To the documentation ... best to my knowledge the DPU replace is not documented at all. As this feature should not be initially supported. 
So we probably have to create the documentation for the whole replace.

**Comment by tomas-knap** [comment]
Nez upravim DPU template general, tak tlacitko save je disabled. Jakmile neco upravim a opustim textbox atd., save bude enabled. Kdyz prejdu na DPU template conf, tak je save enabled. Kdyz opoustim DPU template dialog a save je enabled, tak pokud zmenu generovala zalozka general, tak upozornim. Pokud to generovala zalozka confiuuration tak zjistim jestli se conf opravdu zmenila a kdyz jo, tak upozornim. Jinak nic.
