### ISSUE TITLE
Enable to launch DPU as a console application for debugging purpose

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#504]

**Comment by tomas-knap** [comment]
launch DPU as part of Test

**Comment by skodapetr** [comment]
I have added module-test project. It contains functionality which enable to run DPU-test as standard JUnit test. Please see SPARQL-transformer for sample test. 

If this solution is ok we should create a documentation for it.

**Comment by skodapetr** [comment]
I have added pre-alpha version (sample) into practice tutorial. We should discuss where to place this practice/theory or should we create new page "tests" ?

**Comment by tomas-knap** [comment]
Ja bych pridal proste odstavec za "Deploying the DPU bundle to ODCleanStore web application" do practise?

**Comment by skodapetr** [comment]
Přidal jsem "DPU testing" tak na to pak koukni. Není to pravda moc ukecané .. ale na druhou stranu to testovací prostředí není moc složité a pak opisovat java-doc z funkcí mi taky nepřijde záživné ke čtení.
