### ISSUE TITLE
Error when no connection to db

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#509]
When backend cannot connect to db, it writes stack trace as error. It should write error "Cannot connect to db after the number of tries defined in config.properties" And then in log.debug there could be stack trace. 

![screen shot 2013-09-16 at 4 03 15 pm](https://f.cloud.github.com/assets/3014917/1149329/221ac940-1ed9-11e3-94cb-6b5e6659ce87.png)

**Comment by tomas-knap** [comment]
backend should try to reconnect indifinitely

**Comment by skodapetr** [comment]
I update the default configuration, now backend try to reconnect indefinitely. Is this enough?

**Comment by tomas-knap** [comment]
yes, will test and close
