### ISSUE TITLE
When replacing DPU jar with invalid bundle, two error messages occurs

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#513]
![screen shot 2013-09-19 at 10 38 31 am](https://f.cloud.github.com/assets/3014917/1171459/06438f60-2107-11e3-81d4-3fd4acee1ecb.png)

Problem with file not exist is not relevant! Please test it on an invalid bundle - e.g. havin a wrong package in pom.xml of the DPU

**Comment by kukharm** [comment]
Please could you send me such file for testing? I can't reproduce the error.

**Comment by tomas-knap** [comment]
Take whatever DPU like and change pom.xml -> mainClass parameter for example. mvn install the changed dpu and test

**Comment by kukharm** [comment]
I got file extractor DPU and changed in pom.xml mainClass parameter FileExtractor to File. Then when i tried to replace file extractor jar to this new error jar, i got only one exception 
![error](https://f.cloud.github.com/assets/3471169/1202073/0fd5e01e-253f-11e3-95b2-76a6fba29cec.png)

**Comment by skodapetr** [comment]
And is there class File in this DPU, because if not .. then this is expected behaviour.

**Comment by kukharm** [comment]
i tried one more change mainClass now to "blalblabla" and got the same error, only one.
