### ISSUE TITLE
Update DPU template jar issue

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#514]
kdyz se updatuje jar, tak ukazat notice, ze update successful az dobehne progress bar, nekdy je to tak rychle, ze to neni videt. Tedy je potreba nejaka notice, ve stylu pipeline was saved succesfully

**Comment by skodapetr** [comment]
Re-assigned to me. I'm currently working on reload functionality.

**Comment by skodapetr** [comment]
I do have this notification on my computer, please test now.
