### ISSUE TITLE
Prepare methods for downloading results on SPARQL select

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#521]
please follow the specification/mockup:
https://grips.semantic-web.at/display/LOD2/Debug+Pipeline

related to #520

**Comment by tomesj** [comment]
Implemented by method - File executeSelectQuery. 
See line 1506 on https://github.com/mff-uk/intlib/blob/e7dc256658f193163450987dec604dfe5615a6f1/rdf/src/main/java/cz/cuni/mff/xrg/odcs/rdf/impl/BaseRDFRepo.java,

**Comment by tomas-knap** [comment]
https://grips.semantic-web.at/display/LOD2/Debug+Pipeline

a select query - formats are: 
N3/Turtle -  it behaves like "N3/Turtle" result format in virtuoso/sparql interface
CSV - it behaves like CSV result format in virtuoso/sparql interface

Both these options are working?

**Comment by tomesj** [comment]
N3/TURTLE format is not supported for select in openRDF.

Available formats for saving result of select query are:
XML, CSV, JSON, TSV

I add new enum as new param, when you defined your output format for select.

**Comment by tomesj** [comment]
Solved in commit c0189436561f205dfe5e8bf9f4deddcb34b4b378
