### ISSUE TITLE
Useless Method in RDF Data Unit Helper

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#525]
Method: 
    public Map<String, List<String>> executeSelectQuery(
            String selectQuery)
            throws InvalidQueryException;

is useless, you are losing information about which binding belongs to which solution of the query. Delete this method. There is alternative correct one.

**Comment by tomesj** [comment]
Do you mean delete it definitely or only interface from Data Unit Helper ? Bohuslav used  this method for select.

**Comment by tomas-knap** [comment]
Jirka but can you please test what would happen if:

Data contain triples: <pre><code> http://person1  http://foaf.org/name "1" .  http://person2  http://foaf.org/name "1" . http://person3  http://foaf.org/name "1" . http://person3  http://foaf.org/email "3@tady.cz" . </pre></code>

And the query is:

<pre><code>
select ?s ?name ?email where {
?s http://foaf.org/name ?name
OPTIONAL { ?s http://foaf.org/email ?email } }</pre></code>

So there are three persons, but only the third one has an email. Will your method work properly for the given query?

**Comment by tomesj** [comment]
When I fill then with map as result the table I get expected result:

<table border="1">
  <tr>
    <th>s</th>
    <th>name</th>
    <th>email</th>
  </tr>
  <tr>
    <td><a href="http://person1">http://person1</a></td>
    <td>1</td>
    <td></td>
  </tr>
  <tr>
    <td><a href="http://person2">http://person2</a></td>
    <td>1</td>
    <td></td>
  </tr>
  <tr>
    <td><a href="http://person3">http://person3</a></td>
    <td>1</td>
    <td>3@tady.cz</td>
  </tr>
</table>

**Comment by tomas-knap** [comment]
Jirka, this is the output of the our browser? in debug view/browse?

**Comment by tomas-knap** [comment]
If yes, then please remove the method from RDFDataUnitHelper and leave it there for Bohuslav.

**Comment by tomesj** [comment]
This is output in table - I let write content of map I get thanks select. 

OK, so I remove this method only from RDFDataUnitHelper interface.
