### ISSUE TITLE
Filters - first row in the table (Pipeline execution)

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#53]

**Comment by tomas-knap** [comment]
The basic idea would be that the first row in every table would be row with filters. It should be tested on pipeline execution table, but applicable in general

**Comment by bogo777** [comment]
This looks promising: https://github.com/tepi/FilteringTable . I will try it when more important issues are resolved.

**Comment by bogo777** [comment]
All tables now have filters in header row.
