### ISSUE TITLE
When running DPU, only LOG.INFO+ events are logged for any package used by the DPU

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#530]
I have a DPU having also different classes than the main class with execute() method. However, in these classes log.debug() is stored during normal run

**Comment by skodapetr** [comment]
Could you provide name of that DPU I do simple test with different class and it worked. 

The filter used to filter DEBUG logs should not in any means use information about log's source class.

**Comment by tomas-knap** [comment]
It was jTaggerAnnotator, I will try to reproduce when the deployment on odcs is running and assign to you

**Comment by tomas-knap** [comment]
Cannot reproduce
