### ISSUE TITLE
Generate logs from events

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#532]
Every context.message("ERROR", shortMessage,longMessage) should generate logs: 
log.error(shortMessage + longMessage).

Every context.message("WARNING", shortMessage,longMessage) should generate logs: 
log.warn(shortMessage+ longMessage)

Every context.message("INFO", shortMessage,longMessage) should generate logs: 
log.info(shortMessage+longMessage).

Every context.message("DEBUG", shortMessage,longMessage) should generate logs: 
log.debug(shortMessage + longMessage).

Every DPU start/end should generate proper log message, which is displayed red in the log viewer. IT should be logged at INFO level. Petre, please discuss if you have further ideas

**Comment by tomas-knap** [comment]
Increasing prio, this is important, currently, I have three SPARQL loaders and do not know which one is writing to log

**Comment by skodapetr** [comment]
Messages are logged in format:
12:19:16.229 [Thread-8] DEBUG c.c.x.i.b.d.e.DPUMessage - DPU '{dpu_name}' publish message short: '{short_message}' long: '{long_message}'

Also start/stop logs are generated. I also add information into backend file log about dpu do in backend's log it looks like:
2013-09-23 12:19:16,229 [Thread-8] DEBUG exec:5 dpu:4 cz.cuni.xrg.intlib.backend.dpu.event.DPUMessage - DPU 'isvzus' publish message short: '{short_msg}' long: '{long_msg}'
