### ISSUE TITLE
Store XStream objects in UTF-8

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#533]
Alternativne moznost ulozit config object k DPU template, ale to neni moc hezke

**Comment by skodapetr** [comment]
Přidal jsem logování .. tj. při serializaci se zapíše do logu serializované verze konfigurace. Tedy navrhuju .. shodnout se na DPU konfiguraci .. a porovnat výsledek. Zda jsou serializovaná data stejná, či nikoliv. Na základě tété informace bychom pak navrhli další postup.

**Comment by tomas-knap** [comment]
Petre, tak to prosim nejak zorganizuj, posli co si mame nakonfigurovat

**Comment by tomas-knap** [comment]
commons-module/src/main/java/cz/cuni/mff/xrg/odcs/commons/module/config/ConfigWrap.java

**Comment by tomas-knap** [comment]
Uncomment and test on ODCS

**Comment by tomas-knap** [comment]
Solved by adjusting locales on the server
