### ISSUE TITLE
Default configuration for DPU

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#534]
I placed DPU on the pipeline, then adjusted DPU template dialog and then try to open DPU placed on the pipeline - it failed to load conf, which is correct. Default was loaded but filled with empty text fields, although there is certain text for the proper attributes in Config class.

**Comment by skodapetr** [comment]
Now .. if the configuration is invalid "isValid == true" the message is shown but the configuration is still set to the dialog. The reason for this is that the dialog can try to use some values and prevent complete lost of the configuration. But well it the de-serialisation failed the configuration is lost == missing. 

If the configuration is missing then is used default by means of dialog default .. here we probably could use default like "new configuration". I update the code in this way.
