### ISSUE TITLE
When loading DPU, validate DPU dialog. 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#535]

**Comment by skodapetr** [comment]
What do you mean by "validate" pom.xml and DPU dialog?

**Comment by tomas-knap** [comment]
Sorry, just to validate DPU dialog. The problem is that I can upload DPU, for which there is an error when the dialog is tried to be initialized. So it would be helpfull to test to create the dialog internally when importing new DPU

**Comment by tomas-knap** [comment]
solved
