### ISSUE TITLE
SPARQL Loader freezes for bigger data

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#540]
I was loading cca 200000 triples and in the middle of the process the loader freezes, showing: 

![screen shot 2013-09-23 at 7 54 40 am](https://f.cloud.github.com/assets/3014917/1189503/1148425a-2415-11e3-90d6-3f5fd6a12b70.png)

And then nothing. But it freezes when loading triples of the type x y """content of a file""", thus, literal is long. On Friday, I was trying pipeline with chunk size 10, but it fails for the same reason. When i decrease the chunk size to 1, it worked well. So the problem is that the triples may be long. 

<b>Jirka, you were talking about a problem if the part is too big, right? E.g. for chunk size 5000+. The problem is on Virtuoso site? Do you throw any exception in this case? Or what is the behaviour if the part is too big?</b>

**Comment by tomesj** [comment]
Problem is only, when sql part has total more than 500 lines - (really is cca 1000 chunk size) it is on the Virtuoso site. In this case it is thrown exception and message about it:-)

This behavior is specific - if there is a problem with lenght, Virtuoso return it and you get an exception. 

Last I tested graph it with 600 000 triples and chunksize=500 and it was fine :-)

**Comment by tomesj** [comment]
Tell me please name of pipeline, where the problem is. I try to debug and find out, where is problem.

**Comment by tomesj** [comment]
For testing purposes, please obtain me the latest version at http://odcs.xrg.cz

Thanks.

**Comment by tomas-knap** [comment]
This does not happen any more, at least not during the loading. Will reopen if appear
