### ISSUE TITLE
Cannot connect to database error apears during the pipeline execution

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#541]
Execution started but after a while (30s), the message appears:

![screen shot 2013-09-23 at 2 08 41 pm](https://f.cloud.github.com/assets/3014917/1191130/1bff18e8-2449-11e3-88b0-334918f8426a.png)

THe execution continues further. 

Steps to reproduce: go to odcs.xrg.cz:8080/odcleanstore, select execution monitor.

**Comment by tomas-knap** [comment]
When I turned backend off, the message disappeared after reloading execution monitor. Before that, even if I reload frontend, when I open execution monitor, the message occurs

**Comment by bogo777** [comment]
Notification comes from here:
if(cause.getClass() == VirtuosoException.class && ((VirtuosoException)cause).getErrorCode() == VirtuosoException.IOERROR) {
                        Notification.show("Cannot connect to database!", "Please make sure that the database is running and properly configured.", Type.ERROR_MESSAGE);
                        return;
                    }

So there had to be VirtuosoException with error code IOERROR, which is error code which has exception when it is not possible to connect to database. But it is possibly used in other situations too, which I didn't consider. Is there anything relevant in the log?

**Comment by jakubklimek** [comment]
And during save of pipeline

![image](https://f.cloud.github.com/assets/718827/1191739/00d008bc-2457-11e3-91e3-25f1f4fccac3.png)

**Comment by tomas-knap** [comment]
Bohuslav, did you change the text for this exception from what is shown in #484 ?

**Comment by bogo777** [comment]
No, this is different exception, but I will comment out my replace until I make it more concrete, and we will see the original exception.

**Comment by tomas-knap** [comment]
So the more concrete message:

![screen shot 2013-09-24 at 10 08 13 am](https://f.cloud.github.com/assets/3014917/1198178/8d642260-24f0-11e3-8c04-89dff24f9dbc.png)

**Comment by tomas-knap** [comment]
Similar to #579

**Comment by tomas-knap** [comment]
Duplicates #579
