### ISSUE TITLE
All core DPUs should support cancel - they may be interrupted

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#542]
Consult the documentation in intlib/documentation creation of dpus. Or Petr should know. 

For SPARQL/RDF LOADER, when the dpu is cancelled, all generated data should be deleted. At least you should try to delete them. If it is not possible, end.

**Comment by tomas-knap** [comment]
SPARQL extractor cannot be reasonably cancelled, the same for RDF extractor. But in case of SPARQL loader, check how this could be implemented, so that between loading two parts, cancel flag is checked. Please also discuss whether SPARQL transformer can implement cancel between the queries specified.

**Comment by tomas-knap** [comment]
Akorat z toho commitu neni jasne kde se vola interruptException

**Comment by tomesj** [comment]
Metoda je pouze připravená, tak aby ji mohl zavolat někdo z frontendu na odpovídajícím místě v kódu. Nevím kde to tam přesně je a jak to přesně chceme, proto jsem do frontendu/GUI nešťoural. 

Tipuju, že tam bude nějaké tlačítko jako součást GUI pro přerušení PIPELINE, které po kliknutí (vyvolá událost click) a zavolá na DPU to přerušení  - tedy již tuto implementovanou metodu.

Jde tedy čistě o propojení - to bude asi buď na Bohuslava/Marii.

**Comment by tomas-knap** [comment]
Tomáš #542 - probírali jsme to, osobně bych to radši ještě probral .. neb každý zásah do commons může působit nepříjemnosti existujícím DPU .. podstatou je, že většina execution .. se koná v knihovně (RDF), tedy DPU si nemůže šahat na context.cancelled() .. tedy zvážit zda jde o dobrý případ .. a zda neposkytnout nějakou podporu? na druhou stranu se bojím, že jde o jen o náš "use-case" .. k čemuž bych nerad ohýbal prostředí více než je nutné => preferoval bych nejlépe osobní diskusi na toto téma (aby se u toho dalo kreslit a mluvit)

**Comment by tomas-knap** [comment]
Jirko, jste koukam na #542, tam to takhle resit nejde. Pro tu metodu na radku 520 v BaseRDFRepo nepresunes primo do tridy SPARQL loader? Vzdy ta je opravdu SPARQL loader specific? A pak si muzes na baseRDFRepo volat jen loadDataParts a mezi temi volani si muzes standarnim zpusobem checkovat isCancelled - jak ma Petr v dokumentaci. Nebo tam vidis nejaky problem?

**Comment by tomas-knap** [comment]
Tedy urcite tu metodu na radku 520 vyhod z baserRDFRepo (nikdo jiny nez SPARQL loader ji nepouzije) a udelej tu podporu pro cancelling standardne - budes si volat baseRDFRepo pro kazdou part kterou chces nahrat a mezitim si checkovat, jestli nahodou nejses cancelled.

**Comment by tomesj** [comment]
OK. Chápu, jak to myslíš. Přesunu to tedy co nejdřív.

**Comment by tomesj** [comment]
Počkat, co ostatní metody loadToSPARQLEndpoint s jinými počtem parametrů ? Jak to vyřešit ? Je to skoro identický kód a když to přesunu, už to nemůžu zavolat. Ještě tedy počkám.

**Comment by tomas-knap** [comment]
Jirko, tak je vyhod vsechny z baseRDFRepo, kdo chce loadovat data nekam externe na SPARQL endpoint tak necht pouzije SPARQL loader. Zkontroluj, ze se ty metody loadToSPARQLEndpoint jinde nez ze SPARQL loaderu nepouzivaji.

**Comment by tomesj** [comment]
Používá se to ještě v různých testech - např. VirtuosoTest. Mám to tedy skutečně přesunout ? Tím to zmizí jak z BaseRDFRepo, tak i z interface RDFDataUnit. Takže to vlastně obecně repozitory úplně sebereme.

**Comment by tomesj** [comment]
Navíc, koukám, že to ani moc dobře nepůjde - plno věcí privátních metod by se muselo zvěřejňovat, protože jen přesunout je nelze protože se volají na více místech a to se mi nezdá dobré. Uživatel by měl vidět jen metody repozitáře a ne už nějaké třeba metody na autentizaci, získání connection, přesouvání dat mezi jednotlivými grafy,  atp....

**Comment by tomas-knap** [comment]
Proberem ve stredu

**Comment by tomesj** [comment]
Loading to SPARQL 
- je přesunut do samostatné třídy SPARQL loader 
- cancel uděláno přes context.canceled() - testuje se po každém nahraném partu. Když nastane cancel - zahlásí, že došlo ke CANCEL, skončí loading a ukončí DPU vyhozením výjimky obsahující důvod tento cancel.
- zachovány testy v rámci RDF používající load - přesun této třídy do RDF části.

Issue hotové a připravené zavřít :-)

**Comment by tomas-knap** [comment]
Why there is second SPARQLLoader class in cz.cuni.mff.xrg.odcs.rdf.impl in RDF module? Everything could be in SPARQL loader DPU module, right? Nebo je tam nejakyproblem? Move the class to SPARQL Loader, move the tests there. For tests, you may be inspired by tests for SPARQL transformer

**Comment by tomesj** [comment]
Move SPARQL loader with its tests to SPARQL loader module :-)
