### ISSUE TITLE
Execution monitor does not take all vertical space in the browser

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#543]
![image](https://f.cloud.github.com/assets/718827/1191384/30f52b8c-2450-11e3-9563-06450fd2ca32.png)

**Comment by tomas-knap** [comment]
I know we were discussing that, is that easy to be implemented?

**Comment by bogo777** [comment]
User can set number of rows in execution table in settings and height of the split is computed in a way, that there are no unnecessary scrollbars.
