### ISSUE TITLE
DPU tree empty after exception

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#547]
DPU tree is empty after DPU template upload error.

![image](https://f.cloud.github.com/assets/718827/1191552/6ddd7a42-2453-11e3-8646-aedd0889eb38.png)

**Comment by skodapetr** [comment]
Does it work if you open the application again? Like logout, login?
How did the upload failed? Was it the "replace" upload or "new template" upload?

**Comment by jakubklimek** [comment]
I tried refreshing, that did not help. Then i refreshed the homepage and it jumped to login screen. After login it was OK. It was "new template" upload, failed with "access denied" see https://github.com/mff-uk/intlib/issues/545

**Comment by tomas-knap** [comment]
Bohuslav, in general, it happens that when there is an error in gui (like #545 for example), then GUI is behaving strange and reload in the browser or even reload of the app on the server is needed. Do you have any explanation for that?

**Comment by bogo777** [comment]
Similar problem to #769. Should be solved by same solution.

**Comment by bogo777** [comment]
Outdated, DPUTree is now initialized in enter() method.(Called each access through menu/directly by URL/browser refresh)
