### ISSUE TITLE
Make the design responsive - ugly resizing

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#548]
When I shrink the browser window, frontend does not shrink with it. Instead, really ugly multiple and useless scroll bars show up.

![image](https://f.cloud.github.com/assets/718827/1191655/8d6b16ba-2455-11e3-93b7-8498593407a4.png)

**Comment by tomas-knap** [comment]
This issue with exec monitor is solved, right?

**Comment by bogo777** [comment]
It is connected to this bug in Vaadin: http://dev.vaadin.com/ticket/6024

Current state is, that there is vertical scrollbar for the right part when Log tab is active. But when the window is resized, there is only one vertical scrollbar for whole window.

**Comment by tomas-knap** [comment]
Kubo, check if it is enough so that we can close this issue
