### ISSUE TITLE
Problem when encoding chars to URI during SPARQL loader

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#551]
Input to loader, triples:

<pre>http://odcs.xrg.cz:8899/sparql?default-graph-uri=http%3A%2F%2Flinked.opendata.cz%2Fresource%2Fodcs%2Finternal%2Fpipeline%2Fexec%2F33%2Fdpu%2F3%2Fdu%2F1&query=select+*+where+%7B%3Fs+%3Fp+%3Fo%7D&format=text%2Fhtml&timeout=0&debug=on
</pre>

But all these triples fail when SPARQL loader is executed due to: 

![screen shot 2013-09-24 at 7 09 37 am](https://f.cloud.github.com/assets/3014917/1197461/3a4d19ca-24db-11e3-8b83-8b4f143e1842.png)

Try to load these triples. It is pipeline "Decisions from nsoud" on odcs.xrg.cz

**Comment by tomas-knap** [comment]
Jirka, in case of such errors, output to the log the encoded part being inserted in the loader and being wrong!!

**Comment by tomas-knap** [comment]
Mas tam navic zpetne lomitko vzdy pred '>' u tech XML souboru vliteralu. Kde se to tam bere?

**Comment by tomesj** [comment]
Já jsem použil tabulku pro znaky, které musí být escapované, kterou posílal Jakub - viz issue #511 

<pre>The character escapes are:
\t (U+0009, tab)
\n (U+000A, linefeed)
\r (U+000D, carriage return)
\" (U+0022, double quote - only allowed inside strings)
\> (U+003E, greater than - only allowed inside URIs)
\\ (U+005C, backslash)
\uHHHH or \UHHHHHHHH for writing Unicode characters by hexadecimal codepoint where H is a single hexadecimal digit.</pre>

Znak > se tam objevuje. Neměl by tedy být escapován ?

**Comment by tomesj** [comment]
Zkoušel jsem teď vkládat, literály obsahující > do Virtuosa a skutečně není potřeba, aby byly escapované - projde to v pohodě.

Opravím to tedy v kódu a tím by to mělo být OK.

**Comment by tomas-knap** [comment]
Jirko, napis rovnou test na to, tedy zebudes mit data co nam neprochazela a ted uz budou ok. Otestuj taky prosim ty dalsi veci, tedy:

literal.getLabel().replace("\", "\\")

Tohle dela co?  Proc to tam je:
        if (label.endsWith("\"")) {
            label = label.substring(0, label.length() - 1) + "\\"";
        }

**Comment by tomesj** [comment]
Testy na toto přidám, co nejdříve.

Jinak k významu:
1) <pre><code>literal.getLabel().replace("\", "\\")</code></pre>
- escapuje všechna zpětná lomítka 

2)

<pre><code>
if (label.endsWith("\"")) {
label = label.substring(0, label.length() - 1) + "\\"";
}</code></pre>
- v případě, že literál končí znakem uvozovky ", je potřeba buď escapovat - nahradit za \", či např.přidat znak mezery na konec. Jakub byl pro escape variantu a ta je momentálně v implementaci. Jinde escapovat uvozovky potřeba není.  

1) a 2) jsou nezbytné - Virtuoso si s tím neumí jinak poradit :-)

**Comment by tomas-knap** [comment]
Zkontrolovat specifikaci SPARQL 1.1., upravit podle toho a zkusit na virtuoso a fuseki.
