### ISSUE TITLE
Scheduling: Add "Do not run when schedule is missed"

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#559]
When something is scheduled to run daily at 8AM and it is missed (for example backend not running) and then it is for example 4PM and scheduler runs, it should check whether "Do not run when schedule is missed" is not set. If it is not, the pipeline runs. If it is, it does not run and runs again next day at 8AM.

**Comment by skodapetr** [comment]
The "strict timing" should now be accessible. User can specify the tolerance and if strict timing should be used in scheduler detail dialog. 

If the schedule time is missed and the difference is greater the tolerance then the schedule is simply not executed.
