### ISSUE TITLE
Prejmenovani na odcs - dokonceni

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#560]
Co není: 

Nepřejmenovával jsem třídy ve frontnedu začínající na Intlib... zde myslím, že by obecně bylo lepší přistoupit k nějakému refraktoringu. Honza již zmiňoval použití springu ... to by také přivedlo jisté změny jenž je třeba obecněji začlenit.

Nepřejmenoval jsem Theme frontendu. 

Nepřejmenoval jsem prefixy tabulek v DB. Přeci jen už tak je úprav dost a nechtěl jsem aby update skript byl zbytečně dlouhý.

PS: pro pozorné v update skriptu jsou i sekvence kvůli eclipse-linku (snad to píši dobře) bez nich by nešlo vytvářet nové záznamy v DB

**Comment by skodapetr** [comment]
Prefixy v DB jsou upraveny, github repository přejmenován. 

Úpravy tříd a Theme pro frontned bych dal do zvláštního issue "Frontned refractoring". Tento issue bych uzavřel.
