### ISSUE TITLE
Problems with pipeline copy, than everywhere

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#562]
When trying to copy [INTLIB] Decisions from nsoud.cz pipeline at odcs.xrg.cz:8080/odcleanstore, and trying to show the newly created pipeline record (by going to the page with that record, filtering the page), I got: 

![screen shot 2013-09-30 at 3 49 08 pm](https://f.cloud.github.com/assets/3014917/1237385/3ef79ac6-29d7-11e3-91a8-d244f12322c4.png)

I cannot work with gui, because everytime the db records are loaded, this error is presented (using the pre-lazy loading from last week)

**Comment by tomas-knap** [comment]
At least a way how to remove such problem from db is needed, so that the deployment odcs.xrg.cz is running. (this is urgent) . Tedy napriklad smaz tu pipeline 14 ze vsech relevantnich mist

**Comment by janvojt** [comment]
I deleted the pipeline from DB and it is fine now. I am closing this, please reopen if you can reproduce on current version (with eclipselink).
