### ISSUE TITLE
Unused variable Schedule.name

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/odcs#564]
Variable Schedule.name is stored into DB but is not visible to the user and can not be set by user. (simply missing in dialog). On the other Hand when sending notification or logging name can be handy.

Should we remove the name, or start to use it?

If we decide to use the name then I propose following solution: 
Use generic name or give user possibility to provide the name. Or better if user provides name use provided name, otherwise use (or suggest) generic name.

**Comment by tomas-knap** [comment]
Please propose a solution here

**Comment by kukharm** [comment]
I adding new field "Scheduling rule name" to the scheduling rule creation dialog. But i can not test it works because of exception  https://github.com/mff-uk/ODCS/issues/731

**Comment by tomas-knap** [comment]
Does not relevant, see #738 for update
