### ISSUE TITLE
GUI - refactoring

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#566]
Bohuslave, mohl bys prosim mrknout na ty jednodussi veci, resp. takove, ktere maji minimalni sanci, ze ti zprasi jiz fungujici kod. Tedy napriklad ty balicky, zjednotit indentaciu (tabs/spaces), atributy v classach su niekde zamiesane az za normalne metody, podobne konstruktory, proste takove ty formalni veci - viz https://grips.semantic-web.at/display/LDM/LODMS+Coding+Guidelines

ZKusil bys to prosim do zitrejsiho meetingu? Ty balicky pak muzem pri meetingu probrat a kdyztak jeste upravit. 

Diky,

**Comment by tomas-knap** [comment]
Bohuslav, is this task done?

**Comment by bogo777** [comment]
It is done, maybe some more changes in packages should be done, but that's up for discussion or opinion of somebody other than me.
