### ISSUE TITLE
SPARQL Update which uses certain triples in input to create output

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#567]
Motivatio: I have SPARQL update - insert query, which takes certain triples from input and stores to the output. The original output is not outputted further. How could user write such query in SPARQL transformer? Basically the inserted triples should be in a output data unit but the WHERE condition in the query should work on the input data unit

**Comment by tomas-knap** [comment]
Suggested solution: Support two types of queries: 
- SPARQL Update, which behaves as now
- SPARQL Construct, which operates on input rdf data unit and writes the results to output data unit

**Comment by tomas-knap** [comment]
[10/3/13 1:28:11 PM] Tomas "nappy" Knap: Jirko, k tomu jak jsi upravoval SPARQL transformer, neprojde mi validace
[10/3/13 1:28:17 PM] Tomas "nappy" Knap: prefix lex: http://purl.org/lex# prefix frbr: http://purl.org/vocab/frbr/core# 
prefix dcterms: http://purl.org/dc/terms/ 
prefix fn: http://www.w3.org/2005/xpath-functions/#  
construct {
 ?eoz a frbr:Expression. 
 ?eoz frbr:realizationOf ?oz . 
 ?eoz dcterms:title ?oztitle . 
 ?eoz dcterms:valid ?ucinnost . 
 ?eoz dcterms:language "cs" . 
 ?y lex:definesChange [ a lex:Update ; lex:changeResult ?eoz ] . 
} 
WHERE { { SELECT (iri(fn:concat(str(?oz),'/version/cz/',str(?ucinnost))) as ?eoz) ?oz ?y ?oztitle ?ucinnost where { ?y lex:aktivni-novelizuje ?oz . ?oz dcterms:title ?oztitle . ?y dcterms:valid ?ucinnost . } } }
[10/3/13 1:28:43 PM] Tomas "nappy" Knap: tohle mi projde pres http://www.sparql.org/validate/query
[10/3/13 1:28:49 PM] Tomas "nappy" Knap: ale tvuj dialog to neulozi
[10/3/13 1:28:57 PM] Tomas "nappy" Knap: nezapomnels tam upravit validaci?

**Comment by tomesj** [comment]
Tak jsem to upravil, aby to nově bralo validaci jak update query, tak specialne navic pro construct....Upravil jsem implementaci, protože výsledkem constructu je graph,  tedy všechny jeho trojice se přidávají do grafu, který je označen jako output (contruct je provádí ještě nad inputem). 

Bohužel to nemohu u sebe vyzkoušet, jestli je to OK, protože mi od včerejška stále nejde frontend, Petrovi už jsem kvůli tomu psal.

**Comment by tomas-knap** [comment]
ok, zkusil jsi to aspon pres nejaky test, ktery otestuje ciste ty metody pro vykonavani dotazu?

**Comment by skodapetr** [comment]
Jirka: Frontend .. měl jsi stejný problém jako Tomáš tuším a ten to nakonec opravil konfigurací. Kdyžtak vyvěs klasicky issue .. neb jestli jsi psal přímo mě .. tak jsem to asi někde ztratil .. :(

**Comment by tomas-knap** [comment]
Jirko, k te tve issue, zkus undeploy, restrat tomcatu, clean & build a novy deploy

**Comment by tomesj** [comment]
K tomu testování bych potřeboval ideálně ten formulář, můžu samozřejmě zkusit přímo ten tvůj construct, ale jelikož nemám vstupní data přímo určená pro toto v dotaze, tak těžko dostanu nějaké trojice. 

Pro jiný obecný construct jsem to už zkoušel a funguje (pokud se bavíme čistě o metodě), zda to správně jde uložit a   validovat přes formulář je třeba otestovat.

Zkouším nyní zprovoznit ten frontend podle tvé rady, uvidíme, jestli to zabere :-)

**Comment by tomesj** [comment]
Tak frontend už mi funguje, díky za radu, Tome.
Jinak jsem zkoušel teď přes formulář ten construct a vše v pohodě, akorát jeho výsledkem nebylo při následném běhu pipeline nic, protože jsem neměl žádná data určená pro tento dotaz.

**Comment by tomas-knap** [comment]
Jirko, zkus prosim na http://odcs.xrg.cz:8080/odcleanstore/#!PipelineEdit/13, vytvor tam novy SPARQL transformer test DPU a dej tam to query, co jsem ti posilal. Mi to nefunguje. SPARQL transformer jsem tam novy daval.

**Comment by tomesj** [comment]
Zjistil jsem, že tam nemáš poslední verzi - upravoval jsem validaci v RDF modulu. Máš tam ještě starou verzi, proto to nejde

**Comment by tomas-knap** [comment]
?? Jak nemam posledni verzi? Jsem stahoval dnes z gitu

**Comment by tomas-knap** [comment]
A jeste mam dotaz, proc mi novy SPARQL transformer,ktery natahnu na pipeline hlasi Configuration problem?

**Comment by tomesj** [comment]
Ja totiž ve validaci následně ještě objevil jednu drobnou chybu, tu jsem opravoval někdy dnes dopoledne.

**Comment by tomas-knap** [comment]
Jirko, tenhle update mam. tedy mrkni prosim na ten odcs.xrg.cz, proc to nefunguje, Posilal jsem mail, kde jsou pristupove udaje k serveru, kde jsou logy atd.

**Comment by tomesj** [comment]
Jo, tak to by mě zajímalo taky. Vyhazuje to tuším invalidDialogException. Nic takového nikde u SPARQL transformeru nevidím...To se asi řeší na jiné úrovni, možná databáze, těžko říct.

**Comment by tomesj** [comment]
Koukám, že to máš stále stejné - tuhle chybu jsem měl totiž před opravou taky, ale teď v aktuální verzi na lokálu ji už nemám.

**Comment by tomas-knap** [comment]
Ja byc rekl, ze je problem v tom, ze query je mandatory, ale defaultne tam zadne prednastavene neni. Ale zpet k tomu puvodnimu problemu s tim construct query, zkus to prosim na odcs.xrg

**Comment by tomesj** [comment]
Na odcs.xrg se mi nejde vůbec přihlásit (předpokládám stejné přihlašovací údaje)

**Comment by tomas-knap** [comment]
admin/test funguje normalne

**Comment by tomas-knap** [comment]
Jirko, zapni si kdyztakprosim skype

**Comment by tomas-knap** [comment]
Jirka, was testing also on local, not working. Did you try the same query as above when you tested it?

**Comment by tomesj** [comment]
Yes, I tried your here given construct and it was fine.

**Comment by tomesj** [comment]
See my video: http://www.youtube.com/watch?v=bQTm832KYV4

**Comment by tomesj** [comment]
Přidal jsem i konkrétní test pro validitu,který je použit ve formuláři a ten bez problémů prochází.
