### ISSUE TITLE
RDF File formats for File Extractor

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#57]
Jirka, prepare tests (File Extractor tests) which process also files in: 
N-Triples serialization (which is a subset of turtle (TTL))
N3 serialization (which is a superset of turtler (TTL))
TriG serializaiton (which is TTL with named graphs)

At least one test per one of the serializations. N3, Trig is already in combo box of File extractor, N-Triples should be added to combo box.

**Comment by tomesj** [comment]
Solved :-)
