### ISSUE TITLE
Problems with table Namespaces

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#574]
RDF_PREFIXES koliduje s virtuoso tabulkou. Change the name

**Comment by skodapetr** [comment]
Honza has changed the table name in fb7f8f3ea24cdf7c486e4741bfb8f056c86a54b5

**Comment by tomas-knap** [comment]
Ok, tohle je nova tabulka, ktera se nikde nepouziva, takze to preziju bez
update scriptu, ale jinak prosim tyhle zmeny vzdy s update scriptem, je to
nutne pokud upravujete existujici tabulky, kde uz mam nejaka data.
