### ISSUE TITLE
c.c.m.x.o.b.p.e.PipelineRestart - Pipeline execution has been restarted

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#577]
Please add info about pipeline name and execution record id?

**Comment by skodapetr** [comment]
I have modified the logback file .. so now the stdout log is in same format as log into file. Example:
`2013-10-02 17:07:12,779 [main] INFO  exec: dpu: c.c.m.x.odcs.backend.AppEntry - Running ...`

So there is implicit information about execution and dpu .. so in my opinion we do not need to replicate this information once more.
