### ISSUE TITLE
File Extractor must throw exception if the file does not exist

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#58]
If the file does not exist, there is no error/warning. 

Solution: File Extractor must check whether the introduced file/directory exists - if not, it must throw certain event (DPU_error). If it is a directory, it must introduce a warning (not DPU_error) if the directory exists but there is no file to be processed. 

For easier validation, issued #59 should be solved first

**Comment by tomesj** [comment]
Bug fixed - throw ExtractException if path to file/directory doesnt exist.
