### ISSUE TITLE
Make refreshRow() method for LazyQueryContainer

### ISSUE THREAD

**Issue by bogo777** [mff-uk/odcs#581]
This should make refresh much faster in cases when single or only few of the rows need refreshing.

**Comment by bogo777** [comment]
After closer examination of LazyQueryContainer and Table and reading some discussions online, I changed my opinion about this. 

It would require changes directly in LQC addon. I found easier solution for refreshing when cancelling pipeline and other issues referenced here are more question of speed of loading data, which is now big problem, as described in #599.

**Comment by tomas-knap** [comment]
Bohuslav, so what is the solution you decided for? Which other issues are solved by solving this issue and can be tested?
