### ISSUE TITLE
LastStatus column values on Pipeline list should be presented with icon as in exec monitor

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#582]

**Comment by tomas-knap** [comment]
it should have also filter

**Comment by bogo777** [comment]
Icon is there, but filter is problem. This column is fully generated(execution is fetched for each pipeline and its status is extracted, it has no data representation in pipeline class) and filters on generated columns are not supported.

**Comment by tomas-knap** [comment]
Ok, lets leave it without the filter for now
