### ISSUE TITLE
Use Spring to log every thread start/stop to add possibility to debug the issues as below:

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#588]
In tomcat, I have: 

SEVERE: The web application [/odcleanstore] registered the JDBC driver [virtuoso.jdbc4.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Oct 05, 2013 1:38:00 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/odcleanstore] appears to have started a thread named [Thread-122] but has failed to stop it. This is very likely to create a memory leak.
Oct 05, 2013 1:38:00 AM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/odcleanstore] created a ThreadLocal with key of type [org.springframework.core.NamedThreadLocal](value [Request attributes]) and a value of type [org.springframework.web.context.request.ServletRequestAttributes](value [org.apache.catalina.connector.Request@7f6bfebc]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Oct 05, 2013 1:38:00 AM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/odcleanstore] created a ThreadLocal with key of type [org.springframework.core.NamedThreadLocal](value [Locale context]) and a value of type [org.springframework.context.i18n.SimpleLocaleContext](value [cs_CZ]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Oct 05, 2013 1:38:00 AM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/odcleanstore] created a ThreadLocal with key of type [org.springframework.core.NamedThreadLocal](value [Request attributes]) and a value of type [org.springframework.web.context.request.ServletRequestAttributes](value [org.apache.catalina.connector.Request@556cc8c2]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Oct 05, 2013 1:38:00 AM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/odcleanstore] created a ThreadLocal with key of type [org.springframework.core.NamedThreadLocal](value [Locale context]) and a value of type [org.springframework.context.i18n.SimpleLocaleContext](value [en_US]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Oct 05, 2013 1:38:00 AM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/odcleanstore] created a ThreadLocal with key of type [org.springframework.core.NamedThreadLocal](value [Request attributes]) and a value of type [org.springframework.web.context.request.ServletRequestAttributes](value [org.apache.catalina.connector.Request@b2129ff]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Oct 05, 2013 1:38:00 AM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/odcleanstore] created a ThreadLocal with key of type [org.springframework.core.NamedThreadLocal](value [Locale context]) and a value of type [org.springframework.context.i18n.SimpleLocaleContext](value [en_US]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Oct 05, 2013 1:38:00 AM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["http-bio-8080"]
Oct 05, 2013 1:38:00 AM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["ajp-bio-8009"]
Oct 05, 2013 1:38:00 AM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["http-bio-8080"]
Oct 05, 2013 1:38:00 AM org.apache.coyote.AbstractProtocol destroy

**Comment by janvojt** [comment]
I do not understand what is requested here, can you elaborate?

**Comment by tomas-knap** [comment]
The problem is that certain threads are not properly ended, they survive the main odcleanstore app. So the idea was to log when certain threads were started, finished. Petr said Spring could log that as he is creating the beans.

**Comment by tomas-knap** [comment]
not needed
