### ISSUE TITLE
File Extractor - adjust dialog according to mockup

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#59]
Adjust the interface of the File Extractor as depicted in 
https://grips.semantic-web.at/display/LOD2/DPU+-+Extractor+from+RDF+File

Reason: It is easier for the user to realize what he can input in the fields. Also the validation may be done easier. 

Main changes:
- one field having more functionality is divided to three
- there is extra possibility to upload file

When ready, assign Jirka to adjust the implementation for the DPU.

**Comment by tomas-knap** [comment]
Jirko, please adjust the File Extractor based on the adjusted gui. And test that the choices can be saved, checkbox is working.

Pak jeste prehod tenhle ukol na Marii:
Ahoj, koukal jsem na to, ten vyber moznosti muze byt i tak jak to mas (uprav prosim mockup), akorat tam prosim jeste pridelej podobne jako u SPARQL extractoru zalozku details, kam das "use statistical handler" checkbox. Zbytek nech na zalozce "Core". Da se totiz ocekavat, ze casem pribudou i dalsi moznosti. Uprav prosim i v mockupu.

**Comment by tomesj** [comment]
Funcionality of file_extractor wasn´t change by adding/split 3 types of path. Maria can add Statistacal Handler to mockup :-) 
I can write tests for all 3 types during afternoon tomorrow.

**Comment by tomas-knap** [comment]
Jirka, just check that all options of the extractor are tested. In case of HTTP URI, you may skip the automated test, but check that it is working.

**Comment by tomesj** [comment]
All try all possibilities - problem were only with upload file - fixed. All is working :-)
