### ISSUE TITLE
Problem when opening gui in second tab

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#595]
![screen shot 2013-10-06 at 5 09 38 pm](https://f.cloud.github.com/assets/3014917/1276859/6c8ea01c-2e99-11e3-9a80-4b64dea5383f.png)

**Comment by bogo777** [comment]
How you created this? Open in new tab doesn't work for me in Vaadin(as it is all buttons and not links) and if I open same address in different tab, I must log in again, but it works for me fine.

**Comment by tomas-knap** [comment]
Aha, I also create a new tab and entered address (http://odcs.xrg.cz:8080/odcleanstore/#!PipelineList). No new logging was needed, but it behaved strange. Honza has also experienced this issue, ask him for details as well.

**Comment by bogo777** [comment]
Multiple tabs should be supported in Vaadin7. When I open the second tab, the first one stops responding -> loading circle appears and nothing works anymore.
Only this is in the log:
14:44:25.074 [http-bio-8084-exec-24] DEBUG r.x.v.SpringUIProvider - found BEAN_NAME_PARAMETER: ui
14:44:25.074 [http-bio-8084-exec-24] DEBUG r.x.v.SpringUIProvider - found BEAN_NAME_PARAMETER: ui
14:44:25.542 [http-bio-8084-exec-26] DEBUG r.x.v.SpringUIProvider - found BEAN_NAME_PARAMETER: ui
14:44:25.542 [http-bio-8084-exec-26] DEBUG r.x.v.SpringUIProvider - found BEAN_NAME_PARAMETER: ui

When I open second tab on login page and log in again, I have 2 working tabs. I will investigate this further.

@janvojt What is your experience? Any ideas?

**Comment by bogo777** [comment]
Removing PushHandler helped with multiple tabs. Now it works for me most of the time, but occasionaly the widgetset problem(from the original comment) appears.

**Comment by tomas-knap** [comment]
According to the error message, it seems that some Proxy widget is trying to be created but not available, com.sun.proxy.Proxy is from Spring.

**Comment by bogo777** [comment]
http://blog.oio.de/2013/02/22/vaadins-variable-scopes-vaadinsession-and-ui/

We force UI to be session scope via spring, which is not how it should work.
