### ISSUE TITLE
Execution monitor date is counting even when the pipeline finishes

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#596]
I run the pipeline, then open the detail from the execution monitor. As the detail (show log) was opened, the timestamp in execution monitor was increasing but the pipeline was already finished. 

![screen shot 2013-10-07 at 12 01 07 am](https://f.cloud.github.com/assets/3014917/1277617/0d0de000-2ed3-11e3-9de3-d87cb6f47876.png)

![screen shot 2013-10-07 at 12 01 20 am](https://f.cloud.github.com/assets/3014917/1277618/12930730-2ed3-11e3-8e7b-109932f75c5e.png)

**Comment by skodapetr** [comment]
Could you please provide information about the last Event for this pipeline?

**Comment by tomas-knap** [comment]
Last was SPARQL loader finished, it was the last loader

**Comment by bogo777** [comment]
Sorry, it was remainder from some  testing I did. It was fixed by commit https://github.com/mff-uk/intlib/commit/36ff5503655468945ac9b838a7438eb2b824ae5f
