### ISSUE TITLE
Variation on cannot connect to DB but initiated from DPUs

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#597]
As a resutl execution fails, but when checking DB, it seems to be running, so probably it just did not respond in certain time. 

Solution: The error below should NOT occur. BaseRDFRepo should catch such exception and try to reconnect based on config.properties settings (how many times the engine should try to reconnect). If the connection to db fails after X attempts (as defined in config.properties), runtime exception should be thrown. 

![screen shot 2013-10-07 at 7 57 27 am](https://f.cloud.github.com/assets/3014917/1278468/a0861ec8-2f15-11e3-9625-2ebf4c8e435f.png)

**Comment by tomas-knap** [comment]
What is even worse is that pipeline is not cleaned up, the status is not properly set (it remains in the running status) , it finishes immediately.

**Comment by tomesj** [comment]
Your problem is using JDBC version 4 for RDF. In this case connection to Virtuoso always fail. 

You have use JDBC version 3.

**Comment by tomas-knap** [comment]
But why is it using JDBC4?

**Comment by tomesj** [comment]
I see in your given log that all caused by parts are same like:

virtuoso.jdbc4.VirtuosoException......You use JDBC version 4

If you use version 3 you get something like:
virtuoso.jdbc3.VirtuosoException......

But version 3 dont cause problems in contrast version 4.

**Comment by tomas-knap** [comment]
But why is it using JDBC4? That must be written incorrectly in dependencies of the RDF module?

**Comment by tomas-knap** [comment]
JIrka?

**Comment by tomesj** [comment]
I dont know. I have in my RDF module version 3. Honza use version 4. Maybe somewhere a conflict.

**Comment by tomas-knap** [comment]
Jirka, can you please launch once again your test where you were trying to load 7 milions of triples? And write the result here, I am curious if it will finish succesfully, betting that it will fail

**Comment by tomesj** [comment]
OK. I tested it and write here the result :-)

**Comment by tomesj** [comment]
So loading 7 millions triples to SPARQL endpoint finish sucesscully.

**Comment by tomas-knap** [comment]
Problem with too many connections, solved by the pool
