### ISSUE TITLE
Method for obtaining list of graphs from virtuoso with odcs prefix

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#598]
Ask Petr for details

**Comment by tomas-knap** [comment]
Only those begining with prefix for odcs/execution

**Comment by tomesj** [comment]
Have done - prepared to close.

**Comment by tomas-knap** [comment]
Maria, please prepare a new tab in settings called "Delete debug resources". The tab will contain the component as in the mockup https://grips.semantic-web.at/display/LOD2/Delete+debug+resources

When clicking on "Clean", Jirka's method cleansing the graphs should be called (ask Honza/Petr how to call it)

**Comment by tomas-knap** [comment]
So is it ready for testing?

**Comment by tomas-knap** [comment]
Did you test that at least once? If not, test before me

**Comment by tomas-knap** [comment]
Ask Jirka which method should be callled
RDFDataUnit -> method clearApplicaionGraph()

**Comment by tomas-knap** [comment]
Jirka zkusi

**Comment by tomesj** [comment]
K mazání grafů Virtuosa
- přidána obsluha události k tlačítku pro mazání grafů aplikace v položce Settings 
- po kliknutí smaže všechny grafy používané v aplikaci.
- dá výslednou zprávu o tom jak to dopadlo v podobě notifikace
- funkcionalia též úspěšně otestována

Hotovo a připraveno zavřít :-)

**Comment by tomas-knap** [comment]
The deleting of the debug named graphs in virtuoso could take tens of minutes. I would suggest that when the user clicks on "delete button", message like: "Datum: Task for deleting the graphs was planned.". Backend by to spustil, provedl a az by bylo hotovo, tak by frontend pouze zobrazil hlasku "Datum: Task for deleting the graphs was finished successfully, 10 named graphs was deleted" 

It should work in the same way as deleting old logs, but when requested, it is planned immediately. 

@skodape , please discuss here.

**Comment by skodapetr** [comment]
I do not know how to easily archive this unfortunately. We only directional communication channel from Frontend to Backend now. 

On the other hand .. we can use special thread in Frontend for this. Assume that this is not commonly called function. Neb, bych čekla, že tohle bude výpočetně náročné spíše pro virtuoso a naše aplikace čeká?

**Comment by tomas-knap** [comment]
yes, could be also. But the current situation were I have to wait actively is not good

**Comment by skodapetr** [comment]
Yes the waiting is really bad .. we can have some static "storage" .. at the user request start the thread .. set flag in storage to "executing" .. disable button and show this message. User can work .. see other pages .. and when pruning ends we can show this information in the "pruning  view" that the operation is done .. 

or try to show some notification .. but still the notification will be surprise as I might be doing something else and suddenly .. also I can click on it before I read it as I do not expect is

**Comment by tomas-knap** [comment]
Petre, udelal bys tedy prosim to vlakno ve frontendu? Zaukoluj kdyztak marii/bohuslava, aby ti upravil GUI hlasky, pokud potrebujes
