### ISSUE TITLE
Opening execution log takes long time, it does not end in a minute

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#599]
![screen shot 2013-10-07 at 11 20 21 am](https://f.cloud.github.com/assets/3014917/1279227/d12ab3c4-2f31-11e3-86e3-33fc005577bc.png)

To reproduce: odcs.xrg.cz, pipeline ARES 900 in exec monitor, clicki in exec monitor

Add logging to your code if needed to reveal where the problem is

**Comment by tomas-knap** [comment]
could be related to/caused by #594 #597

**Comment by tomas-knap** [comment]
Problem was also when restarting db/backend. Bohuslav, could you pls check which particalar data are loaded when logs are shown? When having fresh install, it works fine, but as more data is logged it becomes really slower and slower which should not happen, at least not that much.

Probably you should add more logs at debug/trace level to find out which part takes most of the time and then try to look at the queries/which data are loaded from db

**Comment by bogo777** [comment]
It looks like all records/logs/events are loaded. There is setting of maxResults in code, but the resulting query has no limitation.
For example:
SELECT ID, full_message, short_message, r_time, r_type, dpu_id, execution_id FROM exec_record ORDER BY r_time ASC

And it also looks like all references are eager loaded, but I will study that some more.

**Comment by tomas-knap** [comment]
Bohuslav, do you know how to solve this?

**Comment by tomas-knap** [comment]
This issue is crucial as you wrote, because with this issue, logs cannot be used after a while because they simply do not load. Will you please find time tomorrow to work on that?

**Comment by bogo777** [comment]
I think that problem is in EclipseLink or our usage of it. When we used Hibernate, queries were limited to page size and there were no changes in container regarding this. My guess is, that in translating EclipseLink to virtuoso via dialect, max result size is omitted, because it is set to the Query object, but it doesn' t appear in the actual SQL query. @janvojt should know more about it.

**Comment by tomas-knap** [comment]
Honza, please advice Bohuslav. This is urgent, please look on that asap
