### ISSUE TITLE
Adding support for user as owner

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#601]
[10/7/13 4:46:39 PM] Jakub Klímek: predtim to bylo v /data/odcs/backend/working/dpu/user/....
[10/7/13 4:46:58 PM] Jakub Klímek: ted je to v /data/odcs/backend/working/user/default/...

Please reassign if you do not know

**Comment by skodapetr** [comment]
Unfortunately PipelineExecution does not support User as Owner yet. "default" user is used when user for PipelineExecution is null.
Adding support for user ie. assign user to execution should solve this.

**Comment by skodapetr** [comment]
I have this functionality already implemented. 
As it changes database I will commit this on Friday together with possibly "big database renaming".
