### ISSUE TITLE
Events in log may not be sorted properly

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#607]
If more events occur in the same second as below, they may be sorted incorrectly (Loader start is later than Loader body). They should be by default sorted according to their event id.

![screen shot 2013-10-09 at 10 57 58 pm](https://f.cloud.github.com/assets/3014917/1301634/ae800e64-3125-11e3-87dd-26edce7fffc4.png)

**Comment by bogo777** [comment]
Acutally, it didn't help. I think problem is with logging in backend:
![image](https://f.cloud.github.com/assets/1550848/1315918/4ae998f2-328d-11e3-9d57-9dd5a98af8a8.png)
There are logs from Loader execution with earlier date than Loader start

**Comment by tomas-knap** [comment]
Ok, than please remove the sort, so that we do not slow down the logs further

**Comment by skodapetr** [comment]
What exactly is the problem? And where is the body? 
The code before start log is actually a preparation .. the start finished is used to restrict the area where user code is running. Do I miss something as the logs above seems fine to me .. 

Should we have another log that say .. the preparation start .. and user code par start? 
(reassigned to me, as it is really more on backend' logging then anything else .

**Comment by tomas-knap** [comment]
It is fine, closing
