### ISSUE TITLE
Canvas improvement - dpu layout formatting

### ISSUE THREAD

**Issue by bogo777** [mff-uk/odcs#61]
Possibility to select multiple DPUs and perform selected formatting action on them. Formatting actions:

align top - DPUs are aligned to the highest selected DPU
align bottom  - DPUs are aligned to the lowest selected DPU
align left - DPUs are aligned to the most left selected DPU
align right - DPUs are aligned to the most right selected DPU
distribution horizontal - horizontal space between DPUs is same for all selected DPUs
distribution vertical - vertical space between DPUs is same for all selected DPUs

**Comment by bogo777** [comment]
Current version has asked functions, but I would like to make selecting DPUs easier. Also displaying of action bar for formatting could be nicer. I will appreciate any ideas.

**Comment by tomas-knap** [comment]
K možnosti alignování a rovnoměrné distribuce DPU na canvasu:
Je zde nová ikonka na DPU -> DPU layout formatting, která zapíná režim multiselect. Vybraná DPU mají tučnější okraje, vybírají se kliknutím. Zároveň se při najetí na DPU zobrazí menu s možnostmi zarovnání. Opět prosím o vyzkoušení a případné nápady k vylepšení, zejména způsobu zobrazování toho menu. Opět nejlépe k issue. Multiselect mód se ruší kliknutím na prázdné místo na canvasu.

**Comment by tomas-knap** [comment]
Test that

**Comment by tomas-knap** [comment]
It is not that intuitive, let's discuss that on the next f2f meeting. I would like much more, if I could select the DPUs with mouse in a similar way as more icons on the desktop. that right clicking, having context menu. But let's discuss that on the meeting

**Comment by tomas-knap** [comment]
![screen shot 2013-08-15 at 2 06 22 pm](https://f.cloud.github.com/assets/3014917/968486/3e69ff5c-05a3-11e3-82c3-84dbfc4a1d0f.png)

Align left

**Comment by bogo777** [comment]
Selecting the DPUs with mouse in a similar way as more icons on the desktop should be possible, but it would require some additional work, I can only guess that about half a day. Easier solution could be the one, when selection happens when CTRL key is held. As for right click and context menu, this is web application, and I do not know about any way how to make this.

But I agree that current appearence of menu is not nice, I just haven't figured out, how to make it better.

**Comment by tomas-knap** [comment]
Test if it is ok for the use

**Comment by tomas-knap** [comment]
It would be nicer to have the dpu layoting controls (the arrows + horizont/vertical distribut) next to zoomin controls. When at least two DPUs are selected (by using left click + CTRL), the layouting controls become available. When less then two DPUs are selected, the layouting controls are again greyed.
