### ISSUE TITLE
zoom in, zoom out, under buttons intersect with the buttons panel of pipeline

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#612]
When i add new DPU template to the tree in Editing Pipeline section and tree becomes longer then the buttons under the tree (zoom in, zoom out, under) intersect with the buttons panel 
![tree](https://f.cloud.github.com/assets/3471169/1306305/afc0e112-31ad-11e3-84e9-451f06b7d364.jpg)

**Comment by bogo777** [comment]
Let's discuss this with @tomas-knap .

My idea:
Use icons instead of button labels. 
a) Add buttons to the panel with Save/Close buttons in the bottom part of page
b) Create new panel for those buttons in top-right corner
c) leave them under the DPU tree, but just as one row with icon buttons

**Comment by tomas-knap** [comment]
Yes, icons are definitely better. 

I would prefer top-right corner of the canvas, but it should be always visible, as in case of DPU tree, so it should be moving when the canvas is moved. What do you think?
