### ISSUE TITLE
pipeline edge

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#613]
When i click on a pipeline edge sometimes i get Edge detail dialog and sometimes toolbar with Set name and Remove icons, on what it depends? In which cases appears each of this two elements?

**Comment by bogo777** [comment]
When edge detail dialog appears, it is because you clicked on the edge description(eg. input -> output), The text's control is in fact rectangle, so it can be clicked, even when it is not directly on the text. When clicking edge or near the edge, toolbar should appear.

**Comment by kukharm** [comment]
Thank you for explanation. I think there some problem. When i click  in the place where the red dot in the picture
![edge](https://f.cloud.github.com/assets/3471169/1307031/3475b2f6-31b9-11e3-8c11-1ec390ea5e8f.jpg)
i expect to get toolbar but i get Edge detail dialog. Maby todo this rectangle smaller or open Edge detail dialog by double click?
Now I get by experience that toolbar appear only if i click right on edge or above near the edge.
