### ISSUE TITLE
Debug message of pipeline execution

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#619]
Current debug message: DEBUG exec:10130 dpu:14 c.c.m.xrg.odcs.commons.dpu.DPU - 1261

Please add also name of dpu and name of pipeline.

**Comment by skodapetr** [comment]
I can easily do this .. but there is a drawback .. the name of DPU and pipeline will be saved into DB. 

I believe that we can prevent this by proper modification of VirtuosoAppender. But I would like to know Jan's opinion before I change his code.

As alternative solution I can log pipeline name and DPU name .. in separate log message at start of respective execution.

Also we should keep in mind .. that this log is not meant to be used by user as there is direct access from ODCS's Frontned.

**Comment by tomas-knap** [comment]
yes, I will postpone this issue. Maybe it would be enough to show somewhere the DPU ids in frontend? Not nice but useful for debugging.

**Comment by skodapetr** [comment]
or as I mention log something like:
DEBUG exec:10130 dpu: c.c.m.xrg.odcs.backend.execution - starting pipeline id 10130 = "AB"
....
DEBUG exec:10130 dpu:34 c.c.m.xrg.odcs.backend.execution - starting dpu id 34 = "XZ"

So user can get the names from reading the log .. it's cheap quick partial-solution as I understand that this information can make reading logs much more easier .. witch the patter "id = name" .. you can also easily find name for given id.

**Comment by tomas-knap** [comment]
Ok, let's go for this cheap solution.

**Comment by skodapetr** [comment]
Done, I decrease priority to normal as we have partial solution now.

**Comment by skodapetr** [comment]
I have added DPU name to the thread name .. to log then looks like:
`2013-10-25 21:05:30,563 [dpu: PASS Transformer 4] INFO  exec:103 dpu:106 c.cuni.mff.xrg.odcs.backend.execution.dpu.Executor`

Do we want this "feature" ? I'm no sure if it can cause problem with too long DPU name but I didn't find any documented restriction for Thread's name.

**Comment by tomas-knap** [comment]
should be fine, ok, great
