### ISSUE TITLE
Query validator not working

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#623]
I think the query should be OK

![image](https://f.cloud.github.com/assets/718827/1314843/2668c2ec-327d-11e3-9e0b-29f220bff429.png)

**Comment by tomesj** [comment]
Problem is, that query
SELECT count(*) WHERE {?x ?y ?z} 

is not valid via using oficial SPARQL validator. 

See and can try on:
http://sparql.org/query-validator.html

But if you used for validation possible "SPARQL extended syntax" - it is OK. 

I try to see possibilities in my code - if there is possible to set exteded syntax here, or not. 
In worst case we have to seach another variant to solve this.

**Comment by tomesj** [comment]
In code is not possible how to set SPARQL extended syntax. 

I just implemented method for testing this case manually.

**Comment by tomas-knap** [comment]
Jirka, why did you create special validation method? The standard validator does not validate COUNT correctly?

**Comment by tomesj** [comment]
Yes - read my previous comments.

**Comment by tomas-knap** [comment]
Well, what is involved in the extended syntax? What is involved in core? is that documented on the validator's page?  If the extended syntax satisfies with SPARQL 1.1 syntax, then I will use extended everywhere

**Comment by tomas-knap** [comment]
Having method "SPARQLCountValidator" is strange, I would expect ideally one validation method or two at most, but named correspondingly

**Comment by tomesj** [comment]
By SPARQL 1.1 defined on page http://www.w3.org/TR/sparql11-query/#aggregates could be COUNT syntax supported, but openRDF use same validator as http://sparql.org/query-validator.html and this query passed only with set SPARQL EXTENDED SYNTAX, standard using SPARQL syntax dont passed. If I have written yet, there is no possible how to set this in code.

**Comment by tomas-knap** [comment]
Ok, but is this SPARQL EXTENDED SYNTAX covering exactly what is described in SPARQL 1.1., or is it a superset/subset, or is it overlapping with SPARQL 1.1.?

**Comment by tomas-knap** [comment]
Jirka?

**Comment by tomesj** [comment]
From what I have read, SPARQL EXTENDED SYNTAX is superset of SPARQL 1.1. (it is SPARQL 1.1 with extensions). But I never found an official documentation that confirmed it for me.

**Comment by tomas-knap** [comment]
Can you please point me where such info is written? Thanks!

**Comment by tomesj** [comment]
SPARQL syntax
1] http://www.w3.org/TR/sparql11-query/#sparqlSyntax

COUNT - (as agregate function)
1] http://www.w3.org/TR/sparql11-query/#aggregates
2] http://www.w3.org/TR/sparql11-entailment/#aggregates

"Aggregates defined in version 1.1 of SPARQL are COUNT, SUM, MIN, MAX, AVG, GROUP_CONCAT, and SAMPLE."

After this could be syntax supported but why when I try SPARQL 1.1 validator on http://sparql.org/query-validator.html. It is supported only with extended syntax => it must be superset of SPARQL syntax.

**Comment by tomas-knap** [comment]
Ok, but COUNT, SUM, MIN, can be used normally according to SPARQL 1.1, so I think you can have just one validation, which is validating according to extended syntax? But before that, it would be good if you try to contact the authors of sparql.org/query-validator to check that extended syntax is equivalent of subset of SPARQL 1.1

**Comment by tomesj** [comment]
Problem solved using RDF version 2.7.7 - SPARQL 1.1 syntax validation. See #729
