### ISSUE TITLE
SHow named graphs relevant for the given execution

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#627]
In Browse/query tab, when certain data unit is selected, named graph relevant for the given execution should be shown (just as a label). It could be shown under the data unit combo box. If the data unit is changed, the named graph has to change as well

**Comment by tomas-knap** [comment]
related to #520

**Comment by bogo777** [comment]
@skodape Is there a way, how to get this information(graph) from DataUnitInfo? Or combination of DataUnitInfo and ExecutionContextReader? I couldn't find any. If not, can you please add it?

**Comment by skodapetr** [comment]
Well I can move DataUnitFactory from Backend to commons-app. Then you can simply use it to crate (instantiate) DataUnits for given DataUnitsInfo + dpuInstance .. 

Or we can use concept of browsers .. I don't know if it still alive? And I can add code that create RDFDataUnit into the RDFBrowser. 

Personally I prefer the second approach it will also probably reduce your work load a little.

**Comment by bogo777** [comment]
Well I need only name of the graph, to show as a label, it should already exist, I think it is meant for use in query.

**Comment by skodapetr** [comment]
In such case please try DataUnitInfo.getName for "user given name" - probably what you want ?

If you need url .. (which is constructed by ODCS) then:

String id = context.generateDataUnitId(dpuInstance, index); // where index if from DataUnitInfo and context is Execution context info
String graphUrl = GraphUrl.translateDataUnitId(id);

Is this what you are ask for?

**Comment by bogo777** [comment]
Thanks, that is what I needed, the url case.
