### ISSUE TITLE
Refresh automatically checkbox from debug view sometimes dissapears completely for a running pipeline

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#628]

**Comment by tomas-knap** [comment]
When user logs again, it is working, checkbox is there

**Comment by bogo777** [comment]
I came across this when using rerun/redebug from execution monitor. Or if I had detail of finished pipeline opened and switched to running pipeline. Was it that case? Or did it dissappear while watching the running execution detail?

**Comment by tomas-knap** [comment]
Oh, did not know now. Do you know where the problem might be?

**Comment by bogo777** [comment]
I repaired it for the cases I asked about, just don't know if the original problem was the same case.

**Comment by tomas-knap** [comment]
We will reopen if reappears
