### ISSUE TITLE
DPU layout formatting

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#631]
Please explain how works DPU layout formatting tool on DPU instance? I click on icon get rows, but when i click on this rows nothing changes.

**Comment by bogo777** [comment]
Only selected DPUs are formatted. 

To select first DPU, simply click on it. 
To select more DPUs, either click on "DPU layout formatting" icon on toolbar and then click on other DPUs, or hold CTRL key and click on other DPUs.
When mouse is over selected DPU, formatting action bar appears.
Arrow icons are for aligning DPUs.
Distribute icons are for creating same gaps between selected DPUs in given direction.

**Comment by kukharm** [comment]
Thank you, now I understand how it works
