### ISSUE TITLE
Bottom part of DPU tree cannot be shown

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#633]
THERE IS no way how to see the lower part of DPU tree. Which suggestion do you have to solve this?

When opening pipeline:
![screen shot 2013-10-13 at 10 00 00 am](https://f.cloud.github.com/assets/3014917/1321628/81450b1a-33dd-11e3-941f-e3aacc3b0faf.png)

When scrolling down
![screen shot 2013-10-13 at 10 00 06 am](https://f.cloud.github.com/assets/3014917/1321629/84135e1e-33dd-11e3-9c35-9f0d5eea7116.png)

**Comment by bogo777** [comment]
For now, I changed DPU tree to stay at the top of canvas, so it should be accessible by scrolling the main window. There should be a way to set its position dynamically through javacript, just have to get it working with Vaadin. Ultimately, there should propably be scrollbar inside dpu tree, as it can be higher than whole window.

**Comment by tomas-knap** [comment]
There is always scrollbar or never - needs to be solved
