### ISSUE TITLE
Wrap RDF query in class and provide method to add filters to it.

### ISSUE THREAD

**Issue by bogo777** [mff-uk/odcs#638]
For filtering RDF data in Browse/Query tab in result table, possibility to add filter to original query is needed.

From Tomas:
Regarding 3, you should call addFilter or something like that and Jirka should provide the implementation of the method. We need to discuss that with Jirka, please create issue for that.

For me, the best would be, if I would have object which wraps the query, and method addFilter(String columnName, String substring), which adds the corresponding filter to the original query.

It's related to #520.

**Comment by bogo777** [comment]
Motivace:  Filtrování záznamů v tabulce 
Řekněme, že máme RDF query místo stringu reprezentovanou nějakým wrapper objectem. Ten bude mít metodu addFilter(String filter, String columnName), která do původního stringu query, do části WHERE doplní něco jako FILTER regex(str(?columnName),filter,'i') ,aby bylo možné výsledky filtrovat. Výsledek bude třeba 

CONSTRUCT {?s ?p ?o} WHERE { ?s ?p ?o  
FILTER regex(str(?s), "Prague", 'i')  
}

Takhle bych si to představoval. Abych ve frontendu nemusel modifikovat přímo string, ale mohl jen volat metody na objektu, který ji reprezentuje.

**Comment by tomesj** [comment]
Tak jsem ti udělal myslím dost hezkou věc - QueryFilterManager:
Uděláš si novou instanci - dáš tomu původní query a pak si přidáváš/odebíráš filtry dle libosti...

Máš tak metody jako
addFilter(), removeFilter(), getFilters(), ... vše by melo byt intuitivní - případnš stačí kouknout na komentáře

Důležité jsou metody: 
getFilteredQuery()  - vrací transformované query - aplikace postupně přes všechny zadané filtry.
getOriginalQuery() - vraci původní query bez použití filtrů. 

Příklad použití kódu:

<pre><code>
String query = "CONSTRUCT {?s ?p ?o} where {?s ?p ?o} LIMIT 100";
        QueryFilterManager manager=new QueryFilterManager(query);
        
        QueryFilter filterOne=new RegexFilter("s", "Prague");
        QueryFilter filterTwo=new RegexFilter("o", "Object");
        
        manager.addFilter(filterOne);
        manager.addFilter(filterTwo);
        
        //manager.removeFilter(filterOne);
        
        String filteredQuery = manager.getFilteredQuery();
</code></pre>

Výpis filteredQuery dá tento (očekávaný) výsledek:

<pre><code>
CONSTRUCT {?s ?p ?o} where {?s ?p ?o FILTER regex(str(?s),"Prague", 'i') FILTER regex(str(?o),"Object", 'i')} LIMIT 100
</code></pre>

**Comment by bogo777** [comment]
Vypadá to dobře, ale bohužel to nefunguje. Přidám filtr do FilterManageru, ale vrátí mi to původní query. Selže tam matcher v applyFilterToQuery()

Matcher matcher = getMatcher(originalQuery);
String resultQuery = originalQuery;
boolean hasResult = matcher.find();

Tak ten hasResult je false hned napoprvé a nikam se tam ten filtr nepřidá. Původní query byla: CONSTRUCT {?s ?p ?o} WHERE {?s ?p ?o}

**Comment by tomesj** [comment]
Tak jsem zkoušel stejný dotaz u sebe a normálně mi to šlape jak má....

Dáváš argumenty v rámci konstruktoru RegexpFilter bez otazníku ?. Na velikosti by přitom nemělo záležet. Navíc filtry to jenom přidá, pokud se ten název shoduje s where částí tedy pro 

CONSTRUCT {?s ?p ?o} WHERE {?s ?p ?o}

TO jde pro např pro. 
new RegexFilter("s", "Subject");
new RegexFilter("p", "Predicate");
new RegexFilter("o", "Object");

Ale pro 
new RegexFilter("x", "Object"); // to neudělá nic, protože x není ve where.

Zkus to prosím ještě jednou a dej vědět.

**Comment by bogo777** [comment]
Pro SELECT mi to funguje správně. U CONSTRUCTu jsem si neuvědomil, že ať se v té query zadá cokoliv, tak výsledek jsou trojice s subject, predicate, object.(Což je správně) Jen je pak problém to zjištění správného filtru, protože já nemám ty původní názvy sloupců a jejich namapování na trojici. Myslíš, že bys to dokázal odvodit ty? Předpokládám, že se to dělá z pořadí proměnných v CONSTRUCTu. 

Napadají mě 2 možnosti:
a) přes nějaký objekt položím dotaz getColumnName("subject") a dostanu původní sloupec, se kterým sestrojím filtr.
b) v rámci filtru detekuješ, že jde o CONSTRUCT query a to namapování provedeš automaticky tj. já vytvořím RegexFilter("subject", "Prague") , ale ve skutečnosti to přidá filtr pro ten sloupec, ze kterého se subject teprve stane(třeba ?s)

**Comment by tomesj** [comment]
U constructu jsou vždycky trojice, to ano, ale ty mohou být už předvyplněné, např:

Construct {&lt;http://a&gt; &lt;http://b&gt; ?o } where {&lt;http://c&gt; &lt;http://d&gt; ?o }

Co by potom mělo vracet např. getColumnName("subject") - &lt;http://a&gt; nebo &lt;http://c&gt; ?
Jak se se to mělo pak řešit ?

Je jasné, že to omezení, by se mělo týkat pouze proměnných, jinak to nemá asi moc smysl (což aktuální filtr přesně má, jen je třeba znát jméno té proměnné).....Zbytek jsou nějaké pevné konstanty a ty už filtrovat nemá smysl :-)

**Comment by tomesj** [comment]
Navíc to pořadí nelze ani tak jednoznačně určovat, protože např.

CONSTRUCT {?s ?p ?o } where {?o ?s ?p}

Potom to neodpovídá - např. proměnná ?o jako subject v původních datech (v části where) je v nových trojicích objectem....Ty ale můžeš přidat filtr jen do části where...Ale data se ti pak zobrazují podle té části popsané v contruct. Tedy ty chceš omezit subject, ale omezíš si vlastně object (v tomto případě) a to je špatně....

Proto nějaké mapování nemá smysl - nedá se to pro filtrování udělat, navíc klauzule where může být mnohem více složitá a obsahovat v sobě poddotazy.

Takže je asi se obávám, že ti v tomto moc nepomůžu. Buď znát jméno proměnné nebo prostě pak si napsat něco,  co ti ty data vyfitruje, ale už nad vrácenou kolekcí (daným grafem jako výsledkem).

**Comment by bogo777** [comment]
Aha, no je to trochu složitější, než jsem čekal. Možná by nám mohl poradit @tomas-knap jak na to/jak by si to představoval?

**Comment by tomas-knap** [comment]
Tak, reseni bych videl, ze se nebudeme snazit opracovavat ten puvodni dotaz, ale proste prislusne CONSTRUCT/SELECT query, ktere uzivatel zada (pripadne je zadano pres BRowse button) vzdy vysype data do nejake docasne tabulky (relacni), kde sloupce odpovidaji tomu co mas v browseru a nad tim pak muze pracovat Bohuslav. 

Ale to znamena domluvit se s Honzou, jak to udelat, bo potom co uzivatel odesle dotaz, tak se zavola metoda na fasade Honzy, ta zavola metodu Jirky, ten neco vrati, metoda na fasade to zapise do db a poskytne nejaky pohled na data pres PagedTable. Dava to smysl?

**Comment by bogo777** [comment]
Aby tohle fungovalo, tak bychom poprve museli cely vysledek vysypat do relacni tabulky, tedy prijdeme o rychlost pri nacteni prvnich dat. Dalsi otazkou je pak sprava tech docasnych tabulek. Prijde mi to dost slozite, kvuli takove "malickosti"... 

Nedal by se cely ten dotaz jeste obalit jednim CONSTRUCTem, ve kterem by byl ten filtr?

**Comment by tomas-knap** [comment]
Mno, my stejne nacitame jen jednu stranku, ne? Nikolv vsechna data. 

To prave fungovat nebude, bo trebas CONSTRUCT {http://konkretniSubject ?p ?o} se musi na subjektu filtrovat jinak nez ?s ?p ?o pattern. Resp. by se takovy dotaz musel prepisovat jako CONSTRUCT {?s ?p ?o} where {....BIND ?s http://konkretniSubject}

**Comment by tomas-knap** [comment]
Navic ani dva vnorene CONSTRUCTs nedovoluje standard

**Comment by bogo777** [comment]
No momentalne jo, i kdyz ted mam trochu pochyby, co to vlastne dela pri tech COUNT metodach, protoze pri vetsich datech je to velice pomale, ale pokud to budeme chtit filtrovat v relacni db, tak tam ta data musime mit vsechna a az nad nimi pouzivat strankovani/filtrovani.

**Comment by tomas-knap** [comment]
Mno, kdyz mas SELECT count(?x), tak ti to proste vrati jednu hodnotu, takze v tabulce bude jeden sloupec s jednou hodnotou

**Comment by tomas-knap** [comment]
I would suggest to postpone this for f2f meeting next week.

**Comment by tomas-knap** [comment]
No filtering for CONSTRUCT results
