### ISSUE TITLE
Provide method for explicitly overwriting LIMIT clause in RDF query.

### ISSUE THREAD

**Issue by bogo777** [mff-uk/odcs#639]
Related to wrapper from #638.

If original query has already LIMIT clause, I create invalid query while paging. It would be better to control this via wrapper object. 

Method setLimit(int limit) which would overwrite any preexisting LIMIT clause.

From Tomas:
Regarding LIMIT, limit specified in the query should be taken into account when limit for the pages is set. So e.g. if LIMIT is 50 in the user's query and pages are 30, then, the second page should contain only 20 records.

This would work without further changes, I only add LIMIT in gettting paged data, for size() method, original query with LIMIT 50 would be used, and I would know, that only 50 records are available.

**Comment by bogo777** [comment]
LIMIT používám při stránkování. Tudíž chci pokaždé jen 20 záznamů. Uživatel jich chce třeba 100, ale já mu najednou zobrazím jen těch 20 = 1 stránku. Tudíž když jen na konec stringu přidám "LIMIT 20", tak tam bude "LIMIT 100 LIMIT 20", což nefunguje, chtěl bych tedy metodu, která by zajistila, že tam bude správný limit a query zůstane validní.

**Comment by tomesj** [comment]
K tomu co píšeš se dá používá OFFSET, který udělá co je potřeba a vyhovuje syntaxi SPARQL 1.1.

Postupně uvedu příklad: .
1) Mám "query" - to mi vrací např. 238 triplů
2) Uživatel jich chce 100 - potom "query" LIMIT 100
3) Chci dát 20 triplů na stránku (či méně)  
a) pro prvni stranku - "query" LIMIT 20 OFFSET 0
b) pro druhu stranku - "query" LIMIT 20 OFFSET 20
c) pro třetí stránku - "query" LIMIT 20 OFFSET 40
....

Význam syntaxe:
'QUERY' LIMIT X OFFSET Y
- vyhodnotí se dané query, prvních Y trojic se přeskočí, potom se vrátí následujicich X trojic.

Iteračně lze tedy dotazy pro stránky získat např. takto:

PSEUDOCODE:
int Y=0; //start offset value
int X=20; //triples on 1 page
int Limit=100; //user defined limit, if limit not defined, then LIMIT=pocet triplu vracene dotazem

//vsechny trojice se vejdou na 1 stranku.
if (X>Limit) {

   OnePage = "QUERY" LIMIT X //if user limit not defined use: OnePage = "QUERY"
   return;
}

//trojice se rozdělují do více stránek
while(Y+X<=Limit) {

 NextPage = "QUERY" LIMIT X OFFSET Y;
 Y+=X;
}

**Comment by bogo777** [comment]
OFFSET znám a používám, mě jde o to přepsání LIMITu v původní query.

Uživatel zadá:
SELECT ?s ?o ?p WHERE {?s ?o ?p} LIMIT 100

Já chci data pro 1.stránku:
SELECT ?s ?o ?p WHERE {?s ?o ?p} LIMIT 20 (OFFSET 0)
pro druhou:
SELECT ?s ?o ?p WHERE {?s ?o ?p} LIMIT 40 OFFSET 20

Kromě setLimit(20) by to tedy mohlo mít i metodu setOffset(40), případně 1 s nastavením obojího

Do důsledků bychom asi mohli řešit i pokud zadá uživatel rovnou OFFSET(což mi ale přijde už zvláštní a zbytečné/snadno zdůvodníme proč to nepodporujeme)

**Comment by tomesj** [comment]
OK, takže jestli to chápu správně, tak ti stačí object, kterýmu se dá query a pak se na něm zavolá metoda 
setLimit(10), popr. i setOffset(30) a ta vrati ten dotaz, s těmito hodnotami, co chces....

Stačí to takto ? Jestli jo, tak to ti udělám :-)

**Comment by bogo777** [comment]
JJ to je přesně ono. :-)

**Comment by tomesj** [comment]
Jo, tak už si rozumíme, to jsem potřeboval vědět...Nakonec je to jednodušší, než jsem si původně myslel.

**Comment by tomesj** [comment]
Máš tam novou třídu QueryRestriction 
- té dáš query, nastavíš si LIMIT, OFFSET, případně obojí a pak zavoláš metodu 

String getRestrectedQuery() 
- vratí ti správné query dle tvého restriction nastavení.

Toť vše.

**Comment by bogo777** [comment]
Works great.
