### ISSUE TITLE
Comments in GUI - further improved

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#64]
Nechci prudit ;) ale mrkni prosim jeste na ty komentare. Urcite tam popis kazdy parametr vetou a kazdou navratovou hodnotu prosim take. I za cenu toho, ze se ten popis bude opakovat zcasti. Kdyz si nekdo necha zobrazit params dane metody, tak hned vi, jake je role kazdeho pararmetru a co muze ocekavat jako navratovou hodnotu. I ty to ocenis za dva,tri mesice ;)

Priklad (zrovna u tehle metody to nevadi tolik, bo je private a jeste mozna je docasna), ale pro ilustraci problemu:
-  /**
-   \* Stub method for providing stub data, until LogFacade is completed.
-   \* @param dpu
-   \* @return 
-   */
  private List<LogMessage> getData(DPUInstanceRecord dpu) {

Lepe: 
-  /**
-   \* Stub method for providing log messages associated with the given dpu execution, until LogFacade is completed.
-   \* @param dpu DPUInstanceRecord(odkaz) for which the log messages should be obtained
-   \* @return Returns List of LogMessages(odkaz) associated with the given DPUInstanceRecord(odkaz) execution
-   */
  private List<LogMessage> getData(DPUInstanceRecord dpu) {

**Comment by bogo777** [comment]
Zkusil jsem to vylepšit, budu se to snažit psát u nových věcí rovnou.
