### ISSUE TITLE
SPARQL Loader has incorrect configuration in HTTP URL

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#641]
But as a result, the following error occured:

![screen shot 2013-10-14 at 1 24 52 pm](https://f.cloud.github.com/assets/3014917/1325172/5a09165e-34c3-11e3-983c-94cbe918a03d.png)

THis should not happen, SPARQL loader should log something like: Cannot connect to HTTP URL : XX, please check that the target database is running. No stack trace as above.

**Comment by skodapetr** [comment]
It can be useful to mention (or remind) that DPU can failed without exception by publishing ERROR message via context.sendMessage.

If DPU faileds with exception stack trace is attached to the log automatically as it is assumed that it may contains useful data about the failure.

**Comment by tomas-knap** [comment]
Yes, that is the preferred way, Jirka implement it as Petr is saying
