### ISSUE TITLE
Problems with non-unique primary key

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#643]
Everything was working, then I just turned db off and on and the following error occur as I was creating new pipeline:

![screen shot 2013-10-14 at 1 51 34 pm](https://f.cloud.github.com/assets/3014917/1325312/6aa373ca-34c7-11e3-9645-64a684526065.png)

Surprisingly, when I click save for the second time, no error occurs. 

Then I tried to run that pipeline and:

![screen shot 2013-10-14 at 1 52 48 pm](https://f.cloud.github.com/assets/3014917/1325323/a3e550cc-34c7-11e3-9cf6-cfc99f443338.png)

This error does not dissapear when running two times. 

When I solve the last problem, three more problems of the same type occur for Exec REcord, dpu context, dataunit_info. All was working before turning the database off.

SO there is something strange on that, please test to turn the db off and on, while having the same session in gui. 

Related to #634, #635

**Comment by janvojt** [comment]
I cannot reproduce this on my instance. I tried creating a new pipeline with 1 extractor, saving it, killing virtuoso and launching it again, adding a transformer, saving again (without refreshing window). It worked fine.

**Comment by janvojt** [comment]
Is it reproducible on odcs.xrg.cz?

**Comment by tomas-knap** [comment]
Yes, it happens everytime virtuoso is restarted. So just start the pipeline, kill virtuoso, wait for some time, restart virtuoso and the pipeline should continue, but with the error above. You can test today in the evening on odcs.xrg.cz.

**Comment by tomas-knap** [comment]
Well, now it happens even when the db was not restarted. We just run pipeline "Ares test". Then we run the pipeline once again and cancel. Then when editing "Ares test", the issue with primary key occurs

**Comment by tomas-knap** [comment]
Using the following script to repair

sequence_set('seq_exec_context_pipeline', (SELECT MAX(id)+1 FROM exec_context_pipeline), 1);
sequence_set('seq_exec_pipeline', (SELECT MAX(id)+1 FROM exec_pipeline), 1);
sequence_set('seq_exec_dataunit_info', (SELECT MAX(id)+1 FROM exec_dataunit_info), 1);
sequence_set('seq_exec_context_dpu', (SELECT MAX(id)+1 FROM exec_context_dpu), 1);
sequence_set('seq_exec_record', (SELECT MAX(id)+1 FROM exec_record), 1);

**Comment by janvojt** [comment]
So? What is the status? Was it just broken database?

**Comment by tomas-knap** [comment]
Well, the problem is that even when I used fresh db, it shows in the log:

14:15:13 Failed to get a buffer for a new page. Retrying.  If the failure
repeats, an out of disk error will be signalled.  The cause of this is
having too many buffers wired down for preread, flush or group by/hash join
temp space.  To correct, increase the number of buffers in the
configuration file.  If this repeats in spite of having hundreds of
thousands  of buffers, please report to support.
14:19:04 Failed to get a buffer for a new page. Retrying.  If the failure
repeats, an out of disk error will be signalled.  The cause of this is
having too many buffers wired down for preread, flush or group by/hash join
temp space.  To correct, increase the number of buffers in the
configuration file.  If this repeats in spite of having hundreds of
thousands  of buffers, please report to support.
14:20:50 Failed to get a buffer for a new page. Retrying.  If the failure
repeats, an out of disk error will be signalled.  The cause of this is
having too many buffers wired down for preread, flush or group by/hash join
temp space.  To correct, increase the number of buffers in the
configuration file.  If this repeats in spite of having hundreds of
thousands  of buffers, please report to support.

And that it is frozen. Kuba was updating the db, then I will try again and
also report about the problem with primary keys

**Comment by janvojt** [comment]
Are you sure this log message is relevant to relational database? Is [this](https://github.com/openlink/virtuoso-opensource/issues/52) not the same problem?

**Comment by janvojt** [comment]
It is weird the class which logged this is not mentioned.

**Comment by tomas-knap** [comment]
This is log of Virtuoso

**Comment by janvojt** [comment]
I cannot reproduce, but this might have been caused by too many connections to Virtuoso. If this does not happen after commit cfbd3f98 I suggest you close the issue as resolved.

**Comment by tomas-knap** [comment]
I can reproduce this - see odcs.xrg.cz:8080/odcleanstore. Just try to create new pipeline, when you try to save for the first time, error occurs:

![screen shot 2013-10-18 at 3 13 51 pm](https://f.cloud.github.com/assets/3014917/1360628/9349f260-37f9-11e3-962f-503d4149df9e.png)

But it can be saved for the second time.

**Comment by janvojt** [comment]
I tried now, and pipeline is created without any problems.

**Comment by tomas-knap** [comment]
Will reaopen if reaaperas
