### ISSUE TITLE
Separate settings for the connection to virtuoso (relational DB) and virtuoso - store for RDF data processed by the pipelines

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#644]
Motivation: easier rebuild of the DB in case of problems (in the RDF data part), improved performance, 

Solution: Add one more set of params for connecting to DB:
# Virtuoso connection configuration setting

virtuoso.relational.hostname = localhost
virtuoso.relational.port = 1111
virtuoso.relational.user = dba
virtuoso.relational.password = dba
virtuoso.relational.charset = UTF-8

So the params above will determine the connection to the relational database. The existing params in config.propeties will define only connection to RDF data stored as the pipelines are processed. 

Sorry for this enhancement, will try to keep enhancements at minimum.

**Comment by janvojt** [comment]
I changed the priority to urgent, as this will make testing easier.

**Comment by tomas-knap** [comment]
ok, tell me when ready
