### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#645]
![screen shot 2013-10-14 at 5 34 28 pm](https://f.cloud.github.com/assets/3014917/1326885/30440086-34e6-11e3-9e35-429dcd3c281d.png)

**Comment by bogo777** [comment]
Is it on newer version than this commit https://github.com/mff-uk/ODCS/commit/7f86813fa03cd71b018eb4037f630d041b045ed3?
