### ISSUE TITLE
Problem with vaadin - ComboBox

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#646]
When I debug DBpipeline, switch to Execution monitor and click on button "Debug data" I got this exception:

![image](https://f.cloud.github.com/assets/3481055/1328213/8e5f4592-34fd-11e3-8a99-9da9c1a9e6ea.png)

Tomas please reasign this to responsible person for that.

**Comment by bogo777** [comment]
Do you have latest version, have you tried clean&build? Is DBPedia the standard pipeline in the database? Have you clicked "Debug data" or "Debug pipeline"(there is its tooltip on the screenshot so I ask)?

This worked for me today just fine, after any of my commits, last thing I added was label with graph for data unit and it worked fine.

Can anyone else write if it works for them or not?

**Comment by tomesj** [comment]
I used clean & build, restart database for sure.....Yes, it was last version. I clicked on "Debug data", but when can  run copy of DBPedia and I can show log - there was the same problem as using debug ->Debug data (in execution monitor).

Directory for fronetend´s log I have already set.

**Comment by bogo777** [comment]
Sorry, I tested the new feature, but then I wanted to add more space for it, and accidentally changed index in wrong line. Will push fix momentarily.
