### ISSUE TITLE
Namespace prefix dialog

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#648]
When trying to delete prefix: 
![screen shot 2013-10-15 at 10 02 47 am](https://f.cloud.github.com/assets/3014917/1332067/4058fea6-3570-11e3-9117-01c6a0891de2.png)

Please test the whole dialog

**Comment by kukharm** [comment]
Closed by https://github.com/mff-uk/ODCS/commit/8cdf7229b08edf2fd30a0e6770f4b06b1ecddb3b
