### ISSUE TITLE
When launching pipeline, no DPU events occur

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#651]
I start debugging dbpedia pipeline, logs occur but no DPU event
![screen shot 2013-10-15 at 1 13 12 pm](https://f.cloud.github.com/assets/3014917/1333047/db50ed0a-358a-11e3-871d-5eca6541404b.png)

Always when you adjust something test it at least via user interface, better via automated tests

**Comment by bogo777** [comment]
Well, I have no DPU events in the database, so the problem is propably in backend/facade. @skodape @janvojt Any changes that could have caused this?
