### ISSUE TITLE
Pool for connections not working properly - 28k+ connections

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#656]
Is there the limitation on 10000 connections?

![screen shot 2013-10-15 at 1 58 56 pm](https://f.cloud.github.com/assets/3014917/1333300/e5a5b0ea-3591-11e3-8b0c-2c71da735705.png)

**Comment by janvojt** [comment]
Please test, it should be resolved. I tested running about 10 different pipelines (dbpedia, ares, psp, buyers), and RDF database was using around 60 connections, relational database 10. That includes sockets in TIME_WAIT state.
