### ISSUE TITLE
SPARQL Extractor uses jar file for RDF FIle loader

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#657]
![screen shot 2013-10-15 at 4 51 47 pm](https://f.cloud.github.com/assets/3014917/1334499/a3cb9f6e-35a9-11e3-8728-f7762859be5c.png)

**Comment by janvojt** [comment]
Please look into the configuration of DPU template, make sure JAR path is correctly specified as `RDF_extractor/RDF_extractor-1.0.0.jar` and report what you found.

**Comment by tomas-knap** [comment]
Well, this should be correctly prepared in data.sql?

**Comment by janvojt** [comment]
The log in the screenshot says:
1. Extractor **finished**.
2. Installing Loader.

What is wrong with that? I assume extractor was installed in the preceding lines, then extractor finished, so loader can be installed and run.

**Comment by tomas-knap** [comment]
jj, mas pravdu
