### ISSUE TITLE
extractRDFfromFileToRepository should not launch ExtractException?

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#66]
Reason: Cannot be used by the transformer

public void extractRDFfromFileToRepository(String path, String suffix,
            String baseURI,
            boolean useSuffix) throws ExtractException;

**Comment by tomas-knap** [comment]
Petre, should Jirka be responsible for that? Or what is the status of this task?

**Comment by skodapetr** [comment]
Yes he should.
