### ISSUE TITLE
Share RDF connection

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#662]
Instead of using new connection every time base rdf repo is used, it should share the connection. Every DPU should have just one connection. This could be ensured by calling some method getConnection(), which either creates new connection for the thread (DPU) or returns shared connection (the connection for the thread). Please ask Petr about details.

**Comment by tomesj** [comment]
I made substitute all repository.getConnection() calling using method  getConnection() used as singleton. For sure I commented finnaly blocks, where this connection is closed.

**Comment by tomas-knap** [comment]
Jirka, so now every connection is shared by one BaseRDFRepo, which means by one data unit? How did you solve the merge command? You were talking about some problem, they are fine?

**Comment by tomesj** [comment]
I edited only method in BaseRDFRepo - specific method as merge (has different implementation in Local/Virtuoso) stayed without changes. I tried primitive test for trying it - it was fine, but I will be better to test it for pipeline runnig and more complex calling method (parallel using, etc...)
