### ISSUE TITLE
Refresh button in ExecutionMonitor does not work.

### ISSUE THREAD

**Issue by janvojt** [mff-uk/odcs#665]
This is a more general problem though. Table in execution monitor does not refresh automatically anymore. Even worse, it does not refresh after manually clicking on refresh button. It may have been caused by implementing "single-row-updates".

**Comment by janvojt** [comment]
EM is refreshed only by clicking on the menu.

**Comment by bogo777** [comment]
It doesn't work at all? For me it works fine, except some special cases of pipeline finishing/failing. Both in automatic refresh and button, the "check if record newer than last update exists" is used. Is date for log assigned earlier than it is saved to db? I assumed that it is generated the moment it is saved, but maybe it's not the case and my approach doesn't work then.

I will try to recover latest date from showed records and use that in the compare.

**Comment by janvojt** [comment]
Sorry, I never updated the trigger update_last_change, so after the rename it was still setup for intlib table.
