### ISSUE TITLE
Virtuoso.rdf.retries/wait missing in config.properties for frontend

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#668]
configure number of retries before giving up (0 is no failure toleration, -1 is unlimited)
virtuoso.rdf.retries = -1
configure how long we wait before next retrial (in ms)
virtuoso.rdf.wait = 2000

Please test that

**Comment by janvojt** [comment]
In frontend there are no retries, we expect user to refresh page.

In backend this was fixed in commit 58af7e2e.
