### ISSUE TITLE
Event problem

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/odcs#669]
Vidím v jenom okně event k mnoha pipeline .. že tam nemají být je myslím vidět podle časů a délek trvání pipeline.

![events](https://f.cloud.github.com/assets/3341693/1354866/d884a47c-375b-11e3-82f3-e4586b15a724.png)

Přes conductor jsme ověřil, že hodnota v execution_id je jiná .. tj. neměl bych tam vidět více než 4 záznamy.

**Comment by tomas-knap** [comment]
Bohuslave, zkontroluj prosim intlib query container

**Comment by tomas-knap** [comment]
v mem pripade to dokonce vypada, ze se tam objevuji DPU events z predchozich pipeline, ale ne z te aktualni

**Comment by bogo777** [comment]
Ja jsem tam vypnul refresh kvuli testovani rychlosti logu, kdyz ty events stejne nefungovaly. Ale Honza je opravil driv, nez jsem to zase zapnul. V aktualni verzi uz by to melo byt v poradku.
