### ISSUE TITLE
Virtuoso repository for storing intermediate results should be configurable in the config.properties file 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#67]
Currently:

public static VirtuosoRDFRepo createVirtuosoRDFRepo() {

```
            // TODO: Load from AppConfiguration ... 
    final String hostName = "localhost";
    final String port = "1111";
    final String user = "dba";
    final String password = "dba";
    final String defautGraph = "http://default";

}
```

Goal: hostname/port/user/pass/defaultGraph must be configurable without the need for rebuild. Reason: On the production server, I use different port for virtuoso.

**Comment by tomesj** [comment]
Virtuoso used App configuration :-) Solved
