### ISSUE TITLE
Obsolete column Execution monitor

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#671]
What means "Obsolete" column in Execution monitor table? Is it still actual?

**Comment by skodapetr** [comment]
well .. not currently use but the planned use is:
obsolete = true <=> pipeline has been modified during it's execution
to describe it in other way: I start the execution and before it ends .. I modify the pipeline in some way

The execution should not reflect this changes .. so it continue with old (obsolete) pipeline.

I you are satisfied with the answer please close the issue.
