### ISSUE TITLE
Problem with default configuration in DBPEDIA

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#673]
The named graph in SPARQL extractor for DBPEDIA should be http://dbpedia.org, no "/" at the end. Test that the pipeline generates 100 triples when adjusted. Please adjust in data.sql

**Comment by skodapetr** [comment]
Re-assigned to me I will update the data.sql.

**Comment by skodapetr** [comment]
Should be ok now. DBPedia extract 100 triples.

**Comment by skodapetr** [comment]
I have also change configuration from BLOB into string so it should be easier to update them in the future.
