### ISSUE TITLE
When clicking on column header in pipeline list I got exception

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#675]
![screen shot 2013-10-18 at 9 19 17 am](https://f.cloud.github.com/assets/3014917/1358538/b8fe1d62-37c5-11e3-8ee6-2423a1360e48.png)

**Comment by bogo777** [comment]
It is the side effect of bot limiting length of description. Now we cannot sort by it. I will set proper sortable columns for pipeline list and close this.
