### ISSUE TITLE
Pipeline canvas - create new edge does not work for the first time

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#681]
When I put DPU on canvas, try to add edge to the already existing DPU, it does not work, no edge is shown. But when I try to display the icons again and try to create the edge, it is working normally

**Comment by bogo777** [comment]
I am unable to reproduce it. I tried adding DPU to saved pipeline, to new pipeline with and without previously saved in pipeline edit.

What browser do you use? Can you give step by step guide to reproduce it?

**Comment by tomas-knap** [comment]
Well, I am also unable to reproduce, but it was happening. Closing, will reopen if it happens again
