### ISSUE TITLE
Logs from subpackages not included

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#682]
As introduced below, I have DPU UriGenerator, which is using certain classes from subpackages as below:

![screen shot 2013-10-19 at 10 43 10 am](https://f.cloud.github.com/assets/3014917/1365901/8a5617e6-389a-11e3-84e0-8df36e0dffbf.png)

But any log from the subpackages does not display in exec detail - log.

**Comment by skodapetr** [comment]
And are there presented in standard output, backend log file?

**Comment by tomas-knap** [comment]
Yes

**Comment by tomas-knap** [comment]
They are logged at info level, using logger: private static final org.slf4j.Logger logger = LoggerFactory
            .getLogger(IntLibLink.class);

**Comment by skodapetr** [comment]
And could you please post a sample? if the dpu, pipeline is is presented.
