### ISSUE TITLE
If DPU does not define any input, an edge to such DPU should not be allowed

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#685]
Such situation (red arrows) should not happen, yellow notification should appear when user tries to create edge to DPU not having any input and such edge is not created

![screen shot 2013-10-19 at 5 54 20 pm](https://f.cloud.github.com/assets/3014917/1366538/4f476550-38d7-11e3-8da9-744970bf7249.png)

**Comment by bogo777** [comment]
Will solve after #694 is resolved.
