### ISSUE TITLE
GUI Refactoring 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#692]
- Autowiring instead of getApp.get...();
- MVP like style, https://vaadin.com/web/magi/home/-/blogs/model-view-presenter-pattern-with-vaadin
- DataUnitBrowser, RDFBrowser not used
- We discussed with Petr and came to conclusion, that we should set the object being initialized as last step in init method. So if it fails before, it is still null and will be initialized again upon next request. 

Minor:
-setDate v init metode - pouziva se? Prejmenovat pokud jo
-jak a kde se prepinaji ty views?
-IntlibNavigator - pouziva se?

We should meet in the week from 29.10. also with Petr to discuss

**Comment by tomas-knap** [comment]
ViewNames - deprecated

**Comment by bogo777** [comment]
PipelineList and ExecutionList are refactored to MVP.

DPU is refactored to older version of MVP and should be refactored to be up to date.(It should be straightforwad and fast)

**Comment by tomas-knap** [comment]
and regarding the autowiring, this is also pending, right?

**Comment by bogo777** [comment]
Should I continue with autowiring, or is there something we need to discuss first?

**Comment by tomas-knap** [comment]
We discussed with Petr and came to conclusion, that we should set the object being initialized as last step in init method. So if it fails before, it is still null and will be initialized again upon next request. There are possibly many places in code, which need to be changed, I would do it in one step with autowiring/refactoring.

**Comment by tomas-knap** [comment]
Bohuslave, main refactoring must be ready before 12.12, the only thing which may remain is the MVP of other components. Could you please write your plan here? I would suggest to:
1. finish autowiring (but please write below in more detail what is missing regarding that, or if you have any questions, or anything to be discussed whether it is a good idea to autowire or not)
2. object being initialized as last step
3. look at the RDF browser (please discuss what this step will include, so that we can estimate time needed)
4. minor issues

It should be discussed, whether there is time to convert all components according to MVP pattern. Probably not. So I would suggest to check the code and decide/discuss what may be done till 12.12. and what may be done later.

**Comment by bogo777** [comment]
1. I will work on that today and write here any problems/findings about this.
2. Easiest would be to do it as part of process to change the views to MVP(for some components it can be done as part of autowiring process)
3. What should be done with DRF Browser?

**Comment by tomas-knap** [comment]
1 - OK
2 - dej prosim casovy odhad nez to zacnes delat, abychom vedeli
3 - Nic, nechame jak je

**Comment by bogo777** [comment]
Autowiring is mostly done.
2. It will mean to go through every view/component and check/change the initialization behavoir. So half a day at least.

**Comment by tomas-knap** [comment]
Ok, so finish 1)
Then I will put this issue to 0.5 with normal prio to finish 2)

**Comment by tomas-knap** [comment]
Bohuslav, is the autowiring done?

Regarding 2), could you please do that for the components already being refactored according to MVP? Or is it already done

Putting with high prio, although not needed to be tomorrow

**Comment by tomas-knap** [comment]
Please focus on finishing autowiring and proper initialization. Rest of MVP refactoring could  be postponed.

**Comment by tomas-knap** [comment]
Please update what is done - is the autowiring and proper initialization done?

**Comment by bogo777** [comment]
Autowiring is done and initialization for MVP components should be too.

**Comment by tomas-knap** [comment]
So this issue is ready for testing, right?
