### ISSUE TITLE
Optimize PipelineList queries

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#693]
See #209 

The optimizations that can be done in PipelineList are quite straightforward. I believe it would be enough to add 3 columns to pipeline table, where we can save the information about last execution. This would need to be updated by backend when pipeline finishes.

**Comment by tomas-knap** [comment]
Can Petr realize that?

**Comment by skodapetr** [comment]
I can and it should not be complicated  .. but, what about using triggers or stored procedures for that? or this is not for which the virtuoso is designed?

**Comment by tomas-knap** [comment]
? k last execution - ma to byt last execution moje nebo libovolneho uzivatele?  Probrat s Kubou @jakubklimek

**Comment by janvojt** [comment]
Can we consider this finished? Currently last execution is global. To change it "pre user" would not be possible in the execution table, we would need to join with pipeline executions table, as it was previously.

Anyway, I think current behaviour is better. I am really interested in the status of any last run, just to know pipeline is "healthy".
