### ISSUE TITLE
ModuleFacade in DPUExplorer is null

### ISSUE THREAD

**Issue by bogo777** [mff-uk/odcs#694]
I tried to use DPUExplorer for getting DPUs inputs/outputs(as getting it through EdgeCompiler is deprecated). But every time it's called, I get NPE. I debugged it, and the autowired moduleFacade is null.

**Comment by skodapetr** [comment]
Does this happen on every DPU? Or is there way for me to replicate easily?

**Comment by bogo777** [comment]
For me, it happens for every DPU, I can push code where I replaced EdgeCompiler with DPUExplorer, and then it is easily replicatable from canvas. Adding new edge will do.

**Comment by skodapetr** [comment]
One more question .. the DPUExplorer should be used as a spring component (then the autowire is done) you should not create it's instance directly - I probably do not mention this in documentation .. sorry
You should use something like .. 
App.getApp().getBean(DPUExplorer.class);

or directly use autowire .. but we will discuss using autowire on next frontend meeting probably .. to preserve the consistence in frontend I would use App.getApp().. approach.

**Comment by bogo777** [comment]
Ok, that's propably the cause, I didn't know about this. I will try the autowire approach. Will close this, if it solves it.
