### ISSUE TITLE
Database down

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/odcs#698]
steps to reproduce: Virtuoso on, run backend , Virtuoso off .. and then again on ..  

```
2013-10-24 12:57:41,520 [taskScheduler-1] TRACE exec: dpu: c.c.m.x.o.b.execution.Engine - Checking for new executions.
[EL Info]: 2013-10-24 12:57:41.522--UnitOfWork(1882814048)--Communication failure detected when attempting to perform read query outside of a transaction. Attempting to retry query. Error was: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: Virtuoso Communications Link Failure (timeout) : Software caused connection abort: recv failed
Error Code: -3
Call: SELECT ID, t_end, debug_mode, t_last_change, silent_mode, t_start, STATUS, stop, debugnode_id, owner_id, pipeline_id, schedule_id, context_id FROM exec_pipeline WHERE (STATUS = ?)
    bind => [0]
Query: ReadAllQuery(referenceClass=PipelineExecution sql="SELECT ID, t_end, debug_mode, t_last_change, silent_mode, t_start, STATUS, stop, debugnode_id, owner_id, pipeline_id, schedule_id, context_id FROM exec_pipeline WHERE (STATUS = ?)").
[EL Info]: 2013-10-24 12:58:05.52--UnitOfWork(221903249)--Communication failure detected when attempting to perform read query outside of a transaction. Attempting to retry query. Error was: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130824-981335c): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: virtuoso.jdbc4.VirtuosoException: Connection failed: Connection refused: connect
Error Code: -3
Call: SELECT ID, DESCRIPTION, enabled, first_exec, just_once, last_exec, NAME, time_period, period_unit, strict_tolerance, strict_timing, type, user_id, pipeline_id FROM exec_schedule WHERE (type = ?)
    bind => [1]
Query: ReadAllQuery(referenceClass=Schedule sql="SELECT ID, DESCRIPTION, enabled, first_exec, just_once, last_exec, NAME, time_period, period_unit, strict_tolerance, strict_timing, type, user_id, pipeline_id FROM exec_schedule WHERE (type = ?)").
2013-10-24 12:58:06,539 [taskScheduler-1] INFO  exec: dpu: c.c.m.x.o.b.f.DatabaseReconnectAspect - call finished 
```

Q: does this means that database connection failures are handled by eclipse link? So our facades does not know nothing about it (there is no DB down log).
Is there way how to let eclipse link throw the exception? so I can catch it in aspect (which I have already implemented) and write some message .. and try again?

I meet this when I was rewriting backend to use aspects instead of special facades which tolerate database crashes.

But Thomas (without this modification) get same behaviour so I assume that it's not my fault.

**Comment by janvojt** [comment]
The cause for this is that method `PipelineFacade.getAllExecutions(PipelineExecutionStatus)` is not overriden in backend facade. Seems like I forgot to override it :/. If you implemented backend facades using AOP, and included this method in the AroundAdvice, it should work OK.

**Comment by skodapetr** [comment]
Yes .. you are right .. I just let my self confuse with those logs .. which log mechanism is eclipse link actually using?

**Comment by janvojt** [comment]
> which log mechanism is eclipse link actually using? 

There is a property `eclipselink.logging.logger` in persistence.xml, that can set a custom implementation of logger. The documentation says the following:

> The type of logger. By default DefaultSessionLog is used. Valid values are the logger class name which implements org.eclipse.persistence.logging.SessionLog or one of values defined in LoggerType.

I am not sure what you need this for. Do you want to save EclipseLink logs into DB? I think we do not want them to litter DB. Logs in DB should only log the execution process, not the internals of ODCS application.

> napiš zda víš, nebo ne a pak prosím zavři 

I labeled this issue as a bug. Please close with the commit you said you have prepared, so it is linked.

**Comment by skodapetr** [comment]
Nechce se mi je ukládat do databáze.
Nicméně backend používá logback file-appender aby logoval do souboru a tam tyto logy chybí (neb je logback nevidí). Což by mohlo vadit (proč jsou logy na výstupu a nikoliv už v log souboru? ) .. našel jsem třídu pro logování eclipse-linku do slf4j a to pak půjde do logbacku. Tj. tím bychom měli toto také logované, tím bych to uzavřel.
