### ISSUE TITLE
Adjust the module names of core DPUs in Netbeans

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#703]
So that the module names are the same as names in DPU tree:

SPARQL Extractor/RDF FIle Extractor a podobne pro loader.

**Comment by tomas-knap** [comment]
a extractory?

**Comment by tomas-knap** [comment]
SPARQL loader?

**Comment by tomesj** [comment]
Přejmenoval už všechny. Dal jsem sem jen poslední commit.

**Comment by tomas-knap** [comment]
Ok, davej tam prosim vsechny

**Comment by tomas-knap** [comment]
Adjust also data.sql skript (wrong folder with DPU). Otherwise the dpus cannot be loaded on fresh install. Test on fresh install before closing.

**Comment by tomas-knap** [comment]
Please prepare for me also update script which renames jar_dir and jar_name for all records in DPU template containing wrong name. Please do it asap
