### ISSUE TITLE
Mandatory inputs to DPUs must be satisfied

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#706]
When mandatory input is not present among the inputs, what will happen? User should be notified about that. 

Alternatively, he can find out the problem when running the pipeline

**Comment by tomas-knap** [comment]
Currently such problem is reported when the pipeline is run.

**Comment by tomas-knap** [comment]
Which is fine. ALternatively, we could provide "validate" button next to save, close on the pipeline edit. Such validate button can check in the future various aspects.

**Comment by bogo777** [comment]
So should I add the "Validate" button and its funcionality?

**Comment by tomas-knap** [comment]
See #192 regarding the validate button. Needs discussion.

**Comment by tomas-knap** [comment]
When pressing validate button, notification is shown with the list of missing mandatory inputs

**Comment by tomas-knap** [comment]
Yes, please add the validate button to solve this issue and #192 . Or do you have other questions?
