### ISSUE TITLE
When deleting DPU after running pipeline, error shown

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#710]
![screen shot 2013-10-30 at 6 21 35 pm](https://f.cloud.github.com/assets/3014917/1439205/e021521c-4187-11e3-84c2-75bfda2de19d.png)

To reproduce: execute pipeline, delete dpu on the pipeline, try to show the previous log

**Comment by tomas-knap** [comment]
1) smazat logy k DPU instance pokud se maze
2) zkontrolovat jak se to chova kdyz pridam DPU az obrezim si nejaky predchozi beh -> budou tam prazdne logy pro tohle DPU?

**Comment by janvojt** [comment]
I actually did not delete the logs, but removed their reference to DPU instance. Thus logs are still kept, but are only attached to pipeline execution without any information which DPU created them. I believe this is a better solution than to completely delete them (if anyone disagrees it is no problem to change this behaviour).

We should probably document this.

**Comment by tomas-knap** [comment]
Ok. regarding the documentation (technical), we should discuss on the next meeting. But in general, you can start writing a page on the wiki about that in the technical doc section

**Comment by tomas-knap** [comment]
when deleting DPU, events are deleted but logs remain - may be a bit confusing,but justifyable
