### ISSUE TITLE
Parallel editing of pipeliones

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#711]
User should be warned that another user is browsing the same pipeline. User should be also warned that another user has saved the pipeline I have opened. 

Add button "Save as New pipeline"

**Comment by tomas-knap** [comment]
Please propose your solution here

**Comment by janvojt** [comment]
I suggest implementing this through an asynchronous AJAX call (similarly to ExecutionMonitor). Let's say the update interval would be 5 seconds. If pipeline canvas is open, asynchronous call will be made every 5 seconds. Upon this call, we will save a timestamp in database, that currently logged-in user had given pipeline open at given time. Each following call will update this timestamp. If timestamp is older than let's say 10 seconds, we can consider this as "user closed given pipeline".
In the response of this asynchronous call, we can return a list of usernames currently editing given pipeline. This list, if non-empty, can inform user about possible conflicts.

@bogo777 please comment whether this would be easy to implement (I believe so).

**Comment by bogo777** [comment]
So it would be saved in table with user? Or in some special table? That would take care of one user who opened multiple pipelines. There is also the "another user saved your opened pipeline" but we could implement that through simple lastChange column in the pipeline table.

It seems easy enough, refresh listener on pipeline canvas which informs about opened pipeline and asks for conflicts.

Other aproach would be to use Broadcaster in Vaadin - https://vaadin.com/wiki/-/wiki/Main/Broadcasting+messages+to+other+users

But we would need push enabled for that.

**Comment by skodapetr** [comment]
Can we use refresh like in pipeline-execution list instead of push ?
Also I suggest to define some clear interface for this .. between commons-app and frontend.

**Comment by janvojt** [comment]
> So it would be saved in table with user? Or in some special table?

No, I will make a dedicated table, because one user can open multiple pipelines in different tabs/browsers.

> There is also the "another user saved your opened pipeline" but we could implement that through simple lastChange column in the pipeline table.

I agree, sounds reasonable.

> Other aproach would be to use Broadcaster in Vaadin

I would not mess around with PUSH now, it could bring new problems.

**Comment by bogo777** [comment]
Ok, so from frontend I would periodically call something like reportOpenedPipeline(User?, Pipeline) and getPipelineConflicts(User?, Pipeline) which would return e.g. None/Opened/Saved? Or maybe only one method, which updates status and gets result, since it has same parameters and would be used in the same place...

**Comment by janvojt** [comment]
OK, I implemented everything needed in commons-app. I also created a test case, so it should work.

I am reassinging to Bohuslav to implement in frontend. Please use methods `PipelineFacade.createOpenEvent` and `PipelineFacade.getOpenPipelineEvents`.

**Comment by bogo777** [comment]
I looked at the methods and it looks like PipelineFacade.getOpenPipelineEvents returns OpenEvents of all pipelines.
Also, there is no way to detect if pipeline was saved by other user.
