### ISSUE TITLE
Sharing & Permissions for pipelines

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#713]

**Comment by tomas-knap** [comment]
Sharing
I want to share a created pipeline with other users so that they can use and modify it (Req 30)
I want to share a DPU with other users so they save time by not having to configure the DPU (Req 31)
Modification of the logic for showing accessible pipelines, it has to take into account also pipelines shared with me

**Comment by tomas-knap** [comment]
u pipeline musi jit rict ze je private/public. Pokud private tak to funguje jak ted. Pokud je public, tak je treba overit jestli jsou private/public DPU, pokud jsou nejake private, tak se automaticky prevedou na public (notifikace uzivateli jestli to tak opravdu chce). 

DPU tree -> private a public filtrovani (checkbox mame, jen musi fungovat), barvicky - jina barva pro public a private

PipelineList - vidim svoje pipelines (co jsou private) a vsechny public. 
ExecutionMonitor - vidim ty behy pipelines ktere si pustim
SchedullerEvents - kazdy ma svoje

**Comment by janvojt** [comment]
I created issues for Bohuslav to implement changes in GUI (#822 and #823). Everything else is done.
