### ISSUE TITLE
maven missing virtuoso-sesame-7.0.1.jar

### ISSUE THREAD

**Issue by Jan-Marcek** [mff-uk/odcs#714]
Hi,

when I compile source code (ODCS) with maven I get a error:

[ERROR] Failed to execute goal on project RDF: Could not resolve dependencies for project cz.cuni.mff.xrg.odcs:RDF:jar:1.0.0: The following artifacts could not be resolved: at.semantic-web com.openlinksw:virtjdbc:jar:3: Could not find artifact at.semantic-web:virtuoso-sesame:jar:7.0.1 

Where I can find this artifacts ? Have I wrong configuration?

Thanks a lot.

**Comment by tomas-knap** [comment]
reference to odcs maven rep required
