### ISSUE TITLE
Different icons for schedulled (by scheduler) and planned pipelines (to be executed)

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#719]
![screen shot 2013-11-01 at 12 22 47 pm](https://f.cloud.github.com/assets/3014917/1453084/0b054d1a-42e8-11e3-8fa9-410c32d87c11.png)

**Comment by bogo777** [comment]
Any idea how the new icon should look? I have trouble finding icon representing this (planned - to be executed) state.

**Comment by tomas-knap** [comment]
Instead of status schedulled, it should be labeled as "queued", with the icon (resize needed), e.g.: 

http://www.google.cz/imgres?imgurl=http://www.designofsignage.com/application/symbol/hospital/image/600x600/gents-que.jpg&imgrefurl=http://www.designofsignage.com/application/symbol/railway/largesymbols/gentsque.html&h=600&w=600&sz=25&tbnid=d3jl3n3UM4_d_M:&tbnh=129&tbnw=129&zoom=1&usg=__1dOi2uqX5Vs-Xp7kq7dqOZou-E0=&docid=KQMMTw6Ph9OtEM&sa=X&ei=KC56Uv_WM4mRswbTnIDIDg&ved=0CDcQ9QEwAg&dur=210

Icons for the column schedulled may remain the same.
