### ISSUE TITLE
DPUINFO Events holds negative events

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#72]
DPUINFO should not be used to express problems, we should use DPUERROR

![screen shot 2013-07-02 at 1 02 07 pm](https://f.cloud.github.com/assets/3014917/735981/e4875fac-e306-11e2-84eb-8e09af295116.png)

E.g. DPU info holds: Exception: java.io.FileNotFoundException: /usr/local/tomcat/apache-tomcat-7.0.33/webapps/examples/intlib/prague-dbpedia.ttl (Permission denied)

In these cases DPUERROR should be used.

**Comment by tomas-knap** [comment]
Petr, what is the status of this taks?

**Comment by skodapetr** [comment]
I'am a little bit uncertain .. when I look at the "Loader failed" short message it's connected to LoadFailedEvent class and this class use type = RecordType.DPU_ERROR.

**Comment by tomas-knap** [comment]
Seems to be solved.
