### ISSUE TITLE
SPARQL Validator  - standarty

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#720]
Validator openRDF - zjistit dle jakeho standardu validuje validator pro openRDF, verze X.

Validator of FUSEKI
Napsat mail a zeptat se:
1. jestli validator je mozne stahnout zdrojaky k validatoru http://sparql.org/query-validator.html
aby jej bylo mozne volat z aplikace.
2. SPARQL, SPARQL Extended syntax, jakym standardum to odpovida, SPARQL Extended = SPARQL 1.1?

**Comment by tomesj** [comment]
Maily na openRDF i Jenu s dotazy odeslány - zatím čekám na odpověď.

**Comment by tomesj** [comment]
Tak odpověď týkající se openRDF už přišla a je pozitivní.

1) SPARQL 1.1 je podporován v poslední verzi 2.7.7 - tedy přejdeme-li na ní (budu muset udělat pár změn), tak budeme mít schopnou validaci podle standardu SPARQL 1.1 a to chceme.

2) Agregační příkazy jsou musí být vždy správně uzávorkované - jak uvádí standart a mít vždy část AS, jinak to nebude dobře fungovat.

Tj. správný dotaz je např.
SELECT (count(*) AS ?pocet) WHERE {?s ?p ?o }

Špatné dotazy jsou pak:
1) SELECT (count(_)) WHERE {?s ?p ?o } - chybí AS část
2) SELECT count(_) AS ?pocet WHERE {?s ?p ?o } - chybí uzávorkování AGREGACE

Jinak text přímo došlého emailu odpovědi:
Sesame 2.7.7 (current stable release) implements SPARQL 1.1, current W3C 
Recommendation. Sesame does not implement any syntactical extensions to 
the standard (with one minor exception, which is the FROM DEFAULT clause).

SELECT (count(*) as ?c) WHERE {?s ?p ?o } would be correct. But you can't have an aggregate in the SELECT clause without assigning it an alias.

**Comment by tomas-knap** [comment]
Ok, super, tedy v tom pripade prosim updatuj na 2.7.7. (viz #729)

**Comment by tomesj** [comment]
Issue #729 vyřešena - problém se standarty vyřešen :-)
