### ISSUE TITLE
Malformed query exception when browsing RDF data

### ISSUE THREAD

**Issue by bogo777** [mff-uk/odcs#721]
![image](https://f.cloud.github.com/assets/1550848/1454330/10e6de5a-4307-11e3-936b-8544e9c4c70f.png)

Data were stored in localRDF, construct queries worked properly.

**Comment by tomesj** [comment]
Solved problem for local repository, prepare to close.

Note:
If you want see how to have to write well synatax COUNT queries - see issue #720.
