### ISSUE TITLE
Frontend log is not created

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#722]
When running odcs web app on odcs.xrg.cz, the frontend.log is not created although there is in config.properties:

frontend.logdirectory = /data/odcs/log
frontend.log.keepDays = 7

It was working before introducing the cycling (probably). Now there is no frontend.log file in the given folder after deleting the log and restarting odcs web app. 

To reproduce: If you delete frontend.log, restart the app, is the log file created?

**Comment by skodapetr** [comment]
you should use frontend.log.directory (there is dot after word log)
