### ISSUE TITLE
Misleading icons for DPU finished

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#725]
When there is an error in DPU, the log contains: 

![screen shot 2013-11-03 at 3 16 30 pm](https://f.cloud.github.com/assets/3014917/1461099/e082e104-4492-11e3-975a-ebcd0bbe0480.png)

Which is actually true, but the green tick for "DPU finished" is misleading, because there was a problem. So it would make more sense to use blue "info" icon for the DPU/Pipeline.INFO events. Btw. such icon is currenlty used for DPU_LOG - what kind of log level is it? 

![screen shot 2013-11-03 at 3 18 19 pm](https://f.cloud.github.com/assets/3014917/1461103/396334cc-4493-11e3-9d5e-38a37a925e7c.png)

We need to discuss that first

**Comment by bogo777** [comment]
DPU_LOG description from it definition in MessageRecordType: "Log information from DPURecord."

It is not used anywhere directly in ODCleanStore project, so I don't know more about it.

**Comment by tomas-knap** [comment]
Than I would suggest to remove DPU_LOG and use its blue icon for DPU_INFO and Pipeline_INFO. Petre, vis neco o DPU_LOG?

**Comment by skodapetr** [comment]
Aktuálně to asi přežijeme klidně bez něj. Jak název říká, měli jsme ho původně pro log info .. ale pro to stejně teď můžeme použít klasické logování.

**Comment by tomas-knap** [comment]
Ok, tak to prosim Bohuslave udelej jak jsem psal

**Comment by bogo777** [comment]
0bde87ffc37b7978b2dfe5413c8a90b26276ea26

DPU_LOG deprecated for now. Remove completely upon change in db.(Existing records don't work anymore.)

**Comment by tomas-knap** [comment]
Please remove DPU_Log from the possible events
![screen shot 2013-11-08 at 2 40 08 pm](https://f.cloud.github.com/assets/3014917/1500609/58454e0c-487b-11e3-9679-372325d07e34.png)
