### ISSUE TITLE
Do not continue with the pipeline exec in case of certain NON-ERROR DPU events. 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#728]
The default behaviour is that the execution ends when there is ERROR event (not log, but event), right? But it would be also useful to be able to end e.g. with Warning, but do not continue with the next DPUs. 

E.g. if the extractor does not extract any file, there is no sense to launch rest of the 20 DPUs and the result of the pipeline statecould be warning or even OK. 

![screen shot 2013-11-03 at 4 05 15 pm](https://f.cloud.github.com/assets/3014917/1461176/deb49550-4499-11e3-88e4-ab5cdd24e552.png)

**Comment by skodapetr** [comment]
Well should then the "No data to be unzipped" be an error, or you want some settings?
like: terminate execution in case of: error | warning+ , ... ?

**Comment by tomas-knap** [comment]
Well, it is not an error, just one possible result of the DPU and also indication that further steps in the pipeline execution are not needed, because they will produce no data.

So in this case it would be useful to be able to say that pipeline should finish successfully after the first DPU, because no data was available, because it was Saturday/Sunday and supreme court does not publish new data these days. 

But we can leave this for now, to see if we have more use cases for this

**Comment by tomas-knap** [comment]
enable publishing of event "on request preliminary termination"

**Comment by tomas-knap** [comment]
Please adjust in the documentation for DPU creation and close

**Comment by skodapetr** [comment]
I added note into the "theory".. after the execution termination with ERROR .. so I hope it's ok.
