### ISSUE TITLE
Update open RDF to 2.7.7 + check that validator supports COUNT

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#729]
Based on that, the validation in 2.7.7. is enough, there should be only one openRDF validator. So please remove the special CountValidator

**Comment by tomesj** [comment]
1) Update openRDF to version 2.7.7 - commit ff0152909ff3de9ad77ceb1390630f44dea95bd2
2) Remove extension for SELECT_COUNT -.commit 9c9e4d08a1e1c095faf542ef1fb124fe32e0d1d5

Test validation using COUNT/SUM/AVERAGE - works fine.

Prepare to close
