### ISSUE TITLE
Running pipeline with SPARQL transformer and wrong query

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#73]
Create pipeline with a transformer containing a query:

DELETE {?s ?p ?o} where {?s ?p ?o FILTER regex (?o, "^\s_$")}; 
DELETE {?s ?p ?o} INSERT {?s ?p ?x} WHERE { {SELECT ?s ?p ?o (fn:replace(str(?o), '^\s+(\S+._)$', '$1')) AS ?x WHERE {{?s ?p ?o}}} FILTER (BOUND(?x))};

when the pipeline is executed, look in show log dialog, click on DPUINFO for the transformer. As a result, it displays: 
![screen shot 2013-07-02 at 1 12 17 pm](https://f.cloud.github.com/assets/3014917/736087/78918536-e309-11e2-8d3a-8980bf267fb0.png)

However, it should open the dialog with DPU event description. THe problem in this case is the missing declaration of the "fn" namespace

**Comment by tomesj** [comment]
SPARQL query doesnt support regular expression - prefix fn: can be used only with defined prefix.

**Comment by tomas-knap** [comment]
That is true, but why did the given exception occur? I would expect something as "SparqlQuerySyntaxError", with  explanation that there is problem with the undefined prefix or something like that.

**Comment by tomas-knap** [comment]
Jirka, can you please update me on this?

**Comment by tomesj** [comment]
Yes, I try make it :-)

**Comment by tomesj** [comment]
Solved - using SPARQLUpdateValidator.
