### ISSUE TITLE
Browse/Query tab - results of select query

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#732]
The order of columns should reflect the order of variables in the Select query

![screen shot 2013-11-07 at 5 00 24 pm](https://f.cloud.github.com/assets/3014917/1492852/c7445408-47c5-11e3-83b7-b7b930141f64.png)

**Comment by tomas-knap** [comment]
high visibility, increasing prio

**Comment by bogo777** [comment]
I need some support from RDF part. I currently use: binding.getBindingNames() but the names aren't ordered according to query. I need some object/method, which can extract column names in correct order from the query.

**Comment by tomas-knap** [comment]
binding.getBindingNames() - binding is instance of what class?

**Comment by bogo777** [comment]
It is org.openrdf.query.BindingSet

**Comment by tomas-knap** [comment]
And which Jirka's class/method do you use to get such set?

**Comment by bogo777** [comment]
This set represents one result. I iterate through them from MyTupleQueryResult, which is result of .executeSelectQueryAsTuples() on RDFDataUnit.

**Comment by tomas-knap** [comment]
Jirka please provide suggestions how to solve that, than we can discuss. Preferred solution is to use certain openRDF methods to get all the return variables in the select query in the order as written in the query. You should not write any parser for parsing the query on your own.

**Comment by tomesj** [comment]
You should use instance MyTupleQueryResult (as executeSelectQueryAsTuples()) and call method getBindingName - it returns List<String> and then using an iterator you get the names of pattern in the correct order.

**Comment by tomesj** [comment]
I go throth Bohuslav code and find place with variables order problem. This problem could be solved now.

**Comment by tomas-knap** [comment]
Jirka, so what should Bohuslav do to solve the issue from his side? 

And question from my site, how did you help yourself by introducing private List<String> headers? It is still unordered, right?

**Comment by tomesj** [comment]
Bohuslav have nothing to do, I solved the problem yet.

I add list header (it was necessary how get right order header need for table) and use getBindingNames() on MyTupleQueryResult via using next() - BindingSet
- this cause right variable order same as in SELECT query.
