### ISSUE TITLE
Backend should log to a defined file, which is specified as param of backend

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#733]

**Comment by tomas-knap** [comment]
Sample use is: java -jar backend.jar -config "/x/y" ?

**Comment by skodapetr** [comment]
For defining the config.properties yes (or you can use just -c "\x\y" then from the configuration file the path to the log directory is loaded. 
Is that enough? Adding possibility to set log directory from cmd line should take no more the 10 minutes ..

**Comment by tomas-knap** [comment]
Yes, it is enough as it is. Just please document -c param in the documentation (install doc)
