### ISSUE TITLE
Problem when playing with more tabs

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#734]
I opened second tab without using login screen, then I was working with both tabs. After a while, I got: 

![screen shot 2013-11-08 at 11 10 56 am](https://f.cloud.github.com/assets/3014917/1499614/2a472f9c-485e-11e3-83d6-e66382450354.png)

further, when clicking on gui, the layout is broken

**Comment by tomas-knap** [comment]
Please try to test the tool via two tabs, then leave them open for a while and the try to test again

**Comment by tomas-knap** [comment]
Should I test that?

**Comment by bogo777** [comment]
It is ready for testing.
