### ISSUE TITLE
Move pipelineList business logic to facades

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#735]
PipelineListModel contains method, which should be directly implemented on the pipelineList facade. please move these methods there

**Comment by janvojt** [comment]
What is the status of this issue? Which methods are misplaced?

**Comment by skodapetr** [comment]
Já bych se v souvislosti s tím zeptal, na to jak se bindují aspecty .. jestli by bylo možné je všehny upravit tak, aby používali bind přes interface Facade (nebo jiný, jenž by třeba přímo říkla, že pokud ho implementuji tak budu ošetřený třeba proti výpadkům DB .. ) a nikoliv podle balíčku?

**Comment by tomas-knap** [comment]
THis issue is outdated, but please answer Petr's question

**Comment by janvojt** [comment]
Little off topic, but OK. Backend was already binding on Facade interface. I adjusted Virtuoso aspect in commons-app in commit 60b73fcd3cfc407554c0471e5dc5d2962e1e0725.
