### ISSUE TITLE
Reordering of emails in Settings

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#737]
When adding new emails on settings->my account, and clicking save, the inserted emails may be reordered (alphabetically), which is confusing. They should appear in the order as they were inserted.

**Comment by tomas-knap** [comment]
This also happens in notification tab when schedulling event

**Comment by kukharm** [comment]
E-mails are reordered because during the addition of  the new e-mail in GUI I use LinkedList but then when emails save to DB LinkedList converted to HashSet because of function 
    public void setEmails(Set<EmailAddress> emails) {
        this.emails = new HashSet<>(emails);
    }
the order is changed..
Question to Jan: could we use LinkedList instead HashSet for saving to DB?

**Comment by janvojt** [comment]
Changing to List would not help. Also, by design this is a matter of presentation, so this logic should be in presentation layer. I will order emails by id in presenter.
