### ISSUE TITLE
Schedulling rule name Adjustment

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#738]
1. Instead of "Schedulling rule name" field, please call it "description". Such field should not be mandatory. Currently, if it is not filled, notifications tab cannot be saved! (which is wrong, "description" field should be optional).
2. Move the "Description field to core tab under "Pipeline XX was selected".

![screen shot 2013-11-09 at 1 21 24 pm](https://f.cloud.github.com/assets/3014917/1506629/7e782220-4939-11e3-8783-c5df0eeda520.png)

"3." The length for the description should be unlimited, now it is restricted to 45 chars!

![screen shot 2013-11-09 at 1 24 56 pm](https://f.cloud.github.com/assets/3014917/1506634/2e909cd2-493a-11e3-9afa-c27cbbe5c4b6.png)

"4". List of schedulled events should contain "Description" as the second column

**Comment by tomas-knap** [comment]
Please align combo box and text box

![screen shot 2013-11-21 at 4 09 45 pm](https://f.cloud.github.com/assets/3014917/1592623/fcff25c4-52be-11e3-99f8-4e8a864cf09f.png)

**Comment by tomas-knap** [comment]
Restriction on description UNLIMITED! 

![screen shot 2013-11-21 at 4 11 18 pm](https://f.cloud.github.com/assets/3014917/1592639/32ec18b8-52bf-11e3-9def-c1e87c5ce051.png)

**Comment by kukharm** [comment]
Jan, is there some limits on schedule description column in DB?
