### ISSUE TITLE
Daily summary mails

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#740]

**Comment by tomas-knap** [comment]
Works fine, only I think it would be better to have each pipeline in one row, not as: 

![screen shot 2013-11-23 at 11 09 53 am](https://f.cloud.github.com/assets/3014917/1606261/a84db710-5427-11e3-8f20-dff0e54fa0c0.png)

**Comment by skodapetr** [comment]
Hups .. zapomněl jsem tag pro zalomení řádku .. už by mělo být fajn.

Jinak tvar emailu je sestaven "builderem" v backend.report .. tj. pokud by bylo třeba nějaké lepší struktury, barviček, textu .. není problém dodat a modifikovat.
