### ISSUE TITLE
Sheduller event duplicated. Pipeline exec scheduled twice

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#743]
Firstly, Jakub was reporting:

![screenshot_2013-11-10-21-15-48](https://f.cloud.github.com/assets/3014917/1511229/49a0562a-4aa7-11e3-8db8-06367c05dbb1.png)

Based on that, it seems that 4900 was scheduled twice. But when looking to scheduler events, there are two events for 4900:

![screen shot 2013-11-11 at 9 06 46 am](https://f.cloud.github.com/assets/3014917/1511273/9c6a2aba-4aa8-11e3-8248-d7dc2368c599.png)

So the problem is probably with the table of events. Maria, please try to test on your localhost. Try to create event, save event, update certain detail of the pipeline and save again, wait for the schedulled execution (schedule it every few minutes) Repeat for another couple of pipelines.

**Comment by kukharm** [comment]
I catch the next bug: when i double click on Scheduler table row then two windows of one Scheduling rule open (the same is for users table). 
But after saving each of the window the new rule is not created so this is not the cause of duplication. I can not reproduce duplication.

Bohuslav, please look to this windows opening.

**Comment by tomas-knap** [comment]
Have created issue for the two dialogs instead of one - see #784 

Regarding this issue, Marie, could you please focus your testing now on the scheduler events? Again, please write a report in a similar way as in https://grips.semantic-web.at/display/LOD2/Testing 
Please focus on the creation of tens of schedulling events, with couple of different configurations and observe if everything is schedulled once. Before schedulling, create copies of the pipelines (e.g. of the dbpedia pipeline), so that you can schedule more pipelines in parallel

**Comment by kukharm** [comment]
report https://grips.semantic-web.at/display/LOD2/Testing

**Comment by tomas-knap** [comment]
cannot reproduce
