### ISSUE TITLE
Internal error when debugging data

### ISSUE THREAD

**Issue by akreiserswc** [mff-uk/odcs#746]
![odcs-eval-pipeline-error3](https://f.cloud.github.com/assets/4112906/1513859/f4342710-4ae8-11e3-91ef-e4b9aff8589f.png)
1. Debug a pipeline
2. Go to Browse / Query
3. Select a DPU and "output"
4. Click on browse

Stacktrace:
java.lang.UnsupportedOperationException: Incomplete statement
    at org.openrdf.model.impl.TreeModel.add(TreeModel.java:230) ~[sesame-model-2.7.7.jar:na]
    at org.openrdf.model.impl.AbstractModel.add(AbstractModel.java:51) ~[sesame-model-2.7.7.jar:na]
    at org.openrdf.model.impl.AbstractModel.add(AbstractModel.java:41) ~[sesame-model-2.7.7.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.impl.MyGraphQueryResult.asGraph(MyGraphQueryResult.java:54) ~[RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.rdf.repositories.BaseRDFRepo.executeConstructQuery(BaseRDFRepo.java:1032) ~[RDF-1.0.0.jar:na]
    at cz.cuni.mff.xrg.odcs.frontend.container.RDFQuery.loadItems(RDFQuery.java:95) ~[RDFQuery.class:na]

**Comment by tomesj** [comment]
Probably due to some already caught a bug. Currently, everything is OK in the described scenario. In the event that the problem occurred again, please re-open this issue.

**Comment by tomas-knap** [comment]
Alex, what was the commit you managed to find this bug in?

**Comment by tomas-knap** [comment]
Alex, could you please send us also the definition of the pipeline?

**Comment by akreiserswc** [comment]
I tested again today with commit c6710011cc651d7830a6318a104457be946e83e8 and can still reproduce it.

My pipeline just has one extractor:

SPARQLExtractor
SPARQL Endpoint: http://sparql.reegle.info/sparql
Named Graph: http://data.reegle.info
SPARQL Construct:
PREFIX owl: http://www.w3.org/2002/07/owl#
PREFIX foaf: http://xmlns.com/foaf/0.1/

CONSTRUCT { ?dbpedia a foaf:Organization } 
WHERE {
 ?x a foaf:Organization. ?x owl:sameAs ?dbpedia. FILTER (regex(str(?dbpedia), '^http://dbpedia.org'))
}

**Comment by tomesj** [comment]
I tested Alex use case: 
1) Only one SPARQLExtractor 
2) Debug pipeline
3) Execution Monitor -> Browse/Query, select dataUnit:output, button "RUN QUERY"

But there was no problem - I get 5 triples as result. 

See my screenshot:
![image](https://f.cloud.github.com/assets/3481055/1540306/0114d696-4d1e-11e3-8077-fc955a3e0876.png)

**Comment by akreiserswc** [comment]
Possible it is something on my end - I will test again and try to narrow it down..

**Comment by akreiserswc** [comment]
I wasn't able to solve the problem on my machine but it works on a new installation we did today for one of our research projects.
So I guess it is something exotic on my PC that causes it - I will hence close the issue.
