### ISSUE TITLE
Browse/Query tab - no data unit select

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#748]
if no data unit is selected, browse button is correctly disabled. But the run query /run query and download should be disabled as well.

Otherwise, when no input is selected and run query pressed: 

![screen shot 2013-11-13 at 1 54 52 pm](https://f.cloud.github.com/assets/3014917/1531345/0f2beb0e-4c63-11e3-9f70-51f92c469f7b.png)

Please try to solve that for the tomorrow's push

**Comment by tomas-knap** [comment]
The error message than appears again and again

**Comment by bogo777** [comment]
Solved by merging branch executionlist 8d9ef4b079b49dc748488a86b3e9e3c1b2b27e72
