### ISSUE TITLE
RDF File Loader - file extension

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#753]
I set to the DF File Loader   RDF Format: TTL, File path: C:/ted/dbpedia2 after running the pipeline i get file dbpedia2 without extension. Is it correct or i should get file with .ttl extension as set on RDF Format combobox?

And if i set RDF Format: N3, File path: C:/ted/dbpedia2.ttl i get dbpedia2.ttl file. In what format it is really?

**Comment by tomesj** [comment]
Yes, if you set concrete RDF format, you dont get file extension automatically to your given filepath.

So you can create files as 
file, file.mysufix, file.rdf, file.data, ...
(it doenst have any suffix, or whatever you want to have)

Importat is only RDF format for data you select !!!

Data are saved to file always in your selected format !!! (TTL for example).

This situation is very similar for using file extractor with one change:
If you select AUTO format - application try to guess RDF format from file suffix, if file has no suffix, is used default RDF format and in case of problems are thrown an exception.
