### ISSUE TITLE
Execution monitor - Browse/Query

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#754]
Now Browse/Query tab is disabled for USER for all executions. And enabed for ADMIN for all executions. 

Tomas explained me concerning Browse/Query tab:
"Melo by byt enabled kdyz dobehne pipeline v debug rezimu. Pokud ne, je to chyba."

**Comment by tomas-knap** [comment]
JJ, tohle se mi stalo vcera take, to je bug.

**Comment by bogo777** [comment]
Please test it now, I made some changes in branch which I merged today. For me it works fine for both user and admin account. If it's ok, please close the issue.

**Comment by tomas-knap** [comment]
Maria, test that
