### ISSUE TITLE
Delete DPU bug

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#755]
I delete RDF File Loader from DBpedia pipeline. Then  open DBpedia pipeline for Edit - SPARQL Extractor is disappeared too, canvas is empty! 

Then i tried to copy DPpedia pipeline and run. Pipeline run like it has SPARQL Extractor (there events about them) but when i open it to edit it looks like empty too.

**Comment by tomas-knap** [comment]
Marie, please write which browser/version are you using

**Comment by kukharm** [comment]
Google Chrome  version  30.0.1599.101 m 
I tried this scenario one more time but the bug was not reproduce..

**Comment by kukharm** [comment]
Ted mi napalo, mohlo to stat napriklad kvuli tomu, ze dosla pamet? Dneska jsem mazala dpu nekolik krat a vsechno bylo vporadku. Ale jednou kdyz jsem nekolik krat otevirala a zavirala pipelinu tak mi stalo tohle: 
-jsem otevrila pipelinu ale zmizeli hrany, 
-jsem zavrela a otevrela znovu vsechno bylo na miste ale neposluchalo mys, nemohla jsem nic tam pohnout ani otevrit
-jsem zavrela a otevrela po treti - canvas byl uplne prazdny

to jsem zkousela ve Firefoxu 24.0, pak jsem zavrela ho a otevrela v chromu a  vsechno uz bylo vporadku

**Comment by tomas-knap** [comment]
cannot be reproduces, out of mem issue?
