### ISSUE TITLE
Support containsId() method in ReadOnlyContainer

### ISSUE THREAD

**Issue by bogo777** [mff-uk/odcs#757]
For selecting rows in tables using ROC, containsId() method is needed. 

From specification:
https://vaadin.com/api/com/vaadin/data/Container.html#containsId(java.lang.Object)
it might be enough to test it only against currently shown items(current page).

As discussed this should be easy to implement?(use cache)

**Comment by skodapetr** [comment]
Yes .. this functionality is ready and will be available probably tonight.

I also test it by opening detail on ExecutionList by clicking on item and it works fine. (there is still the issue with slow loading of logs .. but this is different story :)
