### ISSUE TITLE
When debugging from canvas, problem with browse

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#759]
open dbpedia pipeline, try to debug till the second dpu, go to browse/query tab - firstly it is prefilled with values but these values dissapear immediately (the fact of dissapearing when switching to the tab looks really awfull). further, when closing the debug, reruning the debug from canvas, going to browse/query, clicking on browse, results appear but the header of the browse/query tab is still dissapearing (disabling), really annoying.

**Comment by bogo777** [comment]
Solved by e12f61c604039af6b89303b65240f4a7d5d151db
