### ISSUE TITLE
Do not use DPU name in path to save localRDF data.

### ISSUE THREAD

**Issue by bogo777** [mff-uk/odcs#760]
If DPU name is used, as it is now, after renaming the DPU the data are inaccessible. For virtuoso it work ok after rename and it should be consistent.

Instead of name, use only id, which remains the same after rename.

Please reassign if you're not responsible for this.

**Comment by tomesj** [comment]
I never use DPU name in RDF for saving /loading RDF data - there is only File directory as parameter for it. 

May is this directory bad set using DPU name. Or it could be caused maybe by using repository when it not access yet (calling one of methods as shutDown, release or delete). I check my code for sure, but mistake is not here.

I assign this for Peter.

**Comment by skodapetr** [comment]
Ok, the name is no longer use (I just forgot to mention the issue name in commit). Just remember that this will broke all existence data in local repositories !!

**Comment by skodapetr** [comment]
Bohuslav (author) please leave this comit open, as Thomas can close it once this will be used on odcs. (we may need to create some conversion script for existing data).
