### ISSUE TITLE
Add visible column list to ClassAccessor and ReadOnlyContainer

### ISSUE THREAD

**Issue by bogo777** [mff-uk/odcs#761]
I would need for ClassAccessor to have list for visible column. For example, in records table, I need dpu instance id for enabling link to logs with preselected dpu instance. But I don't want this to be a visible column in the records table.

Also, when I add generated column to table, it is added as last column. This could override it. I would make method on table, which would ask container for visible columns and set it(as it works now for sortable and filterable columns).

Is there any problem?

**Comment by skodapetr** [comment]
I think it's ok. The can be if we don't want use other technique to create those lists as we now have 4 of them?

Maybe we can use some powerlist list like .. 

id = [Column.new(id, visible, sortable, filterable) ] ..

or we can even add lambda-classes into this is .. which will do access to data. The advantage can be that programmer has to write the column-id on only once place. 

But for now I think the simple solution (add another list) is just ok. You can add it on your own if you wish?

**Comment by skodapetr** [comment]
I see you have added the visible list already. So I change the priority to low .. just in case we will decide to try use more sophisticated approach for creation of this lists.

**Comment by skodapetr** [comment]
We now have new possibility how to create accessors (I forgot to mention this issue in commit). So closing. 
For more details see NewLogAccessor .
