### ISSUE TITLE
Non unique primary key - When new user is created

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#763]
![screen shot 2013-11-15 at 8 09 15 am](https://f.cloud.github.com/assets/3014917/1548345/ec8f532a-4dc4-11e3-855e-1b2772d533e0.png)

It does not disappear when re-saving.

To reproduce: Manage users, new user
On odcs.xrg.cz

**Comment by tomas-knap** [comment]
Actually it is strange that the problem is somehow associated with SCH_EMAIL table

**Comment by janvojt** [comment]
To resolve run [queries for updating sequences](https://github.com/mff-uk/ODCS/blob/cc20bdea5156e809a06540b95f97091e1f97eeaa/db/virtuoso/rdbms/data.sql#L102). I explained how this problem happens at the meeting. I fear that there will be no elegant way to get around this.

> Actually it is strange that the problem is somehow associated with SCH_EMAIL table 

It is not strange, because user email is saved in this table.

**Comment by tomas-knap** [comment]
Yes, but we have to solve this type of issues, e.g. by catching the exception, executing the queries and replaying the user action, so that user does not know that something happen.

**Comment by janvojt** [comment]
I did some googling and found a [bug report/article](http://knowledgebase.progress.com/articles/Article/P89986), where sequence changes made outside of transaction context were lost after DB crash. However this was reported on a different DBMS. I will do some more testing to see how exactly the issue can be reproduced.

If this happens in transaction context as well, I will probably need to parse out the update queries from SQL script during maven build and save it to resources. Then the best solution would probably be to use AspectJ to catch the general VirtuosoException, and if it is a problem with sequences (which could be parsed out from detail message if it has no specific code), run update queries and retry.

**Comment by tomas-knap** [comment]
Is this solved by the aspects?

**Comment by janvojt** [comment]
I described my problem on [stackoverflow](http://stackoverflow.com/questions/20428248/can-i-weave-aspect-into-same-maven-module-it-was-defined-in-and-into-a-3rd-party), but I got no answer. I will try to solve it myself tonight. It is only about configuring maven, everything else is working.

**Comment by tomas-knap** [comment]
Ok, or you may wait one or two days just in case some answer arrives. If not, then you finish it yourself

**Comment by janvojt** [comment]
Allright, it works.

**Comment by tomas-knap** [comment]
How did you solve it finally?

**Comment by tomas-knap** [comment]
uz vidim
