### ISSUE TITLE
Delete pipeline - confirmation dialog should contain the name of the pipeline being deleted

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#764]
![screen shot 2013-11-15 at 8 25 42 am](https://f.cloud.github.com/assets/3014917/1548404/2aec3cf8-4dc7-11e3-8c1e-be0c61a1bf1a.png)

**Comment by kukharm** [comment]
I changed it before, but now my changes is commented, item.getItemProperty("name").getValue() does not work any more.

```
            //String message = "Would you really like to delete the " + item.getItemProperty("name").getValue() + " pipeline and all associated records (DPU instances e.g.)?";
            String message = "Would you really like to delete this pipeline and all associated records (DPU instances e.g.)?";
```

I do not know how to get the name of pipeline now. I can listed all pipelines and then find the name by id in this list, but i think it would not be a good solution..

**Comment by tomas-knap** [comment]
No that is not the best solution. Bohuslav?
