### ISSUE TITLE
DPU instance cannot be added

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#766]
As reported by Maria: 

I created DBPedia pipeline, copied it, then I delete all of them, create new pipeline but was not able to place DPU instance on it. 

Please try to reproduce

**Comment by bogo777** [comment]
I made some changes to canvas related code in 9b3c22f . Please test, if this still occurs, as it doesn't for me and close if not.

**Comment by tomas-knap** [comment]
Maria, please test
