### ISSUE TITLE
Download button from debug dialog launched from canvas not working for logs

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#767]
![screen shot 2013-11-15 at 9 20 56 am](https://f.cloud.github.com/assets/3014917/1548598/e4413e68-4dce-11e3-8275-cd868c24c587.png)

**Comment by tomas-knap** [comment]
Alex will be testing this, increasing prio

**Comment by bogo777** [comment]
Can you test it on the latest version, I made some changes to this in e12f61c604039af6b89303b65240f4a7d5d151db which could be relevant. For me it works fine now.

**Comment by tomas-knap** [comment]
ok
