### ISSUE TITLE
Display descriptions of data units

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#768]
When clicking on edges on the canvas, mapping dialog appears. When pointing on some data unit (input or output), description of such unit should appear in the tool tip (if the description is available in the code). Discuss with Petr how to get the description.

**Comment by skodapetr** [comment]
The commons.app.dpu.DPUExplorer provide methods getInputs, getOutputs .. the return type is List<DataUnitDescription> .. 
The DataUnitDescription class contains all we got about the DataUnit (event type name as a string)

This DPUExplorer is already used I belived. So this can be small local modification.

**Comment by tomas-knap** [comment]
Maria, this has high priority. Why it is not done yet?

**Comment by kukharm** [comment]
Because there was some problem. For ListSelect (that used for data unit) rows don't exist standard vaadin method for tooltip. I consulted with Bohuslav he suggested to change ListSelect to Table. For table there is method for rows tooltip. So i try to do it.

**Comment by tomas-knap** [comment]
Ok, thanks for clarification. Then please try the table with one column

**Comment by bogo777** [comment]
Maria have you made any progress before it was reassigned to me? Any code I could use?

**Comment by kukharm** [comment]
I changed ListSelect to Table 

```
public IndexedContainer getTableData(List<DataUnitDescription> data) {

    IndexedContainer result = new IndexedContainer();
    result.addContainerProperty("name", DataUnitDescription.class, "");
    for (DataUnitDescription item : data) {
        Object num = result.addItem();
        result.getContainerProperty(num, "name").setValue(item);
    }
    return result;
}

    outputSelect = new Table("Output data units of the source DPU:");
    outputSelect.setSelectable(true);
    outputSelect.setMultiSelect(true);
    outputSelect.setNewItemsAllowed(false);
    outputSelect.setWidth(250, Unit.PIXELS);
    outputSelect.setImmediate(true);
    outputSelect.setPageLength(8);
    outputSelect.setColumnHeaderMode(Table.COLUMN_HEADER_MODE_HIDDEN);
    outputUnits = explorer.getOutputs(edge.getFrom().getDpuInstance());
    outputSelect.setContainerDataSource(getTableData(outputUnits));
```

and then added tooltip to table's cells this way

```
    outputSelect.setItemDescriptionGenerator(new ItemDescriptionGenerator() {

        @Override
        public String generateDescription(Component source, Object itemId,
                Object propertyId) {
            if(propertyId == null){
                return "Row description "+ itemId;
            } else if(propertyId == "name") {
                return "Cell description " + itemId +","+propertyId;
            }
            return null;
        }
    });
```

but i can't this way to get tooltip for element in the cell only for cell
