### ISSUE TITLE
view with logs - exception

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#769]
From honza: Also, if view with logs throws an exception, it is not displayed again (for any other execution) until application is reloaded in tomcat.

**Comment by tomas-knap** [comment]
Bohuslav, can you please comment this? do you need any more info from Honza?

**Comment by bogo777** [comment]
It is common problem in our application. If exception occurs during initialization of component/view/etc. it is in invalid state, but it's not null, so next time it is used as if it was already initialized.

Proposed solution 1:
Identify places when components which are re-used are initialized and surround them with try-catch block. If exception occurs, reset the component as if it was not yet initialized. It should be initialized with next request.

Proposed solution 2:
Identify places when components which are re-used are initialized and remove all data-dependent code to section which is called at every access.

**Comment by tomas-knap** [comment]
Well, if there is an exception which then causes the component to be in invalid state, it could also set the component again to null, right? and then should be inicialized again. 

Or simply always inicialize it. (which may have inpact on the time needed to show the components/dialogs). 

So I would go for the first solution.

petr also had some solution, discuss also with him

**Comment by bogo777** [comment]
We discussed with Petr and came to conclusion, that we should set the object being initialized as last step in init method. So if it fails before, it is still null and will be initialized again upon next request. There are possibly many places in code, which need to be changed, I would do it in one step with autowiring/refactoring.

For this current case it should be solved already.
