### ISSUE TITLE
Checkbox "use statistical handler" for extractor 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#77]
An extractor from RDF file/SPARQL endpoint should have an optional checkbox "use statistical handler", which allows to monitor better the extraction process (and also log).  

In the log, there should be at the level of debug information about every triple which has certain problem when the triple was loaded (e.g. wrong datatype, wrong URI...). There should be also information in the log at the level of info about number of triples loaded.

**Comment by tomesj** [comment]
Use statistical handler prepared, added to dialog.

**Comment by tomas-knap** [comment]
Jirko, could you please implement the handler, so that it logs the problems with the data (if the error/warning method of the handler is invoked) and computes the number of triples loaded and then writes it to the log?

**Comment by tomesj** [comment]
Solved as commit d562d4f98e752b687fd0f521a59551b35555486c
