### ISSUE TITLE
Browse/Query tab - put together the format and "run & download" button

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#770]
Motivation: Format is not relevant for the second button, but this is not obvious.

![screen shot 2013-11-15 at 2 32 57 pm](https://f.cloud.github.com/assets/3014917/1550094/7b08311e-4dfa-11e3-83f7-a3f361f66430.png)

So please introduce some panel, which will involve the the combo box and the first button "run and download". Also please the fist button should be "run query", under this button, there should be panel with format selection and download

**Comment by kukharm** [comment]
changes need to pre-clear the browser cache

**Comment by tomas-knap** [comment]
Thanks, could you please change the background color of the panel to white as well?

**Comment by tomas-knap** [comment]
Than we can close
