### ISSUE TITLE
When downloading results of browse/query

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#771]
1. When downloading resutls of browse/query as Trig, the name of the named graph is missing in the downloaded file. Use the name of the graph introduced in the dialog below the data unit combo box. 
2. Use label "N-Triples" in the combo box, not "NT"
3. Use label "RDF/XML" instead of RDFXML

**Comment by tomas-knap** [comment]
Adjust in both combo boxes

**Comment by tomesj** [comment]
Solved :-) Prepared to close
