### ISSUE TITLE
When copying pipelines, the names of the copies must be different

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#773]
When creating multiple copies of the same pipeline, their implicit names must be differernt. Please reassign if needed.

**Comment by janvojt** [comment]
Please specify what exactly does "different" mean. I would suggest the following:

Let's say pipeline name is `DBpedia`. The new name then should be `Copy of DBpedia`. If the new name is taken, append `#1` to it and try again. If this is taken, append `#2` to the new name, so the name of the copy would be `Copy of DBpedia #2`, and so on.

Is this OK?

**Comment by tomas-knap** [comment]
yes
