### ISSUE TITLE
Same name when using COPY pipeline

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#776]
If I create multiple copies of the same pipeline - All has the same name, but only different ID. 

Example:
I have a pipeline A (2 copies)
I get:
Copy of A (id 10)
Copy of A (id 11).

And when I some of these COPIES randomly edit and then I can save or save & close
- I get error that the pipeline with the same name already exists in the system !!!

If is not issue for you, please re-assign it for responsible person :-)

**Comment by skodapetr** [comment]
Maybe ... it depends .. this is similar problem to the DPU copy .. we can use 
1) stored procedures to generate unique name
2) let use fill that name for use, and then show just "warning" in case of conflict - imho the easiest solution

Thomas, can I ask for you opinion?

**Comment by skodapetr** [comment]
ie. duplicit to #773 ..
