### ISSUE TITLE
When clicking on the exec monitor record, no detail dialog appear

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#777]
![screen shot 2013-11-16 at 1 11 11 pm](https://f.cloud.github.com/assets/3014917/1556204/56c46e76-4eb8-11e3-81fa-928bcfe3b040.png)

**Comment by bogo777** [comment]
Does this still occur? Can you give me step-by-step how to reproduce it?

**Comment by tomas-knap** [comment]
cannot reproduce now, reopen if it appears
