### ISSUE TITLE
Uploading file using file extractor

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#778]
When I you use File extractor and the choise upload a file -  so when I save and try to run run (or debug) pipeline, I always get an exception that the file path does not exist.

There is maybe that 
- you upload to temporary/hidden folder
- file system has not access (not enough privileges)

Your goal is test this use-case again, write problems what do you found out, and try to solve this.

**Comment by tomas-knap** [comment]
Should be ok, if the settings for temp dir are correct
