### ISSUE TITLE
Configuration dialog by double click

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#780]
I open DPU for editing and make some changes on canvas: delete and add dpus, replace dpus, change edges. After that i can not open dpu configuration dialog by double click

**Comment by tomas-knap** [comment]
See https://grips.semantic-web.at/display/LOD2/Testing
for the detail scenario to reproduce the bug

**Comment by bogo777** [comment]
I made some changes to canvas related code in 9b3c22f1527637d06cf851547d06dfa72f064655 . Please test, if this still occurs, as it doesn't for me and close if not.

**Comment by tomas-knap** [comment]
Maria, please test

**Comment by kukharm** [comment]
Can not test in scheduler because of exception #804 In user's table it's ok

**Comment by kukharm** [comment]
I tested scheduler by creating records in Scheduler table from Pipelines table. It's also ok, dialog for edit opens one time.
