### ISSUE TITLE
Debug window- log tab error

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#781]
I click on some row in the Log tab of Debug window and get error.
![error2](https://f.cloud.github.com/assets/3471169/1557356/b8476de8-4f11-11e3-9e38-63a2805b1f26.jpg)

then i go to Execution Monitor and try to open this last execution - i get exception

![exception](https://f.cloud.github.com/assets/3471169/1557369/465bfb80-4f12-11e3-846b-77eedd97ab1d.jpg)

**Comment by tomas-knap** [comment]
See https://grips.semantic-web.at/display/LOD2/Testing
for the detail scenario to reproduce the bug

**Comment by tomas-knap** [comment]
Petre, discuss with Honza, who is responsible and reassign if needed

**Comment by skodapetr** [comment]
This was clearly problem with ClassAccesor (missing id column) and class casting .. maybe Bohuslav is more responsible then Honza .. but it was easy to fix, so it should be ok by now

**Comment by tomas-knap** [comment]
Maria, please test and close

**Comment by kukharm** [comment]
Now it's ok
