### ISSUE TITLE
Save as dpu template - exception

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#782]
I open dpu configuration dialog and try to save it as dpu template -  exception
![exception2](https://f.cloud.github.com/assets/3471169/1557387/b805c742-4f13-11e3-95ad-3bfb683f905a.jpg)

**Comment by tomas-knap** [comment]
See https://grips.semantic-web.at/display/LOD2/Testing
for the detail scenario to reproduce the bug

May be a consequence of #781 

Bohuslav, please reassign if it is not a problem in your code
