### ISSUE TITLE
Click on record in Events and LOG table cause an exception

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#783]
If you click on some row (record) in table Events or LOG you got an exception:

Bad cast - It´s expected ValueItem, but is used CompositeItem.

See
![image](https://f.cloud.github.com/assets/3481055/1557490/64196fa6-4f1a-11e3-91a5-cf50f6e0190c.png)

**Comment by skodapetr** [comment]
The component is shared, so it's the same as #781, so closing
