### ISSUE TITLE
DBpedia execution is Failed

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#785]
DBpedia execution is Failed

```
DPU 'SPARQL Extractor' publish message short: 'HTTP/1.1 405 Not Allowed. Caused by <html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.4.2</center>
</body>
</html>


URL endpoint: http://dbpedia.org/sparql POST content: default-graph-uri=http%3A%2F%2Fdbpedia.org&query=CONSTRUCT+%7B%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FPrague%3E+%3Fp+%3Fo%7D+where+%7B%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FPrague%3E+%3Fp+%3Fo+%7D+LIMIT+100&format=text%2Fn3' long: ''
```

**Comment by tomas-knap** [comment]
See https://grips.semantic-web.at/display/LOD2/Testing for steps to reproduce

But Maria, please try again first, could be cause by DBPedia SPARQL endpoint being down

**Comment by kukharm** [comment]
I tried to run i one more time (nothing has changed), now it finished successful.

**Comment by tomas-knap** [comment]
Also the ordering of the executions was ok?

**Comment by kukharm** [comment]
Today Events

18.11.2013 12:36:49                 Starting execution of pipeline
18.11.2013 12:36:49 SPARQL Extractor    DPU started.
18.11.2013 12:36:50 SPARQL Extractor    DPU completed.
18.11.2013 12:36:54     File Loader     DPU started.
18.11.2013 12:36:54     RDF File Loader     DPU completed.
18.11.2013 12:36:59             Pipeline finished

Yesterday Events

18.11.2013 1:20:29              Starting execution of pipeline
18.11.2013 1:20:33  SPARQL Extractor    DPU started.
18.11.2013 1:20:33  SPARQL Extractor    HTTP/1.1 405 Not Allowed. ...
18.11.2013 1:20:34  SPARQL Extractor    Pipeline execution failed.
18.11.2013 1:20:34  SPARQL Extractor    DPU completed.
18.11.2013 1:20:37              Pipeline finished

**Comment by tomas-knap** [comment]
I meant whether the order of pipeline exeuctions (dbpedi-1 - dbpedia-10) was correct - according to the scheduler

**Comment by kukharm** [comment]
Yes it was correct. Problem was not in schedule, i also tried to run this pipeline from Pipeline section without scheduler and the result was also failed.
