### ISSUE TITLE
After pipeline execution bug

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#787]
I create scheduling rule with After pipeline option and select several pipelines. Pipeline by this scheduling rule starts execute before than all of selected pipelines finish.

For details see https://grips.semantic-web.at/display/LOD2/Testing  (17.11.)

**Comment by skodapetr** [comment]
yes .. that expected .. it should start after at least one pipeline from list finished .. (the operation on pipeline list is OR not AND) .. I guess we should refer to the documentation for more info ..

**Comment by kukharm** [comment]
according to documentation https://grips.semantic-web.at/display/LOD2/Scheduler

Schedule the pipeline to run after another pipeline has finished. User then selects from list of accessible pipelines the one after which execution of this pipeline should run. Multiple pipelines can be selected in one rule. The pipeline will run after all the selected pipelines finish. List of pipelines is presented with check boxes on each line for selecting pipelines. (see Mockup1, Scheduling a pipeline, Second option)

**Comment by tomas-knap** [comment]
Well we can add one more choice to scheduler dialog - "to run after all selected pipelines finished" and "to run after one of the selected pipelines finished"

**Comment by tomas-knap** [comment]
Maria, please check that and close

**Comment by kukharm** [comment]
I created 3 copies of DBpedia pipeline DBpedia #1, DBpedia #2, DBpedia #3. And created 3 scheduling rules for them (as automatically run). Then i created after pipeline rule for DBpedia pipeline and set it to run after pipelines:  DBpedia #1, DBpedia #2, DBpedia #3. The result:
After pipeline (DBpedia ) was executed after DBpedia #1 pipeline was executed.
![sch](https://f.cloud.github.com/assets/3471169/1816875/f508571c-6f58-11e3-977a-2fe9f53c6962.jpg)

**Comment by skodapetr** [comment]
We have other "issue": if the pipeline (S) should run after A, B, C .. if the S is disabled .. and A, B, C ran .. then schedule for S is enabled .. the S is not executed until 1) backend restart 2) one of A, B, C is executed
(as these are the times when run-after check is performed)

@kukharm can you please retest and add the above into the documentation? For more details please feel free to skype

**Comment by kukharm** [comment]
please explain how should it work (i'll will add it to doc). now it works the same as i describe at the beginning - the execution start after at least one pipeline from list finished. Is that right?

**Comment by skodapetr** [comment]
Yes it is.

**Comment by kukharm** [comment]
I changed the information in the doc
