### ISSUE TITLE
Browse/Query behaviour - last query

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#792]
When clicking on browse/query, clicking on browse, than switching to a different exec record and back to the previous, I can se the result of the previous query but not the query itself. 

I quite like that the last result of browse/query remains available till the next query but the problem is that the upper part is always disabled when opening the tab so it does not reflext the result displayed.

![screen shot 2013-11-19 at 11 40 05 am](https://f.cloud.github.com/assets/3014917/1571534/58fad3d2-5107-11e3-98a1-7f305cc339c7.png)

When there is a result cached, show also proper header (dpu, data uni, query) for the result.

**Comment by tomas-knap** [comment]
However, when switching from one pipeline exuction record to another, I should not be able to see the previous query relating to a different execution record!!

**Comment by bogo777** [comment]
This behaviour is result of simply not properly clearing data when different execution record is set. So when I will change that, there will be no more cached records, it will stay there only when changing tabs Events, Logs and Browse/Query for the same execution. Is that ok?

**Comment by tomas-knap** [comment]
That is ok

**Comment by bogo777** [comment]
Resolved by a3cca55f430d2a6431c6cf75b068695c3c338070
