### ISSUE TITLE
Fix text

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#796]
![image](https://f.cloud.github.com/assets/718827/1590168/90d2a772-5287-11e3-8e55-617155444afb.png)
Text is misleading. Should be "Starting pipeline execution 509" - it is the number of an execution, not of the pipeline

**Comment by skodapetr** [comment]
Now it should be "Starting execution number:509 pipeline: BuyerProfile"

The reason why I preserve the name of the pipeline is, that when raeding logs (in file) this give you information which pipeline is executed. Is this ok?
