### ISSUE TITLE
Update Vaadin version to solve issue with IE

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#797]
See #790

**Comment by skodapetr** [comment]
Just side note .. we have to change the packages-version in comons.app com.vaadin.package list.

This will also require recompilation of DPUs.

**Comment by tomas-knap** [comment]
We should think how to accommodate Vaadin updates in the future. Recompilation of core modules is ok, but we should not force other to recompile all their module. It is rather better to allow them to use the old version of vaadin (via shared /lib) than starting throwing exceptions when core has a different version

**Comment by skodapetr** [comment]
Topic for next meeting. I also reassign to me .. temproraly

**Comment by skodapetr** [comment]
DPUs now can work with vaadin version 7.1.5 up to 8.0.0 (not included) .. so just change the version in pom.xml a and update version in commons.app - com.vaadin.packageList .. I reassign back to @bogo777 to end the migration
