### ISSUE TITLE
Adjust combo box with RDF file formats also for File extractor/loader

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#799]
![screen shot 2013-11-21 at 3 33 54 pm](https://f.cloud.github.com/assets/3014917/1592360/fe05a3a8-52b9-11e3-81ca-c0b1c02f9d6e.png)

It should be adjusted as combo boxes in the browse/query dialog

**Comment by tomas-knap** [comment]
So that means to use N-Triples and RDF/XML

**Comment by tomesj** [comment]
Format in comboboxes are solved. Prepare to close.
