### ISSUE TITLE
create scheduling rule exception

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#804]
I push Add new scheduling rule button and get exception 

![ex](https://f.cloud.github.com/assets/3471169/1592605/833d605c-52be-11e3-968d-9f24732af74d.jpg)

**Comment by tomas-knap** [comment]
Maria, this works for me on commit 

commit 1d2ec72596acd491cd0cf96bc95fa65fab662cd3
Author: Jiri Tomes Tooomy@seznam.cz
Date:   Thu Nov 21 13:18:30 2013 +0100

Please try again

**Comment by kukharm** [comment]
I have last commit

commit 7b5d0662bfe66b4f8ad8cb17494c5edbcd0b64e4
Author: bogo777 bogo777@gmail.com 2013-11-21 14:36:52
Committer: bogo777 bogo777@gmail.com 2013-11-21 14:36:52
Parent: fe4093430f9e87f835bc773e69434f14ef199b61 (Describe funcionality in Browse/Query. Autowiring in SchedulePipeline dialog.)
Parent: 16edc9da5b20c0c5c92f74e61539c053d7783ccc (Add comment to getHandlerExtractType method in HandlerExtractType enum.)
Branches: master, origin/HEAD, origin/master
