### ISSUE TITLE
Check that user is always warned when he can loose inserted data 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#805]
For example, in settings, if I change my email and click to scheduler menu item, I am not warned, my data is forgotten

**Comment by tomas-knap** [comment]
Please prepare another testing report in concluence regarding the button save:
- if user is always warned when moving away without saving (for all dialogs)
- if user is warned only if he did some change
- if save button is correctly disabled if no changed data

**Comment by kukharm** [comment]
Now for dialogs (lilke scheduling rule creation, DPU creation, user creation) is not implemented confirmation window at all. Should i implement it?

**Comment by tomas-knap** [comment]
no, no further impl

**Comment by kukharm** [comment]
https://grips.semantic-web.at/display/LOD2/Testing
