### ISSUE TITLE
Remove ILQC from the rest of the components

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#807]
ILQC is still used in list of pipelines in Schedule pipeline dialog. I tried to replace it with ROC, but it is not possible, combobox requires some operations that are not implemented in ROC and I don't know if it is easy to implement them. I know about indexOfId(Object itemId) but there could be more.

Also RDFLQC is used in Browse/Query.

**Comment by skodapetr** [comment]
Please leave this to friday meeting .. to discussion.

**Comment by tomas-knap** [comment]
Please check that our container is used everywhere
