### ISSUE TITLE
Last status in Pipelines does not match the real last status in Exec. Monitor

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#809]
![image](https://f.cloud.github.com/assets/718827/1599391/c780be66-5355-11e3-983b-36dc8e6c51d2.png)
![image](https://f.cloud.github.com/assets/718827/1599398/daaf1c1c-5355-11e3-802b-3a4245a946b0.png)

**Comment by tomas-knap** [comment]
Is this happening still? According to Petr, it should be solved already

**Comment by bogo777** [comment]
This should be already solved by automatic refresh of pipeline list from monday.
