### ISSUE TITLE
When just clicking on "-" button next to emails in settings, save remains disabled!

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#816]
![screen shot 2013-11-22 at 11 56 19 am](https://f.cloud.github.com/assets/3014917/1600023/c56fcebe-5364-11e3-87b4-3637082be0df.png)

**Comment by tomas-knap** [comment]
To reproduce: Add second email, save. Then remove the second email, save button is disabled!

**Comment by tomas-knap** [comment]
Problem neni v tom, ze se da odebrat posledni email, ale v tom, ze kdyz mam save disabled a X emailu a jeden odeberu, tak je save stale disabled

**Comment by kukharm** [comment]
I fixed it in https://github.com/mff-uk/ODCS/issues/821. Now when i remove email save button is enable
