### ISSUE TITLE
Mandatory fields for DPU details should be checked only when DPU is placed on the pipeline, not when DPU template is prepared

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#82]
To reproduce: 

Menu item DPUs -> select DPU (for example extractor). Try to change description. Exception occurs which requires to change also other settings. 

SOlution: Mandatory fields should NOT be checked for DPU templates. DPU template may be incomplete with respect to mandatory fields.

**Comment by tomas-knap** [comment]
Yes, you are right, mandatory fields should not be checked in DPU template, but should be checked in DPU instance (when DPU is placed on the canvas and detail edited)

**Comment by kukharm** [comment]
But it checked in DPU instance...
![mandatory](https://f.cloud.github.com/assets/3471169/854328/7a35efcc-f500-11e2-8263-a4a4966dc707.jpg)
