### ISSUE TITLE
Private / public pipeline in GUI

### ISSUE THREAD

**Issue by janvojt** [mff-uk/odcs#822]
1. add radio box in pipeline edit form to choose whether pipeline is public/private
   - default is private
   - once user saves pipeline as public radio box is grayed out, so pipeline cannot be set back to private (same as is with DPU templates).
2. If pipeline is being saved as public, all DPUs are set as public (this is already implemented in `PipelineFacade#save`). Before saving, if pipeline is public, call `PipelineFacade#getPrivateDPUs` to get the list of DPUs that are private. If the list returned is non-empty, warn user.

**Comment by bogo777** [comment]
I will add confirm dialog when there are private DPUs instead of notification, ok?

**Comment by janvojt** [comment]
Yes, I meant a confirmation dialog, so user can still cancel.

**Comment by tomas-knap** [comment]
Adjust the notification: 
![screen shot 2013-11-28 at 2 02 26 pm](https://f.cloud.github.com/assets/3014917/1639956/7c689b38-582d-11e3-835a-85657b35b65c.png)

To:
".. will cause all DPU templates, the pipeline is using, to become public. When they become public, they cannot be reverted to private."

**Comment by tomas-knap** [comment]
Then close
