### ISSUE TITLE
Notification settings on particular events should override default settings

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#825]
As a defalt settings, summary daily mails should be sent. This is fine. But I have also specified earlier that after executing pipeline INTLIB Decisions from nsoud.cz - Daily updates, I should also get immediate report. Howerver, such email is not sent from the time daily reports are supported.

**Comment by tomas-knap** [comment]
Problem is that data from notification settings for schedulled events are not stored properly. Dialog se chova divne. 

![screen shot 2013-12-16 at 5 56 21 pm](https://f.cloud.github.com/assets/3014917/1756473/6fbeab94-6673-11e3-8683-61115ea67562.png)

**Comment by tomas-knap** [comment]
Create new schedulling rule A , edit notification. Create another schedulling rule B, switch to notification, close. Open the rule A.

**Comment by tomas-knap** [comment]
Marie, tell me please when it will be solved. This is a major problem

**Comment by kukharm** [comment]
i try to resolve it today

**Comment by kukharm** [comment]
test please

**Comment by tomas-knap** [comment]
Maria, if i add one email for schedulling rule A, save, open B, open A, I can see only one email - so the problem is still in emails. Testuj prosim poradne

**Comment by kukharm** [comment]
i have a problem with adding rule now #946

**Comment by tomas-knap** [comment]
It works, but it is strange that I can add the same email address more times. If I try to save the notification containing one email more times, show an eror "Email X is introduced more times, please correct".

**Comment by kukharm** [comment]
I can't reproduce, or i don't understand the scenario.

I create event A and there put 2 emails: admin@example.com, admin2@example.com
Then i create B  with checked Use default notification settings.
Then i open A and there are 2 emails admin@example.com, admin2@example.com.

Other way
I create new event C and there put 1 emails: admin3@example.com
Then i create D with checked Use default notification settings.
Then i open C and there is 1 emails admin3@example.com.

I tested it about 30 min last time and everything worked fine.

**Comment by kukharm** [comment]
I will add the control for the same e-mails.
