### ISSUE TITLE
 Could not open JPA EntityManager for transaction

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#826]
I can not run frontend on localhost - problem with EntityManager (EclipseLink)

![image](https://f.cloud.github.com/assets/3481055/1611587/17ceed1e-55b0-11e3-970d-43555a4c879a.png)

If is not for you, please re-assign it.

**Comment by skodapetr** [comment]
Máš puštěné virtuoso? 

Nicméně dle dalšího tvého issue (kde jsi měl potíž s updatem DB), se toto "vyřešilo" ?

**Comment by skodapetr** [comment]
@tomesj Jaký je aktuální stav? pořád to trvá? nebo to přešlo?

**Comment by tomesj** [comment]
Měnil jsem si DB a od té doby už se mi to neukázalo :-)

**Comment by skodapetr** [comment]
Ok, tedy v reakci ..
