### ISSUE TITLE
Canvas contains old mappings if the DU is renamed

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#828]
When data unit name is updated in DPU (was output but now it is renamed), it is not reflected on the canvas. But it is only realized when running the pipeline when the pipeline fails. 

As a result the following situation may occur: 

Canvas: 

![screen shot 2013-11-25 at 9 11 32 pm](https://f.cloud.github.com/assets/3014917/1616572/ebbda1b2-560d-11e3-9036-4d6da40ea2a2.png)

But when clicking on Edge detail between QA DPU and loader:

![screen shot 2013-11-25 at 9 11 40 pm](https://f.cloud.github.com/assets/3014917/1616585/1deb3b7c-560e-11e3-906f-79f8fb0f3d9f.png)

Solution: 
Canvas should color an edge by red, if the existing edge mapping is no longer valid.

**Comment by tomas-knap** [comment]
Bohuslav please propose the solution here, we will discus that tomorrow

**Comment by bogo777** [comment]
If the mapping is no longer valid, remove it from the mappings.

If there is no mapping, color edge red.(Standard behaviour.)

**Comment by tomas-knap** [comment]
So you will check the validity of mappings when opening pipeline canvas?

**Comment by tomas-knap** [comment]
Napis Petrovi, he will discuss that with you
