### ISSUE TITLE
1 day, 1 week instead of 1 days, 1weeks

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#829]
When rule of scheduled event contains number 1, then there should be singular of days, weeks etc. Create a special rule for that. 

![screen shot 2013-11-25 at 10 04 57 pm](https://f.cloud.github.com/assets/3014917/1617006/5623a14e-5615-11e3-8ce1-a65068546f71.png)

**Comment by kukharm** [comment]
Closed by commit https://github.com/mff-uk/ODCS/commit/0211bc7958efcf79c9e94afb5c0fcbad35d17c83
