### ISSUE TITLE
prazdna DBpedia

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#831]
on commit 479250022fe244d452f14fb20f14d431fd3129d6
Author: bogo777 bogo777@gmail.com 2013-11-25 22:59:20
Committer: bogo777 bogo777@gmail.com 2013-11-25 22:59:20
Parent: 706ce7b75aa34b71b5b4ad26f7921afabcd265a2 (Merge branch 'master' of git@github.com:mff-uk/intlib.git)
Branches: master, origin/HEAD, origin/master

i open DBpedia pipeline and it is empty.

**Comment by bogo777** [comment]
It is because DBpedia doesn't have visibility set in db. Please update it by:

UPDATE "PPL_MODEL"
SET visibility = 1
WHERE id = 1

I also changed it in data.sql
