### ISSUE TITLE
SPARQL Loader Test Context

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#832]
Vyhodit this.context = new TestContext();

Pockej, ale takove nastaveni nemuze byt v produkcnim kodu!! Pouzij TestEnvironment co pripravil Petr. Viz tutorial [1] a nebo se inspiruj u testu na SPARQL transformer. Tohle jeste oprav prosim vsude, zakladam na to issue 

Zkontroluj ze nic podobneho se nevyskytuje ani u jineho DPU

[1] http://www.ksi.mff.cuni.cz/~knap/odcs/practice.html

**Comment by skodapetr** [comment]
Možná bych se ještě připojil s dotazel na SPARQL loader testy .. neb mám virtuoso .. na 5111 .. a tedy to nepřeložím, což nevím zda je dobře? 

Nemělo by to být integračním testem? Myslím, že jsme to již jednou řešili .. i se na to někdo externě ptal .. proč mu to nejde přeložit a potom Honza jako řešení právě přidal tu integration-test anotaci.

**Comment by tomesj** [comment]
Vyřešeno 
- poradil jsem si přes v rámci testování přes TestEnvironment. 
- Nikde v kódu už se to nepoužívá, toto bylo odstraněno. 
- Původní contructor pro testy jsem předělal na druhý (alternativní) contructor pro DPU s default nastavením.
- udělal jsem testy jako integrační

**Comment by tomas-knap** [comment]
remove dependency from OSGI Module config and then close

**Comment by tomas-knap** [comment]
nicmene jako integracni by mely byt jen ty testy, u kterych je to opravdu nutne
