### ISSUE TITLE
RDF File Extractor

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#835]
I think that in RDF File Extractor is some conflict of parameters.
What should application do if user select at ones
- Extract files based on the path to the directory - stop if some file cause error
  on the Core tab and
  - Extract only triples with no errors.
    on the Details tab ?
    Should pipeline stops or extracted triples with no error? (Now it stops)

The same in case of combination 
-Extract only files based on the path to the directory, which cause no errors
and
-Stop pipeline execution if extractor extracted some triples with an error.

Feasible solution:
Instead of 2 parameters 
-Extract files based on the path to the directory - stop if some file cause error
-Extract only files based on the path to the directory, which cause no errors

use one
-Extract files based on the path to the directory

**Comment by tomas-knap** [comment]
Leave only one option - Extract files from directory. 

Add choice below "If directory....", which is radio button group: 
- when there is a problem parsing a file, it is skipped
- when there is a problem parsing a file, extraction ends with error

**Comment by tomesj** [comment]
Solved and prepared to close :-)
