### ISSUE TITLE
SPARQL Extractor

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#836]
Is it Ok that i can save SPARQL Extractor without any settings?

**Comment by tomesj** [comment]
I think, that is OK
- there are only mantatory SPARQL endpoint (must start with http://),
  - if named graphs are empty - is used default graph on that endpoint
  - if SPARQL construct query s empty - is used default query like "CONSTRUCT {?x ?y ?z} WHERE {?x ?y ?z}".

**Comment by tomas-knap** [comment]
Well at least SPARQL endpoint is mandatory, Jirka, check that.

**Comment by tomesj** [comment]
Yes, SPARQL endpoint is mandatory - have to starts with prefix http://

**Comment by kukharm** [comment]
But in sparql endpoint field is default string  "http://" so that is why there is no error that mandatory field is empty, but i can save DPU with sparql endpoint "http://". It's correct?

**Comment by tomesj** [comment]
We are not responsible that enpoint http:// dont exist. User must specify right URL enpoint path - this is only check,that this URL starts with this prefix :-) What else do you want to check (use as default) ?

**Comment by kukharm** [comment]
we may check the format of URL address by some regular expression

**Comment by tomesj** [comment]
That´s right - but is some rule to descibe this ? And is necessary to solve this ? 
@tomas-knap add please your opinion to our discussion.

**Comment by tomas-knap** [comment]
I think it is fine to just check that some string starting with http:// is there
