### ISSUE TITLE
testing SPARQL Extractor/Loader

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#837]
I need some 
SPARQL endpoint:
Named Graph:
with error triples and with no triple extracted for testing SPARQL Extractor/Loader

Could you please write down some of that.

**Comment by kukharm** [comment]
Also for testing  SPARQL Loader i use
-SPARQL endpoint  http://localhost:8890/sparql-auth
-Named Graph  http://goal, http://myName, http://XXX 

but get error in execution: DPU 'SPARQL Loader' publish message short: 'HTTP/1.1 401 Unauthorized. Your USERNAME and PASSWORD for connection is wrong. URL endpoint: http://localhost:8890/sparql-auth POST content: default-graph-uri=&query=CLEAR+GRAPH+%3Chttp%3A%2F%2Fgoal%3E&format=application%2Frdf%2Bxml' long: ''

Could you please give mi USERNAME and PASSWORD or some another endpoint for testing.

Also i need some scenarios to check that options on Details tab works.

**Comment by tomesj** [comment]
For SPARQL endpoint for update http://localhost:8890/sparql-auth 
you have to set USERNAME and PASSWORD...Default setting is for these are "dba" "dba".

**Comment by tomesj** [comment]
Use previous described USERNAME and PASSWORD - it could be fine :-)
