### ISSUE TITLE
What is shown under last exec columns? getLastExecution?

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#843]
should last exec respect pipeline owner or logged user?

context. getLastExecution() - what is the result? Add method getLastGlobalExecution()?

Sepsat strucne, marie pak da do user doc

**Comment by skodapetr** [comment]
Podle posledního stavu: 
Pokud je pipeline privátní tak její běhy jsou také privátní. 
Pokud je pipeline public tak její běhy jsou také public. Tedy nelze mít privátní běh pro veřejnou pipeline. 

Tedy pod last_exec columns je globální poslední běh ( a ten také vrací getLastExecution)

Což je přesně to co čekáme, neb pokud je pipelina private tak tam nejsou běhy od jiného uživatele. 
Pokud je public, tak pak také jdeme přes všechny běhy, neb jsou všechny všem viditelné a tedy je správné vzít poslední execution. 

Přehazuji na @kukharm a prosím jí o zahrnutí do dokumentace k PipelineList, tabulka poslední běh k dané pipeline.

Metoda getLastGlobalExecution tedy dle mého názoru není zapotřebí.

**Comment by kukharm** [comment]
i added information to https://grips.semantic-web.at/display/LOD2/Pipelines+Section
