### ISSUE TITLE
Browse/Query dialog not working properly 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#847]
Based on the release from this afternoon, when using browse/query, trying to select a different data unit, shortly after that, it swaps to the default one. Also when clicking on browse, data are shown only for short period of time and erased again.

**Comment by bogo777** [comment]
Were you using DESCRIBE?(Clicking on the result table cells)

There is a bug, which causes DESCRIBE to be called multiple times, I will push fix shortly.

If not, is it easily reproducible? Which data/pipeline?

**Comment by tomas-knap** [comment]
No, I was not able to click on any data, the resulting data appears only for 1/2s or so.

**Comment by tomas-knap** [comment]
Pipeline "test" na odcs. Pozor nemam tam spravne nastavenou visibility pro dpus, takze kdyz kliknes na pipeline, tak se nezobrazi nic 

Pust si v debugu, jdi na browse, prepni selected dpu na prazdne, pak znovu sparql transformer. zkus preponout na output z inputu - v ten moment mi to skoci zpet. Kdyz tam necham input, dam browse, tak se data zobrazi jen na moment

**Comment by bogo777** [comment]
Found the problem, Petr changed refreshing for debug data and it continued to run after pipeline was finished and caused this to happen.
