### ISSUE TITLE
Grouping controls in SPARQL loader details tab

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#848]
Now the SPARQL Loader configuration dialog on details tab looks like: 
![screen shot 2013-11-27 at 5 21 15 pm](https://f.cloud.github.com/assets/3014917/1633202/1cda15f6-5784-11e3-85ce-4480631fe41d.png)

WHich is a bit confusing. 
Please group certain settings via a Panel together. You should group it as shown below: 

One group:
![screen shot 2013-11-27 at 5 21 36 pm](https://f.cloud.github.com/assets/3014917/1633198/14bad568-5784-11e3-89d4-08c99e8a951f.png)
Another group:
![screen shot 2013-11-27 at 5 21 29 pm](https://f.cloud.github.com/assets/3014917/1633200/17dee2b6-5784-11e3-80ce-3911d1c679b3.png)

**Comment by kukharm** [comment]
changes need to pre-clear the browser cache and reinstall SPARQL loader

**Comment by tomas-knap** [comment]
Thanks, couple of minor things to the loader detail dialog: 
- put the button default size next to the text box with chunk size
- check that only positive integers may be used in the text box with chunk size
- "(Use 0 for no repeat ...)" -> This should be only in tool tip OR next to the text box
- check that only integers may be used for "count of attempts"
- chech that only positive integers may be used in text box "time in ms"

**Comment by tomas-knap** [comment]
Maria, just one thing. When entering wrong value to some textbox, it is silently replaced with a correct value. That is not correct behaviour. 

Solution: When there is an error in the configuration and user tries to save it, an error message should appear as in #898. You should not automatically replace the inserted value with the default value. User has to correct it manually.   Please check this not only for SPARQL loader, but also for other DPUs

**Comment by kukharm** [comment]
Please clarify witch one textbox replaced value and in what scenario. I can not reproduce. When i enter error values to Chunk size,Count of attempts and  Time in milliseconds they  are not replaced after pressing save button. error message is appear.

**Comment by tomas-knap** [comment]
Can you please post a screenshot of the error messages?

**Comment by kukharm** [comment]
![sparqlloader](https://f.cloud.github.com/assets/3471169/1750416/c39be5ec-658d-11e3-9f4d-4cabd3146068.jpg)
I see there only problem with text of error messages, because it don't consist all problems description

**Comment by kukharm** [comment]
i corrected the message
![sparqlloader](https://f.cloud.github.com/assets/3471169/1750628/a002b622-65a3-11e3-86ed-c169ce0c1386.jpg)

**Comment by tomas-knap** [comment]
Ok, I will test
