### ISSUE TITLE
Long schedule description causes table to go outside of display area.

### ISSUE THREAD

**Issue by janvojt** [mff-uk/odcs#850]
We should cut text longer than x characters in table and append ... .
This problem will probably occur at several places (pipeline description, ...).

![screenshot](https://f.cloud.github.com/assets/2247062/1638694/e851a2de-5811-11e3-856d-444850d87c7e.png)

**Comment by bogo777** [comment]
Done for pipeline name and description, for pipeline name in execution list and for description in scheduler. Any other places?

**Comment by bogo777** [comment]
Max lenght of column is set in Utils class(now 100). Is it ok? What other value should it be?

**Comment by tomas-knap** [comment]
This is fine
