### ISSUE TITLE
visibility of publish pipeline in scheduler

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#860]
I check scenario:
"Log as user x, publish pipeline, check that user y can see it."

User y see published pipeline in Pipelines section but do not see it in the "Schedule a pipeline" dialog in Scheduler section. When user y open "Schedule a pipeline" dialog by "Schedule" button in Pipelines section he can see it.

**Comment by janvojt** [comment]
This seems to be fixed now.

![screenshot from 2013-12-18 18 30 47](https://f.cloud.github.com/assets/2247062/1775674/329e21fc-680a-11e3-92c7-d448e442dafb.png)
