### ISSUE TITLE
Problem with private DPU templates

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#861]
![screen shot 2013-12-02 at 12 37 13 pm](https://f.cloud.github.com/assets/3014917/1654191/2441006e-5b46-11e3-99d1-1e316a86a362.png)

It is confusing, that user cannot create DPU because of the name clash, but he cannot see the conflicting DPU. 

Please propose the solution.

**Comment by skodapetr** [comment]
Related to #855, the problem is not only with DPUs but also with pipelines

**Comment by skodapetr** [comment]
I see two possible solutions:
1} Ignore this, ie. the name of the DPU/pipeline is given by user and we will not restrict him. There can be same names for different object (no problem for ODCS as it use IDs).

2} We separate the scope of private/public. 
I can have private DPU with the same name other public DPU (they can be differentiate by color), but once I decide to publish it I have to provide unique name. 
Also I can have private DPU with the same name as someone else.

**Comment by tomas-knap** [comment]
Regarding 1) it will be ok, but as soon as the  user publishes his private DPU having the same name as another already public DPU, it will be confusing. 

Rather easy solution would be 2),  so that when user creates private DPU with the colliding name, everything will be ok. When user tries to publish DPU, or create new DPU directly as public with the name already existing, he will be warned that before doing that, he has to change the name. 

?

**Comment by skodapetr** [comment]
1) yes, we can say that, there are no restriction, this situation can happened and leave user to do hist best .. 

2) yes, it should be not so much complicated .. and imho. it's more user friendly

**Comment by tomas-knap** [comment]
Yes, I am also for 2)

**Comment by skodapetr** [comment]
I have checked the current behaviour and it seems to me .. as there is no name check at all .. have we removed it, or do I overlook something?

**Comment by tomas-knap** [comment]
We will keep it as it is
