### ISSUE TITLE
Users - changing pipeline created by a different user

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#862]
![screen shot 2013-12-02 at 12 42 26 pm](https://f.cloud.github.com/assets/3014917/1654222/dadedada-5b46-11e3-8349-ae1d6c180eeb.png)

**Comment by skodapetr** [comment]
How we decide that at the end? Is there public-read, public-edit permissions? Or just private/public?

**Comment by tomas-knap** [comment]
I would opt for public-read and public-edit. I could imaging having a set of referential (best practise) pipelines, which others (e.g. student) should have rights to change, even by chance.

**Comment by tomas-knap** [comment]
Should be solved together with Bohuslav, Bohuslav should have a way to find out if the user is privileged to work with the pipeline etc.

**Comment by janvojt** [comment]
This is resolved by ab28c820 in #859.
