### ISSUE TITLE
Problems with Settings -> my account tab

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#866]
1. There should not be possible to enter chars to Settings: 

![screen shot 2013-12-02 at 3 59 50 pm](https://f.cloud.github.com/assets/3014917/1655429/7f15bf90-5b62-11e3-9d59-f0c5ca8fbbe7.png)

Actually the only allowed values should be 1-100 for example. 
1. When I set number of rows, I got notification: Emails successfully saved. But the notification message should be "My account settings were successfully saved"

**Comment by kukharm** [comment]
Validation was already done in last commit i had  10259e5ab6165b65685c24e3223033342902d2bc so i changed notification messages.

**Comment by tomas-knap** [comment]
I created a special issue for better notification messages
