### ISSUE TITLE
Pipeline duration is not updated in exec monitor properly

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#868]
When I debug pipeline, uncheck automatically refresh (on details), then duration is not updated. Further, even if I check "automatic refresh" again, the duration is not updated further. 

![screen shot 2013-12-02 at 5 26 31 pm](https://f.cloud.github.com/assets/3014917/1656167/a0ae24ce-5b6e-11e3-8260-fb26197f82a8.png)

![screen shot 2013-12-02 at 5 26 37 pm](https://f.cloud.github.com/assets/3014917/1656168/a382dc12-5b6e-11e3-81d3-0ae4d9a2edb3.png)

**Comment by bogo777** [comment]
That is strange, the checkbox relates only to the detail, execution list is refreshed always.

But for running pipeline duration is computed as current time - start time. For finished pipeline it is end time - start time and end time can be reported with delay so duration can decrease after refresh.

**Comment by bogo777** [comment]
There was bad order of refresh actions on execution list, should be fixed by 473f9b6093e2358d424b51d918bc527b50a3a744
