### ISSUE TITLE
Edges on the canvas dissappeared

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#869]
Week before, I create pipeline [QA] TED data - 3DPUs + 2 edges. 
When opening pipeline [QA] TED data today, no edges are visible. But if you try to add new edge between extractor and transformer, it cannot be added. 

Bohuslav, please check where the problem is. Check also that DB is ok (with Jan's help if needed). 

![screen shot 2013-12-02 at 6 16 33 pm](https://f.cloud.github.com/assets/3014917/1656689/ff26ae7e-5b76-11e3-9284-cc4f868bb80e.png)

**Comment by bogo777** [comment]
![image](https://f.cloud.github.com/assets/1550848/1658862/f917a6c8-5b99-11e3-988c-29e02323de9c.png)

This is propably the cause, strange is, that it is not shown when pipeline is loaded. Will investigate further.

**Comment by skodapetr** [comment]
It does not have to be the cause. This is related to some package .. updates. We though that rdf.impl package is not used, but it is. This 'rdf-impl' error should occur no more. But according to the times .. it is probably the source.
Sorry for that.

**Comment by tomas-knap** [comment]
Ok, I will test
