### ISSUE TITLE
RDF File Extractor - Not a valid (absolute) URI

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#872]
I create RDF File Extractor and set Extract file from the given HTTP URL. http://www.reeep.org/dir.ttl RDF format AUTO.
Then i try to run pipeline with this DPU. Run pipeline-fail.
    Message:
    DPU 'RDF File Extractor' publish message short: 'Not a valid (absolute) URI: [line 11]' long: '' 

full testing scenario in https://grips.semantic-web.at/display/LOD2/2013-11-26+DPUs+and+confirmation+windows+testing

**Comment by tomesj** [comment]
Tak jsem se na to díval a vyhozená chyba je v tomto případě správná - ten soubor nemá totiž hned první řádek s daty napsaný správně:
<> foaf:primaryTopic <#org> . - URI, které reprezentuje v tomto případě subject nemůže být nikdy prázdné !!!

Tedy myslím, že to, že to skončilo, je správně - je tam použit RDF parser pro příslušný formát (pro tento konkrétně TTL) a ten umí přeskakovat pouze některé chyby (například neopovídající typy literálů, ...) a chybu jako je tahle - základní syntaktickou,  nedokáže přeskočit.

**Comment by tomas-knap** [comment]
JJ, je to ok
