### ISSUE TITLE
Missing LOGS after failure and recovery DB

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#874]

**Comment by tomas-knap** [comment]
Jirko, popis tu "steps to reproduce"

**Comment by tomesj** [comment]
Uděláte si jednoduchou pipeline (FIle extractor - SPARQL loader)
- jakmile začně běžet loader shodíte DB, po chvilce jí znovu nahodíte (necháte doběhnout) a sledujete, co se stalo
- shození si zkuste pro případy
- a) mezi tím, než se zavolá metoda load (s tím, že znám už všechny parametry)
- b) někde během získávání a práci s httpConnection - nejlépe v metodě getEndpointStreamReader (najdete v BaseRDFRepo), kterou loader používá
- c) během toho, že se vám už nahraje několik data parts, ale ještě né všechny (stejně tak lze sledovat přerušení u metody getInsertQueryPart - příprava vytvoření data part pro nahrání - v třídě SPARQL loader) 
- měly by být vidět logy o pokus vytvořit a nahrát ten data part, který se nestihnul a pak pokračovat normálně dále v nahrávání
- d) přerušení na konci loadování všech data partů, ale ještě před metodou moveDataToTarget (která přesouvá data z temp grafu do skutečného cílového)
- e) přerušení i po metodě moveDataToTarget, ale ještě před uvolnění a ukončení (shutdown, delete) repozitáře

To jsou asi všechny scénáře :-)

**Comment by tomas-knap** [comment]
Ok, a v kterych pripadech nastava, ze nejktere logy nejsou zalogovane v DB?

**Comment by tomesj** [comment]
V podstatě u všech výše zmíněných :-)

**Comment by skodapetr** [comment]
Jen se zeptám .. jak mám stihnout\poznat schodit virtuoso .. než se zavolá nějaká metoda? 

Na druhou stranu, je možné .. že některé logy by mohli zmizet .. pokud by se aplikace pokusila zalogovat a databáze byla mimo .. nicméně, ikdyž je tam zcela jistě hodně případů .. čekal bych něco jednodižšího .. případně skutečně diff mezi db a file logem.

**Comment by tomesj** [comment]
No jednoduše třeba tak, že si dáš příslušný breakpoint a pustíš v backend v debugu. Když se ti to zastaví na breakpointu shodíš DB a necháš běžet dále - pak ji obnovíš a necháš doběhnout celé a koukáš, co se děje. Pak můžeš zkusit přerušit též náhodně normálně při run - aspoň třeba 10 krát :-) Mě se to podařilo i při tomto klasickém runu vychytat skoro všechny případy pro zastavení (chce to ale určitě kapku štěstí - ale ten debug je jistota :-)

**Comment by skodapetr** [comment]
No .. doufal jsem v něco snažšího 0:  .. ale když bude čas tak to zkusím.

**Comment by tomas-knap** [comment]
How was this issues solved?

**Comment by skodapetr** [comment]
Well we store all logs into the ArrayList before they are flushed into the database (in case we have batch insert, we have it now for virtuoso .. ) ... then once upon the time (4300ms) the flush method is called. The flush method swaps the buffers (ArrayLists) and try to save logs into the database .. if failed then try again and again .. in mean time the logs are stored in the second ArrayList ..

**Comment by tomas-knap** [comment]
So when switching e.g. to mysql, we have to copy & adjust batch inserter for virtuoso? 
Ok, so I will close?

**Comment by skodapetr** [comment]
Maybe .. the mysql seems to be reasonable database so it probably supports the batch update/insert as well. But the SQLAppender is probably one of the places that should be revised in case of database change.

**Comment by tomas-knap** [comment]
ok
