### ISSUE TITLE
Last log refresh not performed when cancelling pipeline

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#879]
When viewing a running pipeline's log and clicking on cancel, the log stops refreshing too early and does not show all log entries. It needs to be refreshed in order to see the end of the execution.

**Comment by bogo777** [comment]
Refreshing of detail data(including logs) stops when execution is marked as finished/failed/canceled(not cancelling) in db. So it's about when the pipeline is marked, or if there is some delay in writing logs to db. We can add one extra refresh, if that will help? @skodape

**Comment by skodapetr** [comment]
Well .. there is a delay  .. the logs are written once per 4 seconds .. or where there are more then 50 logs .. extra refresh .. should help .., or we may use some technique to force logs save before the end of execution?

**Comment by bogo777** [comment]
If it's possible it would be nice to force logs to save before marking execution as ended, so it would really be last action regarding that execution.

**Comment by skodapetr** [comment]
ok, reassign .
