### ISSUE TITLE
Combo box with DPUs in exec records detail not working sometimes properly

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#880]
The combo box sometimes does not contain all the DPUs for which there is already a log. If I click on exec monitor records for pipeline which has already finished, it is fine. But when observing the log and then, at certain moment try to filter, certain DPUs may not be accessible

**Comment by bogo777** [comment]
We currently use list of DPUs from execution context, where only finished DPUs are. Other way would be to show all DPUs from the pipeline. 

We could use the current approach for finished pipelines, so we wouldn't show DPUs which were not part of execution in case of debugging to certain node and the other for running pipeline.

Alternatively we could use DependencyGraph for both and show only the DPUs which will be run(if there is not error.)

**Comment by tomas-knap** [comment]
Yes, but the problem is that I cannot filter logs from the currently running DPU. And also the problem was also with already finished DPUs - sometimes when debugging pipeline, it was necessary to reload execution monitor view and reopen the debugged pipeline to see all the DPUs in the combo box

**Comment by bogo777** [comment]
There are 2 ways how I'm getting DPUs now:
1. for finished/failed/cancelled pipelines - from execution context - only DPUs which were executed are shown
2. for running pipelines - ALL planned DPUs are shown

**Comment by tomas-knap** [comment]
Ok
