### ISSUE TITLE
SPARQL Extractor not supporting cancel

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#884]
When cancelled... still counting triples....
![image](https://f.cloud.github.com/assets/718827/1692751/6da04f3c-5e82-11e3-88ac-3f36d0192d15.png)

**Comment by tomas-knap** [comment]
When SPARQL is using our own handler to parse the triples, it should support cancel

**Comment by tomesj** [comment]
Solved. SPARQL extractor supported CANCEL now :-)

**Comment by tomas-knap** [comment]
Jirka, and what about the statistical handler?

**Comment by tomesj** [comment]
CANCEL is suported in Statistical Handler too, but this is implemented in TripleCountHandler. It is supported thanks inheritance.
