### ISSUE TITLE
SPARQL Extractor slow

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#885]
Internal...:
http://linked.opendata.cz/resource/dataset/seznam.gov.cz/ovm/list

<pre><code>PREFIX s: &lt;http://schema.org/&gt;
CONSTRUCT {?address ?p ?o}
WHERE 
{
?address a s:PostalAddress ;
?p ?o .
}</code></pre>

approx 50 000 triples.

Using internal's sparql endpoint: approx 5s.
Using SPARQL extractor: approx 9min.

**Comment by tomas-knap** [comment]
Kubo, when extracting, do you have "use statistical and error handler" on in SPARQL extractor settings?

**Comment by jakubklimek** [comment]
Tried that, it is slow both with and without it.

**Comment by tomas-knap** [comment]
As looking into the code: 

switch (handlerExtractType) {
            case STANDARD_HANDLER:
                handler = new TripleCountHandler(connection);
                break;
            case ERROR_HANDLER_CONTINUE_WHEN_MISTAKE:
                handler = new StatisticalHandler(connection);
                break;
            case ERROR_HANDLER_FAIL_WHEN_MISTAKE:
                handler = new StatisticalHandler(connection);
                failWhenMistake = true;
                break;
            default:
                handler = new TripleCountHandler(connection);
                break;
        }
1. So based on that, even if "use statistical and error handler is unswitched", your TripleCountHandler is used. Why? When "use statistical and error handler" is NOT checked, there is no need for counting triples. The internal handler provided by the openRDF should be used in this case. (question: If default handler is used, how the errors discovered in data during parsing are reported? Aneb jak v tomto pripade open RDF reportuje chyby?)
2. What is the difference between standard and default branch above? Is default branch reachable in the code above?

**Comment by tomas-knap** [comment]
Please measure the time for the use case above when using:
1) the construct directly
2) default openRDF parser. 
3) statistical and error handler

**Comment by tomas-knap** [comment]
Please summarize the findings, so what is the improvement in the performance

**Comment by tomesj** [comment]
How I was written on skype
- with get InputDataStream using construct query - there was no problem (same time as using contruct query direct in Virtuoso dialog)
- problem is that RDFParser parse data data stream slower, if that input data stream from construct are too large.
- time of parsing is of cource longer for Statistical and error handler, but defauft handler and TripleCountHandler (simple extension - const O(1)) have same time.  

Low performance
- cause by fixing problems with #877 (Virtuoso connection failure)

Make performance better:
- optimalize to use shared connection for that as were in version before solving #877.
- this step make faster all operation (e.g. loading to SPARQL endpoint,...)

**Comment by tomas-knap** [comment]
Ok, so you optimized the use of shared connection and all operations working with RDF store should be faster? What is the idea of the optimalization?

**Comment by tomesj** [comment]
Yes, you right, because all RDF operation are depended on connection (RepositoryConnection).

**Comment by tomas-knap** [comment]
And what was the idea of the optimalization, where was the problem with the previous FailureTolerantRepo?

**Comment by tomesj** [comment]
The problem was, that if some method in FailureTolerantRepo need connection for it´s execution - this connection was getting as calling repository.getConnection() method and this was´n optimal, because if some connection has been existed yet, the system try to get the next connection (but really the same - it´s time consuming). 

Now this method is called only, when it is necessary - we have null shared connection or connection is not been opened yet - it can be caused by connection failure.

**Comment by tomas-knap** [comment]
Jirko, jeste dotaz, proc pouzivas pro SPARQL extrakci (validace nezaskrtnuta) ten nas tripleCountHandler? Podle me se ti to urcite o 20-30% zrychli kdyz budes pouzivat primo ten jejich handler (ted ho jen prevolavas). Zkus to prosim. Tedy zmer prosim jak dlouho trva neco nacist ted a jak dlouho trva to same jen s tim jejich defaultnim handlerem.

**Comment by tomas-knap** [comment]
Pouzij ten priklad v zahlavi issue

**Comment by tomesj** [comment]
Dobře, vyzkouším a dám vědět co a jak, ale řekl bych, že se moc neušetří :-)

**Comment by tomesj** [comment]
Tak jsem naměřil následující výsledky:

Použitý endpoint: http://internal.opendata.cz:8890/sparql
Použitý named graf: http://linked.opendata.cz/resource/dataset/seznam.gov.cz/ovm/list
Použitý dotaz:

PREFIX s: http://schema.org/
CONSTRUCT {?address ?p ?o}
WHERE 
{
?address a s:PostalAddress ;
?p ?o .
}

Použité handlery a získané časy:
1) Statistical and error handler - průměrný čas 2:06 (naměřeno 2:16, 1:59, 2:03)
2) TripleCountHandler - průměrný čas 1:47 (naměřeno 1:45, 1:50, 1:46)
3) Defaultní handler (RDFInserter) - průměrný čas 1:46 (naměřeno 1:44, 1:50, 1:44)

Z naměřených výsledků tedy vyplývá, že bychom nadále měli jako default handler používat TripleCountHandler, neboť časově je totožný jako klasický handler (RDFInserter) a navíc tím získáme:
1) Přehled o počtu extrahovaných trojic
2) Extrakci pouze validních dat
3) Možnost použít CANCEL a tak extrakci a celou pipelinu manuálně zastavit

**Comment by tomas-knap** [comment]
Ok, to jsi zkousel s ukladanim mezivysledku do virtuosa nebo localRDF?

**Comment by tomesj** [comment]
S ukládáním výsledků do Virtuosa :-)

**Comment by tomas-knap** [comment]
Without statistical and error handler

![screen shot 2013-12-31 at 2 54 06 pm](https://f.cloud.github.com/assets/3014917/1827092/174da4fe-7223-11e3-99cb-b9b11b965278.png)

With stat. and error handler: 

![screen shot 2013-12-31 at 2 55 07 pm](https://f.cloud.github.com/assets/3014917/1827093/2eaf05f2-7223-11e3-9627-936407bae61c.png)

**Comment by tomas-knap** [comment]
In case of using local RDF and without statistical and error handler it took 3+ minutes. 

![screen shot 2014-01-03 at 8 02 05 pm](https://f.cloud.github.com/assets/3014917/1841613/c15c1736-74a9-11e3-8406-0840725d9841.png)

When using virtuoso, it took 30s (as above)

**Comment by tomas-knap** [comment]
Performance of localRDF could be improved?

**Comment by tomas-knap** [comment]
Performance was already improved - there was problem using transactions - they were not used effectively
