### ISSUE TITLE
Browse/Query really slow for localRDF intermediate storage

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#886]
Go to ODCS, open exec monitor detail with id 674, go to browse/query, and try to browse data, e.g. for gov-cz:Organy. You can wait minutes and no data appear. What is the reason for that? It seems that data are lazy loaded, so I would expect to see first 30 triples really quickly. What is the problem? what are the queries being executed to the DB? Ask Petr to help you tuning the queries if they are suspicious. 

This is a problem, becuse browse/debug is are core feature and it cannot be used properly. 

I am using localRDF repo currently.

**Comment by tomas-knap** [comment]
Please test the browse working with couple of milions of triples. It should be possible because of the lazy loading. Ask Jirka (@tomesj) how to generate 7 milions of triples

**Comment by bogo777** [comment]
We talked about this, we are lazy loading data, but we need the total count triples to show total pages. And count function for CONSTRUCT is really slow, especially for localRDF. From what I got from looking to source, we are iterating through all triples(see BaseRDFRepo, method getSizeForConstruct() ). I think any improvement should be made there.

**Comment by tomesj** [comment]
If you want show only total pages - for browsing all data in graph (construct query like CONSTRUCT {?x ?y ?z} WHERE {?x ?y ?z } - call method getTripleCount().

**Comment by tomesj** [comment]
I updated method using only in last version - it could be faster :-)

**Comment by tomas-knap** [comment]
Jirka, please test that - run the pipeline with 7milions of triples and native store in debug mode and then try to browse. The method on count could take < 1s, so I would expect the first results in the browser in < 1s. Please report here.

**Comment by tomesj** [comment]
So I tried browse on the large collection (7 milions triples)
- if you open concrete pipeline, click on BROWSE first is time ~8s
- then if you change DPU, input/output, and click on BROWSE - time is always very short ~1s

**Comment by tomas-knap** [comment]
Thanks, why does it take 8s first time? What is the reason for that?

**Comment by tomas-knap** [comment]
@bogo777  do you have any clarification why it is much slower first time?

**Comment by bogo777** [comment]
I don't. I will add some logging, so we see, where it spends this time. 

@tomesj  Could you give me the guide how to generate 7 milion triples?

**Comment by tomesj** [comment]
@bogo777 
The simples way how to get graph with 7 milions triples:
1) Download file with 7 milions triples / or something size like this
2) Load this file in your concrete named graph through Virtuoso conductor -> Linked Data ->Quad Store Upload

I actually don´t have this file on my disk yet, only graph in Virtuoso,

But you can used file like this:
9,8 mil triples
http://www.cs.toronto.edu/~oktie/linkedct/linkedct-dump-2009-03-10.nt 

Or see page for large RDF data collection and download file about size you need:
http://www.w3.org/wiki/DataSetRDFDumps

**Comment by tomas-knap** [comment]
Bohuslave, pro ty data, napis si pipeline se SPARQL extractorem, ktera stahne nejaka vetsi data. Inspiraci muzes brat tu: http://linked.opendata.cz/ Je tam seznam datasetu, i s prislusnym named graph, ktery zadas do konfigurace SPARQL extractoru. Adresa SPARQL extractoru je http://linked.opendata.cz/sparql

**Comment by tomas-knap** [comment]
Vystup extraktoru pak zkus zobrazit v browseru. Pro zjisteni poctu triplu v datasetu: klikni na dataset na linked.opendata.cz a dostatnes statistky

**Comment by bogo777** [comment]
Zkusil jsem 5 extractorů z různých grafů z linked.opendata.cz, ale ač ukazují, že mají přes milion triples, tak se mi jich vždy extrahuje jen 10001. A výsledný graf, který má 50005 triples přes conductor, tak v Browse/Query ukazuje 667 stran \* 15 triple na stránku = opět jen 10000 triples.
Předpokládám, že problém je někde na naší straně? Je potřeba někde něco nastavit?

**Comment by tomas-knap** [comment]
10000 byva standardni limit poctu vracenych records ve virtuoso.ini pro praci se SPARQL. Zvedni si jej. Nebo pouzij localRDF misto virtuosa

**Comment by bogo777** [comment]
I have about 5M triples and it acts little strange. Sometimes it is extremely slow(propably due to RAM), then it takes several seconds and sometimes it is very fast(possibly caching). I added logging when calling RDF queries, so please test it yourself. In any case, it is always stuck on the RDF method(size/data) query, so there is no delay in frontend code.

For first query there is this in the log:
12:33:10.849 [http-bio-8084-exec-25] DEBUG c.c.m.x.o.f.c.rdf.RDFQuery - Size query started...
12:33:10.962 [http-bio-8084-exec-25] DEBUG o.o.r.DatatypeHandlerRegistry - Registered service class org.openrdf.rio.datatypes.XMLSchemaDatatypeHandler
12:33:10.964 [http-bio-8084-exec-25] DEBUG o.o.r.DatatypeHandlerRegistry - Registered service class org.openrdf.rio.datatypes.RDFDatatypeHandler
12:33:10.965 [http-bio-8084-exec-25] DEBUG o.o.r.DatatypeHandlerRegistry - Registered service class org.openrdf.rio.datatypes.DBPediaDatatypeHandler
12:33:10.967 [http-bio-8084-exec-25] DEBUG o.o.r.DatatypeHandlerRegistry - Registered service class org.openrdf.rio.datatypes.VirtuosoGeometryDatatypeHandler
12:33:10.969 [http-bio-8084-exec-25] DEBUG o.o.r.DatatypeHandlerRegistry - Registered service class org.openrdf.rio.datatypes.GeoSPARQLDatatypeHandler
12:33:10.976 [http-bio-8084-exec-25] DEBUG o.o.r.LanguageHandlerRegistry - Registered service class org.openrdf.rio.languages.RFC3066LanguageHandler
12:34:07.113 [http-bio-8084-exec-25] DEBUG c.c.m.x.o.f.c.rdf.RDFQuery - Size query finished!

It may be that 7 seconds difference Jirka wrote about.

**Comment by tomas-knap** [comment]
Jirko, hod sem prosim ten query, kterym zjistujes ten pocet zaznamu

**Comment by tomas-knap** [comment]
The problem which should be solved is why query on count of triples is sometimes very slow

**Comment by tomesj** [comment]
Pokud se jedná o zjištění všech záznamů v kolekci - (tedy dotaz např. CONTSTRUCT {?x ?y ?z} WHERE {?x ?y ?z} ), volá se rovnou metoda - connection.size(), která vrací počet všech záznamů

Pro select se položí dotaz typu SELECT (count(*) as ?pocet) WHERE {....} a ten počet se vrátí jako výsledek...
Pro nějaký obecný jinak omezený contruct dotaz - na základě contruct dotazu se vytvoří graf - ten se předá modelu a na tom se zavolá metoda size() - která vrátí velikost :-)

**Comment by tomas-knap** [comment]
"Pokud se jedná o zjištění všech záznamů v kolekci". Ok a cim se lisi ten pripad "Pro nějaký obecný jinak omezený contruct dotaz - na základě contruct dotazu se vytvoří graf - ten se předá modelu a na tom se zavolá metoda size() - která vrátí velikost :-)"?

"Pro nějaký obecný jinak omezený contruct dotaz - na základě contruct dotazu se vytvoří graf - ten se předá modelu a na tom se zavolá metoda size() - která vrátí velikost :-)"

Aha, ale to prakticky znamena, ze zkonstruujes vysledek dotazu a pak spoctes triples? To neni dobre. To je pak lazy querying k nicemu, ne?

**Comment by tomesj** [comment]
Tak když máš construct dotaz, tak ten vždycky vrací nějaký graf a když chceš zjistit velikost, tak není jiná možnost než to dát modelu a zavolat metodu size. 

Neboť samotný graph tuto funkci nemá a kdybys jí chtěl naimplementovat ručně, musel bys vzít všechny ty trojice, které dostaneš, projít je a spočítat kolik jich je, což by nebylo moc dobré. 

Nebo víš o nějaké jiné metodě ? Nemůžeme bohužel kombinovat SELECT A CONSTRUCT a zjistit tak velikost třeba jedním dotazem, což by bylo optimální :-)

Co já vím, tak jde jen o získání celkového počtu trojic pro daný dotazy - samotné trojice se pak načítají lazy způsobem, tedy ten je zachován :-)

**Comment by tomas-knap** [comment]
To jo, ale blbe je, ze v podstate musis vsechny trojice nacist u constructu do pameti abys ziskal jejich pocet, ne?

**Comment by tomesj** [comment]
Ne, ty dostaneš jako výsledek constructu instanci grafu, takže se drží jen tato instance. Jen tuto instanci dáš modelu a dostaneš instanci modelu s istancí grafu a na ní zavoláš metodu. Myslím, že to není tak, že by se v tom grafu drželi všechny trojice - bude to taky implementované lazy, tedy načtou se, až je skutečně potřeba. Kdyby jsi třeba zavolal iterator na tom grafu pro jejich procházení, nebo něco podobného...Jinak podle mě v paměti místo nedrží.

**Comment by tomas-knap** [comment]
Jirko, popis prosim na wiki postup, tedy hlavne me zajimaji ty dotazy, kterym se zjistuje kolik bude vysledku na obecny CONSTRUCT. Udelej to prosim do zitrka.

**Comment by tomesj** [comment]
Tak sepsáno 
https://grips.semantic-web.at/display/LOD2/Size+of+query+result

Jinak v vlastní dotaz používáme v podstatě jen pro SELECT, všude jinde už voláme metody openRDF sesame.

**Comment by tomas-knap** [comment]
Jirko, okomentoval jsem na confluence, pri model.size se musi nejprv nacist vsechny triples.

**Comment by tomas-knap** [comment]
Udelal bych aspon to, ze bych po stisknuti tlacitka browse, nevolal CONSTRUCT, ale SELECT ?s ?p ?o WHERE {?s ?p ?o}. Samozrejme ten select musi pracovat jen na prochazenou data unit. Tim padem se pouzije efektivnejsi varianta prochazeni, navic je mozne filtrovat. 

V pripade describe se primo vola SPARQL DESCRIBE?

**Comment by tomas-knap** [comment]
u SPARQL constructu si holt uzivatel pocka. Pripadne by mel pouzit u constructu spis query and download.

**Comment by tomesj** [comment]
Co se týká procházení všech trojic, tam se volá metoda size() přímo na repozitáři (RepositoryConnection) nikoliv na modelu a volá se přímo :-) Myslím, že SELECT nebude rychlejší, ale klidně to tak můžu předělat, jestli chceš.

See http://openrdf.callimachus.net/sesame/2.7/apidocs/org/openrdf/repository/RepositoryConnection.html#size(org.openrdf.model.Resource...)

Co se týká DESCRIBE, tak pro zjištění počtu to funguje jako u CONSTRUCTu nebo výsledkem dotazu DESCRIBE je GRAF stejně jako u CONSTRUCTU. Tedy obě používají i stejnou metodu, jen s jinými parametry :-)

**Comment by tomas-knap** [comment]
Depends on the implementation of repository.size(), but probably yes. 

Co se tyce toho selectu, proc vlastne ten count pocitame jako: 

http://my.dc SELECT (count( \* ) AS ?selectSize) WHERE { SELECT ?x, ?y WHERE {?x dc:has ?y} }?

Vzdy by slo vzdy nahradit v originalnim selectu tu cast pred WHERE tim "SELECT (count( \* ) AS ?selectSize)", ne?  Samozrejme by to chtelo konzultaci s dokumentaci.

**Comment by tomas-knap** [comment]
Ale je pravda, ze ne vzdy. Problem by mohl byt kdyz bychom meli napriklad 
{Select ?s ?p ?o WHERE {} } UNION { Select ?s ?p ?o WHERE {} }

**Comment by tomas-knap** [comment]
ok, tak to nech, jak to mas, jen prosim zkus pro moji informaci porovnat ty dve varianty pro browse, tedy: 
1. CONSTRUCT {?s ?p ?o} where {}
2. SELECT (count( \* ) AS ?selectSize) WHERE { SELECT ... }

Zkus to prosim na vetsich datech, trebas na tom 7milionovem ;)

**Comment by tomesj** [comment]
Dobře :) Zkusím to porovnat a rovnou tam dám to rychlejší :-)

**Comment by tomas-knap** [comment]
Kdyztak zatim jen porovnej a pak rozhodneme

2013/12/20 Jiøí Tome¹ notifications@github.com

**Comment by tomesj** [comment]
Tak jsem si pro všechny grafy ve Virtuosu zavolal obě metody pro zjištění všech prvků v kolekci a měřil u nich časy.

Výsledek:
Pro grafy s velikostí do cca 2000 prvků je lepší použít přímý přístup ( místy je rozdíl až o 50 ms), naopak pro větší grafy je lepší použít SELECT přístup, (většinou je rozdíl v rozmezí do 30 ms)

**Comment by tomas-knap** [comment]
Tak tam dej ten select. Zoptimalizuj to prosim jeste tak,ze si vzdy zjistis, jestli je v tom dotazu jediny prikaz "SELECT". Pokud ano, tak postupuj dle 1. Pokud je tam vice "SELECTU" v originalnim dotazu (to nebude caste), tak bys pouzil stavajici pristup pro SELECT. 
1. nahradis puvodni dotaz novym nasledovne:

SELECT ma vzdy tvar: SelectClause DatasetClause\* WhereClause SolutionModifier, DatasetClause vzdy zacina FROM, ale neni povinna, tedy: 

-pokud je tam FROM: nahradis SELECT xxx FROM ... tim SELECT (count( \* ) AS ?selectSize) FROM ...
-pokud tam neni FROM: nahradis SELECT xxx WHERE ... tim SELECT (count( \* ) AS ?selectSize) WHERE ...
- pripadne prefixy pred "SELECT" musis zachovat!

Kdyztak koukni na http://www.w3.org/TR/sparql11-query/#rSelectClause

Vyhoda je, ze v tomhle pripade bys mel byt vyrazne rychlejsi nez doted (neb ted vlastne konstruujes cely select a az pak pocitas count nad vysledkem).

**Comment by tomas-knap** [comment]
a Browse bude potom pouzivat select

**Comment by tomesj** [comment]
OK, instrukce jsou mi jasné :-) Takže to tak udělám :-) Tím bychom měli dosáhnout ideální optimalizace :-)

**Comment by tomesj** [comment]
Tak jsem optimalizoval výpočet size ty SELECT queries, jak bylo popsáno :-)

Jinak co se týká procházení všech dat v kolekci - používá se pro zjištění velikosti nyní metoda getResultSizeForDataCollection (založená na SELECT dotazu). 

V rámci aplikace browse/query se ale zobrazuje stále dotaz CONSTRUCT {?x ?y ?z} WHERE {?x ?y ?z} neboť pro následné načítání prvků do lazy collection je lepší (výše popsaná metoda založená na selectu jen vrací počet).

Zkoušel jsem a funguje to dost dobře. Dosáhli jsme opět zrychlení :-)

**Comment by tomas-knap** [comment]
Diky, jake je to zrychleni? 10% nebo 300%?

Ja bych pouzil ten select misto constructu pro browse - tedy pokud to zobrazeni dat trva zruba stejne. Duvod je ten, ze vysledek selectu se da filtrovat

**Comment by tomesj** [comment]
Zrychlení je cca 10%
Jinak já právě zkoušel použít ten select místo contructu i pro přidávání do containeru, ale bylo to hrozně pomalé. (přitom logicky dotaz na velikost je stále stejně rychlý). Možná se tam něco přidává neefektivně, ale to je spíš na Bohuslava. 

Proto se nejlépe na browse hodí varianta construct dotaz (select dotaz pro zjištění počtu). Můžu to klidně předělat i na ten select, aby se dalo filtrovat, ale bude to znatelně pomalejší.

**Comment by tomas-knap** [comment]
Pockej, to je divne. Bych cekal vetsi zrychleni. Zkusim na to kouknout. 

@bogo777  netusis proc je SELECT ?s ?p ?o WHERE {?s ?p  ?o } znatelne pomalejsi nez CONSTRUCT {?s ?p  ?o } WHERE {?s ?p  ?o }?

**Comment by tomas-knap** [comment]
Je potreba vyresit: 

Problém je, že pro [1] aktuálně počítáme špatně velikost dle #886, neboť má to jen 1 select - nemá FROM, ale má to WHERE

uděláme z toho SELECT (count(*) AS ?selectSize) WHERE { GRAPH ?g {?x ?y ?z}}
tedy zanedbá se to DISTINCT, což se v původním případě nedělo.

**Comment by tomas-knap** [comment]
Navrhuji rozsirit logiku takto: 

Je-li v puvodnim SELECTu DISTINCT, tak se takovy dotaz neda optimalizovat a postupuje se jako v pripade, ze je tam vicero selectu.

**Comment by tomesj** [comment]
Dobře, rovnou to tak naimplementuji :-)

**Comment by tomas-knap** [comment]
pozor ze distinct muze byt velkym i malym pismem

**Comment by tomas-knap** [comment]
teoreticky i jako DistincT

**Comment by tomesj** [comment]
Tohle mám všeobecně podchycené :-)

**Comment by tomas-knap** [comment]
Tak je to komplikovanejsi, viz napriklad dotaz: 
SELECT (count(*) as ?x) WHERE {?s ?p ?o} LIMIT 1000

Tak prosim pro ted zakomentuj to tvoje vylepseni a nech tam tu puvodni variantu, tedy SELECT (count(*) as ?x) WHERE { SELECT {} }. Tedy necht se to vzdy chova jako by tam bylo vic SELECTU, tedy tak jak se to chovalo driv. Pardon ;)

**Comment by tomesj** [comment]
Dobře - vrátím to tedy zpět na původní variantu :-)

**Comment by tomesj** [comment]
Vrácené zpět na původní verzi pro výpočet v případě selectu. Tím bych to asi uzavřel :-)

**Comment by tomas-knap** [comment]
For working with Virtuoso, it is fast enough (immediately) for 50000 triples.

**Comment by tomas-knap** [comment]
Test on localRDF

**Comment by tomas-knap** [comment]
When trying localRDF, it is really slow, 60s+ please try that. You can use extractor with settings: 

Please examine the source code, especially the work with native repository. Can something be optimized? Pri tehle rychlosti staci krokovat a pozorovat co trva tak dlouho a proc. Muze to byt par vterin, ale ne 60s+

There must be some problem when working with localRDF store

**Comment by tomas-knap** [comment]
Browse not useful with localRDF repo!! This is critical

**Comment by tomas-knap** [comment]
1)
"- Bohuslav totiž v RDFQuery používá v metodě size() a loadItems vždy novou instanci pro LocalRepo

tedy během browseru se dvakrát vytvoří repozitář a dvakrát se do něj nasypou data
to lze zrychlit určitě na jedno načtení - držet si ten repozitář sdíleně (podobně jako connection)."
Jo, to by urcite slo. Kolik by to obnaselo prace?

2)

"Jde o to, že pro localRepo abychom mohli spočítat velikost, tak načítáme do repozitáře daný soubor graf

nejvíce času pak trvají načtení dat ze souboru do repozitáře - metoda parse(fileStream, baseURI)"
Pockej,kdyz pustim v rezimu debug pipeline nad virtuosem, tak po dobehnuti zustanou data v pristusnych grafech v DB. Kdyz pustim v rezimu debug pipeline nad local RDF, tak potom zustanou soubory, ktere uz primo predstavuji ty native repozitories ne? Tedy staci se nad tim souborem (repozitarem) dotazat stejne jako nad virtuosem, ne? Nebo jak si tam ukladas data pro pozdejsi browse/query?

3)
"- dále ještě metoda setContainerDataSource - řádek 210, třída IntlibPagedTable, frontend (především super.setContainerDataSource(newDataSource));"

V pripade prochazeni dat na virtuosem to trva stejne dlouho nebo podobne?

**Comment by tomas-knap** [comment]
Od JIRKY:

1) Už jsem opravil viz commit 9d20a5162c3c0ade229bbc4f3ab3508b395da8eca a issue #886

2) Pro Virtuoso je to tak jak píšeš, pro LocalRepo by to šlo taky, ale tam se ty data nasypou do souboru a pak se vytvoří prázdné LocalRepo a všechno se tam nasype.

Rozdíl je v tom, že když vytvoříš instanci virtuosa a dáš mu správný graf, můžeš rovnou pracovat.
Když jednou vytvoříš LocalRepo můžeš s ním pracovat tak dlouho, dokud ho nezničíš. Jak to ale jednou uděláš, už nemáš šanci - jde o to, že pak nelze udělat něco ve smyslu vytvořím instanci a dám jí jen název grafu a můžu pracovat (tak jako pro virtuoso), to tady nefunguje - proto se data před "zničením" načítají do souboru a zase "načítají" do repozitáře :-)

Alternativou by bylo držet si jeden/více repozitářů někde a nikdy je neukončovat (jen v případě ukončení) aplikace - pak by se data nemusela načítat.

3) V případě Virtuosa je to rychlé, ta metoda totiž volá v sobě to druhé načítání repozitáře - v současnosti už je to sdílené, takže je taky už rychlá :-)

**Comment by tomas-knap** [comment]
Jirko, add 2) : 
Co brani tomu pri pipeline exec na localRDF prehravat ta data z jednoho repozitare do druheho primo? Jedine co musis zajistit je, ze pri mergovani si udelas nejaky repozitar, ktery pak priradis prislusne data unit. Ale mergovani se deje na zacatku prislusneho nasledneho DPU, takze to by melo byt ok?

Co se tyce toho browse/query, co nechapu je, proc se kdyz poustim pipeline v debug rezimu vse vysype do souboru a kdyz dam pak browse/query, tak se data nejdriv musi nahrat do rep a az pak se nad nimi da dotazovat. Proc proste nemuzou zustat ty native repozitories v adresari misto tech souboru?  A kdyz se pak dotazuju, tak si jen pustim prislusnou native store (s jiz nahranymi daty) a dotazuju se rovnou. Neni to pozustatek toho inMemoryStore, ktere se pak ukazalo jako nedostacujici?

**Comment by tomas-knap** [comment]
Jeste tu tedy chybi vyresit: 

Jde o to, že pro localRepo abychom mohli spočítat velikost, tak načítáme do repozitáře daný soubor graf
- nejvíce času pak trvají načtení dat ze souboru do repozitáře - metoda parse(fileStream, baseURI)
- dále ještě metoda setContainerDataSource - řádek 210, třída IntlibPagedTable, frontend (především super.setContainerDataSource(newDataSource));

Coz souvisi i s predchozim komentarem, jirko komentuj prosim

**Comment by tomas-knap** [comment]
promysli a priprav prosim na zitra jak by se to dalo resit, aby se dalo pracovat primo s native repositories a nemuselo se to presypavat do souboru a zpet. Podle me je to pozustatek toho inMemoryRep, kde se to proste nejak serializovat muselo (do souboru), ale pro native rep to neni nutne

**Comment by tomas-knap** [comment]
Duvod Jirko, proc trva na tehle optimalizaci je, ze s tim Virtuosem to porad funguje dost na heslo, tedy localRDF je stabilnejsi. Ale ten browse je moc pomaly

**Comment by tomesj** [comment]
Na to se podívám, jaké máme varianty

Z toho, co zbývá (trvá dlouho)
- to načtení souboru do repozitáře - metoda parse(fileStream,baseURI)
- setContainerDataSource - je už vyřešeno tím sdílením repozitáře 

Jako mě nahrávání dat ze souboru taky přijde jako kravina, které zbytečně zdržuje. Souhlasím, že nejlepší by bylo si držet příslušné native ve složkách místo souborů. Teď jde jen o to, jestli můžeme když vytvořím instanci na místě, kde máme localNative soubory, tak jestli se to automaticky nepřepíše - tedy že budeme muset mít native stále aktivní. To zjistím a dám vědět

**Comment by tomas-knap** [comment]
Pockej, ale tu instanci muzes vzdy delat v tom pracovnim adresari a ten je unikatni pro kazdou execution, ne?

**Comment by tomesj** [comment]
To je pravda, pracovní adresář je unikátní, ale po vytvoření musíš zavolat metodu inicialize a tam se obávám, že si soubory pro repozitář tvoří sama - nezajímá jí, že je zrovna na místě, kde už nějaké soubory jsou. To ale musím ověřit, když by to tak nebylo, tak by asi nebylo co řešit - stačilo by nemazat repozitář :-)

**Comment by tomesj** [comment]
Tak je to dobré - když mám repozitář typu native (localRepo) na nějaké cestě, vytvořím instanci, používám,...na konci musím zavolat shutDown pro uvolnění. Když se pak zadá stejná cesta, stejné ID a stejné jméno grafu, rovnou se inicilizuje repozitář se správnými daty - tedy nic se nepřepisuje

Tedy stačí si ten repozitář opakovaně tvořit na stejné cestě a bude to OK
- tohle stačí vyměnit (někde kde to používá frontend/backend) a bude to vyřešené :-)

**Comment by tomas-knap** [comment]
Ok, to je dobra zprava. Tedy prosim popis co je potreba upravit.

**Comment by tomesj** [comment]
V podstatě stačí znát
Cestu k repozitáři, jeho ID, dataUnitName a namedGraph, se kterým se pracuje

Instanci vždy vytvářet jako
RDFDataUnit unit=RDFDataUnitFactory.createLocalRDFRepo(path,id,dataUnitName,namedGraph);
po použití volat unit.shutDown() nebo unit.release()

Co je potřeba upravit
1) Tam, kde se ukládalo
- pamatovat si ty udaje, aby pak šel přesně stejnou cestu, měl stejné ID, graph,...

2) Tam kde se používalo (načítalo)
Nepožívat RDFDataUnitFactory.createLocalRDFRepo("") a pak unit.load(..), ale vytvořit instanci podle všech parametru - rovnou obsahuje všechna data, která tam měla po posledním použití, pokud se nic nesmazalo.

Poznámka
nevolat unit.delete() - to totiž vymaže všechny soubory včetně dat, při vytvoření by byl repozitář prázdný

**Comment by tomas-knap** [comment]
A tohle implementoval kdo v te soucasne verzi?

**Comment by tomesj** [comment]
Je to ve frontendu, možná i v backendu - tak předpokládám, že Petr nebo Bohuslav

**Comment by tomas-knap** [comment]
We will discuss tomorrow

**Comment by tomas-knap** [comment]
1) Je treba upravit RDFDataUnitHelper.getRepository() - JIrka poresi s Petrem kde ziskat params pro inicializaci repozitare
2) soubor se vubec nevytvari pri pipeline run a localRDF

**Comment by tomas-knap** [comment]
Jirko, poprosil bych jeste nejake porovnani. Tedy ze nahrajes trebas 50000 trojic a pak zkusis browse a nejaky dotaz na virtuoso a localRDF. Vysledky prosim zapis na confluence na zvlastni stranku do devel. notes. Zopakujj pro milion trojic.

**Comment by tomas-knap** [comment]
U me se to zda ok, cekat 4-5s se da. Zkousel jsem 50.000 a 300.000.
Akorat se mi nelibi ze delam praci za tebe

**Comment by tomesj** [comment]
Včera jsem seběhnul pipeline s těmi půl miliony triplů, dnes jsem se chystal na ten milión. Stačilo jen počkat - byl jsi ale koukám mnohem rychlejší :-)

**Comment by tomas-knap** [comment]
V pohode, s temi pul miliony to bylo ok?

2014/1/10 Jiøí Tome¹ notifications@github.com

**Comment by tomesj** [comment]
Jo, vše OK :-)

**Comment by tomesj** [comment]
Tak pro 1 mil trojic jsem u sebe zjistil hodnoty následující
Virtuoso - cca 20 s
LocalRDF - cca 50 s

**Comment by tomesj** [comment]
Summary results were added to confluence page:
https://grips.semantic-web.at/pages/viewpage.action?pageId=51808678

**Comment by tomas-knap** [comment]
ok, diky

2014/1/11 Jiøí Tome¹ notifications@github.com
