### ISSUE TITLE
Loader - check that first chunk is not skipped

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#889]
SPARQLLoader, line 347 - first part is constructed, but never loaded. The loader starts from loading the second part with offset at "chunk size"

**Comment by tomesj** [comment]
That is not true,
- first part defined on line 347 is set to String query (see line 359), and then is prepared second part used in next while cycle (on line 360). If next data part doesn´t exist null value is return and while cycle ends. 

For loading is used method getEndpointStreamReader with parameter query (line 367)

**Comment by tomas-knap** [comment]
jj, vidim, ok
