### ISSUE TITLE
Back button needs to preserve the page listed in paged lists

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#891]
When I am on page 2 in pipelines, click on a pipeline and go back, I end up on page 1 of the list. This is VERY annoying and probably applies to all lists.

**Comment by tomas-knap** [comment]
The solution would be to remember the already set filters. I have found that it is annoying mainly in the pipeline list. We have everywhere the clear filters button (in pipeline list/exec monitor/scheduller event/manage users), so I would suggest to remember the filters in these cases?

**Comment by jakubklimek** [comment]
Yes. Filters also need to be remembered.

**Comment by bogo777** [comment]
For this to work correctly we would have to save paging/filtering information as part of url. Such change will take some time. I will start with paging first.

**Comment by skodapetr** [comment]
Do we? really? I mean .. the pages are spring beans .. with scope "session" so we can basically hold them .. and reuse them - so we can show the page in the last state.

But also the questions if our application design is ready for this (and I believe it's not :( .. it can be easier to use URL as Bohuslav suggest. 

I just want to mention this as imho a possible solution.

**Comment by bogo777** [comment]
Well Back button and its action is made by browser and it is not detectable as different from direct URL access in Vaadin. For menu clicks we could propably differentiate.

I looked at this and using uri fragment seems like standard solution for this in Vaadin. And it shouldn't be too hard, there is already working example for paging in pipeline list.

**Comment by tomas-knap** [comment]
Should we test?

**Comment by tomas-knap** [comment]
Pipeline list. If I repeatadly add owner filter and then click clear filters, strange uri si being built - URI with duplicates:

http://odcs.xrg.cz:8080/odcleanstore-test/#!PipelineList/page=1&owner.use&owner.use&owner.username=admin
http://odcs.xrg.cz:8080/odcleanstore-test/#!PipelineList/page=1&owner.use&owner.use&owner.use&owner.use&owner.use&owner.use&owner.username=admin

Further, if I add filter, which does not filter anything, but I put it there, it is not reflected in the URI (try it for "name" in pipeline list)

**Comment by bogo777** [comment]
There was problem with parameters matching in uri fragment(name filter is substring of owner.username), should be fixed now.

**Comment by tomas-knap** [comment]
back button works correctly
