### ISSUE TITLE
SPARQL transformer don´t need add/merge data to unused inputs

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#893]
Actually when we used SPARQL transformer we merge/add data to all inputs (input, optional1,...optional3), but when this data are large collection and we used only one (or two) inputs of that - we don´t merge data to others unused inputs - transformer is slowly.

Goal is merge/add only to used inputs and transformer will be more faster :-)

**Comment by skodapetr** [comment]
@tomesj : Mohl bych poprosit o nějaký rozpis? Nebo co je cílem .. neb definice "pokud se to nepoužívá, tak to tam nepředávat" .. co znamená nepoužívá a jak na tohle přijdu? 

Pokud tam není mapování tak se nic nepředává, pokud tam je .. tak nemám šanci zjistit jeslti se to pak v DPu použije nebo ne.  - tady bych spíše viděl Lazy RDF DataUnit, jenž by nemusela Merge vykonávat okamžitě ale až po dalším použití.

**Comment by tomesj** [comment]
No jde hlavně o to, aby se mergovalo jen na to, co je skutečně namapované - jsem včera koukal na nějakou pipelinu na odcs.xrg.cz a zdálo se mi, že to právě tak nebylo (možná že jsem se špatně díval)

**Comment by skodapetr** [comment]
@tomesj: No možná, tedy pokud by jsi měl po ruce log .. neb pokud je to jak říkáš, tak je o chybu, nikoliv záměr. Neb ty bez mapování by to mělo ignorovat. Tedy pokud by jsi narazil na takové chování, tak bych asi poprosil o odkaz, abych mohl prozkoumat kde je chyba.

**Comment by skodapetr** [comment]
@tomesj Sice je to iterace 5, ale i tak, proč mít otevřený issue. Máš tedy Jirko nějaké podklady? jestli ne, tak jeslti by jsi to tu zavřel a půjdeme zase o dům dál :)

**Comment by tomesj** [comment]
Já tu chybu někde viděl, až ji najdu, tak ti jí sem dám, prozatím Ti to tedy zavřu :-)
