### ISSUE TITLE
Scheduller - run after another pipeline 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#895]
When setting in scheduller "run after another pipeline", in the list of pipelines this pipeline will run after I should not see pipeline for which the current scheduled event is prepared.

**Comment by skodapetr** [comment]
Reassign, I think I'm the right person for this as I'm author of the container used in this case.

**Comment by skodapetr** [comment]
Přidal jsem k InMemorySource metody (as asi špatně napsal číslo issue :( ) .. pro add, remove položky .. tedy mělo by být možné podle aktuálně zvolené pipeline odebírat-přidávat tento seznam. 

Neb není nejlepší při každém výběru, znovu načíst celý seznam .. a pak jen jednu odebrat.

Bohužel, trochu nerozumím kódu (v SchedleDialogu) a jeho struktuře, tedy předávám Marii jako autorce, snad jí úprava potrvá kratší dobu než by trvala mně.

**Comment by tomas-knap** [comment]
Marie?
