### ISSUE TITLE
SPARQL Extractor/Loader - SPARQL Endpoint should not be prefilled

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#896]
Currently, there is a value http://, which is prefilled. THis is wrong. The field should be empty and mandatory - user has to fill the value. 

Solution: Show http://localhost:8890/sparql as a hint to the user (greyed) in the textbox for SPARQL endpoint. Adjust in both cases - extractor/loader

**Comment by kukharm** [comment]
"http://" was set directly in DB i changed file  data.sql in project. For changes in local DBs it needs to use script prepared by Jirka (i'll send in email).
