### ISSUE TITLE
Pipeline confict - the current pipeline should not be in the list

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#897]
In the list of pipelines with which the current pipeline is in conflict should not be the pipeline itself, this is strange. related to #895

**Comment by skodapetr** [comment]
Well It's actually the use-case from Jakub. From first point of view it may be confusing (hope the documentation helps here). The reason for this is to enable run only one instance of given pipeline at time.

reassigned to me

**Comment by tomas-knap** [comment]
Ok, the documentation should probably help, please tell maria how the user documentation should be extended and assign on her

**Comment by skodapetr** [comment]
Dobře, tedy @kukharm pro připomenutí: v seznamu konfliktních pipeline jsou všechny pipeline .. pokud je některá pipeline přesunuta do toho seznamu vpravo . tj. je konfliktní, tak se ta aktuální pipeline (tak ke které jsou to konflikty) čeká až skončí executions těch konfliktních a až pak se pustí její exekuční část (čeká ve stavu running). 
Pokud vyberu pro pipeline A konflik s A .. tak to znamená, že může běžet aktivně jen jedna instance. Pokud jich pustím více, tak se hezky provedou jedna po druhé. 

Tj. prosím zda toto odpovídá dokumetnaci? Ale myslím, že by mělo.

**Comment by kukharm** [comment]
i added information https://grips.semantic-web.at/display/LOD2/Pipeline+conflicts

**Comment by tomas-knap** [comment]
Ok, current pipeline should be there
