### ISSUE TITLE
Check all text fields and provide user friendly error message

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#898]
WHen going to settings -> myAccount and filling "aa" to number of items on page, it displays an error, which is ok, but the text of the error must be more user friendly - It should be understandable to nonIT person - so something like "Number of pages in the list must be a number. You entered XX. Please correct that before saving. "

Please check that for all text boxes in the core app (not for dialogs for DPUs) - check that if number is expected, user cannot enter anything else and save it. If number in some format is expected, check that format.

**Comment by kukharm** [comment]
Resolved by commit https://github.com/mff-uk/ODCS/commit/57b0b38f5aa5970b69d0092a67ceb7d53395189b
