### ISSUE TITLE
ModuleException -load config dialog

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#9]
![bug](https://f.cloud.github.com/assets/3481055/473905/2dc36e32-b75a-11e2-92ca-15f2665a4b31.jpg)

I found it in master and in release 0.1.1

**Comment by skodapetr** [comment]
Could you please send me jar file with this DPU?

**Comment by skodapetr** [comment]
Fixed. The DPU implementation used unimported package. Add some more detail message for this case ? ...
