### ISSUE TITLE
Create DPU dialog

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#90]
When selecting JAR file and clicking on button "Upload", upload dialog appears and the file is being uploaded. that is fine. However, when upload finishes, see picture below, 
1. the upload dialog does not dissapear 
2. there is label next to the upload button, which says "no file selected". But there should be the file which was just apploaded
3. I don't see the reason for two buttons- choose file and upload. One is enough.

To solve 2 and 3, I would suggest to:
Hide button upload. The file will be uploaded right after confirming the selection of the file. Remove the label "Upload file: xxx.jar". The name of the uploaded file should be next to the button "Choose file" instead of label "no file selected". 

![screen shot 2013-07-11 at 1 37 14 pm](https://f.cloud.github.com/assets/3014917/781317/7a96e90e-ea1e-11e2-8d0b-0181ebef7b0d.png)

**Comment by tomas-knap** [comment]
Great, it works, 

three more comments to DPU create:
1. Visibility should be preselected in the DPU create dialog as Public, user may change it but one option has to be selected.
2. When clicking on the button cancel during uploading, the dialog closes. However, I am not able then to upload any other file. Solution: When cancelling upload, I have to be able to select and upload new file. 
3. When saving and the JAR file already exists in the target/dpu folder, it wrotes: 

![screen shot 2013-07-12 at 11 49 19 am](https://f.cloud.github.com/assets/3014917/787403/0c8b9994-ead9-11e2-8ae6-c1f7f2a30561.png)

The required behaviour is as follows: 
- check if certain existing DPU template uses the already existing JAR file 
  If not, you may simply replace the file with the file user would like to upload and no error occurs.
  If yes, the error message should involve information about the name of the DPU template which already uses such JAR file. User is not allowed to upload the JAR file with the same name.

**Comment by kukharm** [comment]
I can't catch 2.

I choose a file.
Then the status window with upload info is appear.
I push the Cancel button, after that the upload is interrupted and the status window closes.
Then in the DPU Template Creation window I push the button "Choose file"
The window for file choosing is open and i choose a file. Then the status window with upload info is appear....
I can wait until the download is complete, or cancel it and repeat the procedure again.

**Comment by tomas-knap** [comment]
Maria, ad 2), you select file, confirm by OK. Then during the upload process, you click "Cancel" in the upload dialog. Next, you try to select new file. As a result, no upload dialog occurs. Can you replicate that?

**Comment by kukharm** [comment]
I do that, but  after selected a new file I have the uploading process in normal mode.

**Comment by tomas-knap** [comment]
Ok, lets discuss that during next meeting

**Comment by kukharm** [comment]
I wrote a mail to our team with a request to test this scenario.

**Comment by tomas-knap** [comment]
Works for others
