### ISSUE TITLE
Cancelled executions are restarted when the backend is again onlince

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#902]
TO reproduce: On ODCS, I cancelled executions:

![screen shot 2013-12-12 at 10 16 28 am](https://f.cloud.github.com/assets/3014917/1731696/912bd238-630e-11e3-9939-421e6ffbd9c1.png)

They are not properly cancelled, because extractor does not support cancelling.

Then I restarted backend and these cancelled executions are restarted - even if they were cancelled and have strict timing in scheduller:

![screen shot 2013-12-12 at 10 17 56 am](https://f.cloud.github.com/assets/3014917/1731699/b62276f0-630e-11e3-93f1-2e434c29b291.png)

Solution: When there is any exec monitor in the cancelling status, it should NOT automatically starte when backend is online again.

**Comment by skodapetr** [comment]
The problem has no relation to the .. cancelling state .. no so long ago I have updated the run-after functionality and made some mistakes .. which results in this behaviour .. it should be ok now .. for every case I have added some logs. 
I also add special message for cancel-saniteyer.

**Comment by tomas-knap** [comment]
Not working properly, at least on ODCS. 

I just restarted twice backend and executions 23142, 23143, 23135, 23136 are still in cancelling state

**Comment by skodapetr** [comment]
And the virtuoso is responsible? As from logs and.. when canceling, the DataUnits are deleted .. if they use virtuoso and the virtuoso is iresponsible .. then the cancelling thread wait for virtuoso to responds ..

**Comment by tomas-knap** [comment]
problem is with virtuoso, otherwise cancelling is ok
