### ISSUE TITLE
Menu behaves strange when screen is resized

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#905]
![screen shot 2013-12-12 at 10 35 49 am](https://f.cloud.github.com/assets/3014917/1731779/337513cc-6311-11e3-832d-a19f4cfe6355.png)

Menu should not shrink

**Comment by skodapetr** [comment]
I do not even know that Vaadin have this functionality.
imho: on the other hand it's more like it's not a bug it's a feature. On the small screen (like the ine in the picture) you do not have to scroll in order to have full access to the menu.
