### ISSUE TITLE
Align DPU TEmplates-> DPU Instances with PipelineList

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#907]
DPU TEmplates -> DPU instances:

DPU Instances show all the pipelines user may normally see (the content is the same as for PipelineList)
Just check that it is the same as for pipelineList

**Comment by bogo777** [comment]
Currently, all pipelines with DPU are shown. I tried to change it, but didn't succeed. Can @janvojt help me? 
I tried to modify PipelineFacadeImpl.getPipelinesUsingDPU() with @PostFilter("hasPermission(filterObject,'view')") but that's propably wrong.

Also, what happens, when user A creates DPU, makes it public, user B uses it in private pipeline, but user A wants to delete the DPU?

**Comment by tomas-knap** [comment]
Well, what we can do is that we show the tab "DPU Templates -> DPU Instances" only for admins.

**Comment by tomas-knap** [comment]
Please discuss here @janvojt

**Comment by janvojt** [comment]
I reassigned to myself. Should we bump priority to high?

**Comment by tomas-knap** [comment]
How much time do you need for it?

**Comment by janvojt** [comment]
> what happens, when user A creates DPU, makes it public, user B uses it in private pipeline, but user A wants to delete the DPU?

From the documentation:

> Available actions on DPUs:
> - DELETE
>   - Available to DPU owner
>   - Only available if DPU is not used in any pipeline => can be safely deleted.
>   - The User can Delete only the DPUs , which was created by himself. 

Therefore, user A needs to ask user B to delete DPU instance from his pipeline.

**Comment by tomas-knap** [comment]
Ok, so you suggest that DPU templates -> DPU instances will be visible only to admins and author of the DPU? 
When the author of the DPU would like to delete DPU which is used on some pipeline created by another user, he has to ask that user to delete the pipeline. If admin, author of DPU would like to delete the DPU which is used by another user, he can firstly delete the pipeline of the other user and then delete the DPU.

So the only thing which has to be done: 
1) DPU instances tab is visible to admins and author of the DPU template
2) DPU instances tab shows the pipelines normally visible to the current user

**Comment by tomas-knap** [comment]
That does not work for me, see ODCS-test. I logged as a "user" and still can see DPU instances and all pipelines using it. Is that because the DPU template is public? So basically I can see DPU instances for all public DPU templates?

**Comment by janvojt** [comment]
> Is that because the DPU template is public?

No, it is because the pipelines are public.
