### ISSUE TITLE
Pipelines in strange state in exec monitor

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#909]
When looking at ODCS, on executions 725-730, something strange happened there: 

Although the exec  detail says pipeline finished, it is still in the cancelling state:

![screen shot 2013-12-12 at 1 22 22 pm](https://f.cloud.github.com/assets/3014917/1732832/13541018-6328-11e3-986e-b7b861d1180f.png)

Or pipeline is in the state of running in exec monitor, but based on the events, it has already finished: 

![screen shot 2013-12-12 at 1 22 48 pm](https://f.cloud.github.com/assets/3014917/1732836/2c65c556-6328-11e3-82c8-01a2fb8f3523.png)

So it seems that the state of the pipeline does not reflect the actual state. But it is also strange, that time is not running for the pipelines being in the cancellin/running state. As looking to db, it is wrong in DB, so gui is actually showing it right based on the DB. But why the duration is not updated in GUI?

May be related with #902 

@bohuslav please check that as wel

**Comment by skodapetr** [comment]
Je to divné .. prohlédnu logy. Zkusil bych redeploy poslední verze - to by mělo pomoci s #902 a snad ukončit ty vysící. Také jsem přidal pár logů jenž by měli napovedět jak k této situaci došlo, bez toho pro to nemám snadné vysvětlení.

**Comment by tomas-knap** [comment]
Ok, zkusim redeploy a uvidime

**Comment by tomas-knap** [comment]
Tak jsem zkusil verzi z 14.12. (rano) a nefunguje to: 

![screen shot 2013-12-16 at 8 43 32 am](https://f.cloud.github.com/assets/3014917/1752648/c93606ec-6626-11e3-9815-a9777786cde4.png)
![screen shot 2013-12-16 at 8 43 22 am](https://f.cloud.github.com/assets/3014917/1752649/cd203246-6626-11e3-94c4-f344c6d2d6ea.png)

Pipelines sebehnou, to je ok. Nicmene status se neupdatuje, tedy ackoliv pipeline uz davno skoncili, maji stale nastaveno running. Blbe je to uz v DB, kde jsou ve stavu running. 

![screen shot 2013-12-16 at 8 51 07 am](https://f.cloud.github.com/assets/3014917/1752651/d9df0304-6626-11e3-9f37-083593a2ea55.png)

**Comment by tomas-knap** [comment]
Check exec 23108-23112

**Comment by skodapetr** [comment]
It looks like there is problem in logs flush, I have removed call of this function please try redeploy.
