### ISSUE TITLE
Combo with 10+ DPU instances

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#910]
If the pipeline has more then 10 DPUs, then, when looking at combo box in exec monitor detail, strange things happen. It shows the first cca 9 items. When clicking on the link to get more: 

![screen shot 2013-12-12 at 2 42 57 pm](https://f.cloud.github.com/assets/3014917/1733229/7fbf3eca-6333-11e3-81aa-726024ce4461.png)

**Comment by bogo777** [comment]
It was caused by refreshing the DPU list. But it is changed only upon finishing the execution, so it is now the only time it will be refreshed.
