### ISSUE TITLE
Execution monitor: Execution list (left part) overflow and no scrollbar

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#913]
![image](https://f.cloud.github.com/assets/718827/1740388/a6d19ba6-63c5-11e3-9a3b-29045d7724a9.png)

**Comment by bogo777** [comment]
Column name was changed and width was set for bad column. Please test it now and if this still occurs, can you write your browser and its version?

**Comment by tomas-knap** [comment]
Please test
