### ISSUE TITLE
If DPU (SPARQL Extractor) is cancelled, it should not try to reconnect 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#917]
If if it is set to be reconnected indefinitely

**Comment by tomas-knap** [comment]
Jirka, can this be done easily?

**Comment by tomesj** [comment]
Nevím, jak to přesně je myšleno - nějaký příklad by nebyl ? 

Když se extrakce to dostane do metody getEndpointStreamReader, kde se získává stream s daty z endpointu, tak se to získávání spojení řídí počtem pokusů (neboť tato metoda je univerzální pro více použití a tak nemůže mít v sobě context sledující přerušení).

Přerušení se dá udělat buď před tím nebo až během parsování dat.

**Comment by tomas-knap** [comment]
Mno, problem je kdyz zadas spatnou adresu SPARQL endpointu. Pak se ti to reconnecti porad a nejde to zrusit. Si zkus udelat pipeline se SPARQL Extractor a zadej nejaky neexistuji endpoint.

**Comment by tomesj** [comment]
Tak jsem to zkusil a skončilo mi to hned na chybu: UNKNOWN HOST :-)

**Comment by tomas-knap** [comment]
tak zkus dat do sparql endpointu http://localhost:8080/sparql

**Comment by tomesj** [comment]
Tak tentokráte mi to rovněž skončilo, tentokráte na chybu:
HTTP/1.1 404 Not Found.

**Comment by tomas-knap** [comment]
tak zkus http://internal.xrg:8080/sparql

**Comment by tomesj** [comment]
Tak opět chyba Unknown host :-)

**Comment by tomas-knap** [comment]
I will show you on the f2fmeeting

**Comment by tomesj** [comment]
Tohle už není dávno aktuální, ne ?
