### ISSUE TITLE
SPARQL Extractor - settings how many times it should try to reconnect in case of problems

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#918]
Motivation: If I put wrong connection string, it tries to reconnect indefinitely

Solution: As for SPARQL loader, extractor should be also configurable regarding how many times it tries to reconnect in case of problems. Default is 10.

**Comment by tomesj** [comment]
Default is -1 (infinity), not 10 (this is default chunkSize).

So I add these parameters (attempts count + time between them) to SPARQL extractor dialog same as to SPARQL loader, OK ?

**Comment by tomas-knap** [comment]
Ok, but it is connected with #917, if sparql extractor is cancelled, it should not try again and again to connect using wrong connection string

**Comment by tomesj** [comment]
Problem solved :-) Retry parameters add to SPARQL extractor (same as to SPARQL loader).
