### ISSUE TITLE
Check that autorization works as defined below

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#921]
https://docs.google.com/document/d/1DW6NtUmRFS2tlWu-FeHlsXTS2u45atyCrBY8BYM6uag/edit

We tried to simplify that as much as possible. 

Ask Bohuslav to prepare: 
In pipeline detail: Public-R: add such possibility to pipeline edit (user may set the pipeline to be private, public-R, public-RW) (Bohuslav)
Instead of header “Editing pipeline”, use header “Pipeline detail”. In case user has only Public-R rights to the pipeline, there should be read text after “Pipeline detail” saying “Pipeline is open in read-only mode”  (Bohuslav)

**Comment by tomas-knap** [comment]
Related to #922

**Comment by janvojt** [comment]
I believe I am done, assigning to Bohuslav.

**Comment by bogo777** [comment]
Needed changes described in #945 and done.

**Comment by janvojt** [comment]
Currently, if user changes pipeline to public-RO, he can then change it to public-RW. However once pipeline is set as public-RW it cannot be changed back to public-RO. I understand why it cannot be changed to private, but I think it would be useful to leave the possibility to change to public-RO (I can't think of any problems that might arise from this). @tomas-knap what do you think?

**Comment by tomas-knap** [comment]
Yes, it should be possible to change pipeline from public-RW to public RO
