### ISSUE TITLE
Authorisation - support

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#922]
https://docs.google.com/document/d/1DW6NtUmRFS2tlWu-FeHlsXTS2u45atyCrBY8BYM6uag/edit

related with #921

**Comment by tomas-knap** [comment]
Petre, napis prosim jaky je stav, muzem tohle uzavrit?

**Comment by skodapetr** [comment]
Ono je to paralelní k #921 , za mě tam toho snad už moc není .. tedy možná bych v tom 921 dořešil spíše ..

**Comment by tomas-knap** [comment]
Petre, mas tu jeste neco nebo uz je to hotove?

**Comment by skodapetr** [comment]
Myslím, že v této věci už se vše udělalo .. a co se neudělalo, to už se zapomnělo.
