### ISSUE TITLE
Backend neuklada nic do DB

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#923]
Latest change (yesterday/today till 14:00) caused that events, changes in the pipeline state, ... are not stored to DB - but it should be there according to logs of backend. 

If pipeline is in queued state, it starts again and again (state is not stored).

@janvojt  could it be connected with aspects introduced in the recent days?

Connected to #919

**Comment by skodapetr** [comment]
Zkoum jsem logy .. a narazil na věci jako: 

```
2013-12-13 14:35:21,248 [pool-2-thread-1] INFO  exec:745 dpu: c.c.m.x.o.b.p.e.PipelineInfo - Starting execution number: 745 pipeline: Extractor test
2013-12-13 14:35:21,283 [pool-2-thread-1] INFO  exec:745 dpu:474 c.c.m.x.o.b.e.p.Executor - Starting execution of dpu 474 = SPARQL Extractor
2013-12-13 14:35:40,916 [pool-2-thread-2] INFO  exec:745 dpu: c.c.m.x.o.b.p.e.PipelineInfo - Starting execution number: 745 pipeline: Extractor test
2013-12-13 14:35:40,931 [pool-2-thread-2] INFO  exec:745 dpu:474 c.c.m.x.o.b.e.p.Executor - Starting execution of dpu 474 = SPARQL Extractor
```

Tj. pipeline staruje pořád, to by mohlo vysvětlit #919 - ale, po startu pipeline je stav nastaven na running a pak by neměla být spuštěna znova - tj. její stav se nemění (což je vidět i ve frontendu).

Dále k posledním běhům na ODCS jenž se chovají takto podezřele nejsou žádné events= messages i když podle logů by být měli.

Log jako takový tam totiž je a ten se generuje v konstruktoru té eventy, zároveň jsou také logy z aspektů .. tj. zřejmě se tam volá něco s DB. 

@janvojt  Tj přijde mi, že backend vůbec nekomunikuje s DB, je to možné, poznáš to z logu na odcs?

Dále jsem objevil, jisté duplicity v logu (jiné než způsobené tímto) ty by mohli být způsobené výpadky Virtuosa a mojí chybou v implemntacei SqlAppenderu .. to prověřím, nicéně nelze to příliš posoudit díky nic moc stavu zbytku app.

**Comment by janvojt** [comment]
Teraz nemam cas to riesit, ale moze to byt tym aspektom. Zakomentujte nad tym mojim aspektom co som vcera menil anotaciu `@Aspect`, ak to zacne fungovat tak je to tym. Zajtra sa nato pozriem. Popravde backend som vobec neskusal ci funguje spravne...

**Comment by janvojt** [comment]
Je mozne ze sa to bije s aspektom pre backend, ktory zaistuje retry pri spadnuti DB, oba aspecty su na niektorych rovnakych metodach. Inac si neviem vysvetlit preco by to pre frontend fungovalo a pre backend nie.

**Comment by tomas-knap** [comment]
Solved by removing aspect which was used to update wrong sequences in DB. Problem - solution for sequences should be different
