### ISSUE TITLE
RDF File Extractor - uploaded file at a wrong location

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#930]
If I upload a file in RDF File extractor and then run the pipeline, I got: 

![screen shot 2013-12-16 at 12 49 59 pm](https://f.cloud.github.com/assets/3014917/1754050/6c36ce32-6648-11e3-843b-3126c6d5a09c.png)

Please test a simple pipeline on ODCS with a single file extractor, upload a file there.

**Comment by tomas-knap** [comment]
It was working earlier, please explain where the problem is

**Comment by kukharm** [comment]
I didn't do ​​any changes in  RDF File Extractor in recent times. The uploader of  RDF File Extractor uploads file to template directory of users PC as it was earlier. I checked this template directory and the file really was there. 
In execution monitor i get message that Path to file "C:\initlib2\intlib\backend\null\dbpedia2.ttl"doesnt exist. I don't know why application try to find file in C:\initlib2\intlib\backend\ (in my case) may be it knows someone from backend.
![file extractor](https://f.cloud.github.com/assets/3471169/1754711/f590f3b6-6656-11e3-8d11-5fb23a720e5e.jpg)

**Comment by kukharm** [comment]
I also have problem with file loader path 

![fileloader](https://f.cloud.github.com/assets/3471169/1754758/2475cdd6-6658-11e3-8c9d-ce2d12dd4dcf.jpg)

The path i was set in file loader dpu was  С:\ted\testextractor.rdf

**Comment by skodapetr** [comment]
The description in DPU (on the screen) does not have to be "up-to date". Can you provide screenshot of the configuration screen or even serialized configuration? 

Also please .. how did you created the RDF extractor? From some template ?

In this case .. the description is probably out-dated .. this can happen as it's actualized only when DPU is saved and has empty configuration.

**Comment by kukharm** [comment]
RDF extractor wasn't create from template the instance was placed to canvas from dpu tree. I add  configuration screen of RDF extractor but it isn't contain the path to upload file.. And i checked template directory, the file was there so upload was correct.
![fileextractor](https://f.cloud.github.com/assets/3471169/1754798/27e34286-6659-11e3-9f1b-3cbe32c997e6.jpg)
![fileloaderr](https://f.cloud.github.com/assets/3471169/1754800/29d37192-6659-11e3-8be3-9489b804371a.jpg)

**Comment by skodapetr** [comment]
It's not as bad as it may seems to be (the differences between the details, events etc .. ). But still the configuration (xml) from database, and logs .. would help a lot in full understanding of the issue.

**Comment by tomas-knap** [comment]
@tomesj Jirko, zda se ze problem se tam objevil po jedne z tvych uprav v #849 - projdi si ty commits. Konkretni je problem v tom, ze metoda fileUploadReceiver.getPath() vraci NULL: 

if (extractType == FileExtractType.UPLOAD_FILE) {
                path = fileUploadReceiver.getPath() + "/" + textFieldPath
                        .getValue().trim();

```
        }
```

**Comment by tomesj** [comment]
Podívám se na to,
i když tohle je problém, který jsem kdysi sám reportoval a vy jste mi ho potom zavřeli - že prý extrakce z uploadovaného souboru je OK. Je vidět, že není :-)

**Comment by tomas-knap** [comment]
Jirko, kouknes se na to prosim co nejdriv? Budu tam problem s tou metodu getPath

**Comment by tomesj** [comment]
Aktuálně ladím a hledám, kde je problém, tak snad na to brzy přijdu :-)

**Comment by tomas-knap** [comment]
ok, diky za info

2013/12/17 Jiøí Tome¹ notifications@github.com

**Comment by tomesj** [comment]
Problem solved :-) I tested it and it works fine :-)
