### ISSUE TITLE
After run/debug pipeline is not redraw pipeline status and exucution time

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#931]
When I run/debug pipeline  then I am automatically direct to execution monitor, but I pipeline status and exucution time is not change (redraw). 

When I click on execution monitor manually or click on other header field and then back, redraw is OK :-)

**Comment by bogo777** [comment]
Does this happen for every execution? Or some specific? There was issue with duration refreshing, but it looks ok now. Please test on the latest version.

**Comment by tomesj** [comment]
OK, I try it and in case no problem close this issue :-)

**Comment by tomesj** [comment]
Yes, it´s fine now :-)
