### ISSUE TITLE
Canvas with two dependency trees - NPE

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#936]
When I created pipeline: 

![screen shot 2013-12-18 at 3 09 40 pm](https://f.cloud.github.com/assets/3014917/1773769/e1f10b2c-67ee-11e3-9e46-ae0ccc847a2f.png)

I click debug icon on DPU (file loader) and got: 
![screen shot 2013-12-18 at 3 11 25 pm](https://f.cloud.github.com/assets/3014917/1773749/8d50d93a-67ee-11e3-9845-a87463fc46ed.png)

But it is a normal valid pipeline, which has to work.

**Comment by tomas-knap** [comment]
If I remove the top 2 DPUs, save and try to debug from canvas, it still shows NPE, which is strange. Please explain

**Comment by tomas-knap** [comment]
Also if I click on exec monitor, to the problematic execution above, I got the same error again

**Comment by skodapetr** [comment]
The same exception I also get when I try to debug (run as debug and open the detail in execuiton monitor) the "Copy of Dbpedia extractor", although the pipeline seems to be ok on pipeline edit.

**Comment by bogo777** [comment]
I tried to reproduce this on local, with no success, it works fine. Will investigate further.

**Comment by tomas-knap** [comment]
Can you reproduce that on odcs?

**Comment by bogo777** [comment]
I can reproduce it on odcs on "Copy of Dbpedia extractor" pipeline.

**Comment by tomas-knap** [comment]
And do you know the reason?

**Comment by bogo777** [comment]
I would like to inspect the database on odcs. I found credentials in some old mail, but it doesn't work anymore. Can you mail me actual credentials?

**Comment by tomas-knap** [comment]
rel db http://odcs.xrg.cz:8899/conductor, dba/dba01OD

**Comment by bogo777** [comment]
Thanks, it looks like corrupted data.
![odcs_corrupteddata](https://f.cloud.github.com/assets/1550848/1799961/cce38ac0-6bb3-11e3-9d12-93a221ac2009.png)

These are nodes and edges(but there should be only one edge!) of Copy of Dbpedia extractor pipeline. There is the extra edge from non-existent node, which causes NPE. But how it got there?

**Comment by bogo777** [comment]
I will try testing pipeline creation and repeateadly add/remove DPUs, see if there is any problem with that.

**Comment by tomas-knap** [comment]
Maybe the cascade delete - when deleting DPU, edges should be deleted as well - does not work properly

**Comment by tomas-knap** [comment]
Any findings?

**Comment by bogo777** [comment]
Well, for the extra edge, the second node exist in database, it is assinged to graph with id 210, but this graph has no pipeline assinged, which should be impossible. So the data are corrupted, I thought it could have happened during copying of pipeline, but it doesn't work for the original example of the bug...

**Comment by janvojt** [comment]
This should have been fixed by 3201022cba94bf0c976934a0fe2c767d042fcdda. Please retest.

**Comment by tomas-knap** [comment]
Ok now
