### ISSUE TITLE
URI in the results of the select query not highlighted

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#938]
![screen shot 2013-12-18 at 3 27 18 pm](https://f.cloud.github.com/assets/3014917/1773875/98f5fbce-67f0-11e3-94eb-47876ca9fbca.png)

They are highlighted if it is CONSTRUCT query, but not for select

**Comment by bogo777** [comment]
Cannot reproduce on local.

**Comment by tomas-knap** [comment]
Also cannot reproduce
