### ISSUE TITLE
Filtering list of pipelines in dialogs

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#943]
When creating new scheduled event - run after another pipeline, the text box filtering the list of available pipeline is not working properly. It should work as a filter - if I write AR, it should filter the list of pipelines available. 

![screen shot 2013-12-18 at 5 54 25 pm](https://f.cloud.github.com/assets/3014917/1775344/4bcc1a3a-6805-11e3-8417-64362d034921.png)

In a similar way as for scheduled event - schedulling after another pipeline - please add in the conflicts dialog possibility to filter the list of pipelines I am selecting the conflicting pipelines from:

![screen shot 2013-12-18 at 5 43 03 pm](https://f.cloud.github.com/assets/3014917/1775202/99459ff4-6803-11e3-9f91-6a224a22de17.png)

So the filter will filter the pipeline in the left textarea in pipeline conflicts dialog. 

Ask Bohuslav for help if needed.

**Comment by kukharm** [comment]
was closed by Petr
