### ISSUE TITLE
Read-only mode for pipeline edit

### ISSUE THREAD

**Issue by bogo777** [mff-uk/odcs#945]
Due to Public-RO a Public-RW rights, it is neccessary to have read-only mode for pipeline edit.

This is proposed solution:
Pipeline settings(name, desc, visibility) are read-only.

For pipeline canvas there is already Standard/Develop mode, so for RO only Standard mode is enabled(only possible actions are highlighting DPUs and edges and opening DPU and Edge detail)

Make DPU detail read-only, can we easily do this for DPU's specific configuration dialog? @skodape 

Same for edge detail(or maybe not show it at all, as there is only mapping funcionality)?

Hide DPUTree for RO mode?

Hide/disable save buttons in pipeline edit/DPU detail dialog?

Please confirm/discuss/propose another solution. @tomas-knap

**Comment by skodapetr** [comment]
Well, I was thinking about this .. I would just "hide" the save button .. and show message "read only mode" .. this do the job .. not the most user friendly solution  .. I agree, but fast, effective  and imho easy to implement

btw. made the configuration dialog is not easy as it's provided by the DPU's author .. and he has access to the whole Vaadin

**Comment by tomas-knap** [comment]
Yes, I would also go for the most simple realization - there will for sure be certain further bugs in December, so I would focus rather on them and not on a new functionality, which is not core. 

So I would suggest to:
1) change "Editing pipeline" to "Pipeline detail". 
2) When pupline is shared in RO mode, there will be a red text next to "Pipeline detail" that it is read only mode. 
3) Save buttons will be disabled. 

What do you think?

**Comment by bogo777** [comment]
Done as written in last comment. Please test and close/change priority.
