### ISSUE TITLE
ODCS support for Virtuoso 7

### ISSUE THREAD

**Issue by janvojt** [mff-uk/odcs#947]
- check if ODCS works with Virtuoso version 7
- identify problems
- explore possibility of supporting both versions 6 and 7

**Comment by janvojt** [comment]
I built Virtuoso 7 version from today (openlink/virtuoso-opensource@2701d3f242a630562302471d168d20fec5ed2805):

```
23:46:55 OpenLink Virtuoso Universal Server
23:46:55 Version 07.00.3207-pthreads for Linux as of Dec 18 2013
23:46:55 uses parts of OpenSSL, PCRE, Html Tidy
23:46:56 Database version 3126
```

Frontend does not work. I am unable to login. The problem is, that queries return empty resultsets. I spent several hours debugging to find out, that the problem is in `VirtuosoResultSet.next()` of JDBC. It always returns `false`, even though resultset contains rows (which I saw in debugger at `DatabaseAccessor#processResultSet()`).

@tomas-knap please add new version of Virtuoso JDBC to our nexus maven repo. The new version may be compatible with Virtuoso 7. I can only be guessing right now whether new JDBC will be backwards compatible with Virtuoso 6. If you update it tomorrow afternoon, I can check it out tomorrow night. Otherwise after Christmas.

**Comment by tomas-knap** [comment]
Honzo, when you build Virtuoso 7, you should also get the JDBC driver. Can you find it?

**Comment by tomas-knap** [comment]
Send it to me, I will add it to maven proxy

**Comment by janvojt** [comment]
OK, which JDBC driver should be used for RDF data then? @tomesj had some problems with the driver we currently have, so I assume there will be the same problem with a newer one...

**Comment by tomas-knap** [comment]
For RDF data, we start using 2.7.7 Sesame connector. Based on that, as @tomesj said, we can use jdbc v4. Do I remember correctly? 

By observing dependencies of rdf module, I can see jdbc version 3. Can we update on v4?

We should update anyway because the problems when working with RDF and virtuoso might be cause by jdbc v3

**Comment by tomas-knap** [comment]
#949

**Comment by tomas-knap** [comment]
Please test the jdbc v4.1, pom dependency:

  <pre> <dependency>
            <groupId>com.openlinksw</groupId>
            <artifactId>virtjdbc</artifactId>
            <version>4.1</version>
        </dependency> </pre>

**Comment by tomas-knap** [comment]
I can close this, right?

**Comment by janvojt** [comment]
I created #952 and #953, so we can close.
