### ISSUE TITLE
For older execution records, there is wrong icon for dpu events

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#948]
Filter executions having ID < 470, click on detail. DPU events have warning icon instead of standard info. 

![screen shot 2013-12-19 at 12 31 24 pm](https://f.cloud.github.com/assets/3014917/1781983/44c0cd98-68a1-11e3-97f9-37a58f3c465e.png)

**Comment by skodapetr** [comment]
imho" this is possible, as we added some icons ... (or I believe so) so the index is bad .. to fix this we would need to find out when we done this change and alter the database.

**Comment by bogo777** [comment]
Yes, it is because of Event type enum change.

**Comment by tomas-knap** [comment]
Ok, we can leave it as it is

wont fix
