### ISSUE TITLE
SPARQL loader not working

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#951]
Please check execution 23180 on ODCS - log events "Data XX part was skipped"
Check why it was skipped. Is the form of the query submitted to target ODCS ok? 

![screen shot 2013-12-19 at 5 14 02 pm](https://f.cloud.github.com/assets/3014917/1783811/9f107128-68c8-11e3-8e63-b4c8de31e32e.png)

Write you findings here. Why it was skipped?

**Comment by tomesj** [comment]
V tomto případě se na server posílala nějaká nevalidní data, např. URI ve špatném formátu nebo tak podobně :-)

**Comment by tomas-knap** [comment]
Jirko, zkontroluj prosim pro jistotu ta data, tedy zkus je decodovat a overit - manualne zkusit nahrat na virtuoso. At vime ze chyba neni na nasi strane

**Comment by tomesj** [comment]
Dobře :-)

**Comment by tomas-knap** [comment]
Jirko, nejake nalezy? Tohle je dulezite issue, prosim podivej se na nej co nejdrive

**Comment by tomesj** [comment]
Tak našel jsem tam skutečně chybu v datech
- konkrétně např. pro data part 151/7613 v SPARQL loader ares or
- neprojde např trojice 
  http://linked.opendata.cz/resource/domain/ares/business-entity/CZ27749240/spolecnictvi-s-vkladem/1986-07-16/bedn%C3%A1%C5%99-lubo%C5%A1/splaceno http://purl.org/goodrelations/v1#hasCurrencyValue """100%"""^^http://www.w3.org/2001/XMLSchema#decimal . 

Virtuoso hlásí chybu:
Virtuoso 22003 Error SR127: Can't convert CAST to numeric
- tedy konkrétně vadí ta hodnota 100% u typovaného literálu, který má být decimal.

**Comment by tomas-knap** [comment]
Diky, 

tedy zkusim to sebehnout jeste jednou, s tim, ze zaskrtnu validaci dat pred nahranim. 

Mel bych tam pak mit podobny vystup jako u RDF validatoru, tedy ze hlasis v DPU evente seznam vsech problematickych triplu a srozumitelne duvody? Chapu spravne?

**Comment by tomesj** [comment]
Zkoušel jsem ještě druhou sérii - konkrétně data part 320/7613 v SPARQL loader ares or
- neprojde např. trojice http://linked.opendata.cz/resource/domain/ares/business-entity/CZ25736361/zakladni-kapital http://purl.org/goodrelations/v1#hasCurrencyValue """3.445.000,-Kč"""^^http://www.w3.org/2001/XMLSchema#decimal .

Je co se týká validace, je to tak jak říkáš, jen v aktuální verzi máme, že když jsou data nevalidní, tak se nic nehraje - což bude tenhle případ....Původně jsme tam měli i možnost nahrát pouze ty validní data (které projdou validací), ale to ty jsi pro tuto variantu :-)

**Comment by tomas-knap** [comment]
Check encoding in URL

**Comment by tomesj** [comment]
Kódování všude používáme UTF-8 :-)

**Comment by tomas-knap** [comment]
The data was skipped due to errors in the data, check the encoding
