### ISSUE TITLE
Strictly Timed works wrong

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#957]
I switch of backend and scheduling pipeline to run in a minute and put tolerance 2 min. Then i switch on backend in a 4 min. - pipeline is execute

**Comment by skodapetr** [comment]
I tried on local host and .. it does not run the execution. 

Can you provide more details - log, schedule rule config (screen)?

Also try it again with some more obvious intervals like .. tolerance 2 minutes .. run after 10 minutes?

**Comment by tomas-knap** [comment]
Maria, please test again

**Comment by tomas-knap** [comment]
And write your findings here

**Comment by kukharm** [comment]
I tested it one more time with tolerance 3 minutes and i switched on backend in a 10 min - execution was not run. 
Also i tried tolerance 10 min and  switched on backend in a 5 min -  execution was run. 
Everything is ok
