### ISSUE TITLE
Available pipelines in scheduling rule dont consist new created pipelines

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#958]
I create copies of dbpedia pipeline and would like to schedule them one by one but i don't see this new pipelines in available pipeline list instead of them i see there one old pipeline was deleted from the system. This new pipelines also are absent in pipeline combobox. 
Possibly something is wrong with dialog initialisation or with container @skodape what do you think?

**Comment by skodapetr** [comment]
Yes it's ... the dialog is initilized only once .. (as it's autowired in view which is scope .. ) .. and the InMemorySource .. load/refresh data only when load() method or constructor is called .. so what you have to do is:
a) for every path that can be used to open dialog add the InMemorySource.load method
b) create new instance of dialog when ever it's opened .. 

What surprise me is that the bean with scope="session" live through the user log in and out. 

@janvojt, @bogo777 guys, do you know about that? .. for example in this case I log in as Admin .. open scheduler .. logout, log in as a User .. and I see the same as the admin ..  so we should consider this in frontend and update our patter based on this .. like .. that the data of any dialog, component etc .. should be always set when the view/dialog is shown. - we may even consider declaration of some "interface" for this.

**Comment by tomas-knap** [comment]
Maria, why is this issue NOT done? If something is unclear, discuss here.

**Comment by tomas-knap** [comment]
When I schedule a pipeline, specify certain settings in the core tab, save the changes. Then I schedule another pipeline - by default I see the previous changes.

Solution. Everytime I click "schedule" (or in general open schedula a pipeline dialog) the dialog must be properly initialized to the same initial values (today is selected in the calendar, etc.)

**Comment by tomas-knap** [comment]
Maria, please discuss with @bogo777 how to initialize the dialog properly
