### ISSUE TITLE
Better differentiate DPU and DPU template in GUI labels

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#96]
Based on the usability feedback:

To Bohuslav:
-Menu item "DPUs", please rename to "DPU Templates"
-in DPU tree, 
    - "Only my DPURecord" -> "Only my DPU templates"
    - text "DPUs" on the line before "Extractors" -> change to "DPU Templates"
- DPU detail
  - button "Save and store to DPU tree" -> rename to "Save as DPU template"

When ready, please assign Maria.

To Maria: 
DPUs menu item:
- "Create DPU" -> "Create DPU template"
- similarly for "Import DPU" 
- "Copy DPU", "Delete DPU", Export DPU-> remove the word "DPU"
- tab "Data" -> rename to "General", tab "Configure" to "Template Configuration"
- in the DPU tree, ensure that the changes above (Bohuslav's part) are done. 

Please adjust mockups, also for the Bohuslav's changes.

**Comment by kukharm** [comment]
I'll adjust mockups when in confluence will be possible.

**Comment by tomas-knap** [comment]
Ok, thanks, we will close the issue then when mockups are adjusted

**Comment by tomas-knap** [comment]
Marie, have you adjusted the mockups?

**Comment by kukharm** [comment]
There some problems with edit. For example on page https://grips.semantic-web.at/pages/viewpage.action?pageId=41848387 i adjusted the mockups. In edit mode my changes is applied, and if i press "edit" changes will be seen. But after save and exit edit mode changes are not applied to the mockup

**Comment by kukharm** [comment]
Resolved by mockup export/import
