### ISSUE TITLE
Parallel editing - issues discovered by Honza

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#960]
Dva uzivatele maji otevrenou stejnou pipeline.
1. Jeden zmeny ulozi, nezobrazi sa notice inemu uzivatelovi - len zostava notice ze to ma otvorene.
2. Ked otvorim read-only pipeline, dam "Save as new copy", vytvori sa mi kopia, ale canvas zostane v read-only mode. Je nutne canvas zavriet a znovu otvorit pipeline aby som mohol editovat.
3. Save as new by se melo zobrazit jen pro pipeline in read only mode. V tomto modu bych taky schoval tlacitka save a save & close uplne, at jich tam neni moc. Jen prosim Bohuslave zkontroluj, ze to tak je

**Comment by bogo777** [comment]
Ad 3. And what about the case when pipeline is saved by another user and saving it would cause to overwrite his save? I think there should be this button also. And should there be some additional warning upon save which would cause overwrite?

**Comment by tomas-knap** [comment]
Just to supplement 1) it would be good to notify the second user that the first has saved the pipeline, thus, that the second is not working with the actual version. Thus the notification "Another user is also browsing the pipeline" should be supplemented with notification "user x made changes to the version you are editing, please refresh the pipeline detail". To realize that,  I would add button refresh, which is equivalent to reopenning of the pipeline detail and reloading the latest version in DB. Usefull, when second user would like to see the latest version without the need to close and open the dialog. 

Please discuss

**Comment by skodapetr** [comment]
Sounds reasonable .. user also should receive this information when he saves the pipeline ..  about the refresh button, it may be nice to have a link .. so I can open on other tab .. and see both versions 

maybe in case of  "other user update" we can give user possibility to "save as a copy" with his changes or "overwrite" (I do not know if this is possible)

but this is kind  "advanced" solution imho .. just want to mention this as a possible approach

**Comment by tomas-knap** [comment]
Regarding 3) Yes, that is true. Save as new might be useful even in cases when the pipeline is in private mode e.g. Maybe we can leave the button save as new in all cases. I would suggest to have buttons save, save & close, copy, copy & close, close. The behaviour of "copy" would be: "save as a new pipeline and open the pipeline detail of that new pipeline", copy and close = "save as a new pipeline and close". What do you think? The only problem is that there are lots of buttons, but this may be solved by CSS styling or icons for buttons in the future. 

In case two users are editing, first saves changes, then the second should get notification about that (see above), so that he knows that there are not only users browsing this pipeline but also that some of them already saved changes. Further, if the second user clicks:
- save, save & close: he should be notified that he was editing version, which is not actual and whether he would like to:
  1)save anyway (overwrite changes of the other one)
  3)cancel the save
- copy, copy & close: he should be notified that he was editing version, which is not actual and whether he would like to:
  1)copy anyway (but he will not see changes of the other user)
  3)cancel the copy

Please discuss
