### ISSUE TITLE
Menu styling

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#961]

**Comment by bogo777** [comment]
There should be support for this from Vaadin via special css class, but it doesn't seem to work. Will look into it more.

**Comment by tomas-knap** [comment]
Bohuslav, 

current situation is: 
![screen shot 2014-01-09 at 5 14 13 pm](https://f.cloud.github.com/assets/3014917/1879373/31966fbc-7949-11e3-8c57-387afab52785.png)

Could you please return back the font (boldness) as it was:

![screen shot 2014-01-09 at 5 14 22 pm](https://f.cloud.github.com/assets/3014917/1879375/35d86800-7949-11e3-8778-2bdad40d37f4.png)

I liked the previous font format more, the current font is a bit blurred. I think it is enough to emphasize the selected item with the greyed box around,

Solution: Use the same font as before, use greyed box to highlight the selected one. 

Thanks

**Comment by tomas-knap** [comment]
Asi za to muze @janvojt 
https://github.com/mff-uk/ODCS/commit/5babcae61db479c276dd6e91b23be60526ad3ab6

**Comment by janvojt** [comment]
Yes, I changed this. My situation (on Linux - every OS has a little different set of fonts):

Before:
![screenshot from 2014-01-10 14 23 23](https://f.cloud.github.com/assets/2247062/1887381/2f3b25f6-79fc-11e3-8aa3-56c501fe5686.png)

After:
![screenshot from 2014-01-10 14 25 57](https://f.cloud.github.com/assets/2247062/1887432/495a38ae-79fd-11e3-8c73-a6eabddb58d7.png)

Anyway, I did not expect it to look so much different, so change as you like.

**Comment by janvojt** [comment]
Fixed in 8454b86a6fd58c12d45c7bce72cb64de86ac7d94.
