### ISSUE TITLE
Schedulling to past - last exec column

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#962]
When I schedule new pipeline, schedule it to run every week, starting from tomorrow. Last execution column is empty, which is correct. Then I change it to run every week but starting from yesterday. As a result, last execution column is filled, which is wrong.

**Comment by skodapetr** [comment]
Can this be replicated on odcs?

**Comment by skodapetr** [comment]
Do you use strict timing?

**Comment by tomas-knap** [comment]
No strict timing. You can see it, see [Ontology] FRBR pipeline in
scheduller. But as I am checking again, it seems that the reason why the
last execution is prefilled is because it was manually run at that time.
Should we show times of manual runs in last exec column?

**Comment by tomas-knap** [comment]
So basically I schedulled pipeline to be run tomorrow, I test it (by manual
running), there was a problem, so I reschedulle it to todays morning, so
that it is firstly launched in a month

**Comment by skodapetr** [comment]
Well.. then I gues that the backned start the execution before you update the rule.

**Comment by skodapetr** [comment]
Yes.. but if do not use strict timing, the the pipeline is run asap after the date of next|first schedule is before "now".

So if you schedule pipeline from yesterday .. run every week .. then the first execution is now .. and the second now + 7 days ..

**Comment by tomas-knap** [comment]
Yes, you are right. That is maybe a bit confusing, but could be a feature :)
