### ISSUE TITLE
Failed to create DataUnit for DPU 'XSLT'

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#973]
Failed to create DataUnit for DPU 'XSLT'

To reproduce: 
- go to http://odcs.xrg.cz:8080/odcleanstore-test
- pipeline execution: 115 , ares test pipeline

Reason: &lt;http://linked.opendata.cz/ontology/odcs/DataUnit> in the query below

Stack trace:
cz.cuni.mff.xrg.odcs.rdf.exceptions.InvalidQueryException This query is probably not valid. : SPARQL execute failed:[SELECT ?pName ?pValue where {&lt;http://linked.opendata.cz/ontology/odcs/DataUnit> &lt;http://linked.opendata.cz/ontology/odcs/xsltParam> ?x . ?x &lt;http://purl.org/dc/terms/title> ?pName ; &lt;http://www.w3.org/1999/02/22-rdf-syntax-ns#value> ?pValue . ] Exception:virtuoso.jdbc4.VirtuosoException: SQ074: Line 3: SP030: SPARQL compiler, line 3: syntax error at ';' at '' immediately before end of statement at cz.cuni.mff.xrg.odcs.rdf.repositories.BaseRDFRepo.executeSelectQueryAsTuples(BaseRDFRepo.java:1385) at cz.cuni.mff.xrg.intlib.extractor.simplexslt.SimpleXSLT.collectXsltParams(SimpleXSLT.java:109) at cz.cuni.mff.xrg.intlib.extractor.simplexslt.SimpleXSLT.execute(SimpleXSLT.java:312) at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.executeInstance(Executor.java:226) at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.execute(Executor.java:354) at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.run(Executor.java:433) at java.lang.Thread.run(Thread.java:724) org.openrdf.query.QueryEvaluationException : SPARQL execute failed:[SELECT ?pName ?pValue where {&lt;http://linked.opendata.cz/ontology/odcs/DataUnit> &lt;http://linked.opendata.cz/ontology/odcs/xsltParam> ?x . ?x &lt;http://purl.org/dc/terms/title> ?pName ; &lt;http://www.w3.org/1999/02/22-rdf-syntax-ns#value> ?pValue . ] Exception:virtuoso.jdbc4.VirtuosoException: SQ074: Line 3: SP030: SPARQL compiler, line 3: syntax error at ';' at '' immediately before end of statement ... 6 common frames omitted at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.execute(Executor.java:354) at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.run(Executor.java:433) at java.lang.Thread.run(Thread.java:724)

Please write where the problem is.

**Comment by tomas-knap** [comment]
It is urgent, because otherwise ARES test pipeline cannot be debugged, thus I cannot test one of the most problematic pipelines

**Comment by tomesj** [comment]
Někde v implementaci nebo v nastavení XSLT používáte nebo voláte tento dotaz:

SELECT ?pName ?pValue where {http://linked.opendata.cz/ontology/odcs/DataUnit http://linked.opendata.cz/ontology/odcs/xsltParam ?x . ?x http://purl.org/dc/terms/title ?pName ; http://www.w3.org/1999/02/22-rdf-syntax-ns#value ?pValue .

V dotazu chybí uzavírací závorka na konci "}" - proto je navalidní a skončí vše chybou

**Comment by tomesj** [comment]
Což dokládá i zdrojový kód XSLT

String query = "SELECT ?pName ?pValue where {<"+ subject +"> <" + config.getParamsPredicate() + "> ?x . ?x <" + config.getParamsPredicateName()+ "> ?pName ; <" + config.getParamsPredicateValue() + "> ?pValue . ";

řádek 105, třída SimpleXSLT :-)
Tedy jednoznačná chyba autora této implementace :)

**Comment by tomas-knap** [comment]
Diky, mne zmatlo to "Data unit creation failed", necekal jsem ze za vytvareni DU je zodpovedny muj kod ;)

**Comment by skodapetr** [comment]
Jen pro moje info .. kde já myslel, že tam máme validaci těch RDF dotazů? 
Chápu z tohoto správně, že tedy zde není použita?
