### ISSUE TITLE
Grouping of controls in pipeline detail

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#975]
![screen shot 2013-12-22 at 6 53 57 pm](https://f.cloud.github.com/assets/3014917/1798177/26a43a46-6b32-11e3-9d52-c21e430d57e0.png)

**Comment by kukharm** [comment]
@tomas-knap specify please how they should be grouped?

**Comment by tomas-knap** [comment]
Groups: 
Save and Save & Close
Copy and Copy & Close

Also the buttons should be divided to two parts, one part (on the left) contain validate and conflicts, the other part the rest. There should be more space after conflicts button. 

Please put here the screenshot when done before commiting to the rep

**Comment by kukharm** [comment]
![buttonbar](https://f.cloud.github.com/assets/3471169/1888174/eda5177e-7a09-11e3-8476-c76c83dc5873.jpg)

**Comment by tomas-knap** [comment]
ok, muze byt, jeste prosim hod tu dvojici copy a copy & close pred save a save& close
