### ISSUE TITLE
No named graph specified (at least according to logs) - while executing ares test

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#979]
Please look at ODCS-test (http://odcs.xrg.cz:8080/odcleanstore-test/).

Open exec monitor, check execution 116. When looking into logs, trying to get the named graphs used, I got strange logs: 

![screen shot 2013-12-25 at 3 07 32 pm](https://f.cloud.github.com/assets/3014917/1808682/0e4f1694-6d6e-11e3-891e-c29979b8b905.png)
1. Why is the TO named graph name not filled? 
2. WHy is the from named graph introduced in short message, but not in long message of the log?

**Comment by tomesj** [comment]
Tak o tomhle bohužel nic nevím 
- koukal jsem i do kódu a tam se to loguje všechno správně (konkrétně třída VirtuosoRDFRepo, řádek 170). 
  To je vidět i v tom sloupečku, kde se jména grafů normálně objevují správně :-)

Jak se dělá detail zprávy, bohužel já nevím :-)

To by měl vědět @skodape nebo @bogo777 . 
Ty ti také patrně dokážou vyřešit, tak jim k tomu nechám prostor na vyjádření a opravu :-)

**Comment by skodapetr** [comment]
Try the file log from backend (this eliminate possible problem in SQLAppender) if the same message is in the file then we got empty strings on your 170 line .. if not ,,then we can try to find out what happen.

**Comment by tomas-knap** [comment]
When logging there is a code: 

logger.info("START merging " + second
                            .getTripleCount()
                            + " triples from <" + sourceGraphName + "> "
                            + "TO <" + targetGraphName + ">.");

SO it is strange, that there is "from TO" in the log browser, but no "<", ">".

**Comment by skodapetr** [comment]
btw. the better approach to logs is imho:
logger.info("START merging {} triples from < {}">  TO < {} >.,  second.getTripleCount(), sourceGraphName, targetGraphName );

this does not prevent the sourceGraphName and targetGraphName  to be empty strings. Where does those values comes from?

**Comment by tomas-knap** [comment]
Yes, the approach mentioned by @skodape should be used everywhere, because it is more effective - the placeholders are replaced with particular values, no concatenation of Strings, which is not effective. 

Jirka, please check that by inspecting the code, adding some tests. Just in case.

**Comment by tomas-knap** [comment]
As I was checking the logs again, the names of the graphs are there. Strange, will reopen if reappers
