### ISSUE TITLE
Prepare working DPU Linker 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#98]

**Comment by tomas-knap** [comment]
Petr, please check the problems with dependences of Silk.jar. When launching Silk.executeFile(conf, null, Silk.DefaultThreads(), true); in Silk Linker DPU extractor, the error occurs:

Pipeline execution terminated because of: java.lang.IllegalArgumentException: http://www.w3.org/2001/XMLSchema at javax.xml.validation.SchemaFactory.newInstance(Unknown Source) at de.fuberlin.wiwiss.silk.util.ValidatingXMLReader$XmlReader.read(ValidatingXMLReader.scala:69) at de.fuberlin.wiwiss.silk.util.ValidatingXMLReader.apply(ValidatingXMLReader.scala:39) at de.fuberlin.wiwiss.silk.util.ValidatingXMLReader.apply(ValidatingXMLReader.scala:53) at de.fuberlin.wiwiss.silk.Silk$.executeFile(Silk.scala:92) at de.fuberlin.wiwiss.silk.Silk.executeFile(Silk.scala) at cz.cuni.mff.xrg.intlib.extractor.silklinker.SilkLinker.extract(SilkLinker.java:90) at

It seems that the problem is with two conflicting XML parsers (or two versions), could be cause by xml-apis.jar within silk-lib.jar. The classes in xml-apis.jar should be part of standard java distribution as well. But that has to be verified. 

When solved, please assign back on me.

**Comment by tomas-knap** [comment]
Any progress in this?

**Comment by skodapetr** [comment]
Based on our last meeting I have expected that you first try slik-linker in standalone application? To be sure, that the cause of this error is caused by xml-apis.jar.

**Comment by tomas-knap** [comment]
Yes you are right ;)

**Comment by tomas-knap** [comment]
Silk is called as extra process
