### ISSUE TITLE
Pipeline remains in cancelling state

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#980]
I managed to cancel pipeline exec shortly before the normal run was finished and the result is: 

![screen shot 2013-12-25 at 3 35 57 pm](https://f.cloud.github.com/assets/3014917/1808726/f92f3be6-6d71-11e3-907b-a9786cdaa6fa.png)

As a result, pipeline remains in cancelling state

**Comment by skodapetr** [comment]
Well this can "happen" we need to update the PipelineFacade.stop method to fix this .. in the transaction we have to load the instance .. check for it's state .. and if running then change to "cancelling" otherwise we should do nothing.

**Comment by skodapetr** [comment]
I done the adjustments based on my previous comments .. this can be hard to replicate and so to test, but let's hope that the problem is history ...
