### ISSUE TITLE
Try mysql as a relational database instead of virtuoso 6/7

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#982]
We have couple of problems when working with Virtuoso: 
- problem with sequences
- problem with strange serialization of national characters to configuration of DPU instances, logs, above certain length
- ...

Please test mysql as relational database. If it behaves well, I would suggest to add one param to config.properties, which allows user to specify whether he would like to use mysql or virtuoso6 or virtuoso7 as a relational database. 

Mysql is available under free license, right? 
THis issues has highest priority among the normal 0.5 issues you have, even before further experimenting with Virtuoso 7. Virtuoso 7 will not help us regarding wrong serialization, it is a matter of the jdbc probably.  Please discuss if you feel it differently

Please tell me when you can try it, it would be best to know that mysql will be working till 31.12.

**Comment by tomas-knap** [comment]
It seems that we have solved the problem with national chars in long Strings. But anyway, it would be useful to know if mysql can be easily used. 

I would suggest you will test mysql and if there are no problems, mysql is working smoothy, you will add support for it. If you find some problems during that one day testing and it seems that it will take 3+ days to adjust our code to work with mysql, leave this to January after trying Virtuoso 7. What do you think?

**Comment by janvojt** [comment]
I do not see this as a high priority issue. You already need Virtuoso to run ODCS for RDF, so what would be the motivation of running it on MySQL? I definitely do not see this urgent enough to spend half a day setting up the environment to work on this at home during Christmas (I am not in Prague). So if we want to do this, definitely not earlier than January...

Anyway, it should not be complicated. What I can think of that would be needed to be done:
- modify configuration
- create a dedicated schema definition for MySQL
- add maven dependency for MySQL JDBC
- choose the correct driver on EclipseLink startup
- modify db dumping and update tools
- disable workarounds for problems with sequences and foreign keys

**Comment by tomas-knap** [comment]
Ok, I will plan it for January. national chars were solved by NVARCHARs, so it is not high prio issue now.

**Comment by janvojt** [comment]
This is finished in e0369f4e035b72dcfcea11f571e43274e5689811.
