### ISSUE TITLE
Browse/Query - adjusting query, cannot run the query

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#984]
To reproduce: 

-Run dbpedia pipeline, go to browse/query, click browse. 
-Then adjust query e.g. to 
CONSTRUCT {?s ?p ?o} WHERE {?s http://xyz ?o}
-Click query. As a result no data is displayed.
-Adjust the query to the previous value and click query.
-Query button does nothing

**Comment by bogo777** [comment]
Cannot reproduce, tried both on local and ODCS.

**Comment by tomas-knap** [comment]
also cannot reproduce now
