### ISSUE TITLE
ARES TEST - problem with SPARQL loader - connection refused

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#987]
I was again running ares test (see ODCS, execution 23268), there was a problem with SPARQL loader. 

![screen shot 2013-12-27 at 6 20 53 pm](https://f.cloud.github.com/assets/3014917/1815562/65bf26a2-6f1d-11e3-8aea-58a519406f96.png)

In particluar, there are two errors in the log: 

![screen shot 2013-12-27 at 6 22 02 pm](https://f.cloud.github.com/assets/3014917/1815563/6d5b827a-6f1d-11e3-8ff7-44d76726b007.png)

![screen shot 2013-12-27 at 6 22 13 pm](https://f.cloud.github.com/assets/3014917/1815565/700b3b96-6f1d-11e3-921f-f1b72261c5b2.png)

Please explain. 
Note: The deployed version on ODCS is from 22.12.

**Comment by tomesj** [comment]
The reason of this exception is:

Count of attempt is more than set RETRY_CONNECTION_SIZE - you have to set this param to value 10 (not to infinity) - after 10 attempts to reconnect it´s thrown this exception. See screeen. 

![image](https://f.cloud.github.com/assets/3481055/1815888/f3462240-6f28-11e3-9ffd-ff6a7a8e1a9e.png)

**Comment by tomas-knap** [comment]
Ok, pak se omlouvam, nicmene kdyby tam byla hlaska kterou jsi tam ted dodal, tak by to bylo jasne. Tys ted upravil  to nastaveni SPARQL loaderu? Koukam, ze ted tam mam vsude -1

**Comment by tomesj** [comment]
Jo, nastavení už jsem změnil na -1 :-) Tu hlášku jsem právě upravil, aby to nebylo zavádějící a rovnou to celé nechat pustit znovu :-) 

Jinak to vyzkouším ještě nezávisle na tom u Honzy - už jsem mu psal, protože bohužel nemůžu nechat svůj hlučný počítač běžet takovou dobu.....

**Comment by tomesj** [comment]
Jinak ještě poznámka - loader, který se používá pro AREST test pipeline, 
tedy 
http://internal.opendata.cz:8891/sparql-auth

Není dostupný. Nevím, zda je to účel, každopádně se nedivím, že nemůže pipeline ani doběhnout, když tento endpoint není ani dostupný - to bohužel nevyřeší ani infinity parametr.

**Comment by tomas-knap** [comment]
Jeste k te vyjimce, proc je v short message: Pipeline failed because of exception. 

Melo by v te short message byt napriklad. Cannot load data to target endpoint, because connection cannot be established.
V long message je pak exception, to je ok.

**Comment by skodapetr** [comment]
Tohle je asi spíše na mě .. tem log je odemně .. prakticky to znamená, že DPU.execute() vyhodila exception .. tu zachytil kód ODCS (takový super catch jenž kolém té metody je právě pro tyhle případy, jinak by to zabylo vlákno DPU) .. zalogoval a ukončil pipeline. 

Pokud by to mělo být jak píšeš ty Tome, tak by tuhle chybu muselo odchytit DPU .. a vypublikovat error message a pak skončit.

**Comment by tomesj** [comment]
Pokud vím, tak tahle zpráva se tvoří někde v backendu - nejsem jejím autorem. To bude vědět @skodape. Jinak co se týká logů, tak jsem si všiml, že ač se používá pro logování přítup, který popsal Petr, 

tj např. 

LOG.debug ("Something {} var", variable); 

Tak stále tam, kde je jméno grafu v <...> tak se v detailu zprávy nic neukazuje, ale v přehledu je vše OK.

**Comment by skodapetr** [comment]
The log message already commented. But to the LOG.debug .. can you give example? As I do not fully understand what to you mean by "Tak stále tam, kde je jméno grafu v <...> tak se v detailu zprávy nic neukazuje, ale v přehledu je vše OK." ? 

In you example is nothing like "<"  ">" .. or they are in that variable? 
What is the message detail ("detailu zprávy") and what is the overview ("přehledu")?

**Comment by tomas-knap** [comment]
Ok, nicmene Petr s tim nic lepsiho neudela. Nicmene kdyz koukam do prehledu events, tak je tam eventa: "Endpoint http connection stream .." Tedy Jirka to odchyti, zaloguje event(ERROR), ale pak jeste vyhodi DPU exception? Je nutne tam jeste vyhazovat DPU exception? Nestacilo by ten stacktrace dat do long message u te jedne event(ERROR)?

**Comment by tomesj** [comment]
Petr see 
![image](https://f.cloud.github.com/assets/3481055/1817593/e3f44ef8-6fae-11e3-86d8-8d67f7f829d1.png)

Message contains graf name, but there is not in log message detail.

**Comment by tomesj** [comment]
Výjimku je nutné vyhodit, protože je třeba řešit smyčku pro získání InputStreamu z endpointu (případ kdy byl překročen počet connection)

Tato metoda se používá na více místech a pouze vyskočení z cyklu nebo vrácení nějaké hodnoty by pak mělo skoro katastrofální následky.

Jsou jen 3 možnosti
a) stream je OK - pak se se vrátí, ideální stav
b) je tam nějaká chyba ohledně endpointu - např. neznámý host, bad/unautorized response - získá se chybový stream - vyhodí se InsertPartException
c) Výpadky connection - chyba typu IOException - když dost pokusů, zkouší se znova - jinak konec a vyhození RDFException (náš případ)

**Comment by tomas-knap** [comment]
Nerikam, ze neni dobre vyhodit vyjimku, to je urcite ok. Ale nemusis ji vyhazovat az Petrovi, ale odchytis si ji sam v logice DPU

**Comment by tomesj** [comment]
Jde o to, že RDFException vždy probublá až do metody execute v případě DPU a tam je většinou tento kód

``` java
catch (RDFDataUnitException ex) {
    context.sendMessage(MessageType.ERROR, ex.getMessage());
    throw new DPUException(ex.getMessage(), ex);
}
```

Tedy mám použít jen context sendMessage(...) a už DPU exception nevyhazovat ?

**Comment by tomas-knap** [comment]
To chapu, ale neni problem tu exception odchytit uz na urovni DPU, ne? Tedy ze pak DPU execution neskonci na vyjimku, ale regulerne chybou.

**Comment by tomesj** [comment]
No vždyť ano - ten kód výše, je na úrovni execute methody v rámci DPU - tedy stačí použít jen context a ne už dál vyhazovat výjimku DPUException - to je to, na co jsem se ptal a ty jsi mi na to vlastně teď nepřímo odpověděl.

Pak by mělo DPU skončit chybou a ne výjimkou :-)

**Comment by tomas-knap** [comment]
Jo, jak pises, uz nemusis tu DPUException vyhazovat. Nicmene ten stack trace u te DPUException dej to long message u te error event. Aby tam nebylo jen "Nelze se pripojit", ale aby tam byl i ten stack trace v detailu (long message)

**Comment by tomas-knap** [comment]
Oprav to prosim u vsech core DPU, tohle neni urgentni, az se k tomu dostanes. Nejlepe do 31.1.

**Comment by tomesj** [comment]
Je to jasné :-) Opravím to, až vyřeším ten zbytek :-)

**Comment by tomas-knap** [comment]
Pripraveno k otestovani?

**Comment by tomesj** [comment]
Ano
