### ISSUE TITLE
New setting of DPU template- Template configuration works wrong

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#989]
Is not possible to change default configuration setting for DPU defined in DPU tempate/template configuration.

If you change some value -> click on save button - the previous (not new value) is still used.

Configuration is always same (is not possible to change it) - you can create new pipeline with this DPU (which config tried to change) and check it.

**Comment by tomas-knap** [comment]
For which DPU?

**Comment by tomesj** [comment]
For all DPUs - problem is global.

**Comment by tomas-knap** [comment]
Please describe the steps to reproduce on one example. Thanks!

**Comment by tomas-knap** [comment]
works for me
